### ISSUE TITLE
As a developer I need scaffolding for the UI so I can contribute to the project

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#1]
AC:

- [ ] Basic React App UI on cloud.gov dev environment 

Tasks: 

- [x] Create React App
- [x] Dockerfile created to be used locally and on cloud.gov 
- [x] Create directory structure to so ui and api live in the same repo
- [x] CF manifest 
- [x] Add Jest
- [x] Add Cypress
- [x] USWDS

DoD:
 - [x] minimum 90% code coverage test
 - [x] 0 linting errors and warnings
 - [x] 0 accessibility errors
 - [x] deployed to a dev environment
 - [x] all significant changes have been documented
 - [x] free of high and medium security vulnerabilities

**Comment by lfrohlich** [comment]
AC looks good from my perspective.

**Comment by shubhi-raft** [comment]
> AC looks good from my perspective.

great, thanks. @lfrohlich moving this to do.
