### ISSUE TITLE
As OFA admin, I can see a log of which users had access to the system on a specific date.

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#100]
Description:
Recommendation from Kathleen during Sprint Demo 8/4/2020

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
addressed as an acceptance criteria in #394 :
>Clicking on 'Manage' opens a new page that provides user profile and login history
