### ISSUE TITLE
As tech lead, I want a better process for requesting, approving, and changing access to TDP

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1001]
Current **_request_** process:
1. User creates an account in login.gov and proceeds with the login.gov account verification process
2. User requests access to TDP via request [page](https://tdp-frontend.app.cloud.gov/edit-profile). This will trigger the generation of a user profile record on the backend. 
3. User sends email to sys admin (_for non-privileged access_) or sys owner (_for privileged access_) requesting access to TDP. 

Concerns about this process: 
- Users do not receive any notification confirming that their request was submitted or received. 
- Sys admin does not receive any notification of new requests. 
- New requests are managed in the same table in django admin as approved users (difficult for sys admin to distinguish)

---
Current **_approval_** process (_includes assigning permissions_):
1. Sys owner (_for privileged users only_) or sys admin approves users by cross-referencing django admin user lists against OFA's vetted list of users (maintained outside of TDP). If there's a x-ref match, approval granted via email. 
2. Sys admin navigates to approved user's profile to assign access rights. 
3. Sys admin notifies user via email that access to TDP has been assigned. 

Concerns about this process: 
- Parts of the approval process take place externally from TDP. 
- Vetted list of users is not maintained within TDP.
- Sys admins can approve (_non-privileged users only_) and assign permissions to users only by changing selections within a user's profile. 
- User profile changes are not verified prior to being applied (e.g. Please verify that you wish to change x, y, and z fields in user's profile) 
- Sys owner does not receive any notification of new users being assigned to sys admin role. 
- Users do not receive any notification of approval and permissions assigned. 

---
Current **_change_** process :
1. User sends email to sys admin or sys owner to request change to their TDP access (e.g. change in group permissions, account deactivation, account reactivation [_note: users also currently have the ability to change their own STT via the profile page, which is the same as the request access page_])
2. Sys admin or sys owner approves changes via email. 
3. Sys admin implements changes via user profiles. 
4. Sys admin notifies user of changes via email. 

Concerns about this process: 
- Change requests submitted externally from TDP _or_ users have the ability to change their  STT by navigating to profile page (either is problematic). 
- Parts of the change approval process take place externally from TDP
- Same issues documented above re: approval process

---
**Potential tickets**:
- As an STT user, I want to provide enough info (name, STT, region) in request form so admin can approve my access to TDP.
- As an STT user, I want to be notified when my TDP access request is submitted, approved, or denied. 
- As a sys owner/admin, I want to be notified when someone requests TDP access. 
- As a sys owner, I want to be notified when sys admin permissions have been assigned. 
- As an STT user, I want to provide enough info in request form so admin can change my access to TDP. 
- As a sys admin, I want to maintain approved users and requesting users in separate tables in django admin. 
- As a sys admin, I want to maintain vetted list of users within TDP. 

**Notes**:
- Need to determine ACF AMS/NextGen/Login.gov before deciding on any changes to request process (#683)
- Need to layout pros/cons of invite vs request model before making any changes to request process (#883)
- The request process would need to be settled before Release 2.

**Comment by amilash** [comment]
@lfrohlich Do we say access request flow is V1 or v2? I think its V1- since we'll need to have integration done with any new solution- BUT we are integrated with login.gov. So can this be an enhancement in V2 since we have the basis covered? What do you think?

**Comment by abottoms-coder** [comment]
I have created tickets out of the "potential tickets" section located here:

#1336 
#1335 
#1334 
#1333 
#1337

**Comment by valcollignon** [comment]
@ADPennington double check the tickets above to make sure this issue is safe to close out. Per backlog refinement 11.23.21

**Comment by valcollignon** [comment]
@ADPennington can you check the tickets above to see if this issue can be closed out? TY.
