### ISSUE TITLE
Implement Welcome Page for Logged In Users

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1012]
Implement a basic welcome page for logged in users.

**Acceptance Criteria:**
- [ ] Matches UX designs (link)
- [ ] Responds correctly to user role / lack thereof

**Comment by reitermb** [comment]
![image](https://user-images.githubusercontent.com/28515874/129796809-54d3cb77-19de-475a-9678-775476e3bf34.png)

**Comment by abottoms-coder** [comment]
@reitermb Can we remove the blocking dependency here and what acceptance criteria would you like for this?

cc @amilash

**Comment by reitermb** [comment]
> @reitermb Can we remove the blocking dependency here and what acceptance criteria would you like for this?
> 
> cc @amilash

Removed! 

- [ ] Matches UX designs (link)
- [ ] Responds correctly to user role / lack thereof 

Something like those probably cover it pretty well given the thin slice of new content/functionality here
