### ISSUE TITLE
Round 7 (Sprint 24-26) UX Research and Design

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#1017]
**Goals for round research:**
- (Release 1) To validate current state journey maps for regional managers and 
- (Release 1) To understand what processes will be needed to enable regional staff to confirm the identities of grantee users.
- (Release 1) Workflow for access request for STT's to be granted access and login.
- (Release 3) To understand the depth of parsing blockers and how they are currently being communicated to grantees.
- (Release 3) To understand how grantees interpret current error communication around parsing blockers to inform changes to the current workflow and language
- (Release 3) To test error solutions with grantees to determine if new communication will result in the effective diagnosis of errors and error prevention.

**KPI's Targeted**
- TBD

**Personas Targeted**
- Regional Manager
- Grantee (States and Tribes)

**Focus within the round:**
*Sprint 24 (June 23 - July 6) focus: Current State Analysis of Error Communication and Regional Staff Workflow Validation*
- (Secondary Research / Async w/ DIGIT) Analysis of all parsing blocker errors / their meanings
- (Secondary Research / Async w/ DIGIT) Analysis of related instructions and workflow documentation for parsing blockers
- (Journey Map Workshop w/ Regional Staff) Regional Manager journey map validated
- (Workflow Workshop w/ Regional Staff) Workflow for user request validated

*Sprint 25 (July 7 - July 20) focus: Iteration and Testing for Parsing Blocker Communication*
- (Ideation Workshop w/ Internal / 3 DIGIT / 3 Regional Staff) Lofi solutions for parsing blockers are explored
- (Usability Session w/ STTs) Lofi mockups for parsing blockers are tested
- (Ideation Workshop w/ DIGIT) Lofi mockups for parsing blockers are updated based on feedback

*Sprint 26 (July 21 - August 3) focus: Test Error Communication for Parsing Blockers*
- (Usability Session w/ STTs) error mockups for parsing blockers are validated

**Research Planning Workshop to define epic deliverables:** https://app.mural.co/t/raft2792/m/raft2792/1621971341246/2f99fbea9db26da97a542b88c79c3fd2f2877d9a

**Research Round 7 Synthesis:**
TBD (Follow on)

**Comment by reitermb** [comment]
![image](https://user-images.githubusercontent.com/28515874/131410564-c0b3a6ef-f353-4048-afa6-0ba12ae52bb7.png)
missing adult or child record

![image](https://user-images.githubusercontent.com/28515874/131410856-64cd20e5-faf7-4a6a-b69c-6ac21844e2a0.png)
wrong quarter

![image](https://user-images.githubusercontent.com/28515874/131410988-3f1c5320-1390-4e93-986c-54775fdab09a.png)
too short
