### ISSUE TITLE
Name for new platform

### ISSUE THREAD

**Issue by cmajel** [raft-tech/TANF-app#104]
Description:
We found in earlier user research that there is confusion around the names of TDRS systems. And names are important; they help set expectations with users and with ACF investment managers. 

This issue is to explore what we want to name the new system and decide on a name. Some of the names that have been discussed include:

* TDRS: TANF Data Reporting System (current name)
* TDP: TANF Data Portal

Misc thoughts:
* Conduct a naming exercise with stakeholders/STTs?

Relates to 
* #101 

AC: <Needs review>

- [ ] Sample acceptance criteria

Tasks: <Needs review>

- [ ] Sample tasks

DoD: <Needs review>
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

* [Notes from prior user research on name collision](https://github.com/HHS/TANF-app/wiki/2020,-Spring:-Understanding-the-local-experience#what-we-tested)  

Open Questions:

(any clarifying questions in support of the issue)

**Comment by lfrohlich** [comment]
Tied to #726
