### ISSUE TITLE
SPIKE: Authentication Feasibility Research

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1046]
As a PO I need to know what the effort involved would be for the dev team in order to implement the authentication options we have on the table so that I can factor this into my decisions making as we move forward to decide on and approach. This will be one of the factors along with budget, and others.

AC:
- Document feasibility and high level estimated tasks that would be needed for ACF/AMS (#1134) & Next Gen (#1153) implementation.
- Must have high level tasks
- Tasks must be roughly estimated (10, 20, or 40 (40pts= 1 sprint for 1 dev)
- Document any technical tradeoffs between the solutions as a (feature/capability) matrix
- Create "Authentication Epic" with tasks and approach (and link this ticket and other tickets labled as authentication)

**Comment by ADPennington** [comment]
[link ](https://teams.microsoft.com/_#/files/dev?threadId=19%3A96fae73b37194050a5fb671ddf2380e3%40thread.skype&ctx=channel&context=ACF%2520AMS%2520docs&rootfolder=%252Fsites%252FTANFDataPortalOFA%252FShared%2520Documents%252Fdev%252FACF%2520AMS%2520docs)to acf ams integration information (if we were to go forward without nextgen)

**Comment by ADPennington** [comment]
@abottoms-coder also including a link to this [documentation](https://github.com/raft-tech/TANF-app/issues/842), which includes high-level takeaways for level of effort to integrate with acf ams based on documentation collected so far.

**Comment by ADPennington** [comment]
@abottoms-coder answers to questions posed to ACF AMS team on 7/12 saved in onenote.

**Comment by amilash** [comment]
This is now unblocked though it has been ongoing.

**Comment by abottoms-coder** [comment]
@amilash @ADPennington @lfrohlich 
First draft to pro/con and trade offs [here](https://hhsgov.sharepoint.com/:o:/r/sites/TANFDataPortalOFA/SiteAssets/TANF%20Data%20Portal%20(OFA)%20Notebook?d=wcbce2e7517b24e70b42260d034fcd4af&csf=1&web=1&e=FEbV0K)
Perhaps it's just my OneNote app but the above link doesn't actually work for me, hoping it's better for y'all. If not, it is located compliance>Authentication>Trade-Offs Matrix

Should this ticket be moved to some sort of review?

**Comment by ADPennington** [comment]
@abottoms-coder thank you for this. left some questions in onenote.

**Comment by amilash** [comment]
link to tradeoffs matrix: https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2FTrade-Offs%20Matrix%7Ce0b9826d-f3f9-41c4-99a8-93a8b200ad78%2F%29

**Comment by abottoms-coder** [comment]
@lfrohlich I replied to the last question I saw in the tradeoffs matrix. Is there anything else on this ticket or should it be closed?

**Comment by lfrohlich** [comment]
@abottoms-coder closing this. thanks for responding to everything! looks like everything has been captured in the tickets.
