### ISSUE TITLE
Verify Admin Permissions Hierarchy and Roles

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1058]
Please review and update to the appropriate permissions
https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2FPermissions%7C67b61c8f-b200-46e8-8e73-b5aa6382a19c%2F%29 

1. Lauren and Alex Review
2. Dmitri give input based on Regional Manager Workshop

AC:
- Update the documentation in onenote (https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2FPermissions%7C67b61c8f-b200-46e8-8e73-b5aa6382a19c%2F%29) 
- Call out any discrepancies between what Lauren/Alex's thoughts and what we hear in the Workshop.

**Comment by amilash** [comment]
This is a no-code ticket. Moving to QWASP review to validate. I believe we have the spec confirmed, which is the scope of this ticket.

**Comment by lfrohlich** [comment]
@ADPennington  have you had a chance to validate the user approvals column?

**Comment by ADPennington** [comment]
> @ADPennington have you had a chance to validate the user approvals column?

yep. lgtm👍🏾 note for future reference: STT data analyst user approval rights connected to #40, which we recently closed for now. we can revisit later after V2 +  UX research.

**Comment by lfrohlich** [comment]
I believe this can be closed out
