### ISSUE TITLE
Conduct and Record Interviews

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#108]
DUPE to #324

Description:
For August - September research cycle, the interviews are conducted and notes are recorded. 

AC: 
- [ ] Interviews are conducted. 

Tasks: 

- [ ] Conduct the interview with the recruited participants
   - Moderator
   - Note taker(s)
   - Observer(s)
- [ ] Consolidate notes if there was more than one note taker
- [ ] Record and store notes in permission restricted folder

DoD: 
 - [ ] Documentation: notes are stored in a secure, restricted folder

**Comment by lfrohlich** [comment]
DUplicate
