### ISSUE TITLE
Update ADRs

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1082]
Upon review of our 15+ ADR documents, it seems some of them are just pro/cons list without a definitive "yes we did this" and the language is hesitant. For clarity of onboarding moving forward, I suggest a series of edits reaffirming the decisions made therein and general updates. If need be, deletion or some ADRs may be warranted for reducing duplicative records or their obsolete nature. 

Acceptance Criteria:
- [ ] All ADRs should have clear, definitive language affirming the decision was actually implemented
- [ ] All ADRs should be up to date to the best of our knowledge
- [ ] All obsolete or out-dated ADRs will be deleted or merged with relevant ones

Tasks:
- [x] Update ADR 001 template 
- [x] Update ADRs 002 through 008
- [x] Update 009 through 012
- [x] Update ADR 009 diagram
- [x] Update ADR 013
- [x] Update ADR 014 
- [x] update ADR 015
- [x] Decide on ADR 016
- [x] Update ADR 017 (maybe rename based on above decision)
- [x] Sync with [our workflow](https://hackmd.io/tC1rZryATLOx-wgum7u2DQ#If-a-design-issue-is-done-and-needs-to-be-handed-off-to-Dev-team)

**Comment by amilash** [comment]
When do we want to bite the bullet and do this update work?

**Comment by abottoms-coder** [comment]
Live linked gitflow ADR here:
https://hackmd.io/UWE4n0nSS_acTRfbakAPdw

**Comment by abottoms-coder** [comment]
Met with @ADPennington , we will each manage the ADRs and reconvene early next week for mutual review. She will take odd numbered ADRs and I will take even numbered.

**Comment by abottoms-coder** [comment]
While working through I feel we have a redundant file:
https://github.com/raft-tech/TANF-app/blob/issues/1082-ADR-edits/docs/Architecture%20Decision%20Record/008-deployment-flow.md

This is redundant to the readme here: https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/TDP-environments-README.md

And could be merged with this other ADR:
https://github.com/raft-tech/TANF-app/blob/issues/1082-ADR-edits/docs/Architecture%20Decision%20Record/014-deploy-strategy.md

We could merge 8 and 14, delete 8, or leave the branch as-is.

**Comment by ADPennington** [comment]
> While working through I feel we have a redundant file: https://github.com/raft-tech/TANF-app/blob/issues/1082-ADR-edits/docs/Architecture%20Decision%20Record/008-deployment-flow.md
> 
> This is redundant to the readme here: https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/TDP-environments-README.md
> 
> And could be merged with this other ADR: https://github.com/raft-tech/TANF-app/blob/issues/1082-ADR-edits/docs/Architecture%20Decision%20Record/014-deploy-strategy.md
> 
> We could merge 8 and 14, delete 8, or leave the branch as-is.

@abottoms-coder i vote to merge 14 into 8 and delete 14. the others following 13 will need to be renumbered.

**Comment by ADPennington** [comment]
12/27/2021 Update:
- ADR 005 now acknowledges decision to leverage 2 new authentication services (ACF AMS and NextGen XMS
- ADR 006 provides context on what we mean by ATO process being "simpler" 
- ADR 007 provides context on why we're using S3 buckets and lays out implications
- ADR 008 reorganized for clarity around 2 different decisions: (1) moving away from the concept of a 4-step deployment flow and (2) creating 4 spaces within the dev environment

**Comment by ADPennington** [comment]
12/28/2021 Update:

Reviewed and/or updated ADRs 009 - 012, and 014.
- 009 simplified with workflow embedded in dropdown. reference to exceptional workflows (e.g. dependabot PR review) added. The diagram needs revision and I've asked @sreedevip to take the lead on this based on the updates herein. **Note:** some referenced links arent pointing anywhere yet. 
- 010 added missing section
- 011 embedded restaging steps within a dropdown
- 012 added reference to other program office using clamav
- 014 reorganized and added frontend dependency review process re: a11y as documented in #1449 (which now needs to be refined to implement config change. 
- 016 suggested moving this out of ADR subdir and into tech doc subdir.

**Comment by ADPennington** [comment]
12/29/2021 Update:

Reviewed and/or updated ADRs 013, 015, and 017. 
- 013 -- minor formatting fixes and re-org
- 015 -- minor formatting fixes and re-org
- 017 (zap) -- formatting fixes and added justification for why we have zap in the first place and added link to other program office that leveraged the waiver. 

This completes my review of all ADRs. When the PR is out of _draft_ mode, links should be filled into the appropriate ADRs, renaming/renumbering will also need to be accounted for.
