### ISSUE TITLE
As an OFA analyst, I can log in to my account 

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#11]
Description: Create a UI based on mockup for login screen #7 and incorporate #3. 

AC:
- [ ] OFA analyst is redirected to login.gov to login 
- [ ] OFA analyst sees a placeholder page with a placeholder welcome message

Tasks: 
- [ ] Render welcome page based on user role
- [ ] Setup page access based on role

DoD:
- [ ] minimum 90% code coverage test
- [ ] 0 linting errors and warnings
- [ ] 0 accessibility errors
- [ ] deployed to a dev environment
- [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities

**Comment by lfrohlich** [comment]
Covered in #56 #57 #61 #65
