### ISSUE TITLE
As OFA tech lead, I need to update ATO docs for release 2

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1104]
### Boundary diagram updates needed: 
Need to add a route from backend to TDRS (Sftp nightly transfer) for tribal MVP. This edit should be made to a 2nd (temp) version of the boundary diagram. 

### SSP updates needed
Need a 2nd (temp) version of SSP that includes the 2nd version of the boundary diagram referenced above). 
Add email service

### CMP updates needed
Need a 2nd (Temp) version of configuration management plan that includes env variables to connecting to ACFTitan server

### O&M updates needed
Need a 2nd (Temp) version of operations and maintenance manual that includes env variables to connecting to ACFTitan server

ACs:
 - [x] 2nd version of boundary diagram created to reflect release 2 data flow
 - [ ] 2nd version of SSP created to reflect release 2 boundary diagram
 - [ ] 2nd version of CMP created to reflect ACF Titan env vars
 - [ ]  2nd version of O&M created to reflect ACF Titan env vars

**Comment by ADPennington** [comment]
@valcollignon this can be tagged for release 2.

**Comment by stevenino** [comment]
Can start when #1133 is worked
