### ISSUE TITLE
TANF Aggregate Data (03) File Parsing - As a data analyst, I want my data files to be parsed so that my submission can be validated/accepted by TDP

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1110]
Description:
Parsing of TANF STT submissions for Aggregate Data.

AC: 
- [ ] Data File parsing logic is in place such that data file submission can be completed by user and parsed by system for full submission once errors are resolved.
- [ ] Data Errors tell user specifically where in the file they occur, and therefore what exactly needs to be fixed in order for the submission to be complete
- [ ] TDP gives the user all data errors for a submission in a way they can easily save or export so they can take the issues back to their case management software and fix the issues then recreate an export for resubmission to TDP.
- [ ] Data Errors must be issued in human readable plain language so that an english speaker can easily understand what is needed. 
- [ ] T6 records will be split per calendar-month vs the multi-month record via Section3 Field pdf descriptor.

Tasks: 
- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities

Supporting Documentation:
- [TDP workbook](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTDRSResearchDesign%2FShared%20Documents%2FDev%2Fdev%2FParsing%2Fdata%2Ftanf%2FSection3&viewid=981949f0%2D98e1%2D4ace%2D8da8%2D436aca592a46)
- [TANF parsing notebook](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTDRSResearchDesign%2FShared%20Documents%2FDev%2Fdev%2FParsing%2Fhtml&viewid=981949f0%2D98e1%2D4ace%2D8da8%2D436aca592a46&noAuthRedirect=1)
- legacy documentation
  - https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_report_section1_10_2008.pdf 
  - TANF Data Report - Section 3 - TANF Aggregated Data Collection For Families Receiving Assistance Under The TANF Program
https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_report_section3.pdf

Open Questions:

- how difficult would it be to parse the T6 record such that there is one record per state and month VS per state and quarter? Note: this would require mapping calendar qtr to rpt_month_year (see section 3 portion of parsing notebook for example)

_one record per state and quarter (TDRS)_
![1110p2](https://github.com/raft-tech/TANF-app/assets/63075587/587a3300-5bd1-4638-98c7-d8fccecfa90e)

_one record per state and month (TDP?)_

![1110p1](https://github.com/raft-tech/TANF-app/assets/63075587/b08aeda4-3b62-4580-86cf-fe0f1dd60886)

**Comment by ADPennington** [comment]
@Smithh-Co added TANF Section 3 documentation
