### ISSUE TITLE
UI Scaffolding Updates based on PR feedback

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#112]
Description:
Based on the feedback on [PR #37](https://github.com/HHS/TANF-app/pull/37) (which has been merged), this story is to address the changes recommended there. 

AC:
 - [x] Update the favicon to use the USWDS flag (instead of the default React icon) 
![image](https://user-images.githubusercontent.com/7072066/89814811-ba046a80-db11-11ea-881f-9e196a09c050.png)
 - [x] Remove the `private: true` flag from `package.json` since there's no need to prevent publication, as it's an open source project.
 - [x] Install missing peer dependencies: `eslint` and `jest` (which resolves `warning` output from `yarn install`)
 - [x] Add `.gitattributes` to treat `yarn.lock` as binary blob, so it doesn't show up in diffs -- cleaner PR diffs
 - [x] Ignore auto-generated Cypress directories

DoD: 
 - [x] minimum 90% code coverage test
 - [x] 0 linting errors and warnings
 - [x] 0 accessibility errors
 - [x] deployed to a dev environment
 - [x] all significant changes have been documented
 - [x] free of high and medium security vulnerabilities

**Comment by lfrohlich** [comment]
This is complete
