### ISSUE TITLE
TANF Active Data (01) File Parsing: As a TDP Platform I reject garbage files that dont pass pre-parsing error validation.

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1127]
### Description

_Before_ parsing each record of the TANF Data Report Section 1 file (i.e. TANF Active Data file), the legacy system, TDRS, currently checks the file for the following:

1. Are the file types and naming conventions valid? (e.g. is it a flat file with the ADS.E2J.FTP#.TS## naming convention?)
2. Does the file have a valid record layout? (e.g. if the file name indicates that it is a section 1 file, are the appropriate section 1 record types included in the file and do the records have the appropriate length?)

These are referred to as "_pre-parsing_" checks since the system will reject and discard the file _before_ it is fully parsed if an error is encountered during one of these checks. This rejection is an indication that the system doesn't know how to parse the file given the content therein.

---
As of May 2022, TDP:
- checks the [file type](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-frontend/src/components/FileUpload/FileUpload.jsx) upon upload [ #430]
- scans submitted files for viruses and throws out any where one is found and stores the remainder in S3 [#817]
- does not yet check if the uploaded file is blank [#1215]
- can accept the expected file naming conventions as documented [here, for example](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/states.csv) but will also accept files that are not named this way, which is a welcomed departure from TDRS rules. 
- does not yet check that the file has a valid record layout. This check involves parsing the file content by record type, record length, report month,  case number , and disposition to help determine how, if at all, to parse the full file. More background and logic for this check is available here [See "pre-parsing" section of the TANF Parsing Notebook](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/Shared%20Documents/Forms/AllItems.aspx?viewid=6ecbc5f1%2Dfa9c%2D4b0a%2Da454%2D35e222e8044e&id=%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fdev%2FParsing%2Fhtml).

The goal of this ticket is to ensure that TDP verifies that files uploaded as Section 1 data have the correct content to justify parsing it using Section 1 parsing logic. If not, the file should not be parsed, and the reasons why should be made available to the STT. 

### ACs:
- [ ] If the file section is "Active Case Data", then record types should be T1, T2, and T3
- [ ] If the file section is "Active Case Data", then all T1 records with DISPOSITION == 1 should have a length >= 156
- [ ] and so on.... see comment [here](https://github.com/raft-tech/TANF-app/issues/1127#issuecomment-894477260)

### Supporting Documentation

- See [here, under "How does TDRS determine that the data are acceptable to be stored?"](https://github.com/raft-tech/TANF-app/blob/develop/docs/Background/Current-TDRS.md#faqs). Includes links to pre-parsing research and code + parsing code. 

### Open Questions:
- Is it better to verify that this is a section 1 file via "pre-parsing" checks first (I.e. if/else approach) or attempt to parse the whole file and return errors only if discovered? (I.e. try/except approach)?

**Comment by amilash** [comment]
@ADPennington , @abottoms-coder can you pair on writing subtask or tickets for the new metadata logic and make sure the spec in the notebooks has everything we want in it (or add to it?)

**Comment by ADPennington** [comment]
@abottoms-coder some notes below as background for our pairing session, as discussed during 8/6 tech sync: 

### Current TDP reportfile [metadata](https://tdp-backend-staging.app.cloud.gov/admin/reports/reportfile/1/change/):

- Original filename
- Slug
- Extension
- (Fiscal) Quarter
- (Fiscal) Year
- Section (**note**: _only 4 types currently captured, we might need 12: 4 per program type: TANF, Tribal TANF, SSP_)
- Version
- User
- STT
- File 

### Pre-parsing checks that need to be implemented in TDP 
Please note:
- the table below includes a little background to help with your review of the pre-parsing section of the notebooks
- Numbering below is a reference to the pre-parsing checks in the abovementioned notebooks
- The checks below should align with those documented in the [errors that block parsing](https://app.mural.co/t/raft2792/m/raft2792/1624455269095/a03c7a41f537ee50530451e7cb2a26fa11d2c9e6?sender=alexandrapennington7597) section of the mural board. I left yellow stickies on this board to note any differences

| Check | Suggested metadata to rely on | Other notes | 
|--|--|--|
| 2. Check the types of records on the file. | Section | consistency chk between Section _and_ record types; record type needs to be parsed for this |
|3. Check the length of the records on the file. | Section | consistency chk between Section, record type, and length; record type and disposition needs to be parsed for this |
|8. Header record encryption ind in-range| STT | we know which STTs are sending files w/ encrypted SSNs. documented [here](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/tdrs-backend/tdpservice/stts/management/commands/data). We only want to apply decryption logic on files that we expect to be encrypted. Else SSN digits could be erroneously changed during parsing step. |
|10. Report month/qtr consistent with quarter selections| Section, (Fiscal) Quarter, (Fiscal) Year | consistency chk between section, quarter, year _and_ report month or report quarter; report month or report quarter needs to be parsed for this |
|12. Case number in sequence| Section | report month and case number must be parsed for this|
|13. Cases present across record types| Section | report month and case number must be parsed for this|
|14. Check for duplicate cases| Section | report month and case number must be parsed for this|

**Comment by ADPennington** [comment]
@andrew-jameson @reitermb i updated the ticket description feel free to add clarifying Qs in the open question section + any comments for further discussion. cc: @stevenino @lfrohlich

**Comment by ADPennington** [comment]
per 5/13 cross-product sync, closing this ticket. it will be satisfied in #132.
