### ISSUE TITLE
Django admin button color update

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1131]
https://www.acf.hhs.gov/digital-toolbox/visuals/visual-style-guide 

The Django admin console uses a slightly different blue than the color guide for ACF. This is a nice to have and not fully essential as it is an internal facing tool, however while we're building, we should get it right.

- [ ] Update Button colors
- [ ] Do a check on other colors and style guide preferences
- [ ] Update as needed, so we are in alignment with the style guide

Thanks!

**Comment by valcollignon** [comment]
Not a priority. Can change on the admin page https://tdp-backend-staging.app.cloud.gov/admin/admin_interface/theme/1/change/. We might want to look into making this the default going forward.

**Comment by robgendron** [comment]
@ADPennington @ttran-hub Please confirm if still needed.

**Comment by robgendron** [comment]
Add to the admin session -7/17 please @reitermb

**Comment by reitermb** [comment]
Already implemented, this was pre django508
