### ISSUE TITLE
How does the government grant access to the system using login.gov?

### ISSUE THREAD

**Issue by cmajel** [raft-tech/TANF-app#114]
Description:
This may very well be a duplicate ticket; please close or migrate if this is covered elsewhere.

We're using login.gov for account creation, but we know there is an additional need to approve an account to have access to the system. This is a place to discuss how this will be managed.

<needs refinement>
AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

Adding some notes from the conversation with the Login.gov team:
* It's common for partners to integrate an identity and access management system (IAM) into login.gov when users first enter the system. They support any integration over SAML or [OIDC](https://developers.login.gov/oidc/) which is industry standard and their recommended approach. 
* They mentioned that a few HHS applications have a login.gov <> IAM integration, and mentioned [Okta](https://www.okta.com/products/) as one that's been used
* The login.gov team is happy to answer questions about integrations if its helpful

Open Questions:

(any clarifying questions in support of the issue)

**Comment by cmajel** [comment]
cc @lauraGgit who I'm sure has thoughts on this.

**Comment by adamcaron** [comment]
Yes this is a good question. 
- How does a new user get added to the Login.gov team/partnership? 
- Who does the adding?
- The person who does the adding: how do they know when there's a person to add? Who reaches out to them?
- For someone who wants to be added - or if a state admin wants to add a data preparer for her state, how does she know who to contact? How does she even know she _needs_ to contact someone to get the new data preparer access to Login.gov?

**Comment by shubhi-raft** [comment]
dupe to #211

**Comment by shubhi-raft** [comment]
@alexsoble @carltonsmith Do we need to discuss this?

**Comment by amilash** [comment]
@dk-ui is this part of the research for authentication requests, or is it moot and I can close since we're already integrated with login.gov?

**Comment by dk-ui** [comment]
@amilash Correct, this is part of the access request workflow work. This can close. :)
