### ISSUE TITLE
As a data prepper, I want to evaluate mockup of all the data uploaded for my STT 

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#116]
**Description:** 
Getting data to OFA can be a collaborative effort between many people and users from the same locality (possibly counties) may need to see each other’s work. We want to evaluate how users that are part of a particular STT view of a list of all the uploads for my STT so they can work with colleagues to build their submission. To do so, we will create wireframes for evaluative testing during the Round 3 of the user research. 

**Questions**
1. What does "This can be similar to the prototype transmissions view" mean?
2. Should this done by section by section?
3. Should revision history be shown? Should status (e.g., created, edited, uploaded, finalized, etc.,) of uploads be shown?
4. Is this only for data prepper or for all STT admin/ and other potential STT user types as well?
5. Does this include view and share capability? 

**What will not be done in this issue**:
1. The mockups will not be created as deliverables for Dev team and may not meet all of the USWDS guidelines. 

AC: 
- [ ] Wireframes are created and reviewed 
- [ ] Wireframes are added to #226

Tasks: 

- [ ] Mockup layout for ?
- [ ] Review layout with Dev for any functionality issues and update mockup as appropriate
- [ ] Hold a workshop w/ OFA + 18F to review mockup and gather any feedback
- [ ] Update mockup as appropriate

**Comment by matthewjdoty** [comment]
@lfrohlich, this has been marked as a duplicate, can we close it?

**Comment by lfrohlich** [comment]
@matthewjdoty  what is this a duplicate of?

**Comment by amilash** [comment]
is this still needed? @dk-ui @lfrohlich ?

**Comment by lfrohlich** [comment]
@dk-ui  do you think this is captured elsewhere? I don't fully know what we were getting at originally

**Comment by dk-ui** [comment]
@lfrohlich @amilash This was to help accommodate larger STT teams that have multiple data analysts. Definitely a future (very future) feature from my view. More research would be needed to understand what data analysts need to see in regards to what other data analysts in their office upload when someone is out sick for instance. As to what was tested in round three, we played around with the versioning of files as a V1 feature for this ask. See image ![image.png](https://images.zenhubusercontent.com/5f31541dba4d1b90dabcf906/6b6e5826-3c9e-4588-851b-d1a9424401e0)

**Comment by dk-ui** [comment]
We can capture the ask for this ticket within the ideas board in the product board but I don't think it deserves a ticket at this stage of the project.

**Comment by amilash** [comment]
Okay, moving to V4. Thanks.

**Comment by valcollignon** [comment]
This ticket has been duplicated by the resubmission epic. Specifically, the submission history page. Can we close this issue @lfrohlich ?
CC: @ADPennington @sreedevip @reitermb

**Comment by lfrohlich** [comment]
Closing this as a duplicate
