### ISSUE TITLE
Browser Compatability

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1163]
What are our current browser compatibility requirements?
Currently TDP works on all browsers except IE. 
Do we need to support versions of IE and if so which ones.
@lfrohlich  @ADPennington Lets discuss.

**Comment by ADPennington** [comment]
maybe worth an inquiry (perhaps via secondary research where possible) at the permission group-level. I think ofa admin, ofa user, and ofa sys admin groups use chrome primarily but im not sure about regional and STT staff. 

I can only authenticate w/  my piv using chrome and edge (which [reportedly](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/#:~:text=If%20you're%20a%20consumer,and%20more%20modern%20browsing%20experience) will replace IE soon-ish). my issue with firefox may be isolated. 

 cc: @lfrohlich @amilash @ttran-hub

**Comment by lfrohlich** [comment]
w/ IE on it's way out I would like to not worry about it, but given the old systems grantees use we may need to think about it. @reitermb could this be something we start asking grantees in workshops? e..g what browser and version they use? Or is there another way we could go about sorting this out? I could also poll the RO staff.

**Comment by reitermb** [comment]
Just to document it here: 
We've encountered several grantees who've used IE—but none so far who don't have easy access to alternatives
