### ISSUE TITLE
TDP Design Documentation

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1174]
We need an overview of all the research docs and 

- [ ] One Note as internal team draft. 
- [ ] Readme for design docs. Table of Contents which lists
     - all design research files, dated and named by "epic and area" topic + description of research track and contents (rather than research round)
     - 
- [ ] Within these be it be clear what key decisions lead to feature adoption, etc..

**Comment by dk-ui** [comment]
dupe close

**Comment by amilash** [comment]
@dk-ui  dupe of what?

**Comment by amilash** [comment]
@lfrohlich  please close this ticket its a dupe.
