### ISSUE TITLE
SPIKE: User Groups Access

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1178]
_Topic_: Now that we know what our user access and permission matrix looks like:
- what does this mean for accessing data? 
- from which storage systems should these data be made available to each user group? 
- from where should user groups access data? (frontend, backend, somewhere else?)

_Important for permission requirements to have parity w/ legacy system (TDRS), especially where piv/cac is concerned._  

### TDRS permission reqs
| User Group| Data access|
|---|---|
|Sys admin | needs piv/cac for: read/write/delete access to raw files + to read/write/delete data in dB; |
|OFA Admin | n/a | 
|OFA User| needs piv/cac for:  read access to raw files  + db username and password to query* dB tables; | 
|Regional OFA staff| no access to raw files or dB; needs piv/cac to access feedback reports on ACF network drive| 
|STT users | read/write/delete access to ACFTitan server folder to transmit raw files; read access to feedback reports sent via email| 

### Notes:
- OFA user will not need access to raw files for TDP, but _**will**_ need to authenticate via piv/cac to query dB
  - query*, in this case, does not mean create, update. OFA users have _read-access_ to dB 
  - query example: 
```
##select all the data from the STRATUM_MOE table for FY20
SELECT *
FROM TANF.STRATUM_MOE
WHERE CALENDAR_QUARTER in (20194,20201,20202,20203);
```
- STT users will need access to historical feedback reports generated throughout each fiscal year

### Questions:
- How will STT users access feedback reports? from what source will these reports be generated, and should these be generated on-demand or after every "successful" transmission (assuming all req data available to generate rpt)? [**digit**]
- Does sys admin currently need piv/cac to access S3 and RDS? If not, how do we change this? [**dev**]

_**this is still in-progress**_

**Comment by abottoms-coder** [comment]
@ADPennington Can we have a call/chat to discuss this spike? I was wondering what actionable items might come out of this and what the intent might be or if we can close as we explore elastisearch/kibana reporting stack.

**Comment by ADPennington** [comment]
closing this ticket, as it is related to the elasticsearch spike.
