### ISSUE TITLE
As an OFA analyst, I need to connect directly to the database, so that I can run custom SQL queries.

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#118]
Description:
(please define the reason as to why this issue is being created )

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
We are not going to allow Analysts or anyone except super users to access the DB directly. Closing as will not do.  This would pose a security risk.
