### ISSUE TITLE
Lo + Hi Fi UX/UI For Parsing Errors

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1181]
What do errors look like in TDP

- An approach to display errors whether its in one batch or sequentially- how does this look and show up in th eapp for users
- A UI for what error display looks like (pop up? In line? Etc?)

**Comment by valcollignon** [comment]
Propose to close this issue. #1200 and #1199 will fulfill this issue.
CC: @lfrohlich @ADPennington @sreedevip @reitermb

**Comment by valcollignon** [comment]
Closed per backlog refinement 12.14.21
CC: @lfrohlich
