### ISSUE TITLE
Errors UX/UI v3.0

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1182]
When we deliver Parsing in V3 we will need to automate errors as well. The old TDRS provided cryptic errors. We will prioritize plain language errors for TDP users as we build new errors into the TDP parsing engine.

**UX lifts include:**
- A "Style guide" mapping language to types of errors TDP will be able to output
- UX for downloadable and in-app versions of error reports (views of all errors relevant to a given file submitted to TDP) 

**Approach**:
- start with the current error format and error types
- ideate human readable / plain language versions
- evaluate with grantee participants (and OFA) 

**Notes:** 
- Detailed commentary on errors types can be found in #1101 

Error Types:

- Pre-parsing errors -- These types of errors are considered to be violations of the expected record layout, so the records are not "eligible" to be parsed or validated. See existing reference material (in UX murals and parsing notebooks) about what these errors are and how to detect them. 

   - Should disallow garbage file types to be uploaded.  

   - Should assess if a file submission is valid for parsing 

   - Should not take into account field length of entries within rows since TDP will not think about the header whereas TDRS did. 

- Out-of-range value errors – These are based on the above mentioned instructions. 

   - Making sure the value of data incoming is defined as the system. i.e. Gender- current system processes a binary and so currently an error is thrown. For TDP, we want to not have this throw an error.   

- Errors re: inconsistent values across data elements within a record – These are also based on the above mentioned instructions (e.g. If SSI recipient = yes, then SSI amount received > $0). 

- Errors re: inconsistent values across related records within a section file – These errors are also based on the above mentioned instructions (e.g. For every family (T1) record for a given month, there is no evidence that at least one adult (T2) or child (T3) associated with the family's case (T1) is a TANF recipient).

**Comment by valcollignon** [comment]
@reitermb to create description for each issue in this epic and will bring items to next UX backlog refinement to build AC with team
CC: @sreedevip @ADPennington @lfrohlich

**Comment by robgendron** [comment]
All associated tickets are closed.
