### ISSUE TITLE
Permitted users for login.gov authentication 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#12]
Description:
Who decides which individuals get invitations for accounts?

Question - Does OFA admin user group send invitations? Or, it is subset (super user) within the OFA admin group that can send invitation?

AC:
- [x] List of individuals (super users?) who can send invitations to users
- [x] List of individuals(super users?) who can delete users

DoD:
- [x] List is received from the PO and shared with the Dev team

**Comment by shubhi-raft** [comment]
Questions:
1. Who we need to talk to in OFA?
2. Do we need to talk to STTs? Which ones and who they are?

**Comment by lfrohlich** [comment]
From OFA, you would want to talk with the data team (Alex, Thomas, and Yun), tribal TANF (Denise/Elma), and  maybe a regional office representative too (Shantel from RO 4 or Christina from RO 3). Is this better as one convo or separate? 

I think talking to STTs about their roles and needs as it relates to user groups is a good idea to incorporate into the user research plan. 

I think permissions based on groups, but can discuss.

For these specific AC, I think Alex, Thomas, Yun, and myself would need to be able to add and delete users as OFA administrators.

**Comment by shubhi-raft** [comment]
Got it; OFA admin is the only user group that can add or delete users.

To do - ask STT about their roles and user needs as it relates to user groups and how they manage the data submission. Plan to incorporate questions around this topic in the research plan.

@lfrohlich moving this ticket to review. if it looks good, feel free to close it.

**Comment by lfrohlich** [comment]
Looks good to me, thanks

**Comment by shubhi-raft** [comment]
Based on the sprint review for Sprint 0, this may need to be discussed more. Issue #[40](https://github.com/raft-tech/TANF-app/issues/40) has been created as a follow-up. 

fyi @lfrohlich

**Comment by lfrohlich** [comment]
Completed tasks. Closed.
