### ISSUE TITLE
As a data prepper, I can see the data I uploaded so that I can assess it's completeness

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#121]
Description:
It can take multiple data sources to create a complete data submission.

- Design considerations for a future UI - look at extranet
- Consider how manual data entry and correction will be supported in a new system.
- Consider what it would look like if a user provides an incomplete data file.

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
This is done. Closing.

**Comment by amilash** [comment]
This is done. Closing.
