### ISSUE TITLE
Notifications and Comms (V2)

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1214]
Link UX + Engineering tickets related to this epic.

TDP App Notifications/Comms Epic
Goal: First Value add on top of better tech. Enhancement of UX + need to elucidate submission status' to users.
Priorities
- Submission Status Items
- Comms Management Items
Submission Status: Folks can now know what's up with their submission status. Lets
**UX Needed:**
- UI for Submission status- In App + Notification (in all or email)
- Aspirational User Journey/User flow Submission Status - Validated
- User Flow Submission Status including notification (in app and email)
- UI emails
- Copy for Emails and in app flow.

Development Needed:
- Submission Status
- In app notifications
- Email notifications (?) https://app.zenhub.com/workspaces/sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/1462

**Comment by valcollignon** [comment]
Removed from V3 due to creation of #1604 per V3 Roadmap Discussion.
CC: @lfrohlich

**Comment by stevenino** [comment]
Need to write backend email tix along with the required email notification tix for pilot program.

**Comment by stevenino** [comment]
@ADPennington I believe this epic is ready to close.

**Comment by ADPennington** [comment]
completed when the last v2 email ticket #1844 was implemented.
