### ISSUE TITLE
V2 Submission Status UX/IO (w Manual)

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1217]
For V2 users will be submitting files. The files then get batch downloaded and back uploaded to TDRS for parsing and submission.
We need a UX whereby users will be notified (as a combination of manually and automated) that OFA Admins can support Users to know the status of thier file submission.

AC:
- [ ] ofa admin needs to know from TDRS when files are in, submitted, be able to communicate errors, and when files are done.
- [ ] STT Data Analysts need to know when their files, have errors, need to have resubmission happen, etc..

- [ ] Journey Map for admins + Users
- [ ] User Flow for admins + users
- [ ] UI designs.

**Comment by abottoms-coder** [comment]
Alex, we will certainly have logging statements in Django Admin about SFTP transfers but there isn't any other notification system built currently that I'm aware of. However, I am not saying an automated e-mail system couldn't be built easily and scoped into our nightly SFTP ticket.

**Comment by ADPennington** [comment]
> Alex, we will certainly have logging statements in Django Admin about SFTP transfers but there isn't any other notification system built currently that I'm aware of. However, I am not saying an automated e-mail system couldn't be built easily and scoped into our nightly SFTP ticket.

sounds good @abottoms-coder ! log entries of the nightly transfers should be sufficient for this, especially since we have the ability to filter w/ #1230 😄 cc: @amilash

**Comment by amilash** [comment]
Thanks, @lfrohlich  closing as per discussion w @ADPennington .
