### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1232]
Reports Epic:
Goal: V3 will have Parsing built in TDP and we will be able to automate reporting.
We have technical info on the current reports.
This is a research priority, but should be a low lift b/c mostly it will be based on the technical spec which we have, and we will need to create and/or update the (Data Model). Priority is Parity, then enhancements.
Approach: A.) Start with existing reports. Automate them and deliver them VIA TDP in app and via email.
b.) build enhanced reporting capabilities under 'analytics' epic.

Needed from UX/Design: For all User Types:
- [ ] Notional User Flow - of in app automation
- [ ] Reports Dashboard UI
- [ ] Report Notifications (in app + email)
- [ ] Current Reports spec- Technical have this from @ADPennington in the one note documents
- [ ] OFA + STT Report Current Journey Map/ User Flows (process, timing/cadence (and what thats based on - technical or compliance), delivery mechanisms)

+ Aspirational Reporting (See Analytics Epic)-> + Value Adds that support OFA in delivering value to Grantees and for programs. What kind of analytics and insights can we enable for OFA and Grantees once we have (Maybe this is separate an Analytics Epic)

Questions:
1. Do we need to have reporting built into TDP at the same time as production data being submitted?  Or can there be a delay and a stop gap for current reporting methods (analog?)? 
2. Do reports get automated currently or are they coming out of  a different system? 
3. Does Reporting need to be in Release 3 with parsing? or can it be V4? 

- Link to Reports research/specs from Alex in One Note [ ]

**Comment by robgendron** [comment]
@reitermb should this include #2909? Is #2933 or #2923 dupe epics? Recommendation: We use #2923 titling.

**Comment by reitermb** [comment]
> @reitermb should this include #2909? Is #2933 or #2923 dupe epics? Recommendation: We use #2923 titling.

I'm good with that recommendation. 2909 is scoping previously un-scoped parts of the 3.4 Elastic & Kibana refinement epic with the idea being that we're effectively walking on a follow-on piece of that in 4.0 so technically I think we're either putting it under the umbrella of Admin Console improvements (which it doesn't really belong under) or need a Data Reporting 4.0 epic.

**Comment by robgendron** [comment]
Deemed closed by team.
