### ISSUE TITLE
IPv6 requirement based on executive order - FY23

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1238]
https://en.wikipedia.org/wiki/IPv6 
https://www.hhs.gov/web/governance/digital-strategy/it-policy-archive/complete-transition-to-ipv6-memorandum.html

TDP now must be compliant under executive order with IPV6.
•	All new networked Federal information systems must be IPv6 enabled NLT FY2023

The implementation of Internet Protocol version 6 (IPv6) continues to be a top priority for agencies and the end of FY21 is quickly approaching. OMB Memorandum [M-21-07 ](https://www.whitehouse.gov/wp-content/uploads/2020/11/M-21-07.pdf) requires agencies to complete an implementation plan by the end of the current fiscal year, and the recently released Cybersecurity Executive Order has cross-cutting priorities with IPv6 implementation.

- [ ] Talk to OCIO about what this means

**Comment by abottoms-coder** [comment]
As an aside, ipv6 has been generally implemented to be backwards compatible with ipv4 networking stacks so I'd be highly surprised if cloud.gov isn't already using ipv6 underneath. I think this ticket might mostly be a non-issue as we haven't built a network of systems.

With a quick glance over our logging, ipv4 addresses are present in the frontend logging but typically ivp4 addressing is used as a convenience in modern application stacks. Ultimately, we are beholden to how we communicate with cloud.gov and potentially other services. I think we might want to look over any localhost/127 references and gunicorn/nginx files to see if any ipv4 references need to be updated to ipv6.

**Comment by abottoms-coder** [comment]
Per discussion with @ADPennington, closing.
