### ISSUE TITLE
NIST SPoo8 - Updated Security Controls

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1249]
https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final 

Sept 2020 updated NIST Reqs came out of executive order. We need to know if we need additional compliance and security work to be in compliance. 

Revision 5 of National Institute of Standards and Technology (NIST) Special Publication 800-53, Security and Privacy Controls for Information Systems and Organizations. This update provides guidance on the next generation of the security and privacy controls framework, addressing a need for a more proactive and systematic approach to cybersecurity. Most systems will need to go through the ATO process using the new control sets and will also only have a short time to comply with the EO.

https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/
- Encryption must be FIPPs 140-2 compliant. 
- Data at Rest – must be encrypted.
- ALL SYSTEMS that are funded by the gov’t. no matter where they live; must have their privileged access by using a PIV card and GFE.  This includes low systems. 
- MFA Requirements.  No more accessing systems with just User Name and password.
- All systems must have BOD -18 – 01 compliant throughout the network.
- Privacy Controls are now required for all systems that contain any PII.

**Comment by ADPennington** [comment]
- re: _Adoption of multi-factor authentication and encryption for data at rest and in transit - 180 Days from White House Executive Order issue date of 12 May 2021_

  - TDP requires MFA by default
  - data in S3 buckets and RDS  are encrypted at rest (AES-256 encryption algorithm) by default
  - need to check about encryption in-transit

- re: _Expansion of HSPD-12 – all users with elevated privileges must be HSPD-12 compliant._

  - TDP sys admins use PIV cards to access system; these are hspd-12 compliant. 

- re: _Expansion of Security Information and Event Management coverage – requires development support to configure log collection for application-level logs_

  - TDP currently configured to capture logs of : data submissions, sys admin activities (e.g. approving and changing permissions for users), log-in and logout, virus scanning

- re:  _Acquisition and deployment of Network based and Host based Intrusion Protection technologies in every environment hosting Federal Data_
   - TDP is hosted in cloud.gov. descriptions of its continuous monitoring tools are [here](https://cloud.gov/docs/ops/continuous-monitoring/#automated-components)
   - do we need to discuss TDP-specific tools we use to maintain system security (e.g. clamav, zap, dependabot)

_more coming_

**Comment by ADPennington** [comment]
this feels like a dupe of #1237

**Comment by abottoms-coder** [comment]
Per discussion with @ADPennington, closing.
