### ISSUE TITLE
Multi-factor Auth and encryption for data at rest

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1251]
TDP must be compliant with the following:

https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/ 

Adoption of multi-factor authentication and encryption for data at rest and in transit - 180 Days from White House Executive Order issue date of 12 May 2021
- [x]   Data in transit protection requires leveraging unique web certificates (reduction/removal of general purpose [wildcard] certificates) 
- [x]     Data-at-rest requiring use of encrypted data storage options
- [x]     Expansion of HSPD-12 – all users with elevated privileges must be HSPD-12 compliant.
Acquiring new security tools and expanding scope/coverage of existing tools to improve detection of vulnerabilities and incidents
- [x]  Expansion of Security Information and Event Management coverage – requires development support to configure log collection for application-level logs
- [ ]   Acquisition and deployment of Network based and Host based Intrusion Protection technologies in every environment hosting Federal Data

The White House
Executive Order on Improving the Nation's Cybersecurity | The White House

**Comment by amilash** [comment]
as per @ADPennington 

Alex P. <notifications@github.com> Unsubscribe
10:59 AM (23 minutes ago)
to raft-tech/TANF-app, me, Author

re: Adoption of multi-factor authentication and encryption for data at rest and in transit - 180 Days from White House Executive Order issue date of 12 May 2021

- TDP requires MFA by default
- data in S3 buckets and RDS are encrypted at rest (AES-256 encryption algorithm) by default
- need to check about encryption in-transit

re: Expansion of HSPD-12 – all users with elevated privileges must be HSPD-12 compliant.

- TDP sys admins use PIV cards to access system; these are hspd-12 compliant.

re: Expansion of Security Information and Event Management coverage – requires development support to configure log collection for application-level logs

- TDP currently configured to capture logs of : data submissions, sys admin activities (e.g. approving and changing permissions for users), - log-in and logout, virus scanning

re: Acquisition and deployment of Network based and Host based Intrusion Protection technologies in every environment hosting Federal Data

- TDP is hosted in cloud.gov. descriptions of its continuous monitoring tools are here
- do we need to discuss TDP-specific tools we use to maintain system security (e.g. clamav, zap, dependabot)

more coming

**Comment by abottoms-coder** [comment]
Per discussion with @ADPennington, closing as dupe.
