### ISSUE TITLE
As a data prepper, I want to be able to assign different statuses to the data (e.g. prelim, final)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#129]
Description:
(please define the reason as to why this issue is being created )

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
Do we want users to assign status, or do we want them to be able to see status and its assigned automatically? My vision for this is that is automatic based on how far the file is through the processing based on statuses that we define based on the engineering. 
Recommend we remove this b/c this will not be a thing that is manually assigned, but automatically updated by the app based on its processing progression.

cc @abottoms-coder @lfrohlich  @reitermb

**Comment by reitermb** [comment]
> Do we want users to assign status, or do we want them to be able to see status and its assigned automatically? My vision for this is that is automatic based on how far the file is through the processing based on statuses that we define based on the engineering. 
> Recommend we remove this b/c this will not be a thing that is manually assigned, but automatically updated by the app based on its processing progression.
> 
> cc @abottoms-coder @lfrohlich  @reitermb  

I believe this was originally describing something that would be a post parity enhancement. It stems from something we heard from grantees about potentially wanting to be able to evaluate (for errors) or draft a file with TDP without also having to submit it for OFA review. This is similar to what a lot of folks are used for in their own systems or in fTANF.

@lfrohlich does that sound like what you had in mind with this ticket or am I describing something else?

**Comment by lfrohlich** [comment]
@reitermb  i think that's right. this is a post-parity, and I agree that it should be automatically assigned until a future enhancement that allows for draft files, pre-submission. closing for now
