### ISSUE TITLE
TDP Stores Security Clam AV scans for HHS Compliance

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1291]
In order for TDP to be in HHS compliance, we need to store all of our security scans and enable HHS the ability to have access as needed to download them should an audit arise.

Types of scans we need to store ( @abottoms-coder  and @jtwillis92 will you add the details here):
- [ ] Logs from Clam AV scan results during Data File uploads. It may be helpful to tie these to a `LogEntry` model instance so they can be viewable in the Django Admin.
- [ ] Link log entry to file object that will allow us to reference the file and user
- [ ] Will use custom model filters in DAC to find CLAM AV-only records and can then further filter by month
- [ ] We can store these in TDP Cloud.gov S3 and have admins users to access them via a link in Django admin.

Acceptance Criteria:
- [ ] TDP Store all security scans indefinitely
- [ ] These scans should be stored organized by month.
- [ ] They are easily accessible and can be downloaded by TDP Admins and or HHS directly
- [ ] stored scans are legible for what type, and when the scan occurred  (named and dated)
- [ ] TDP Documentation is created for where scans are located and how to access them

**Comment by jtwillis92** [comment]
One thing to note - in the event of a failed ClamAV scan we do *not* store the rejected file so there will be no link to a file for those types of Log Entries. Will determine what additional information can be provided with the log.
