### ISSUE TITLE
As a data analyst, I can submit a file (so it can be parsed)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#131]
Description:
(please define the reason as to why this issue is being created )

AC: 

- [ ]  blank fields, wrong format, out of range, conflicts between fields, etc. 

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
This is done.
