### ISSUE TITLE
[Spike] Evaluate method/lift of a research-oriented TDP environment

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1314]
**Description:**
As TDP starts adding more functionality, some pieces may be better evaluated (usability & concept tests) in TDP rather than in a clickable prototype. Research could use a version of TDP that can be accessed easily during research sessions (read as: no account creation / complex / 2FA login process). This ticket evaluates whether the env variable used for pa11y gets us mileage toward this and if not how else we can achieve it. 

**Tasks:**
- [x]  Dev design sync on this topic
- [ ] Document process for using proposed environment for research, or any other meeting notes

**Meeting Notes:**
UX would like to:

- Be able to smoothly give users access to an instance of TDP for research session use only (i.e. not full pilot real usage)
- If we can remove or diminish the barrier of logging in / 2FA / access requesting etc... that's ideal. 
  - Problematic for security controls to have no login / also the sharing of the password each time
  - setting up test users in this environment could be beneficial for dev troubleshooting too (e.g here's your UN/PW)
    - Like the XMS button we could just point the login button toward the auth method for those test users
    - Unknown dev lift to get back to the basic django login—likely relatively small
    - Would likely live in dev or in staging
    - Most immediate need is the django auth setup. A new environment is a single hour task. Other unknowns about balance of this with sprint work / pilot prep. Worst case scenario is probably 3-5 tickets of 3-5 pts each, respectively covering frontend, backend, environment, covering edge cases around these test users and our user model. Optimistic is two tickets of 5pts or less.
      - The first thing up in ticketing would be "How do I create an admin user that can login to django admin backend" — By doing this we could predict the remaining lift needed to 
- Staging access?—ability to test stuff without it being 100% QASP'd, 
  - Just a matter of the deploy label for an environment

**Comment by stevenino** [comment]
@reitermb to schedule meeting week 5/2/22

**Comment by stevenino** [comment]
Held meeting on 5/3/22. Path forward is to create a new epic to capture the work to create a research oriented TDP environment.
