### ISSUE TITLE
[Spike] Backend Email System

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1335]
**Description: **
To enable all comms, TDP needs a backend automated e-mail system. This should be secure, preferentially with signed messages to prevent spoofing and mitigate phishing. Find the best solution for our needs and stack.

**Acceptance Criteria:**
- [ ] Evaluate a solution which is easily controllable and maintainable
- [ ] Solution should ideally have the ability to have certified/signed messages
- [ ] Cost analysis

**Timebox**:
 - 8 hours

**Notes**:
- What are the compliance implications? Do we need to use an ACF email server? 
  - we have been told (per IPT 4/6/22) that we need to use HHS mail relay

**Supporting Documentation**:
 - https://github.com/cloud-gov/pages-mailer
 - https://aws.amazon.com/ses/
 - https://www.mailgun.com/smtp/free-smtp-service/free-open-smtp-relay/

**Comment by abottoms-coder** [comment]
Potential solutions:
https://github.com/cloud-gov/pages-mailer
https://aws.amazon.com/ses/
https://www.mailgun.com/smtp/free-smtp-service/free-open-smtp-relay/

**Comment by stevenino** [comment]
Need to discuss at TDP IPT meeting on 4/6/22. Once there is clarification on the email server requirements we can move forward with this spike ticket.

**Comment by lfrohlich** [comment]
do we need any more info before initiating this spike now that we know we need to use HHS mail relay? @abottoms-coder  cc: @stevenino @ADPennington

**Comment by stevenino** [comment]
> do we need any more info before initiating this spike now that we know we need to use HHS mail relay? @abottoms-coder cc: @stevenino @ADPennington

To me this spike either goes away or gets repurposed since we no longer have to evaluate different email servers.

**Comment by abottoms-coder** [comment]
In my view, we should close this ticket. Once we have dev-actionable information from HHS, we would write a new ticket and prioritize it.

**Comment by lfrohlich** [comment]
we should discuss what dev-actionable info we need

**Comment by stevenino** [comment]
Not required since HHS email server (ironport) has to be used per backlog refinement on 4/12/22
