### ISSUE TITLE
As an OFA analyst, I can see the validation errors for a file so that I can help the data prepper troubleshoot.

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#134]
Description:
OFA Analysts act as support to STT's. This role will need to have read access to the STT upload error files, as well as the file submitted that is throwing an error. 

AC: 
- [ ] OFA Analyst has read access to STT upload errors
- [ ] OFA Analyst has read access to STT upload files
- [ ] OFA Analyst can find the right upload/error files because they can see the metadata and find them by (filtering/sorting)by STT, Submission status,  date and quarter, etc..

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by stevenino** [comment]
Closed as OBE
