### ISSUE TITLE
[SPIKE] Test hero images in code & adjust spec accordingly

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1346]
Problem Statement: The div where the login button/text is displayed blocks core parts of our new background images and we'd like to see about modifying it and/or images to better fit. 

Questions: 
 - Can the textbox be right-aligned? 
    - (Miles) I'd think this would be pretty easy technically. I'm hesitant to default to that solution though for a11y & general design heuristic reasons—aligning core elements of a page to the right while everything else is left aligned. 
 - Does the new position still look good across the more common screen resolution sizes?
This is a follow-on to #1331 

AC: 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [x] Decision is documented for how to proceed (e.g. as is, right aligning the login box, changing how the background images are displayed, etc...)

Tasks
- [x] Evaluate how the background images look with the current page (in code; current prototype can be accessed here https://reitermb.github.io/TDP-Project-Update/)
- [x] Ideate/prototype solutions & improvements
- [x] Check for accessibility

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by reitermb** [comment]
"1/4 - 3/4" login - hero image idea too

**Comment by reitermb** [comment]
Update—probably best achieved via modifying the images themselves. Photoshopping in some new space to the left of each.

**Comment by valcollignon** [comment]
Demo by @reitermb / 11.23.21

**Comment by valcollignon** [comment]
Should be completed during holidays per sprint planning 12.21.

**Comment by reitermb** [comment]
Reviewable images are in our coded design demo environment here: https://reitermb.github.io/TDP-Project-Update/ 

Let me know if there's anything I missed that jumps out as looking off!

**Comment by lfrohlich** [comment]
These look good to  me!

**Comment by reitermb** [comment]
@lfrohlich Do you have thoughts over whether we should demo this or rather hold off until it's implemented and just demo the code implementation? I just ask since it's an area with a pretty high demo rate already (original image selection, original code implementation, and the squishy version of the image modifications).

**Comment by lfrohlich** [comment]
@reitermb makes sense to wait for code implementation, thanks! I'll close

**Comment by lfrohlich** [comment]
#1532 is follow on for implementation
