### ISSUE TITLE
As a data prepper, I need to be able to edit fields/cells in my file so that I can fill in missing values.

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#135]
Description:

User research findings: 
The TDRS extranet is really missed, especially how it provided a way to submit data and view past data to confirm status
Context for a future design team on what has worked for users in the past.

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by robgendron** [comment]
Deemed no longer needed.
