### ISSUE TITLE
Relocate login textbox on splash page

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1357]
Problem Statement: The text box where the login button is displayed blocks core parts of our new background images and we'd like to see about moving this to improve the page's aesthetic.
Questions: 
 - Can the textbox be right-aligned? 
 - Does the new position still look good across the more common screen resolution sizes?
This is a follow-on to #1331 

AC: 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 
- [ ] [User flow is updated](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

Tasks
- [ ] Explore relocation options for textbox with new images
- [ ] Check for accessibility

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by reitermb** [comment]
Closing as dupe
