### ISSUE TITLE
As a data analyst, I need to be able to indicate whether the resubmission should replace existing data for that quarter

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#136]

**Comment by amilash** [comment]
@lfrohlich the current UX already delineates whether a user is changing a file or uploading a file for the first time ![Screen Shot 2021-07-15 at 11.55.04 AM.png](https://images.zenhubusercontent.com/60afeb64d7f7425008c16536/1a6b2a4f-52c9-422f-8c16-f0fe796885ce)

I think this is done and we can close it, this happens by default already.
