### ISSUE TITLE
As a data analyst, I want to delete a file so it's not confused with a newer, more complete file.

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#137]
Description:
(please define the reason as to why this issue is being created )

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
@lfrohlich our TDP system does versioning, so it will always reference the latest file. There is no need to have the user delete old files. I think we can close this.
