### ISSUE TITLE
Django Admin a11y Fixes (Follow-on)

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1392]
### Description ###
Tickets contained in this epic are centered around making a11y fixes to Django administration for screen reader only users and users with dexterity/mobility issues to at least a WCAG 2.0 AA Standard. This epic exists as part of the technical debt backlog. Thus, tickets in this epic should not be considered in pursuit of immediate compliance. 

### Risks ###
- 

### OKRs ###
-

### Supporting Documentation ###
- Original set of fixes were documented in #1223 and a follow-on epic from #892

**Comment by valcollignon** [comment]
@reitermb @ADPennington @jorgegonzalez and Thomas to meet today 11.2.21 to discuss/refine individual issues.

**Comment by reitermb** [comment]
@ADPennington @ttran-hub All Tickets should now be updated with screenshots! I went for some simple mockups to illustrate some of the ones that are bigger from a visually changing page content standpoint (the sidenav ticket for instance)

**Comment by ADPennington** [comment]
tickets associated with this epic:

#1410 
#1411 
#1412 
#1413 
#1414 
#1415

**Comment by ADPennington** [comment]
@reitermb thanks! @ttran-hub and I just went through and cleaned up this epic a bit and moved some of the notes into the individual tickets! I'll work on coordinating a mtg w/ RJ next. Also, we recommend cleaning up the hackmd such that it captures a synthesis of all the django accessibility issues, including a table that summarizes the issue, the ticket associated with the issue addressing it, and a section that includes any other relevant notes or supporting documentation. Most of the information is already here, so happy to brainstorm on how we can go about restructuring the flow of the md. This cleanup can be tackled after our session with RJ 😄

**Comment by valcollignon** [comment]
Meeting scheduled with RJ on Tuesday 11/16. This meeting will be the basis for prioritizing all tickets in this epic to make sure we're ready to bring into future sprints.

**Comment by ADPennington** [comment]
rescheduled for 11/17.

**Comment by valcollignon** [comment]
Add to backlog refinement 11/23 per @ADPennington / dev sync 11.17.21

**Comment by lhuxraft** [comment]
Created replacement epic in board, closing
