### ISSUE TITLE
As a TDP user, I want to easily navigate to specific pages of the TDP website

### ISSUE THREAD

**Issue by sreedevip** [raft-tech/TANF-app#1417]
AC
- [x] Information Architecture (IA) of the TDP website is captured in a tree-test and includes current and future pages of TDP
- [x] 5-8 OFA participants have taken the test
- [x] Results have been analyzed and findings shared with the team to discuss potential changes to the Information Architecture

Tasks
- [x] Create a tree-test using [Optimal Workshop](https://www.optimalworkshop.com/) or similar tool (e.g. Google Forms) to test the Information Architecture (IA) of TDP that includes both existing and future pages from the Sitemap 536](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/536)
- [x] Administer an unmoderated test among 5-8 OFA participants, who can be recruited from DIGIT and regional managers
- [x] Analyze the results of the test to determine the usability of TDP website IA and the efficacy of Google Forms as an alternative to Optimal Workshop in a comments in a [hackmd](https://hackmd.io/qw6eKlVHT3OQetKYdfe2Dg) 
- [x] Create follow-on tickets for testing with grantees, research synthesis and dissemination

DoD
- [x] Information Architecture has been tested with OFA, i potential changes to IA documented and follow-on tickets created
- [x] @lfrohlich has reviewed and signed off

**Notes**
A good overview of Information Architecture and tree-testing can be found on the [Nielsen Norman group's](https://www.nngroup.com/articles/tree-testing/) website

Once the IA is tested with both OFA and Grantees, then: 
- [ ] Present the findings to the PO and dev. team to discuss changes, if any, to the IA and subsequent lift for the dev. team
- [ ] Makes changes, if any, to the Sitemap on Figma
- [ ] Use the findings of this ticket and follow-on testing tickets to inform the [HTML Sitemap](https://github.com/raft-tech/TANF-app/issues/1385)

Final DoD
- [ ] Information Architecture has been tested and changes made to the IA
- [ ] Changes have been reflected in the Sitemap [536](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/536)

**Comment by valcollignon** [comment]
@sreedevip @reitermb  add to UX sync agenda

**Comment by sreedevip** [comment]
@valcollignon The testing part of this ticket will continue in the next sprint
CC @reitermb @lfrohlich @ADPennington

**Comment by sreedevip** [comment]
Tasks edited to reflect changes discussed in backlog refinement on 12.7.2021. Changes include 
- Testing efficacy of Google Forms by testing IA with OFA users in the first round
- Using findings from this ticket to create a follow-on ticket to test IA with grantees
cc: @valcollignon @reitermb @lfrohlich @ADPennington

**Comment by valcollignon** [comment]
@lfrohlich sent out survey yesterday 12.20. Depending on number of responses received by 1/15/22, this ticket will be in the next couple of sprints.

**Comment by sreedevip** [comment]
Updated DoD to reflect the scope of this ticket. Initial DoD - which captured the scope of testing with both STT and OFA users- moved to the notes section under Final DoD. Changes agreed upon during standup on 1/14/22

**Comment by sreedevip** [comment]
Updated last task to encompass all follow-on tickets

**Comment by lfrohlich** [comment]
@sreedevip i made some comments in the hack.md of the synthesis and follow on tickets. can you add the link to the hack.md synthesis in the description above? Also, noting that AC #4 changes to the sitemap will wait until after testing with grantees

**Comment by sreedevip** [comment]
@lfrohlich 
1. I incorporated/replied to your comments in the  [sitemap synthesis document](https://hackmd.io/qw6eKlVHT3OQetKYdfe2Dg). Post spell-check, comments now appear in reverse order at the bottom of the page 
2. Added link to hackmd in Task #3
3. Moved AC #4 to Final DoD in the ticket
cc: @ADPennington @valcollignon @reitermb

**Comment by sreedevip** [comment]
Follow-on tickets have been created #1591, #1592,#1593 and pulled into newly-created Sitemap epic #1590
@lfrohlich @valcollignon @reitermb @ADPennington

**Comment by lfrohlich** [comment]
Thanks, @sreedevip ! I'm closing this ticket
