### ISSUE TITLE
Sidenav traps focus on close button

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1419]
## Description
When logged into TDP and viewing it at a breakpoint that displays the menu as an openable overlay sidenav focus is trapped on the close menu button. 

![image](https://user-images.githubusercontent.com/28515874/139933330-d28b9258-41f4-4cdd-a1b3-5769b2fbda19.png)

## What I expected to see
Focus should shift as the user tabs through the menu rather than staying locked onto the close button.

## What I did see
Focus stays locked on the close button of the menu overlay. 

## Other Helpful Information
I believe this might be a bug that has reemerged due to removing the extra "Sign In" button in the upper right hand of the unauthenticated TDP landing page. I remember an a11y conversation from over a year ago that led to that extra sign in button due to some nuance of react that was resulting in improper rendering of the authenticated app menu when there weren't any menu items on the unauthenticated page.

**Comment by valcollignon** [comment]
Dev needs to investigate and see when this was introduced.
CC: @abottoms-coder @ADPennington

**Comment by riatzukiza** [comment]
Jorge, miles and I have been working on this, we feel like we are pretty close to done on this. We still have an a11y issue, but we have more control over the elements involved in the problem now, and its just a matter of pushing through some debugging.

**Comment by riatzukiza** [comment]
@jorgegonzalez @reitermb @abottoms-coder

**Comment by valcollignon** [comment]
@riatzukiza working on this issue and hopes to be completed before holidays.

**Comment by abottoms-coder** [comment]
Previously demo'd.
