### ISSUE TITLE
FTANF - As a data prepper, I want to manually input data into the system so that I don’t have to access a different program to prepare files.

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#142]
Description:
User research findings: 

- Creating “a perfect file” is really hard; Data submitters have to resolve downstream data errors, meet TDRS formatting requirements, and wait a long time for feedback.
- +1 to allowing manual data entry in a new system, especially for Section 3 and 4 (which are shorter and mostly aggregate data.)

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by andrew-jameson** [comment]
Closed per Backlog Refinement
