### ISSUE TITLE
As OFA tech lead, I need to update ATO docs for release v1.0

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1422]
_Context_:

**O&M updates needed**
Environment variables in our frontend and backend cloud.gov apps have been updated as part of the production deployment audit ([ref](https://github.com/raft-tech/TANF-app/issues/1778#issuecomment-1128825026)). As such, the Operations and Maintenance manual, which includes descriptions of these variables, needs to be updated.

**Boundary Diagram updates needed**
The placement of the clamAV application in the [boundary diagram](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Security-Compliance/boundary-diagram.md) is different than its placement in the [environment diagram](https://github.com/raft-tech/TANF-app/pull/1070#discussion_r669612382) which is confusing. Also, the boundary diagram description does not currently include any information about ClamAV. Also, references to environment/spaces should probably link to the environment diagram.

Additionally after the ACF AMS integration, the diagram will need to be updated to reflect the different routes ACF and non-ACF users will take into TDP. 

**SSP doc updates needed**
Abovementioned diagram updates need to be embedded in the SSP doc. Also, the django admin screenshots need to be updated to reflect new features (security scans, user profiles, etc). And the user flows embedded in the SSP need to be updated to reflect how ACF and non-ACF users gain access to the system, given new integration with ACF AMS . 

**CMP doc updates needed**
This should be updated with any new information about configuring to and maintaining TDP's secure state, especially as it relates to the new authentication methods and timeframe for addressing critical vulnerabilities (in response to the WH EO on [cybersecurity](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Security-Compliance/WH_CybersecurityEO.md).

**508 remediation plan updates needed**
This should be updated to reflect that django admin is fully 508-compliant upon closing out the final ticket in #1392 

**System Design Document updates needed (_this was initially completed as part of the critical design review_)**
Any elements of this [document](https://teams.microsoft.com/l/file/56B21A41-470A-4082-837F-65D0A3274F75?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FSDLC%2F3_RAR_CDR_TRR%2FTDP_System%20Design%20Doc%20for%20CDR%201.21.21.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) that are being updated in other docs (e.g. boundary diagram, software used) should also be updated here. 

**Appendix X updates needed** 
Relevant access controls should be updated in this [document](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/TDP-%20Controls-MODERATE_AppX_20210426_Technical.xlsx?d=w1defb5806e0d4794819b5a74334011a6&csf=1&web=1&e=zAvVxd) to reflect new authentication methods for acf users. 

**POAM** 
PIV/CAC and OWASP-related issued captured in the most recent version of the [POAM](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/System%20Security%20Plan/TANF-POAM-2021.xlsx?d=w375c3e5f052b40c9a2cb8ed752362cbc&csf=1&web=1&e=brA78I) should be updated to reflect remediation or resolution. The POAM update process documented [here](https://github.com/raft-tech/TANF-app/issues/1185#issuecomment-893520763) should be followed.

ACs:
 - [ ] Update O&M Manual w/ correct ENV variables on frontend/backend Cloud.gov apps + HHS CircleCI project settings 
 - [ ] SSP document needs updated screenshots and associated descriptions of diagrams and user flows. 
 - [x] Boundary diagram updated re: ClamAV placement and authentication methods
 - [x] boundary diagram markdown updated with more description and references to environment diagrams. 
 - [ ] CMP doc updated
 - [x] 508 remediation plan updated
 - [x] appendix x updated
 - [x] System design document updated
 - [x] POAM document updated
 - [ ] TDP ISSO review and approve updated documents

**Notes**
- add env variables to O&M and CMP  for the SFTP file transfer for release 2(#1133).

**Comment by ADPennington** [comment]
@valcollignon this is blocked by #1282.

**Comment by ADPennington** [comment]
@lfrohlich issue summary updated per 12/15 IPT mtg cc: @valcollignon

**Comment by valcollignon** [comment]
@ADPennington updates look great! thank you!
