### ISSUE TITLE
[Draft] As ACF tech lead, I need a list of items, by TDP page, for QA team to check for issues (Release 1) 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1446]
_Context_
Re: #310 [comment](https://github.com/raft-tech/TANF-app/issues/310#issuecomment-970551639)--we need to ensure that the system buttons behave as expected on each page for an authenticated user. 

### Frontend 
authenticated users: `ofa admin`, `ofa data analyst`, `data analyst`, `ofa regional staff`, `developer`

#### [Welcome](https://tdp-frontend-staging.app.cloud.gov/welcome) page (logged in)
- Does sign out button work as expected?
- Does privacy policy link point to a valid webpage?

### Backend 
authenticated users: `ofa sys admin`

---
_Open Questions_
- test on different browsers? if so, which versions? 
-

**Comment by valcollignon** [comment]
Revisit in January per backlog refinement 12.21. Leaving unrefined at this time.

**Comment by stevenino** [comment]
OBE per backlog refinement on 9/27/22
