### ISSUE TITLE
Authentication/Authorization Task Flow Diagram

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#145]
Description:
- Map the task flow for Authentication/Authorization flow to help the dev team create a basic application flow

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Create a task flow diagram to map out user authentication via backend, login.gov and frontend.  

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
This issue will be included as a task in auth user story.

**Comment by lfrohlich** [comment]
Captured as a task in #211
