### ISSUE TITLE
[Frontend Bug] Sidenav menu is blank when user is not logged in

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1451]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

The sidenav menu does not include any links (it is entirely blank). If we intend for users to utilize it to go somewhere (e.g. the appropriate authentication method url), then this should be updated; else we should reconsider whether a sidenav menu is needed on frontend when logged out. 

## Action Taken

- go to frontend staging site (you should be logged out) 
- adjust dimension of the browser window until the menu button appears
- click the menu button and observe results

## What I expected to see

Menu tab includes links to navigate to on the page; else seems like a menu on this page is not needed (as it would probably just be links to the login buttons, unless we wanted to point to other less pertinent links on the page). 

## What I did see

The menu tab on frontend, when logged out, is blank

![menu](https://user-images.githubusercontent.com/63075587/142286492-320220b4-99e4-4ce5-9c03-70cfbddd8891.PNG)
## Other Helpful Information

+ URL of the page I was on: https://tdp-frontend-staging.app.cloud.gov/
+ Browser and version: Version 94.0.4606.61 (Official Build) (32-bit)
+ Operating System:  Windows 
+ Is the issue repeatable?:  yes 
+ Has the issue occurred more than once?: n/a

**Comment by jorgegonzalez** [comment]
![Screen Shot 2021-11-17 at 5 14 45 PM](https://user-images.githubusercontent.com/12901172/142291150-da0f9b8a-ceec-44d4-8ce9-1649614464c0.png)

Just clarifying it does appear when logged in.

This is a useless menu when a user is logged out, in my opinion we should remove the button entirely when logged out cc @reitermb

**Comment by ADPennington** [comment]
> ![Screen Shot 2021-11-17 at 5 14 45 PM](https://user-images.githubusercontent.com/12901172/142291150-da0f9b8a-ceec-44d4-8ce9-1649614464c0.png)
> 
> Just clarifying it does appear when logged in.
> 
> This is a useless menu when a user is logged out, in my opinion we should remove the button entirely in this case cc @reitermb

I agree @jorgegonzalez

**Comment by valcollignon** [comment]
Demo by @jorgegonzalez - 12.21.21
