### ISSUE TITLE
OFA Analyst Task Flow Diagram

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#147]
Description:
- Map the task flow for OFA Analyst to hep the dev team create a basic application flow 

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
dupe to #211
