### ISSUE TITLE
As a sys admin (dev), I can edit names of users through Django admin console

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#149]
Description:
This issue will deliver sys admin (dev) editing names of test users through ~~command line interface~~ the Django admin console. 

AC: 
- [x]  Dev demos updating a user's first and last name

Tasks: 

- [x] demos updating a user's first and last name using Django admin console. 
 

Supporting Documentation:
(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:
(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
@carltonsmith has demoed this functionality to OCIO and product team

**Comment by lfrohlich** [comment]
this was merged as part of #309 on 1/12/21
