### ISSUE TITLE
 Backend service allows authorized admin permission to get list of current roles

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#150]
Description:
OFA Admins need to be able to get a list of all current roles

AC: 

- [ ] Endpoint exists that returns a list of all current roles for authorized users

Tasks: 

- [ ] Test that endpoint returns a list of all current roles
- [ ] Test that only authorized users are able to get the list of current roles
- [ ] Create endpoint that returns a list of current roles

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
dupe to #9

**Comment by amilash** [comment]
see notes in epic. irrelevant
