### ISSUE TITLE
 Backend service allows authorized admin permission to change roles assigned to user

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#151]
Description:
OFA Admins need to be able to update the roles assigned to users

AC: 

- [ ] Endpoint exists to update user roles
- [ ] Only authorized users can update user roles

Tasks: 

- [ ] Test endpoint updates user roles
- [ ] Test only authorized users can update user roles
- [ ] Create endpoint to update user roles

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
This is done and can be handled in our Django Admin. Leaving this open to represent building this work in an admin UI as an enhamcement.

**Comment by amilash** [comment]
This functionality is done and delivered via Django admin console. Closing as done. We can reopen new tickets for when we do work to build permissions management into the TDP UI.
