### ISSUE TITLE
 Backend service allows authorized admin permission to add user roles

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#152]
Description:
OFA Admins need the ability to edit permissions for role

AC: 

- [ ] Endpoint exists that assigns permissions to a role and removes permissions from a role

Tasks: 

- [ ] Test that an existing permission is assigned to an existing role
- [ ] Test that an existing permission that is already assigned is removed from an existing role
- [ ] Test that an OFA admin can execute adding and removing permissions
- [ ] Test that non-OFA Admin (and non-Superuser) users cannot add or remove permissions
- [ ] Create endpoint to either remove or add a role's permission

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
see notes in epic. irrelevant
