### ISSUE TITLE
Backend service allows authorized admin permission edit roles

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#153]
Description:
OFA Admins need the ability to edit user permissions

AC: 

- [ ] Endpoint exists to retrieve a list of all permissions
- [ ] Endpoint exists to retrieve all permissions assigned to a user
- [ ] Endpoint exists that allows OFA Admins to update user permissions (add new and remove existing)

Tasks: 

- [ ] Test endpoint retrieves existing permissions
- [ ] Test endpoint retrieves user's assigned permissions
- [ ] Test that OFA Admins are able to edit user permissions
- [ ] Test that non-OFA Admins (or superusers) are not able to edit user permissions
- [ ] Create endpoint that returns a list of permissions
- [ ] Create endpoint that returns user's existing permissions
- [ ] Create endpoint that updates a user's permissions

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
see notes in epic. irrelevant
