### ISSUE TITLE
Backend service allows authorized superuser permission to assign user OFA admin group

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#154]
Description:
Superusers need to be able to assign OFA Admin role to a user

AC: 

- [ ] Endpoint assigns OFA Admin group to a user when a superuser assigns it

Tasks: 

- [ ] Test that SuperUsers can assign a user to the OFA Admin group
- [ ] Test that non-SuperUsers cannot assign a user to the OFA Admin Group
- [ ] Determine groups of the current user
- [ ] Determine if the user is a superuser
- [ ] Create the OFA Admin group
- [ ] Create Django permission for assigning the OFA Admin group to a user
- [ ] Assign above permission to superusers
- [ ] Create endpoint that will assign groups to users when the user has permission to do it

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
@abottoms-coder can I close this as a dupe of the new permissions matrix stories/epic?
