### ISSUE TITLE
Backend service allows OFA Admin users to create roles

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#155]
Description:
OFA Admin users need the ability to create new roles

AC: 

- [ ] Endpoint exists that creates a new role

Tasks: 

- [ ] Test that system creates a new valid role
- [ ] Test that OFA Admin users can create a new role
- [ ] Test that non-OFA Admin users cannot create a new role
- [ ] Create endpoint that creates a new role

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
see notes in epic. irrelevant
