### ISSUE TITLE
As an OFA Admin, I can create new Roles through the UI

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#157]
### Definition of Done:

- [ ]  minimum 90% code coverage test
- [ ] 0 linting errors and warnings
- [ ] 0 accessibility errors
- [ ] deployed to a dev environment
- [ ] all significant changes have been documented
- [ ] free of high and medium security vulnerabilities

**Comment by lfrohlich** [comment]
We decided we don't want this as a function
