### ISSUE TITLE
V2 Sitemap

### ISSUE THREAD

**Issue by sreedevip** [raft-tech/TANF-app#1590]
This epic captures all aspects of  TDP's Information architecture and includes development and testing of its sitemap.

The way pages are organized in a website, often called its Information Architecture, is an important aspect of the user experience of an application, which has the potential to make navigation of its features a frustrating or enjoyable experience. Easy-to-understand labels, clear call-to-action buttons (e.g. log in) and logical nesting of menu categories contribute towards a friction-less navigation experience for the user.

**Notes**
A concise overview of Information Architecture and tree-testing can be found on the [Nielsen Norman group's (NN/g](https://www.nngroup.com/articles/tree-testing/) website

Information on how to interpret tree-testing results can also be found on [NN/g](https://www.nngroup.com/articles/interpreting-tree-test-results/)

**Comment by stevenino** [comment]
Waiting for Dev tix to be written after #1385 is completed

**Comment by stevenino** [comment]
@ADPennington can we close this?

**Comment by ADPennington** [comment]
> @ADPennington can we close this?

yes
