### ISSUE TITLE
Add fields to user

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#160]
Description:
The backend should have fields for user first name, last name and STT

AC: 

- [ ] Endpoint updates user with first name, last name and STT
- [ ] Endpoint returns user data with first name, last name and STT
- [ ] Endpoint returns all users with first name, last name and STT

Tasks: 

- [ ] Test endpoint updates user with first name last name and STT
- [ ] Test endpoint returns user with first name, last name and STT when it exists
- [ ] Test endpoint returns a list of all users with first name, last name and STT
- [ ] Update user model with the new fields
- [ ] Generate and run migrations to add new fields
- [ ] Create endpoint to update user with first name, last name and STT
- [ ] Create endpoint to return a single user with first name, last name and STT
- [ ] Create endpoint to return all users with first name, last name and STT

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
@carltonsmith is this a duplicate to #309?

**Comment by amilash** [comment]
Dupe, so closing
