### ISSUE TITLE
Discuss and transfer Sprint retro action items to board

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#162]
Description:
Discuss and transfer Sprint retro action items from 8/18 [mural board](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1597770944553/4b4d8d6dca3fe174aca3e66d0e4aa5462289dfe5) to sprint board as issues/tasks.

AC: 

- [ ] Tasks are complete

Tasks: 

- [x] Define Demo Ready and Sprint Done in Team Charter
- [x] Update charter with some language on: 
   - [x] Collaborative sync/review prior and during Gov review
   - [x] Gov review days are good for technical debt, spike stories, documentation, which gives Raft team 7 working days.
   - [x] situations where all user stories in 'To Do' Sprint Board have been addressed, individual can pull from prioritized product backlog 'Ready to go for Next Sprint'

**Comment by shubhi-raft** [comment]
@SelenaJV can you do a quick review to see if we are good on the team charter and accept any of the remaining track changes.

**Comment by SelenaJV** [comment]
Yup. Looks good. Thanks @shubhi-raft
