### ISSUE TITLE
Compile a list of states to learn from and interview for Round 3 (September 2020)

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#163]
Description:
We want to create a list of diverse states, who have had many different experiences and face many different challenges, to focus our research on.

Possible criteria to consider:
* TANF- report generation difficulty (based on survey findings) - High/Medium/Low
* Error-rate
* Resubmission rate
* Centralized vs decentralized states

Outcome: Creating a list of criteria and document why we are choosing STTs and provide a list of STT to interview for the next round of research 

AC: 

- [x] Recruitment criteria is documented. 
- [x] X STTs are recommended to reach out to for Round 3. 

Tasks: 

- [x] Define criteria for recruitment 
- [x] Draft email for OFA to identify states that meet the criteria
- [x] Review the criteria for the previous round of research
- [x] Work with OFA and 18F to quantify any metrics related to the recruitment criteria to establish a baseline for narrowing down STT selection
- [x] Pair findings from OFA interview notes, OFA interview synthesis, and 18F's "Understanding the Local Experience" to strengthen STT selection
- [x] Document the process of how the recruitment criteria was created
- [x] Document the process of how list of states were down selected
- [x] Refine documentation based on feedback from Shubhi and Matthew

DoD: 
 - [x] Documentation: Draft list of states is shared with Lauren and Christine.
 - [x] Documentation: Process of how the recruitment criteria was created is shared with Lauren and Christine.
 - [ ] Documentation: Process of how list of states were down selected is shared with Lauren and Christine.

**Recruitment Criteria and Down Selection Process Documentation Link :** 
https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B1a533a84-0000-423d-8274-c0767d9f471d%7D&action=view

**List of STTs Link :** 
https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc=%7BA12B53AF-3CD1-40C3-93CF-AE26DCD51264%7D&file=Criteria%20for%20STT%20Interviews.xlsx&action=default&mobileredirect=true&cid=0c2f1e51-38fe-4566-ba23-a0f433397358

**Comment by dk-ui** [comment]
@matthewjdoty @shubhi-raft This is ready to review. Let me know if I am missing anything.

**Comment by dk-ui** [comment]
@shubhi-raft @matthewjdoty This is ready to review.

**Recruitment Criteria and Down Selection Process Documentation Link :** https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/_layouts/15/WopiFrame2.aspx?sourcedoc=%7Bcc80d768-1419-4a5e-a3dc-47dc0414ef4c%7D&action=view

**List of STTs Link :** 
https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc=%7BA12B53AF-3CD1-40C3-93CF-AE26DCD51264%7D&file=Criteria%20for%20STT%20Interviews.xlsx&action=default&mobileredirect=true&cid=0c2f1e51-38fe-4566-ba23-a0f433397358

**Comment by matthewjdoty** [comment]
Move to "Gov Review". The document can be found [here](https://teams.microsoft.com/l/file/1A533A84-0000-423D-8274-C0767D9F471D?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch%2FShared%20Documents%2FUser%20Research%2FSTT%20Research%20September%202020%2F%23163%20Compile%20a%20list%20of%20states%20to%20learn%20from%20and%20interview%20for%20Round%203.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch&serviceName=teams&threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287).

**Comment by cmajel** [comment]
@dk-ui this is such a great resource to have! 🎉  Love that we're building an index for future research and the documentation on thought process.

My main concern here is the lack of tribes; it feels like they were not included in the initial analysis. 

A few notes: 
* I like the diversity of states you've collected - a nice mix of geo, engagement and case size. 
* In the excel index file, territories and tribes are missing from the master list. Can we make adding those a follow up task, as we want to include them in our research?
* You mention there were blockers to reaching out to tribes - is that current? If not, can we add a follow up issue (or add details to this card) for how we'll move forward with tribe recruitment? 
* I noted a few places where we may want to be sensitive to availability
* And, noting here that its great that we have 9 identified. Do you have a minimum you'd hope to interview for the next round?

With the details of including tribes added and those follow on tasks ,this looks good to me. cc @lfrohlich

**Comment by lfrohlich** [comment]
In looking this over with @cmajel  we confirmed that the three territories are included. @dk-ui  and I have spoken about talking with Denise and Thomas to get the information for tribes so i think that makes sense as a follow on issue for the next sprint. I'll make a placeholder issue that can be scoped out more in sprint planning.

**Comment by lfrohlich** [comment]
@dk-ui  this looks great! I made a few notes on the tribes criteria. I see that there are criteria documents in two of the channels -- Design and User Research. Is User Research the final one? We have some cleaning up/deduplication to do with the folders, which I can help with.

**Comment by dk-ui** [comment]
@lfrohlich Yes, the two are the same. I agree, we should only have one version. I'll see what my user privileges allow me to do regarding cleaning this up too.

**Comment by lfrohlich** [comment]
This was completed in Sprint 3
