### ISSUE TITLE
DataFile metadata should be read-only in Django admin

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1630]
It has come to my attention that the `version` field of our `DataFile` objects can be mutated from Django admin.  Sys admins should not be able to change **any** metadata for transmitted files. This is no bueno and needs to be addressed.

![Screen Shot 2022-02-11 at 2 40 48 PM](https://user-images.githubusercontent.com/12901172/153658732-f4a969d6-9732-4a57-8337-7f8ba084460f.png)

## AC

- [ ] All metadata fields in DataFile are read-only

## Tasks 
 - [ ] Update admin class for [data_files](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/tdrs-backend/tdpservice/data_files/admin.py)

**Comment by ADPennington** [comment]
per 2/16 dev sync: ticket revised to capture decision to make all data_file metadata `read_only` cc: @valcollignon @abottoms-coder

**Comment by jorgegonzalez** [comment]
Closing this ticket as this work in encapsulated in the PR for #1658
