### ISSUE TITLE
As a user, I want to document current state of my journey to inform the next round of research

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#165]
Description:
Synthesize OFA research and Round 3 STT research to outline a grantees current state of journey. Outcome of this journey map will be to draw out assumptions and identify gaps for the next round of research. The presumptive journey maps will be created for the following personas - ~~Vendor,~~ OFA, large grantee teams, mid grantee team, small grantee team, and Tribes - to document the current state.

AC: 
- [x] Presumptive proto ~~current state~~ journey maps for validation are drafted for each persona - ~~Vendor,~~ OFA, large grantee teams, mid grantee teams, small grantee team, and Tribes
- [x] Round 4 research issue is updated to note that the final current state journey maps are outputs of the Round 4 research #447

Tasks: 
- [x] Refine personas from #371 ([Spring Personas](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1592254280716/2ae8293a3233a95941d548cda4f373faab96b40b) and Round 3 research) to use for journey mapping, if necessary
- [x] Draft journey maps for each persona and determine knowledge gaps that have to be filled and figure out near term research goals 
- [x] Address knowledge gaps and prioritize pain points with OFA workshop 
- [x] Need for service blueprint is evaluated and a follow-on issue is created, if necessary 

Supporting Doc:
- [Journey/Persona working mural](https://app.mural.co/t/raft2792/m/raft2792/1606937827107/330634f214aa853c6fc410aade3af08e9fa3407b) 🔒 
- [OFA Workshop](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1608238114372/191c53b8ef538838bc8c179daa238dd5c5dcc9e8) 🔒 

Note:
- Proto journey maps are rough drafts of the concrete journey maps 
- Proto journey maps for vendor persona have not been created, instead, vendor persona has been included in the 'Large (Hybrid) Team - State' and 'Small Team - Tribe'. 
- This work will also drive follow-on tickets relating to a complete service blueprint of TANF and the TDP problem space. An early version of some service blueprint elements currently appears in the working mural (see supporting documentation)

DoD:  
- [ ] Documentation: ~~Presumptive~~ Proto journey maps with assumptions and open questions are documented and shared
- [ ] @lfrohlich has signed off

Deliverable(s)
- [Link to the proto-journey maps](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1608238114372/191c53b8ef538838bc8c179daa238dd5c5dcc9e8) 🔒

**Comment by cmajel** [comment]
Adding a [reference to the existing process map](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1593114727729/906879aaeb5467c27f0ae3dfbcf5fcfd9cf8ca89) created from prior rounds of research.

**Comment by cmajel** [comment]
@shubhi-raft and @matthewjdoty thinking about this more, how do we think this would differ from the [existing process map](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1593114727729/906879aaeb5467c27f0ae3dfbcf5fcfd9cf8ca89) of how data moves from STTs to OFA?

**Comment by matthewjdoty** [comment]
Thanks, @cmajel. The process map and journey map will be complimentary artifacts that help us understand users' journey(s) in submitting TANF data. While the process map helps us understand what's happening and when from our perspective, the journey map will help us understand what the user is thinking, feeling, and doing through the process. In all transparency, I'm not sure if this will be a separate artifact or an additional layer of value/insight added to the process map. Either way, this issue was created for us to begin the process of mapping what we're learning about user needs, wants and expectations.

**Comment by kniz-raft** [comment]
Closing per Jen & Miles
