### ISSUE TITLE
Design mockup for a new user to create a new user profile 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#166]
Description:
Create mockups for a new user who has setup a login.gov account but has not yet setup a profile to: 
(1) add profile information - first name, last name, and associated STT. 
(2) be notified that their profile has been saved and administrator has been notified 
(3) view and edit profile information 
(4) reset password

Figma link: https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=628%3A468

Problem:
login.gov only provides us with user email, not name / other helpful data. To enable OFA Admins with the ability to understand who should receive which permissions and access to which data we need to collect name (to allow them an easier path to identifying who a new user is) and STT association (to grant them access to the correct segment of TANF data).

Questions we still have:
- What other settings could eventually be housed on the profile? For instance, might non admin users have use cases for notifications (and need a place to manage those?)
- Are STT level email addresses predictable enough to build in any kind of validation that checks (or auto assigns) STT association based on email domain? Is it important to ensure that an STT user can only access data for their own STT?

Mockups to include desktop, tablet, phone view. 

This is a follow-on to #7.
#203 #210 and #214 were spun off of this based on comments/review.

AC: 

- [x] The problem we are trying to solve is clearly stated, as are questions we still have 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [x] The design is usable, meaning... 
   - [x] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [x] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [x] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks: 
- [x] Document how a new user will flow from TDRS data portal home page to users' welcome page
- [x] Create mockups (including mobile screens) for a new user to get access to the system and add their profile information.
- [x] placeholders and annotations are documented as needed

Open Questions:
- [x] How should a user select their state, tribe, or territory to create the least friction? (multiple dropdowns, or type search?)
- [ ] How are buttons handled through the app? (full width or based on length of text?)
- [ ] How are validation button states handled within the app? 
- [ ] How can a user edit their STT? Put thoughts here : https://github.com/raft-tech/TANF-app/issues/203

DoD: 
 - [x]  Documentation: Design has been documented and shared with PO and team
 - [x] @cmajel has reviewed and signed off
 - [ ] @lfrohlich has reviewed and signed of

**Comment by cmajel** [comment]
Can we say more about what we think new users may need to do at these stages? Is this..
* a step on the way to get access to the system?
* after they've been granted access, guidance on what the system does and how to use it
* something else?

**Comment by reitermb** [comment]
@cmajel This would be the step that would grant a brand new user access to the system in the role of "Unassigned". Basically a default role in the system with no permissions to do anything, just access to any onboarding materials/flows that end up being desirable, and profile setup. Right now we think that that "Profile" is First Name, Last Name, and Associated STT. 

[The Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=0%3A1) now has a couple new screens (under the various user type landing page placeholders) illustrating this, as well as an admin screen starting to dig into how those unassigned users can be assigned roles. 

Any more questions/early feedback welcomed!

**Comment by cmajel** [comment]
Ok thanks! I think this could be a good place to sync up with the dev team on how they are handling authentication so that we're on the same page on what info they need to authenticate, and what info users may have given /can be collected during the login.gov process.

**Comment by reitermb** [comment]
Morning @cmajel @lfrohlich ! This flow is ready for feedback! It's on its own [here](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=628%3A468), or see it in the broader context of the [entire TDP app flow](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=0%3A1).

**Comment by reitermb** [comment]
@cmajel @lfrohlich And this flow as well! On its own [here](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=628%3A142), or see it in the broader context of the [whole TDP app flow](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=0%3A1).

**Comment by shubhi-raft** [comment]
mobile mockups are included in #178.

**Comment by dk-ui** [comment]
@shubhi-raft Mobile Mockups are in, ready to review

**Comment by shubhi-raft** [comment]
Thanks @dk-ui!

@cmajel @lfrohlich ready for your review.

**Comment by cmajel** [comment]
@reitermb @dk-ui  thanks! I'll be reviewing this morning. 

At first glance it looks like we're missing a write up of the first acceptance criteria:
* The problem we are trying to solve is clearly stated, as are questions we still have

Can you update the description of the ticket with those details? I think it's implied but it'll be helpful to have this clearly written out. 

For this one, is the problem that we need more information from users to be able to grant them access to the system after their initial login.gov set up?

**Comment by reitermb** [comment]
@cmajel Thanks! Updated

**Comment by lfrohlich** [comment]
> `Is it important to ensure that an STT user can only access data for their own STT?`
Yes, this is very important.

**Comment by cmajel** [comment]
Added a few comments to the Figma. Summarizing those thoughts:
* We should confirm with dev, but I think name may be collected (or can be collected?) from Login.gov. If so, we may not need to ask again.
* Per the AC problem statement, we want to collect info so that we can grant access to the system. I think we need to adjust the language to set that expectation on the user section (I'm requesting access to a system I can't access yet, rather than I'm filling out a profile).
* I have some concerns around making STT fields editable, and how that affects notifications and access to data. This feels like something we may want to consider out of the hands of users.

**Comment by cmajel** [comment]
> Are STT level email addresses predictable enough to build in any kind of validation that checks (or auto assigns) STT association based on email domain? Is it important to ensure that an STT user can only access data for their own STT?

For this open question, in discussing with @lfrohlich this may be possible, but would be tricky for tribes who don't have a standard email pattern.

**Comment by lfrohlich** [comment]
> I have some concerns around making STT fields editable, and how that affects notifications and access to data. This feels like something we may want to consider out of the hands of users.

Maybe once a role is assigned, the STT they're associated with should be locked

**Comment by cmajel** [comment]
For future tickets, can we post figma links in the description?

**Comment by cmajel** [comment]
@reitermb @dk-ui 

Thanks for responding to Fimga comments! I'm cool signing off on this - a summary of actions:
* You were right about the login name values - thanks for updating me!
* We opened #203 as a follow on to this, because the question of how we verify which user goes to which STT, and who owns edit permissions, still feels like an unknown. And, I expect the dev team may have thoughts on the data access portion of this. 
* There's still  a few small UI / language suggestions still hanging, but I'm ok demoing this tomorrow and signing off for review.

**Comment by lfrohlich** [comment]
I echo what @cmajel  said. Looks good to me and thanks for the responses in Figma! I added #203 to the questions in the description too.  I think this looks good to demo

**Comment by cmajel** [comment]
@reitermb Recapping a few comments from 9/1 sprint review re: predictability of emails - feel free to move if there's a better issue for this:
* Some tribes may not have a predictable pattern
* Sometimes users may not have gov email addresses (eg. a Deloitte email)
* Some states may have different formats (as a Mass employee, I had a @massmail.state.ma.us and @mass.gov emails)

**Comment by lfrohlich** [comment]
Follow on issues have been created (#203 #210 #214). This can be closed.
