### ISSUE TITLE
Get a tour of OFA resource mailbox to determine whether access is needed

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#167]
Description:
Work with OFA team to get a tour of OFA resource mailbox to determine whether access is needed

Problem:
We don't have easy-access to the OFA resource mailbox and need to understand whether there's communication there between STTs and OFA that would provide insights that would aid future research and designs. Specifically whether a deeper analysis (and access) is needed to arrive at those insights.

AC
- [x] Mailbox tour happens and notes are documented [here](https://teams.microsoft.com/l/file/2542A110-040B-44C1-B827-06A54C6EC9F2?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch%2FShared%20Documents%2FUser%20Research%2FOFA%20Resource%20Mailbox%20notes.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch&serviceName=teams&threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock:

Tasks
- [x] Work with OFA to get tour of the OFA resource mailbox

Open Questions:
- How is the mailbox organized? (i.e. Inventory of the folder schema for sorting and segmenting messages)

**Comment by lfrohlich** [comment]
@reitermb  from this conversation did you determine if more access is needed?

**Comment by cmajel** [comment]
@shubhi-raft @reitermb thanks for this!

I added some notes in the doc, recapping here:
* Can you add a a recap of how this investigation happened (when it occurred, how you accessed the data)
* Do we have examples of the types of questions that are asked about policy or resubmission?
* Added some questions around if other teams use the inbox and the team's categorization of the inbox.

**Comment by reitermb** [comment]
@cmajel I've added some detail/clarity, thanks for the questions! (And thanks @lfrohlich for answering some of them already!)

**Comment by lfrohlich** [comment]
thanks @reitermb . This looks good
