### ISSUE TITLE
As as a user, I want README to be updated so I can run TDRS 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#17]
Description: This issue will deliver an updated the README to reflect the monorepo

AC: 
- [ ] README is updated with tasks below
- [ ] Frontend and backend Sub READMEs are relatively linked into the main Raft README
- [ ] Dev issue template is updated to add README as an AC. 

Tasks:
- [x] Technical Overview
- [x] Running both frontend/backend locally and in cloud.gov
- [ ] ~~CircleCI badges~~
- [x] Update the Create React App default Script documentation to be in sync with the new docs in that Readme, if necessary
- [x] Update main README links user to frontend and backend readme

DoD:
- [x] Shared with the PO and team for feedback

**Comment by lfrohlich** [comment]
This may make more sense as continual updating. Some of this could also fulfill OCIO reporting requirements

**Comment by lfrohlich** [comment]
Readmes were updated, this was merged on 1/14
