### ISSUE TITLE
Group discussion on admin controls 

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#171]
Description: 
Dev and Design need to get on the same page re: Admin controls before it can be built. 

Tasks: 
- [x] Drafted two to three admin functionality drafter as thin sliced stories -- use #175 (placeholder)
- [x] Meet to discuss initial questions (round 1). 

AC: Two or three admin functionality have bee drafted and shared with the PO and team

**Possible issues:**
- As an OFA admin, I can invite/approve/add an individual from a STT office to create an account in the app
  - Invite, approve, or add situation?
- As an OFA admin, I can remove a data prepper from the app
- As a new user, I am assigned a role of Admin or Data Prepper
- As an ODF admin, I can see a list of users

**Thoughts**
- These can be ugly and simple to start!
- Don't worry about roles/permissions beyond the two basic ones now--OFA Admin and Data Prepper
- We just need to get through basics of admin now so we can get to uploading
- If good ideas or questions about future admin controls come up, we can put them in the Product Backlog.

**Comment by shubhi-raft** [comment]
Based on the discussion on Aug 26, we will be focussing on:

1. As a new user, I can create a profile on the TDP Landing Page [Research on federal source of truth]
2. As an OFA Admin, I can view a list of users
3. As an OFA Admin, I can filter the users list by region and/or STT
4. As an OFA Admin I can assign roles to new users

**Comment by lfrohlich** [comment]
This was done.
