### ISSUE TITLE
As a user who is not yet logged in, I see a landing page based on the design

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#172]
Description:
We have a [figma design](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-%2F-Admin-Mockups-For-Feedback?node-id=0%3A1) for what a user sees when the user has not yet logged in. This story is to build out that design. This is a frontend only task. 

**What will not be done in this issue**
1. Updating the landing page with demo banner #235

AC: 

- [ ] When the user is not logged in, they see a landing page that matches the figma design
- [ ] This page renders at all form factors specified in the design (aka is "responsive")
- [ ] Use the text and placeholders from the mockup

Tasks:
- [ ] Create unauthenticated login.page
- [ ] Code documentation and annotation of why system is the way it is

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 - [ ] @lfrohlich  has reviewed and signed off
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

Resources: 
- https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-%2F-Admin-Mockups-For-Feedback?node-id=0%3A1

**Comment by shubhi-raft** [comment]
Laura and ADam to touch base on team about CSS

**Comment by shubhi-raft** [comment]
@hilvitzs for the frontend home page, can we have a demo banner and update the text `An official website of the United States government` on https://tdp-frontend.app.cloud.gov/ similar to the signed-in sandbox page? 

Current:
![Screen Shot 2020-09-03 at 11 44 39 AM](https://user-images.githubusercontent.com/22622384/92137204-e2af1580-edda-11ea-96e3-8f991fe4faea.png)

Expected:
![Screen Shot 2020-09-03 at 11 34 25 AM](https://user-images.githubusercontent.com/22622384/92137022-b7c4c180-edda-11ea-92a0-f0e7d8a5c9da.png) 

making this change will close out the feedback from sprint demo 9/1

**Comment by hilvitzs** [comment]
Absolutely! I'll take a look now.

**Comment by adamcaron** [comment]
@shubhi-raft The current branch (PR attached, work in progress) has this change, I this is what you were asking about? 
![image](https://user-images.githubusercontent.com/7072066/92139778-3e2ed280-edde-11ea-8680-74ccdef48a89.png)

**Comment by shubhi-raft** [comment]
@adamcaron ah thanks. is adding a new banner that clarifies this is a demo site an easier change?

**Comment by hilvitzs** [comment]
@shubhi-raft It probably wouldn't be easier. After looking at the code with Adam I think I can add the uswds package and I don't think that it will be too difficult but I wanted to check on the priority of this compared to the stories in the sprint already.

**Comment by shubhi-raft** [comment]
@hilvitzs in that case, I will create a new issue and we can push this out to the next sprint.
