### ISSUE TITLE
Define manual testing practices

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#173]
Description:
Define and confirm manual check Raft will do to meet the QASP: The document can be accessed [here](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287). 

AC: 
- [x] Manual testing practices are reviewed and documented.

Tasks: 

- [x] Meeting/Pairing session with Laura, Lauren, Christine, + Thomas and Raft team to define the manual testing review process
- [x] Document the discussion and share it with the broader team
- [x] Document the practice is team charter + wiki?

DoD: 
 - [x] Documentation: Manual testing has been shared with the PO and team for feedback
 - [ ] @lauragGit has signed off
 - [x] @lfrohlich has signed off

**Comment by lfrohlich** [comment]
Reposting comment from @iamjolly : I do not know if a manual accessibility review was performed on the code for this sprint. This is essential to follow automated testing, as [automated accessibility scans only catch a small subset of possible accessibility issues](https://www.smashingmagazine.com/2018/09/importance-manual-accessibility-testing/). 
TODO: Review all code rendered in the browser for accessibility via automated tools and a manual process such as DHS Trusted Tester or Accessibility Insights for Web.

**Comment by lfrohlich** [comment]
As soon as this is documented in the charter/wiki this is complete from my perspective

**Comment by shubhi-raft** [comment]
@lfrohlich This has been added to the charter (Page 11).

**Comment by lfrohlich** [comment]
Great, thanks @shubhi-raft

**Comment by lfrohlich** [comment]
This is done
