### ISSUE TITLE
As a dev, I want to prevent the frontend Docker Image from running as root

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#174]
Description:
By default, dockerized containers run as root unless explicitly configured to run as a NON privileged user. We currently observe no reason as to why we would need to keep this default unsecured behavior. 

AC: 

- [ ] Frontend image no longer defaults to the `root` user

Tasks: 

- [ ] Create a tdp-user in the Dockerfile
- [ ] Assign it all the needed control over just running the frontend app
- [ ] Ensure no functionality is lost with the new restriction 

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
@carltonsmith has this been done with docker layer caching?

**Comment by kniz-raft** [comment]
Closing since we are moving away from docker
