### ISSUE TITLE
As a TDP user, I see errors when attempting to submit files

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1772]
## Description
When attempting to upload data files, I receive a error message from the frontend.

## Action Taken
After login, click "data files", search any year/qtr, upload file for section 1, click submit.

## What I expected to see
A successful submission message.

## What I did see
In addition to the "network error" below, I've also seen 500 error.
![image](https://user-images.githubusercontent.com/84722778/166825149-852078a3-338e-4d35-b6b6-d98365928417.png)
![image](https://user-images.githubusercontent.com/84722778/167637924-90be8b8c-2e32-495a-93a1-4b72d26dc932.png)

## Other Helpful Information

+ URL of the page I was on: /v1/data-files/ across all dev environments
+ Browser and version: Chrome/latest
+ Operating System: Windows
+ Is the issue repeatable?:  yes
+ Has the issue occurred more than once?: yes

**Comment by andrew-jameson** [comment]
@ADPennington @stevenino Do we have bandwidth to pull this into current sprint or should it be next sprint?

**Comment by stevenino** [comment]
> @ADPennington @stevenino Do we have bandwidth to pull this into current sprint or should it be next sprint?

I prefer to wait until next sprint unless any of the developers have completed all of their in progress tickets.
