### ISSUE TITLE
SPIKE: Investigate why production-deployment workflow fails 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1778]
**Description:**

On 5/10, we attempted the production-deployment workflow from  `hhs:master`, and it failed at the `login to cloud.gov and set application targets` step (see below)
![proddeploy1](https://user-images.githubusercontent.com/63075587/167844581-f34cebef-900e-43ec-9f6e-d43ef33e3653.PNG)

This ticket tracks troubleshooting.

**Comment by ADPennington** [comment]
Checked which routes prod apps are bound to:
```
apennington@HHSL9XYTF13 MINGW64 / 07:01:00 (master)
$ cf apps
Getting apps in org hhs-acf-ofa / space tanf-prod as alexandra.pennington@acf.hhs.gov...

name                requested state   processes   routes
clamav-rest         started           web:1/1     tanf-prod-clamav-rest.apps.internal
tdp-backend-prod    started           web:1/1     tdp-backend-prod.app.cloud.gov
tdp-frontend-prod   started           web:1/1     tdp-frontend-prod.app.cloud.gov
```

Not sure how this happened given [726](https://github.com/raft-tech/TANF-app/issues/726#issuecomment-1114871032), but unmapped temp routes and remapped to correct routes and confirmed:

```
apennington@HHSL9XYTF13 MINGW64 / 08:40:23 (master)
$ cf unmap-route tdp-backend-prod app.cloud.gov --hostname tdp-backend-prod
Removing route tdp-backend-prod.app.cloud.gov from app tdp-backend-prod in org hhs-acf-ofa / space
OK

apennington@HHSL9XYTF13 MINGW64 / 08:45:11 (master)
$ cf unmap-route tdp-frontend-prod app.cloud.gov --hostname tdp-frontend-prod
Removing route tdp-frontend-prod.app.cloud.gov from app tdp-frontend-prod in org hhs-acf-ofa / spac
OK


apennington@HHSL9XYTF13 MINGW64 / 09:18:21 (master)
$ cf map-route tdp-backend-prod api.tanfdata.acf.hhs.gov --hostname tdp-backend-prod
Creating route tdp-backend-prod.api.tanfdata.acf.hhs.gov for org hhs-acf-ofa / space tanf-prod as alexandra.pennington@acf.hhs.gov...
OK

Mapping route tdp-backend-prod.api.tanfdata.acf.hhs.gov to app tdp-backend-prod in org hhs-acf-ofa / space tanf-prod as alexandra.pennington@acf.hhs.gov...
OK

apennington@HHSL9XYTF13 MINGW64 / 09:18:42 (master)
$ cf routes
Getting routes for org hhs-acf-ofa / space tanf-prod as alexandra.pennington@acf.hhs.gov...

space       host                    domain                     port   path   protocol   apps
tanf-prod   tdp-backend-prod        app.cloud.gov                            http
tanf-prod   tdp-frontend-prod       app.cloud.gov                            http
tanf-prod                           api.tanfdata.acf.hhs.gov                 http       tdp-backend-prod
tanf-prod                           tanfdata.acf.hhs.gov                     http       tdp-frontend-prod
tanf-prod   tanf-prod-clamav-rest   apps.internal                            http       clamav-rest
tanf-prod   tdp-frontend-prod       tanfdata.acf.hhs.gov                     http       tdp-frontend-prod
tanf-prod   tdp-backend-prod        api.tanfdata.acf.hhs.gov                 http       tdp-backend-prod

```

**Comment by ADPennington** [comment]
Confirmed the correct key value pairs for the following environment variables in CircleCI:

`CF_ORG`
`CF_USERNAME_PROD`  and `CF_PASSWORD_PROD` (via `cf service-key <service> <key>` [ref](https://docs.cloudfoundry.org/devguide/services/service-keys.html))

**Comment by ADPennington** [comment]
> 1. Confirmed the correct key value pairs for the following environment variables in CircleCI:
> 
> `CF_ORG` `CF_USERNAME_PROD` and `CF_PASSWORD_PROD` (via `cf service-key tanf-keys deployer` [ref](https://docs.cloudfoundry.org/devguide/services/service-keys.html))

Update: there are multiple keys associated with the tanf-key service instance, which can be confirmed via `cf service-keys tanf-keys`. The credentials being used in raft circleci were associated with the test-deploy key and the username for this key has a tanf-prod space role in cloudgov. The credentials in HHS circleci are associated with the deployer key, and the username for this key does _not_ have a tanf-prod space role in cloudgov.  

for the purposes of testing, I updated the credentials in HHS circleci with test-deploy credentials to confirm that the `deploy-infrastructure-production`  job can run. it was successful. the `deploy-production` job was also successful. 
![proddeploy5](https://user-images.githubusercontent.com/63075587/167929931-43d8d546-8fbf-4742-9f54-8cf973036967.PNG)

@andrew-jameson can we discuss the appropriate path forward? There are at least a couple of items worth revisiting:

- appropriate credentials to use for `cf_username_prod` and `cf_password_prod`
- updating tanf-prod space users with appropriate tanf-key service instance credentials
- cleaning up routes (see below) and updating allowed_hosts (per @raftmsohani)
![proddeploy4](https://user-images.githubusercontent.com/63075587/167929481-3d432a55-b307-4381-98dd-7f3c84eb0fc8.PNG)

**Comment by andrew-jameson** [comment]
> @andrew-jameson can we discuss the appropriate path forward? There are at least a couple of items worth revisiting:
> 
>     * appropriate credentials to use for `cf_username_prod` and `cf_password_prod`
> 
>     * updating tanf-prod space users with appropriate tanf-key service instance credentials
> 
>     * cleaning up routes (see below) and updating allowed_hosts (per @raftmsohani)


Yes, happy to discuss when you're available. While the user/pass tasks were noted in #1764 I don't believe I was looped in on all that was done there. I'm also a little curious on why #1766 does not fully address the issues here given that it was functioning prior to recent deployments.

**Comment by andrew-jameson** [comment]
Deleted CDN service, telling it to forward cookie and other auth headers made no difference. Once this operation is complete, will run this:

```
cf create-service external-domain domain tdp-prod-domain -c '{"domains": ["api.tanfdata.acf.hhs.gov", "tanfdata.acf.hhs.gov"]}'
```

**Comment by ADPennington** [comment]
since we're tracking prod-related issues in this ticket, including a link to the most recent update: https://github.com/raft-tech/TANF-app/issues/726#issuecomment-1145303542

**Comment by andrew-jameson** [comment]
Sent follow-up to cloud.gov support ticket #4217 detailing CDN/domain service changes. Next step will be to try circumventing DNS alias records using just cloud.gov provided `tdp-backend-prod.app.cloud.gov`.

**Comment by ADPennington** [comment]
testing login.gov flow 2 ways:

- using alexandra.pennington@acf.hhs.gov results in `{"error":"alexandra.pennington@acf.hhs.gov attempted Login.gov authentication with role(s): []"}` which is expected given #1170 
- using gsa.alexandrapennington@gmail.com results in redirect to request page 🚀

**Comment by ADPennington** [comment]
reached out to hhs help desk re: new DNS for backend app given problem below. 
![backenddns](https://user-images.githubusercontent.com/63075587/175614632-0e43ff4e-0212-4f33-a485-6568dc8fac96.PNG)

this issue has been escalated for additional support on 6/24.

**Comment by ADPennington** [comment]
production-deployment workflow is functioning since [this update](https://github.com/raft-tech/TANF-app/issues/1778#issuecomment-1124204864). there's still some cleanup of environment variables to ensure this continues to work properly but this will be tracked in #897. Closing this ticket  @stevenino
