### ISSUE TITLE
[Research Planning] TDP Pilot 2.0

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1781]
**Description:**

This ticket delivers plans for planned V2.0 research with pilot users including:
- Functional testing of the TDP app
- Functional testing of onboarding content
- Sentiment & satisfaction analysis toward TDP (to be compared to Tribe research [baselines](https://github.com/raft-tech/TANF-app/blob/develop/docs/User-Experience/Research-Syntheses/2021%2C%20Spring%20-%20Tribal%20MVP%20(Release%202)%20Design%20Sprint.md))
- Qualitative insights capture (Watching people use TDP, feedback from users, etc...)

**AC:**
- [ ] A research plan has been created which includes:
    - [x] Research goals
    - [x] Recruitment/participation email copy
    - [x] Recruitment criteria and target participants
    - [x] Kick off meeting
    - [x] Research questions
    - [x] Task Scenarios
    - [x] Timeline (for recruitment and for research sessions)
    - [x] Recruitment Tracker spreadsheet - Excel in O365
    - [x] [STT Contact List](https://teams.microsoft.com/_#/xlsx/viewer/teams/https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA-UserResearch~2FShared%20Documents~2FUser%20Research~2FSTT%20Contact%20List.xlsx?threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&baseUrl=https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA-UserResearch&fileId=089c0da8-9a05-4a80-a840-9b7b72c87f52&ctx=files&rootContext=items_view&viewerAction=view)
    - [x] Request Access, Access Granted Tracker spreadsheet - Excel in O365
    - [x] Ethics, privacy concerns - template consent
    - [x] Where will research documentation be located? Which folder and where? [MS Teams](https://teams.microsoft.com/_#/files/Research%20and%20Design?threadId=19%3Ae92913e3e7d443adb823e6497dff1fb3%40thread.skype&ctx=channel&context=Pilot%2520v2.0%2520Planning%2520and%2520Research&rootfolder=%252Fsites%252FTANFDataPortalOFA%252FShared%2520Documents%252FDesign%252FPilot%2520v2.0%2520Planning%2520and%2520Research)
    - [x] Create hack.md for plan draft
    - [x] Create email inbox tdp_pilot@goraft.tech 
    - [x] Review with UX Sync team - Proposing to review 6/27
    - [x] Review with Andrew - June 30

**Supporting Documentation:**
- [Hack.md](https://hackmd.io/ucJ0B3lPQDuhKFFkX9du9Q?view)

**Comment by lilybl1** [comment]
@lfrohlich @stevenino @reitermb Submitting for QASP review - please note that the consent form is just part of this ticket below: 
[Privacy.pdf](https://github.com/raft-tech/TANF-app/files/8994154/Privacy.pdf)

**Comment by lilybl1** [comment]
@reitermb @lfrohlich The tab "[Recruitment Roster](https://teams.microsoft.com/_#/xlsx/viewer/teams/https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA~2FShared%20Documents~2FDesign~2FPilot%20v2.0%20Planning%20and%20Research~2FParticipants%20Tracker.xlsx?threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&baseUrl=https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA&fileId=18fa2424-6171-466e-b49f-20a4ff018723&ctx=files&rootContext=items_view&viewerAction=view)" has been updated based on what we have from other spreadsheets.

**Comment by lfrohlich** [comment]
@lilybl1 @reitermb FYI I moved this to User Research-Sensitive because it has contact information

**Comment by lfrohlich** [comment]
I sent to Yun and Rebekah to fill in contact info

**Comment by lfrohlich** [comment]
With help from Yun and Rebekah, the contacts are all filled in! @lilybl1

**Comment by lilybl1** [comment]
Thank you. Reviewed and finalized the HackMD with stakeholders. Emails are ready to send out on Tuesday, 7/5 for recruitment.

**Comment by stevenino** [comment]
Emails sent out on 7/5/22. Closed per sprint review on 7/6/22
