### ISSUE TITLE
As a user who is just logged in, I see a landing page based on the design

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#180]
Description:
We have a figma design for what a user sees when the user just logged in. This story is to build out that design. 

AC: 

- [ ] When the user is logged in, they see a landing page that matches the figma design
- [ ] This page renders at all form factors specified in the design (aka is "responsive")
- [ ] Use the text and placeholders from the mockup

Tasks: 

- [ ] authenticated page changes to Dashboard
- [ ] authenticated Dashboard responsive welcome message
- [ ] sign out button destroys the session, and user is redirected to Welcome page -- unable to go back to Dashboard by typing it in the URL
- [ ] sign out button appears in header
- [ ] user's email appears in the header
- [ ] Ensure alert bar is contained in a way that makes sense

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 - [ ] @lfrohlich  has reviewed and signed off
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

Resources: 
- https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-%2F-Admin-Mockups-For-Feedback?node-id=0%3A1

**Comment by shubhi-raft** [comment]
dupe to #64

**Comment by lfrohlich** [comment]
Closed because duplicate
