### ISSUE TITLE
Sprint Retro Follow up 8/18

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#181]
Complete actions items from sprint retro

AC: 
- [x] Tasks are complete

Tasks
- [x] Setup and send Gov Review Friday reoccurring reminders
- [x] Create a new issue for QASP deliverable/COR report/Sprint Report discussion
- [x] Create a new issue for discussion on PR merge and close to main HHS TANF repo

**Comment by lfrohlich** [comment]
Sprint Report issue: #185
PR Merge issue: #186
This is done
