### ISSUE TITLE
[draft] scratchpad of circleci issues

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1836]
**Description:**
_Provide a brief background and justification for this issue_
![image](https://user-images.githubusercontent.com/84722778/171284560-c6a06959-27e9-4e64-9cab-c39c36e3040d.png)

- circleci deployments for dev takes 10 minutes. surely this can be parallelized and streamlined? sub 3 minute goal
   - also, that commit hash isn't helpful, give me the commit message like the other runs.
- when developing a ticket, i want to auto-redeploy my branch instead of off/on the label
- for in-progress tickets, I should be able to deploy whether or not everything succeeded
- for develop/main/master, I obviously do want all the checks to pass before deployment
- i should be able to re-run a deployment even if previous one failed. currently, we have to have a new code commit and wait for all checks to come back green even if the code was fine before because a deployment counts as a failed test.
- I just spent an hour clearing statuses in circleci for a PR so I could deploy it. If done manually, this would've been a single ~6m run. How can we skip the redundant steps to streamline execution time?

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by stevenino** [comment]
Very low priority. Not refined.

**Comment by robgendron** [comment]
@andrew-jameson need to decompose into multiple tickets. Let's connect and organize.

**Comment by lhuxraft** [comment]
May potentially address if the issues come up again
