### ISSUE TITLE
Discuss and finalize sprint report details

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#185]
Description: At the end of each sprint, create a sprint report to be submitted to COR, PO, tasks leads for closing out the sprint. 

AC: 
- [x] Sprint report is finalized

Tasks:
- [x] Use [Sprint 1 PR template](https://github.com/HHS/TANF-app/pull/41) as a starting point
- [x] Discuss with PO and tasks leads what other information should be included in the report
- [x] Update PR template

**Comment by SelenaJV** [comment]
@shubhi-raft Reminder: I'm out this Friday and Monday. What do you need from me so this issue can be closed in this sprint?

**Comment by shubhi-raft** [comment]
@SelenaJV thanks! to close this out, we need:

(1) @lfrohlich to review (team charter - Sprint report (Page 11)) 
(2) PR is updated with any feedback from (1).

**Comment by lfrohlich** [comment]
@shubhi-raft  this looks good to me, and looks like it will satisfy OCIO's reporting. I believe @cmajel and @lauraGgit have both provided input on the Sprint Report, in which case I am fine closing it out. Christine and Laura, can you confirm?

**Comment by lfrohlich** [comment]
This can be closed since sprint reports have been iterated on.
