### ISSUE TITLE
Discuss process to merge PR to main HHS repo

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#186]
Description:
Discuss and finalize the process to merge PR from Raft fork to the main HHS repo.

AC:
- [x] Process is finalized and documented.

Tasks:
- [x] Document who approves the PR and merges it into main HHS repo
- [x] Document the finalized process in wiki and team charter
- [x] Docker Layer Caching, Raft has it, HHS doesn't and seems to fail build? (speeds up builds, starting at $30/mo)

**Comment by shubhi-raft** [comment]
@lfrohlich this has been documented in the team charter.

**Comment by RafterGit** [comment]
Need to discuss PR review process  and remediation follow up process with Alex and Laura as part of the roll-off process.

**Comment by alexsoble** [comment]
I think this one is all done! 

Docker layer caching removed, all CircleCI builds on the HHS repo are green. 

Documented review process to the docs folder here: https://github.com/HHS/TANF-app/blob/main/docs/PR%20Review/qasp-operational-checklist.md
