### ISSUE TITLE
Nightly owasp scan of staging failing

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1873]
## Description

The CircleCI job nightly-owasp-scan is failing consistently starting Friday 6/10.

## Action Taken

N/A

## What I expected to see

A green successful run.

## What I did see

[Failed run](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/8903/workflows/936e10ec-944e-4e68-a97d-93461c0cae27/jobs/21959/parallel-runs/0)
    "Run post-processing task to record OWASP ZAP results":
```
#!/bin/bash -eo pipefail
# These environment variables are exported to Circle CI's BASH_ENV
# by the zap-scanner.sh script for each respective app target.
CMD_ARGS=(
  "$CIRCLE_BUILD_NUM"
  --backend-pass-count ${ZAP_BACKEND_PASS_COUNT:-0}
  --backend-warn-count ${ZAP_BACKEND_WARN_COUNT:-0}
  --backend-fail-count ${ZAP_BACKEND_FAIL_COUNT:-0}
  --frontend-pass-count ${ZAP_FRONTEND_PASS_COUNT:-0}
  --frontend-warn-count ${ZAP_FRONTEND_WARN_COUNT:-0}
  --frontend-fail-count ${ZAP_FRONTEND_FAIL_COUNT:-0}
)

# Evaluate the full command before passing it in so it doesn't
# get improperly interpolated by Cloud.gov.
CMD="python manage.py process_owasp_scan ${CMD_ARGS[@]}"

# Submit a CF Task for execution that will run the necessary command
cf run-task tdp-backend-staging \
  --command "$CMD" \
  --name nightly-owasp-scan

Creating task for app tdp-backend-staging in org *********** / space tanf-staging as ************************************...
memory_in_mb exceeds space memory quota
FAILED

Exited with code exit status 1

CircleCI received exit code 1
```

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

**Comment by ADPennington** [comment]
is this memory quota issue related to the additional apps coming into the space given #1746?  if so, worth discussing if we want to reallocate some of the resources (e.g. clamav) or reconsider if we still want the scans on develop, main, and master branches as noted [here](https://github.com/raft-tech/TANF-app/issues/1754#issuecomment-1110143384)

**Comment by andrew-jameson** [comment]
Last two scan runs have been successful.
