### ISSUE TITLE
As tech lead, I need clamav to detect test virus files

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1995]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

I submitted test virus files in dev-qasp and staging environments and clamav did not detect these as infected. 

## Action Taken

As an `OFA Admin`, I submitted [test infected files](https://en.wikipedia.org/wiki/EICAR_test_file) on the [qasp frontend data files page](https://tdp-frontend-qasp.app.cloud.gov/data-files) and the [staging frontend data files pages](https://tdp-frontend-staging.app.cloud.gov/data-files) 

## What I expected to see

The video [here](https://github.com/raft-tech/TANF-app/issues/1215) demonstrates the expected behavior. 

## What I did see

- successful submission notification on frontend 
- successful submission on backend
![clamav0](https://user-images.githubusercontent.com/63075587/180849157-b6a2ff74-6076-4f0b-9b5b-462434da1590.PNG)
- "clean" scan result on backend
![clamav1](https://user-images.githubusercontent.com/63075587/180849196-7356f703-bac3-4da3-a053-807955a44cbb.PNG)
- evidence that test file is otherwise detected as malicious
![clamav2](https://user-images.githubusercontent.com/63075587/180849269-1ec2928e-d449-4dc9-ad41-dcc3b43a87d0.PNG)

## Other Helpful Information
+ [infected file test script in our codebase](https://github.com/raft-tech/TANF-app/blob/f5d931eb266471aa6e758142d05071f39d8451da/tdrs-backend/tdpservice/test/test_clamav.py#L37)
+ URL of the page I was on: see description
+ Browser and version: chrome
+ Operating System: mac
+ Is the issue repeatable?:yes
+ Has the issue occurred more than once?: yes

**Comment by n0remac** [comment]
Seems like this one can be solved by correctly setting CLAMAV_NEEDED to True in the env file. Once I did that locally this was working as shown in the video.

**Comment by ADPennington** [comment]
> Seems like this one can be solved by correctly setting CLAMAV_NEEDED to True in the env file. Once I did that locally this was working as shown in the video.

@n0remac could you try testing this in a deployed environment? note that I just checked the env variables in the qasp env for example, and the value is currently set to `True`:

```
apennington@HHSL9XYTF13 MINGW64 / 16:35:03 (master)
$ cf env tdp-backend-qasp
Getting env variables for app tdp-backend-qasp in org hhs-acf-ofa / space tanf-dev as alexandra.pennington@acf.hhs.gov...
...
...
AV_SCAN_URL: http://tanf-dev-clamav-rest.apps.internal:9000/
BASE_URL: https://tdp-backend-qasp.app.cloud.gov/v1
CLAMAV_NEEDED: True
...
...

**Comment by n0remac** [comment]
Alex solved this by by changing AV_SCAN_URL to http://tanf-dev-clamav-rest.apps.internal:9000/scan. I am looking into making that the default value.
```
apennington@HHSL9XYTF13 MINGW64 / 15:37:12 (master)
$ cf set-env tdp-backend-a11y AV_SCAN_URL http://tanf-dev-clamav-rest.apps.internal:9000/scan
Setting env variable AV_SCAN_URL for app tdp-backend-a11y in org hhs-acf-ofa / space tanf-dev as alexandra.pennington@acf.hhs.gov...
OK

TIP: Use 'cf restage tdp-backend-a11y' to ensure your env variable changes take effect.

apennington@HHSL9XYTF13 MINGW64 / 15:38:35 (master)
$ cf restage tdp-backend-a11y
This action will cause app downtime.

Restaging app tdp-backend-a11y in org hhs-acf-ofa / space tanf-dev as alexandra.pennington@acf.hhs.gov...
```
