### ISSUE TITLE
As a developer I need scaffolding for the backend so I can contribute to the project

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#2]
AC:

- [x] Basic api service deploy to cloud.gov dev environment

Tasks: 

 - [ ] Create Dockerized Django API application with PostgreSQL database
 - [ ] Add flake8 gem for linting
 - [ ] Add coverge and configure for unit testing

DoD
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities

**Comment by lfrohlich** [comment]
Suggest adding vulnerability scans and a linter as tasks. 
Otherwise, AC looks good from my perspective.

**Comment by shubhi-raft** [comment]
> Suggest adding vulnerability scans and a linter as tasks.

fyi @carltonsmith 

> Otherwise, AC looks good from my perspective.

great, thanks. @lfrohlich moving this to do.

**Comment by carltonsmith** [comment]
Thanks @lfrohlich I have added those to the task list

**Comment by lfrohlich** [comment]
This was completed
