### ISSUE TITLE
SPIKE: Production Analytics / Usage mapping tools

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2006]
SPIKE: As a Program Manager, I want to be able to understand how our users behave/interact as the user base grows and how to best support the users in their experience with TDP. 

[ ] Discuss with someone that has an understanding of PII and how a tool like this would impact staying in compliant (scrub SSN, etc.)
[ ] What are the types of Research Questions we are trying to answer with the implementation of this type of tool 

Ensure that the user experience is as intended  
For UX: Observe usability from active users 
For Dev: Clear replication procedures for troubleshooting bugs/defects 
For PM: Be able to quantify defects/bugs to justify prioritization  
For PM: Offers the ability to insert Feedback forms on the page – compliant with PRA  (Paperwork Reduction Act) 
For PM: Initial analytics on traffic, heatmap capabilities... 
Recordings are at the tab level 

Tools from: 
https://www.crazyegg.com/recordings 
https://www.hotjar.com/ 

Examples of gov sites using this: 
- https://digital.gov/2014/03/26/measuring-user-experience-a-few-tips/

Notes:
1/11/2022
Basic plan $29/month for 10,000 pageviews/month
Questions:

- Could you connect us to the Crazy Egg contact that manages the ACF Crazy Egg account so we can collaborate with them and determine if this should all fall under the same contract umbrella? CrazyEgg was able to locate a generic email address, but due to privacy/security reasons they will not share the contacts. They would be okay facilitating an email exchange and someone from the analytics.gov side can reach out. 
- How can we mask certain PII elements from being displayed and recorded? By default, CrazyEgg masks all text/input fields when someone is typing. We also have a masking feature that will let you mask/specific elements on a page. 
- Could you share how video recordings are stored? The video recordings (all all of our tracked data) are stores in the US on AWS servers. 
- How long are the recordings made available at Crazy Egg? The maximum retention limit for videos is 2 years (before we automatically delete them). Account holders also have the ability to delete at any time. 
- What happens in the event that Crazy Egg database is compromised? If our database is compromised, we can immediately rotate our access keys via AWS. 
- Who can access the video recordings? Only you (account holder) has access to your recordings and your CrazyEgg data. 

[Link to CrazyEgg Privacy Policy](https://support.crazyegg.com/hc/en-us/articles/360056916293-Crazy-Egg-Privacy)

[12:49 PM] Pennington, Alexandra (ACF)
"CrazyEgg: ACF uses CrazyEgg to obtain information on how visitors are interacting with specific ACF Web pages. This allows ACF to evaluate and, if necessary or beneficial, to modify its websites to improve value and usability. The data CrazyEgg collects includes information about as how visitors navigate around a Web page and the most commonly clicked links on a specific Web page. CrazyEgg does not collect personally identifiable information. The Crazy Egg Privacy Policy is available"

Access to Personally Identifiable Information or other Information Stored at Crazy Egg At any time, a Crazy Egg Client or Crazy Egg Visitor may access and/or modify their Personally Identifiable Information or other Information stored by Crazy Egg on their behalf, to enable them to access, rectify and restrict processing of their respective Information, and allow them to export their Information, by accessing their Crazy Egg account and contacting us at privacy@crazyegg.com."

**Comment by reitermb** [comment]
Discuss further in upcoming UX Sync—flag what would need to happen to unblock this for the 3.0/3.1 timelines + IPT

**Comment by lilybl1** [comment]
Per meeting with IPT today, the next steps are to determine with CrazyEgg if they are aware of any other .gov entities utilizing CrazyEgg with PII. I have contacted their customer support team for next steps. ACF Privacy Policy does reference the use of CrazyEgg here https://www.acf.hhs.gov/privacy-policy and then we can engage with Tijan to join a call to address any security issues/concerns with CrazyEgg

**Comment by lilybl1** [comment]
Per discussion in UX Sync, I have connected Lauren/Alex with the CrazyEgg support contact to help facilitate an introduction to the analytics .gov side to further discuss next steps with implementing CrazyEgg to support the grantee's experience as we scale TDP.

**Comment by lhuxraft** [comment]
May be worth pursuing after deploying flags to certain STTs in production. Potential value add = STT facing functionality (e.g., in app error reports). Revisit in future UX syncs (may come up in future research planning)? Need to weigh against other things in the pipeline
