### ISSUE TITLE
Manage Your Account Redirects to Demo on Prod

### ISSUE THREAD

**Issue by n0remac** [raft-tech/TANF-app#2035]
When I go to the production page and go to the profile page and click the button I get redirected to the Demo version of login.gov. 

I checked this on Mac using Firefox.

**Comment by ADPennington** [comment]
@n0remac its hardcoded here: https://github.com/raft-tech/TANF-app/blob/4852f108f79e5cbb0b954cc8abbeaa5483bc5170/tdrs-frontend/src/components/Profile/Profile.jsx#L78

looks like we need conditional logic here.

**Comment by andrew-jameson** [comment]
@stevenino Because this is such a light lift and fairly urgent, I have pulled this into the sprint and assigned to @n0remac to be completed as a hotfix by Wednesday 8/10.
