### ISSUE TITLE
[Research Planning] Human-Readable Error Messages (Section 1)

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2042]
**Description:**

*---After identifying the error codes by STT, this story will focus in on writing the human-readable error messages so that we can test with the STT.---*

**AC:**
As a Grantee, I would like to be able to understand the error descriptions so that I can properly resolve the errors and submit my data files for Section 1. 

**Tasks:**
- [x] Write up the top errors identified into human-readable format
~~- [ ] Review with DIGIT team to ensure interpretation of error messages~~
- [x] Prepare the Mural facilitation accordingly 

**Supporting Documentation:**
- [Errors by STT](https://teams.microsoft.com/_#/xlsx/viewer/teamsSdk/https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA-UserResearch~2FShared%20Documents~2FUser%20Research~2FRelease%203%20(V3)%20-%20Parity,%20Data%20Parsing,%20Automated%20Status~2FTANFSSP_InitialTransmissions_FY20Q1tFY21Q4_RAFT.xlsx?threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&subEntityId=%257B%2522web%2522%253A%2522https%253A%252F%252Fhhsgov.sharepoint.com%252Fsites%252FTANFDataPortalOFA-UserResearch%2522%252C%2522list%2522%253A%2522https%253A%252F%252Fhhsgov.sharepoint.com%252Fsites%252FTANFDataPortalOFA-UserResearch%252FShared%2520Documents%2522%252C%2522folder%2522%253A%2522%252Fsites%252FTANFDataPortalOFA-UserResearch%252FShared%2520Documents%252FUser%2520Research%252FRelease%25203%2520(V3)%2520-%2520Parity%252C%2520Data%2520Parsing%252C%2520Automated%2520Status%2522%257D&baseUrl=https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA-UserResearch&fileId=40dc8fa1-e57f-42b8-8519-5b5d044522bb&ctx=openFilePreview&viewerAction=edit)
- [Section 1 Instruction and Definitions](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_reports_tan_ssp_instructions_definitions.pdf)
- [Facilitation Board](https://app.mural.co/t/raft2792/m/raft2792/1627324002127/5923c0a550ba559b3fb6a61d54b6a7dacbd964e9?sender=u3ca60168b5ac4eb17bf92804)
- [Error Messages](https://app.mural.co/t/raft2792/m/raft2792/1663123254796/d56e7aa2c3d351b92fd6687208449d69d1271519?sender=u3ca60168b5ac4eb17bf92804)

**Comment by lilybl1** [comment]
@reitermb @ADPennington Feedback on 2042 would be appreciated on this one. [Mural](https://app.mural.co/t/raft2792/m/raft2792/1663123254796/d56e7aa2c3d351b92fd6687208449d69d1271519?sender=u3ca60168b5ac4eb17bf92804)

**Comment by stevenino** [comment]
@ADPennington this is ready for QASP

**Comment by ADPennington** [comment]
LGTM @lilybl1 👍🏾

**Comment by lilybl1** [comment]
@stevenino This is ready to move to done.
