### ISSUE TITLE
[wip]As TDP Sys Admin, I want users to know when TDP is down for maintenance

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2066]
**Description:**
As of Aug 2022, TDP has real users in our production environment. As we continue to release new updates and features to prod, we will need to re-deploy the apps which may impact any users attempting to access the system. Similarly, we may experience unexpected downtime. 

**Open Questions:** 

- Currently when the app is down, users see a message like the one below. Would it be better to change this to a 508-compliant page indicating the app is down for maintenance  ([examples](https://www.atlassian.com/blog/statuspage/maintenance-page-examples))?
![2066p1](https://user-images.githubusercontent.com/63075587/204820999-425c15e4-2f93-4229-b0ba-1c188788388f.PNG)

- If we build a maintenance page, what information should be included? (e.g. notification, link to deployment status, how to contact us, etc.)
- Is a maintenance page easier/better practice than triggering an email to approved users?
- if maintenance page best practice, what stages do we want to implement (e.g. do we want to start with just changing the message and deal with designing new page later?) 
---

**Acceptance Criteria:** 

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Comment by stevenino** [comment]
@ADPennington to refine after #1845 is completed.

**Comment by stevenino** [comment]
@ADPennington to refine.

**Comment by ADPennington** [comment]
### 11/30/2022 update --

- dev will investigate most common use case where apps are down, which is when deployment is in flight.  Wondering if the [`no-route`](https://github.com/raft-tech/TANF-app/blob/aa54f3f9775836efbcad8ba33491bcbb3c746352/scripts/deploy-frontend.sh#L52) parameter is needed and if we have sufficient RAM now to exclude it. @andrew-jameson added this investigation to the devops roadmap. 
- we will revisit the need for a maintenance page when we have a use case (e.g. when the app is down unexpectedly). 

closing as will not do. cc: @stevenino
