### ISSUE TITLE
As a admin, I want to see a design mockup for filtering users on mobile and tablet

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#207]
**Problem Statement**: Tables are non-native components in USDS. This issue is to create responsive tablet and mobile mockups for filtering users. The desktop version of the mockups - #178 has been approved.

Specifically: 
- Create larger filter tags (i.e., "Region 2") for mobile to meet accessibility.  
- Create a full screen filter to accommodate filter by state, tribe or territory, which was noted in the interviews, a full screen filter would need to be in place to accommodate those options and not take up too much mobile or tablet screen real-estate.

**What will not be done in this issue**

**Questions to be resolved prior to accepting in sprint:**
1. Confirm accessibility guidelines for mobile and tablet layouts for filtering users

 

**AC**: 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [ ] Create mockups for filtering users on mobile
- [ ] Check for accessibility 

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @cmajel has reviewed and signed off
- [ ] @lfrohlich has reviewed and signed off

**Comment by cmajel** [comment]
@dk-ui to confirm this ticket is to look at how this element would be displayed on smaller screens? Or something else?

![Screen Shot 2020-09-01 at 2 51 51 PM](https://user-images.githubusercontent.com/2374206/91893851-c25c4b00-ec62-11ea-888d-4e39ee5028a3.png)

If so, I'm not sure how much deviation we'd need from the [USWDS combo box pattern](https://designsystem.digital.gov/components/form-controls/#combo-box).

**Comment by dk-ui** [comment]
@cmajel yes this is that ticket. I worked a little on this last sprint and ran into a couple of issues, shown below, that require further iteration.

- For mobile the component needs larger filter tags (I.e "Region 2") because of accessibility which takes up a lot of screen real estate.
- For future iterations, if a user would like to filter by state, tribe or territory, which was noted in the interviews, a full screen filter would need to be in place to accommodate those options and not take up too much mobile or tablet screen real-estate.

Ultimately, for scalability I would suggest going to a full screen filter, especially for smaller formats. What are your thoughts on this?

I can also make quick mockups for both iterations (USWDS component and custom option) when this gets put into a sprint so that we can see them side by side and make a decision on what to develop at that point?

Let me know your thoughts.

**Comment by reitermb** [comment]
Closeable. Making sure we have accessible/mobile friendly table controls will still come into play but this makes more sense as part of revisiting tdp admin mockups
