### ISSUE TITLE
As an OFA Analyst, I want to be able to view the same navigation on my phone or tablet

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#208]
This ticket is generated from remaining feedback on #178

Problem Statement: Navigation on desktop has been approved. How can a user view the same hierarchy and maintain their current workflow on a mobile or tablet device?

Questions:
TBD

AC: 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [ ] Mockup for menu navigation using USWDS components for Tablet and mobile (refer to https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.8.1/components/preview/header--basic.html)
- [ ] Check for accessibility 

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by amilash** [comment]
@lfrohlich From a security perspective is there a reason for us to limit the use of phones/tablets? Does the gov't issue mobile devices? Asking this b/c some of this data is PII. Have we built already for mobile/tablets?

**Comment by lfrohlich** [comment]
An OFA analyst wouldn't use a phone/tablet because they need to use their PIV to access.  STT may use any device, so we'll still need responsive designs for most screens, but not for django admin, for example

**Comment by amilash** [comment]
I am closing as this is no longer needed.
