### ISSUE TITLE
Add integration tests for custom OIDC logic

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#209]
Description:
There should be an integration test to cover the custom Open ID Connect (OIDC) logic in the login process.
This is addressing one of the verbal comments from the Sprint 2 PR regarding the "no cover" statements in areas where we required a response from the login.gov server. 

AC: 

- [ ] Integration tests to cover the custom logic in login.py
- [ ] Unit test to check HttpOnly cookie

Tasks: 

- [ ] Add Mozilla OIDC test server to docker
- [ ] Write tests to cover the login process
  - [ ] Mock state and nonce values
  - [ ] Log in to test server and retrieve token
  - [ ] Mock the OIDC endpoint and add data to session
  - [ ] Use token to log in to app
  - [ ] Write unit test to verify HttpOnly Cookie
 - [ ] Code documentation and annotation of why system is the way it is

DoD: 
 - [ ] @lauraGgit has reviewed and signed off
 - [ ] All tests are passing
 - [ ] There are no linting errors
 
 Note: I am assigning 3 story points to this task, but want to note the risk that we are currently making some assumptions about how the Mozilla test server works. The assumptions are based on good research, so i'm fairly confident it won't be a problem, but if the test server doesn't work the way we expect it could add some time to getting this to work properly.

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

- Does this belong as an acceptance criteria or definition of done?

**Comment by shubhi-raft** [comment]
Update on not completing task 

> Add Mozilla OIDC test server to docker

We ran into dead end with the OIDC integration tests. We had planned to use Mozilla test provider as an alternative. However, it does not authenticate in the same way that login.gov does, and it builds in a redirect that we can't overwrite, making it impossible to use. The only way around this would be to build our own "mini login.gov"  to test against, which would take weeks of effort. Given this, we discussed an alternative approach of using unit tests and mocking the login.gov responses to cover the untested lines of code.

**Comment by shubhi-raft** [comment]
note on open question: included in #221.

**Comment by lfrohlich** [comment]
@shubhi-raft  was this resolved with #236? would be good to tie up this loose end

**Comment by RafterGit** [comment]
> @shubhi-raft was this resolved with #236? would be good to tie up this loose end

@lfrohlich  This was re-opened shortly  after merging the PR since Github has nasty habit of immediately closing issues we've linked to hour PRs . It can be closed

**Comment by lfrohlich** [comment]
Closing
