### ISSUE TITLE
As an admin, I need to understand how a new STT user will be validated

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#210]
Description:
A new user that is a representative of an STT cannot be solely verified via a new users' email domain. In the proposed approach, the onus is on the STT admin to validate new users, however, there may be security concerns around how PII is handled, what is acceptable, and who has access to this information. This issue will document our approach to validating new STT users, assumptions, and any OCIO governance or security controls that need to be accounted for. 

AC: 

- [ ] Document approach (e.g., artifact for get an input for notional validation process) to validate a new STT user including assumptions that shall be tested in Round 3 and/or future rounds of research 

Tasks: 

- [x] Schedule meeting(s) with OCIO, O&M, OFA, 18F, etc., to discuss the current process and future approach
- [x] Document the meeting notes and update the proposed approach and assumptions, if necessary

Note:
- This issue is dependent of schedule availability of OCIO, OFA, O&M, and 18F and may be pushed into next sprint if schedules don't align or if more than one meeting is needed. 
- Shubhi will work with Lauren to create a draft a list of attendees that can represent OCIO, O&M, and other OCIO divisions. 

Open Questions:
- What do we need to know for MVP?
 -- Documented in updated [roadmap](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1592336604317/61159efd030645a74c267130ea19b2083f87dd09) presentation. 
- How might we differentiate between verifying a STT user vs a STT admin? 
  -- For OFA MVP, STT admin will be a regional specialist 
- How do we ensure assumptions we are making for STT admins are correct? 
  --  Discussing with regional specialists 
- What phase of research do we want to talk to STTs about this? Could be part of the conversation guide for Round 3.
 -- Since round 3 does not include any discussions with regional specialists, this will be a separate discussion. #322

Answers to OQ:
- What do we need to know for MVP? 
- How might we differentiate between verifying a STT user vs a STT admin? 
- How do we ensure assumptions we are making for STT admins are correct? 
- What phase of research do we want to talk to STTs about this? Could be part of the conversation guide for Round 3.

Deliverable(s):
- Link to the presentation shared with IPT is [here](https://hhsgov.sharepoint.com/:p:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/%23210%20-%20STT%20validation.pptx?d=w5fb5cb3c03ba41bfa26294a31e5a1f8b&csf=1&web=1&e=bGjnH4). The last slide 'Approach for OFA MVP' lists the agreed upon approach for OFA MVP.  
 - New issue created to track some of the open questions - #322

**Comment by lfrohlich** [comment]
Penyin will send access management documentation for the current TDRS and the latest access management policy.

**Comment by lfrohlich** [comment]
Section 2 of SSP

**Comment by lfrohlich** [comment]
This was done as part of Sprint 5 #63
