### ISSUE TITLE
As a product team, we need to understand how users navigate TDP flow 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#211]
Description:
As a product team, we need to understand how users navigate TDP flow - (user) actions, system actions, and decision points. We will use this task flow to inform decisions on how the site is structured and how users interact with that structure. Once this is created, updating it will be an AC for any future mockups to ensure it stays in sync. This will be a living document and will be low-fi. 

AC: 

- [x] user flow is outlined for the past mockups and placeholders/ future mockups for next epics until Sprint 7
- [x] plan to update the user flow is added to the AC for future design issues (possibly updating design issue template). 

Tasks: 

- [x] Create a draft user flow based on existing screens 
- [x] Create a draft user flow for anticipated functionality for sprint 7
- [x] Bring in test user (Data Prepper) and OFA admin and map out their expected journey

Existing Screens: Profile, Admin, Login and Create Account

Open Questions:
- Does the user flow need to include interaction with login.gov? 
  - For MVP, only create user flow post login.
- Does this sub for logical data model? 
  - Logical data model is not needed

#### Deliverable(s):
- [Link to mockup](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

**Comment by shubhi-raft** [comment]
Capping it to 3 points. Future issues can be spun off if necesssary.

**Comment by shubhi-raft** [comment]
@lfrohlich Per backlog refinement meeting, the task flow could be leveraged for potential OCIO artifacts - logical data model. Physical data model issue can be created from the code; more information is needed.

**Comment by lfrohlich** [comment]
I was looking through OCIO artifacts and trying to better understand logical and physical data models. I found this description online (http://www.agiledata.org/essays/dataModeling101.html):

Logical data models (LDMs). LDMs are used to explore the domain concepts, and their relationships, of your problem domain. This could be done for the scope of a single project or for your entire enterprise. LDMs depict the logical entity types, typically referred to simply as entity types, the data attributes describing those entities, and the relationships between the entities. LDMs are rarely used on Agile projects although often are on traditional projects (where they rarely seem to add much value in practice).
Based on that description I wonder if there is a basic version of the user flow (#211) that could check the logical data model box.

**Comment by dk-ui** [comment]
This ticket will be started in Sprint 3 but not completed in this sprint. Will roll over into sprint 4.

**Comment by lfrohlich** [comment]
I clarified with OCIO that the physical data model can fulfill the requirement for a logical data model. So this not longer needs to be a compliance artifact

**Comment by dk-ui** [comment]
@shubhi-raft @reitermb @matthewjdoty For 'Create a draft user flow for anticipated functionality' were we thinking a collaborative approach for this after the synthesis of the interviews so we can use that synthesis to guide the formation of these user flows?

**Comment by lfrohlich** [comment]
Do we want to update the design template to include updating the user flow diagram? We can include it as part of documentation

**Comment by shubhi-raft** [comment]
@lfrohlich good point, created this [PR](https://github.com/raft-tech/TANF-app/pull/408) to update the design template.

**Comment by lfrohlich** [comment]
Great, thanks @shubhi-raft! I think this will be good to demo at the next Sprint Demo
