### ISSUE TITLE
As an admin, I want to see mockups to remove users from an existing role.

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#213]
Create mockups for OFA (and STT?) admins to unassign roles 

Questions: Is removing users deleting them from the system? What are the data implications, to what degree it's reversible or not? Any other implications - Interaction with login.gov, OCIO security and records issues?

This is a follow-on to #164

AC: 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [ ] Address open questions with OFA, security(?), other appropriate ACF stakeholders.
- [ ] Document decisions and open questions, if any
- [ ] Create mockups 

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @cmajel has reviewed and signed off
- [ ] @lfrohlich has reviewed and signed off

Proposed MVP roles:
- unassigned: total lack of permissions
- admin: all permissions, super user access (aka, Lauren + OFA analysts who are managing the system)
- data prepper: all available permissions for an STT; can access, view and submit data. (aka, anyone at a given STT)

**Comment by shubhi-raft** [comment]
dupe to #328

**Comment by amilash** [comment]
Closing as dupe
