### ISSUE TITLE
As a user, I need the filename for SSP section to be correctly assigned after uploading the file

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2154]
**Description**

After uploading files, the filenames are changed based on assigned section using https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/states.csv. Currently, the logic for renaming files for SSP section is missing and uploaded files are renamed incorrectly for SSP files. The SSP uploaded filename renaming logic has to be added in Datafile.model (see #2090 )

**Acceptance Criteria**

- [ ] SSP section is available in data file upload in frontend
- [ ] SSP section files are correctly renamed as per naming convention in STT model filename
- [ ] filename property in datafile model has the correct logic to rename STT section files using the [states table](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/states.csv)

**Notes**
SSP sections are listed below:
- 'SSP Aggregate Data'
- 'SSP Closed Case Data'
- 'SSP Active Case Data'
- 'SSP Stratum Data'

**Comment by stevenino** [comment]
@raftmsohani Can this be refined similar to #2090

**Comment by raftmsohani** [comment]
> @raftmsohani Can this be refined similar to #2090

@stevenino : Ticket refined
