### ISSUE TITLE
Users know which version of the backend is currently deployed

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#216]
Description:
Adding an API endpoint to the backend to let the user know which version of the backend is currently deployed. This is in support of allowing users to know what changes they can currently can expect to see when referencing future change logs and during development. 

AC: 

- [ ] A user can check an API endpoint to see what version of the backend is deployed

Tasks: 

- [ ]

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
@carltonsmith is this still relevant?

**Comment by stevenino** [comment]
Closed as OBE
