### ISSUE TITLE
front end service fails for 'File not found' when docker-compose is used for local dev

### ISSUE THREAD

**Issue by raft-twhitlock** [raft-tech/TANF-app#2163]
## Description

When running `docker-compose.local.yml` file in the tdrs-frontend directory, its failing with a `file not found` error. Because we are binding a mount when we specify the directory as a listed item in the `docker-compose.local.yml`, docker is looking for this bound directory as a shared directory. Docker, by itself is not aware of any directories that are shared except for the default ones. Default shared directories are listed by OS [here](https://docs.docker.com/compose/gettingstarted/#step-6-re-build-and-run-the-app-with-compose) under the `Shared folders, volumes, and bind mounts` warning.

Depending how each dev's instance of the docker engine or docker for desktop is setup, the project directory `TANF-app` is not configured to be a shared directory within docker. The setting to set this up is documented [here](https://docs.docker.com/desktop/settings/mac/#file-sharing).

## Action Taken

Rather then configuring a bound directory and configuring it to be shared within docker; a better approach and mostly recommended is to use shared volumes within a docker-compose file. The shared volume approach allows docker to manage these volumes with ease vs being limited to a bound directory that is dependent on structures of the host OS. More documentation on this can be found [here](https://docs.docker.com/storage/volumes/)

## What I expected to see

When I run the `docker-compose.local.yml` file from the tdrs-frontend directory; i should be able to have the tdrs-frontend docker image up and running without any exit status being given from the command `docker ps -a`

## What I did see

When I run the `docker-compose.local.yml` file from the tdrs-frontend directory; the front end container exits with a 127 error code. Upon getting the logs from the failed container; it points to docker-compose not being able to copy over files from the `tdrs-frontend` directory to the specified WORKDIR set up in the container image.

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

**Comment by jtimpe** [comment]
Closed as no longer relevant - this was fixed when nginx was connected to the backend
