### ISSUE TITLE
As a system admin, I want the STT object models to be revised

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#217]
Description:
An assortment of small issues related to the STT models which have cropped up over time.

ACs: 
- [x] Type and State field need to interoperate. `State` field should be unavailable if type selected is state. 
- [x] all fields should be `read_only`

Tasks: 
- [x] Adjust `type` field for tribes and states (i.e., do not show the state field for a state object).
- [x] Remove duplicative `code_number` from stt model [here](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/models.py#L31)
- [x] `Code` field should be renamed to represent that it is an abbreviation for the postal service. (e.g. `Postal`)
- [x] Add a `Sample` indicator (for a future ticket: if ==0, then any Section 4 data file should be rejected)

Supporting Documentation:
https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/tdrs-backend/tdpservice/stts/management/commands/data

Open Questions:

(any clarifying questions in support of the issue)

**Comment by valcollignon** [comment]
CSV link needs to be updated
AC needs to be discussed more. Is this intended for the tribe or FIPS code?
CC: @abottoms-coder @ADPennington

**Comment by ADPennington** [comment]
per 2/23 dev sync. 
- @ADPennington review the ACs to double-check the field names
- @tdrs-developers revisit the STT model and determine strategy for having a model for each STT type (Tribe, terr, state)

**Comment by stevenino** [comment]
@andrew-jameson to split this ticket into 2 tickets.
