### ISSUE TITLE
As Lauren, I want some heuristics for user research so I can evaluate vendor work. 

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#218]
**Description** 
Currently, 18F is pairing with Lauren to evaluate issues delivered by Raft. When 18F is gone, Lauren will need to do this review independently. We want to leave her with a heuristics checklist to help. 

**Resources**

- [Melissa Braxton's chart](https://gsa-tts.slack.com/archives/C02ABDXUN/p1597262733011500)
  - [Usability test heuristics](https://github.com/18F/ux-guide/blob/master/_pages/resources/usability-test-quality.md)

**AC**

- [x] Research heuristics checklist is created
- [x] Checklist is weighed against the current GH issue template so they are complementary
- [x] Coordinate with #173 
- [x] Checklist is reviewed with @lfrohlich 
- [x] Checklist is stored in shared location (Teams or GH Wiki)

**Comment by SelenaJV** [comment]
@cmajel I created this issue. If you have a chance, flesh it out before Sprint Planning. Thanks!

**Comment by cmajel** [comment]
@SelenaJV @lauraGgit, I have an early version of [research / usability test heuristics here](https://docs.google.com/document/d/1MB6bJje8Fvr3DXgOejfBs19LejQETXXmeKwutSs78zo/edit#heading=h.dcs9j2vzcsqh). I just made a few adjustments to the existing list.

Can you take a look and see if we're on the right track?

**Comment by cmajel** [comment]
@lfrohlich here's [our draft version of skill area heuristics](https://teams.microsoft.com/l/file/42B2475E-F075-4A17-B405-84665185006F?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FAdmin%2FDraft_%20Skill%20area%20heuristics.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287), which includes design, code and research indicators. These feel in line to me with [our current issue templates](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/.github/ISSUE_TEMPLATE). 

Passing to you for your review / feedback.

relates to #220 #220

**Comment by lfrohlich** [comment]
Heuristics were merged with #61
