### ISSUE TITLE
As Lauren, I want some heuristics for dev issues so I can evaluate vendor work.

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#220]
**Description** 
Currently, 18F is pairing with Lauren to evaluate issues delivered by Raft. When 18F is gone, Lauren will need to do this review independently. We want to leave her with a heuristics list to help. 

**Possible Elements**

- How to check automated tests
- What to look for in automated tests
- How to check test coverage
- What to ask for and look for in Patricks PR review comments. (Greg says to ask vendor to be verbose)
- security issues. How does Lauren know it is secure?

**AC**

- [x] Dev evaluation heuristics list is created
- [x] Heuristics list is weighed against the current GH issue template so they are complementary
- [ ] Coordinate with manual testing guidelines #173 
- [x] Heuristics list is reviewed with @lfrohlich 
- [ ] Heuristics list is stored in shared location (Teams or GH Wiki)

**Comment by SelenaJV** [comment]
@lauraGgit I created this issue. If you have a chance, can you flesh it out before Sprint Planning?

**Comment by cmajel** [comment]
@lfrohlich here's [our draft version of skill area heuristics](https://teams.microsoft.com/l/file/42B2475E-F075-4A17-B405-84665185006F?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FAdmin%2FDraft_%20Skill%20area%20heuristics.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287), which includes design, code and research indicators. These feel in line to me with [our current issue templates](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/.github/ISSUE_TEMPLATE). 

Passing to you for your review / feedback.

relates to #219  #218

**Comment by cmajel** [comment]
@alexsoble would you mind looking at the comments for [the Code Heuristics](https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA~2FShared%20Documents~2FGeneral~2FAdmin~2FDraft_%20Skill%20area%20heuristics.docx?threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&baseUrl=https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA&fileId=42b2475e-f075-4a17-b405-84665185006f&ctx=files&rootContext=items_view&viewerAction=edit)?  There is a question about available automated tools and an edit I made about USWDS and DRY code that I'd like your eyes on before we close this out.

**Comment by alexsoble** [comment]
@cmajel Done! I love the USWDS edit, and I added a comment about automated complexity checking.

**Comment by lfrohlich** [comment]
This was merged with #61
