### ISSUE TITLE
As a Tadpole, I want clarity on AC, DoD, and story points so I know I'm doing the right work. 

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#221]
**Description:**
We've been confused about which considerations are weighed when. Let's meet to work this out and then document our decisions.

**Questions**

- When is DoD evaluated--at issue level or Sprint PR level?
- Who evaluates ACs? DoD?
- What issue templates should be updated to reflect our new understanding?
- What kinds of issues are pointed? Admin? Tech debt? 18F work?

**AC**

- [x] Considerations have been discussed with 18F, Raft, and Lauren
- [x] Raft updates issue templates if appropriate
- [x] Decisions are documented in Team Charter

**Comment by lfrohlich** [comment]
This has been documented in [Teams](https://teams.microsoft.com/l/file/5D09E660-C69D-4A8E-82B9-18DF9C85EB73?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FAdmin%2FAC%20and%20DoD%20Discussion_Issue%23221.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

**Comment by lfrohlich** [comment]
@shubhi-raft  have the issue templates been updated?

**Comment by shubhi-raft** [comment]
@lfrohlich Yes, dev has been updated. No change was required for design and research since DoD for design and research issues will continue to be reviewed at the issue level. Team charter has also been updated per our discussion - Page 9 - with track changes.

**Comment by lfrohlich** [comment]
great, thanks

**Comment by lfrohlich** [comment]
THis is done from my perspective
