### ISSUE TITLE
As a user, I can edit my profile.

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#223]
**Description:**
When a user signs in for the first time, they are prompted to create and submit a profile. This issue will deliver editing the first and last name of a saved profile that can be viewed under the 'Profile' tab. Email and STT fields cannot be edited. 

**Acceptance Criteria:** 
- [ ] Clicking the Edit button causes the first and last name to be editable 
- [ ] Clicking the Save button updates users profile with the change(s) and serves a Success status notification  
- [ ] Testing Checklist has been run and all tests pass

Tasks: 
Frontend
- [ ]  Add Edit button to Profile Page
- [ ] Create Edit Profile component
- [ ] Add two form fields: one for first name and one for last name
- [ ] Add Save button which calls updateProfile
  - - [ ] Serve [alerts](https://designsystem.digital.gov/components/alert/) for successfully updating profile and for unsuccessful validation
- [ ] Add cancel button which navigates back to Profile Page

Frontend Points: 3

Backend
- [  ] Write unit tests for user update endpoint
- [  ] Add endpoint for updating user data
- [ ] Ensure user has permission to update the user
- [  ] Write integration test for updating a user

Backend Points: 3

Open Question:
- Does this need to be delivered for OFA MVP?
   - No.

#### Supporting Documentation:

![Screen Shot 2020-11-09 at 10 51 08 AM](https://user-images.githubusercontent.com/22622384/98563754-8d2f3300-2279-11eb-862d-e1f89635920f.png)

**Comment by amilash** [comment]
This is done.
