### ISSUE TITLE
As an on-boarded user, I can view my profile on the TDP Landing Page

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#224]
Description:
After an admin has assigned a role to a user, the user can see his/her profile on the dashboard page.

AC: 

 - [ ] User can view his/her profile

Tasks: 

Frontend
- [ ] Add a card to the dashboard (for users who have been assigned a role)
- [ ] Add Profile tab to navigation
- [ ] Add My Profile header
- [ ] Card should contain: Name, email, STT, and region

Frontend Points: 2

Backend
- [ ] Write unit tests for user get endpoint
- [ ] Add endpoint for getting user data

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)
 - [ ] Figma: https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-%2F-Admin-Mockups-For-Feedback?node-id=628%3A468
Just this (minus the Edit button and Reset Password button):
![image](https://user-images.githubusercontent.com/7072066/92016525-71ab2780-ed20-11ea-80bc-846f05e69552.png)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
duplicate to #239
