### ISSUE TITLE
Data Files from previous submissions showing up in recent quarter

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2256]
## Description

One of the tribes from the v2.0 pilot submitted feedback that when they went to the 2022 Q4 section that their 2022 Q3 data files were displayed. They were not expecting to see any data files yet. This was an unmoderated session so we didn't have recordings of this happening in real time. The below are the results of our testing in Stage.

We have a video recording, but it is too large to upload here - we can forward via MM if needed.

## Replication Procedures

Pre-requisites:
- Existing data files in 2022, Q3 submitted in the past 
- Access Request Approved for Data Analyst role

- Sign in to TDP in Stage
- Navigate to Data Files
- Select 2022, Quarter Q4 and Search

What I did see: 
- 2022 Q3 data files in the 2022 Q4 sections
![Screen Shot 2022-11-09 at 11 26 02 AM](https://user-images.githubusercontent.com/104451160/201162992-08508bb9-fe80-41e0-9e31-1944b7a435e4.png)

https://user-images.githubusercontent.com/28515874/201205089-f3ca29ba-18d2-4538-a150-a430336d90d1.mp4

What I expected to see
- No data files at all

Part 2: 
- IF you upload data files in a section that already has a data file, submit, receive success toaster, receive submitted data files success email 
- Go back into Data Files and Search for a different quarter
- Then go back to the original quarter where you uploaded files successfully, those data file name don't appear to persist
- Would need to confirm whether the backend has them correctly coded though, but from the grantees perspective it doesn't appear to be persisting.

**Comment by ADPennington** [comment]
### 12/7/2022 Update

A pilot user noticed this bug today. When they tried to pull up files from their Q4, 2022 submission from yesterday,  Q3, 2022 files appeared.

**Comment by lilybl1** [comment]
Jan and I reviewed this and cannot seem to reproduce this again. We can close this ticket out and we will monitor this as we roll into the February 2023 data submission.

**Comment by Smithh-Co** [comment]
Closed per Diana and Jan being unable to reproduce bug. UX to monitor for similar reports heading into Feb 2023 data submission.

@lfrohlich @ADPennington
