### ISSUE TITLE
Finalize user research goals for STT research

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#226]
Description:
Draft user research goals for the next round (September - October) of STT research. Goals will be based on the roadmap: users can login, upload and view data. Working copy is included [here](https://teams.microsoft.com/l/file/E6603F70-2D57-47AD-9FF4-D92840941ED4?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2FSTT%20Research%20September%202020%2FDraft%20Research%20Goals%20-%20STT%20Research%20Goals%20-%20September.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) 🔒  The finalized research goals will be part of the STT research plan (Round 3 of research).

The final document can be found [here](https://teams.microsoft.com/l/file/A7504334-576D-4ADC-B3AF-45A432492E2F?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch%2FShared%20Documents%2FUser%20Research%2FSTT%20Research%20September%202020%2F%23226%20-%20September%20User%20Research%20Goals%20-%20STTs.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch&serviceName=teams&threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287). 

AC: 

- [ ] Research goals have been reviewed and finalized and are ready to be added to the research plan #63 . 

 Tasks: 

- [x] Draft research goals and share it in teams as a working copy 
- [x] Schedule pairing session w/ 18F and OFA to work through the goals
- [x] Document feedback and update goals, if necessary
- [x] Document open questions for future research

**Comment by matthewjdoty** [comment]
Moved to "Gov Review". The final document can be found [here](https://teams.microsoft.com/l/file/A7504334-576D-4ADC-B3AF-45A432492E2F?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch%2FShared%20Documents%2FUser%20Research%2FSTT%20Research%20September%202020%2F%23226%20-%20September%20User%20Research%20Goals%20-%20STTs.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch&serviceName=teams&threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287).

**Comment by cmajel** [comment]
@matthewjdoty thanks! Adding some notes in the doc, recapping here:

* Can you update the description of the issue with the final doc? (top link is still going to the draft)
* For me, goals 3 (upload prototype) and 4(how STTs track submissions) feel the newest and most relevant to the roadmap and an MVP. Goal 1 (understanding team roles) and goal 2 (understanding data transmission process) have been touched on in the past, and feel like enrichment opportunities as time allows. 
* For goal 2 (documenting upload process), noting that this is retreading existing research a bit. Which, could be fine as long as we're being clear about new things we want to learn or how its balanced alongside other topics. Can you add some clarification?
* I think we already know a lot of the reasons why headers/trailers cause issues in the current system (outlined in doc). Is there more info you're looking for?

With those clarifications I'm good signing off for review.

**Comment by cmajel** [comment]
(also noting that in general this level of detail is really nice to see 🎉 )

**Comment by matthewjdoty** [comment]
To: @cmajel 
CC: @lfrohlich 

Excellent Feeback! Thank you so much. Here's where we are...

- We've updated the description of the issue with a link to the final doc
- We agree with you on goals 1 & 2. I'm working with @reitermb & @dk-ui to provide the desired clarity on the additional items we want to learn

**Comment by matthewjdoty** [comment]
To: @cmajel  
CC: @lfrohlich

OK after conversing with @reitermb and @dk-ui we've updated the document and responded to the commentary. Happy to respond to any additional feedback.

**Comment by lfrohlich** [comment]
I think this is close. Building off of Christine's comments, I would advocate for flipping goals 3/4 and 1/2. 1 & 2 do seem like somewhat already covered and later stage/bonus research goals, as opposed to core research goals for this round. ALso, I am a bit concerned that these are too many goals for one round. It might be helpful for me to better understand how you see goals 1 & 2 informing the MVP.  Once you all dive into the conversation guides it could be more clear what you'll have time for, but I would like the focus to be on 3 & 4 first and then 1 & 2 if time allows. Before finalizing/demoing, could you switch the order and emphasis (or could we discuss the rationale for keeping as is)?  Thanks~

**Comment by matthewjdoty** [comment]
@lfrohlich. Excellent feedback! We've updated to goals to reflect the desired priority. We've also explicitly labeled the goals "primary" and "secondary".

**Comment by lfrohlich** [comment]
Thanks! This reorg looks good to me.

**Comment by lfrohlich** [comment]
THis was completed in Sprint 3
