### ISSUE TITLE
Determine user research methods and document ethics, timeline, and logistics for STT Research (Round 3)

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#228]
**Description:**

Based on the approved research goals #226 and expected outcomes #227, (1) determine the methods that will be used to conduct STT research, (2) document ethics, privacy concerns, (3) interview logistics (date, time, and remote web conferencing software) are defined, and (4) timeline for completing Round 3 - STT research.

**AC:** 

- [x] Methods are determined, 
- [x] Ethics and privacy concerns are documented, 
- [x] Interview logistics are finalized 
- [x] Timeline for conducting round 3 research, synthesizing top-line synthesis and detailed findings is documented

 **Tasks:** 

- [x] Methods are informed by user research goals and expected outcomes and outputs
- [x] Review ethics and privacy concerns for spring 2020 research and document any changes
- [x] Draft interview logistics [be cognizant of limited bandwidth and older systems that may be in use by STTs]
- [x] draft research and synthesis timeline - use spring 2020 to frame the duration  
- [x] Pairing with 18F and OFA to discuss and finalize above listed tasks and PII/research privacy conversation
- [x] Document any feedback/questions and update above items as needed
  
**DoD:**

 - [x] Documentation: user research methods and document ethics, timeline, and logistics for STT Research
 - [x] @cmajel has reviewed and signed off
 - [x] @lfrohlich has reviewed and signed off

**Deliverables**
Methods, Ethics, Timeline (documented in the research plan): ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B2E300237-F645-4446-B191-A9EE509026EF%7D&file=%2363%20User%20Research%20Plan%20STTs.docx&action=default&mobileredirect=true))
Interview Logistics ((documented in the interview protocol): ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B0333313B-0F88-406B-B894-07687D32921B%7D&file=%23170%20STT%20Interview%20Protocol%20DRAFT.docx&action=default&mobileredirect=true))
Email for STT Participation: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B645FCFDC-C65D-474A-9C57-D51F3C68AC96%7D&file=%23228%20Email%20for%20%20STT%20Participation.docx&action=default&mobileredirect=true))
PDF Mockup 1 for Limited Bandwidth Users: ([Link](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA-UserResearch/Shared%20Documents/User%20Research/STT%20Research%20September%202020/TANF%20Uploading%20Tool_Mockup%20%231.pdf?CT=1602102632479&OR=ItemsView))
PDF Mockup 2 for Limited Bandwidth Users: ([Link](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA-UserResearch/Shared%20Documents/User%20Research/STT%20Research%20September%202020/TANF%20Uploading%20Tool_Mockup%20%232.pdf?CT=1602102673212&OR=ItemsView))

**Comment by dk-ui** [comment]
@shubhi-raft @matthewjdoty @lfrohlich @cmajel  Only thing still outstanding for this ticket is "Pairing with 18F and OFA to discuss and finalize the listed tasks" Hence this will roll over to sprint 5.

**Comment by matthewjdoty** [comment]
@reitermb please link to the file in the description

**Comment by shubhi-raft** [comment]
@dk-ui @reitermb moving this back to in progress.

**Comment by dk-ui** [comment]
Interview logistics have been updated. See this link.

https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B0333313B-0F88-406B-B894-07687D32921B%7D&file=%23170%20STT%20Interview%20Protocol%20DRAFT.docx&action=default&mobileredirect=true

**Comment by lfrohlich** [comment]
I had a comment in #170 Interview Logistics about whether we're ok including the STT itself in the schedule table, while coding the participant name. This may have been covered in the other conversations you all had about privacy. If it's just about scheduling, is it fine to have the STT. Or event when it's more than scheduling, is it ok as long as it's not the participant name? i'm fine with either.  tagged @cmajel  in teams

**Comment by lfrohlich** [comment]
This is good to close!
