### ISSUE TITLE
Schedule meetings for sprint ceremonies meetings

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#23]
Description:
Schedule sprint ceremonies with the scrum team on a reoccurring basis.

1. Recurring sprint meetings (Start on Wednesday and end on Tuesday) 
2. Sprint review (60 minutes) Tuesdays 

   - Demo format 

   - Pre planning coordinating meeting (30 minutes) (only in the beginning) 

3. Sprint retro (60 minutes) Tuesdays or Wednesdays 
4. Backlog refinement (90 minutes) 
5. Sprint planning (90 minutes) Wednesdays 
6. Stand up @ 10:30 (15 minutes) 

AC: 

- [x] All sprint ceremonies have been scheduled

**Comment by bb-at-raft** [comment]
Proposed by Raft:  

Sprint Review | Tue | 2:00-3:00 PM ET
Sprint Retrospective | Tue | 3:30-4:30 PM ET
Backlog Refinement | Wed | 2:00-3:30 PM ET
Sprint Planning | Wed | 3:30-5:00 PM ET

**Comment by lfrohlich** [comment]
All meeting are scheduled!
