### ISSUE TITLE
As System Owner, I need official guidance for TDP

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2300]
### Description

At ACF, we typically publish **information memoranda (IM)** or **program instruction** for grantees when specialized guidance is needed. 

Before OFA can decommission the legacy system (~Feb 2024), all STTs need to be using TDP. Our experience with recruitment/onboarding since v2.x suggests that STTs and OFA staff would benefit from background information on TDP to support this transition. 

OFA will take the lead on this task and work with the UX team on language as well as any updates to project updates, knowledge center, recruitment/onboarding materials, etc. 

### Details to include
- how the onboarding process will work
- estimated timeline for transitioning from file transfers to TDP
- links to TDP resources (project updates, knowledge center)
- FAQ/tips for preparing to use TDP for data transmissions 
  - can STTs still use .exe tools?
  - getting approvals from STT leadership
  - security-related stuff (e.g. static IP no longer needed)
  - submitting multiple quarters at once (e.g. in one file vs multiple)
  - who should use the system? 
 - etc.

### Final draft
 :lock: [link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/Shared%20Documents/General/TDP%20Draft%20Dear%20Colleague%203.13.23_Final.docx?d=w0b8b25b4d39945faaafcb387b7908340&csf=1&web=1&e=a72GrX)

[Dear Colleague Letter](https://www.acf.hhs.gov/ofa/policy-guidance/dear-colleague-tanf-data-portal)

**Comment by ADPennington** [comment]
@reitermb @lilybl1 started this issue to track the development of the **info memo**. Please feel free to add to the list things we should be sure to mention.

**Comment by lfrohlich** [comment]
Note this may be a program instruction or other type of guidance

**Comment by lfrohlich** [comment]
@ADPennington the [draft ](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/Shared%20Documents/General/TDP%20Formal%20Guidance.docx?d=w8ec8d29d3a6143e39a0e4cb6b4704c53&csf=1&web=1&e=iE5fNg)is ready for your review. I'm thinking we should consider having separate guidance for tribes or a special section for tribes.

**Comment by ADPennington** [comment]
@lfrohlich this looks really good. I left some comments for discussion. I like the idea of a separate section for tribes, but we probably need to think about the placement in the letter, so it doesn't seem like their considerations come last.

**Comment by lfrohlich** [comment]
@ADPennington I made a few more edits-- could you take one more quick before we share with others?

**Comment by ADPennington** [comment]
> @ADPennington I made a few more edits-- could you take one more quick before we share with others?

lgtm! i made minor edits and one light suggestion to mention the feedback form. @lfrohlich cc: @lilybl1 @reitermb

**Comment by lfrohlich** [comment]
Thanks @ADPennington ! @reitermb and @lilybl1 can you take a look when you get a chance?

**Comment by lilybl1** [comment]
@lfrohlich Thank you! Really good content. I've reviewed and shared a few thoughts.

**Comment by reitermb** [comment]
> @lfrohlich Thank you! Really good content. I've reviewed and shared a few thoughts.

Seconded & also added some comments cc @lfrohlich @ADPennington

**Comment by lfrohlich** [comment]
Received edits from regional and DTTM staff, incorporated Ann's edits. Ann approved 3/14
