### ISSUE TITLE
Expansion of Accessibility Testing

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#232]
Description:
Updates need to be made to provide a more thorough accessibility testing reports

AC: 
- [ ] Manual testing of accessibility passes as defined in https://app.zenhub.com/workspaces/tdrs-product-backlog-5f2c6cdc7c0bb1001bdc43a5/issues/raft-tech/tanf-app/173
- [ ] Updates to Pa11y automated testing in CirlcCI to perform a deeper analysis of accessibility adherence.

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
this is done with #173.
