### ISSUE TITLE
As a compliance person, I want to see a database erd.

### ISSUE THREAD

**Issue by lauraGgit** [raft-tech/TANF-app#233]
Description:
(please define the reason as to why this issue is being created )
Generate an erd automatically from the django models, potentially in CI, but as a minimum in a off-off command.

Note: looks like this should be relatively easy using this django library: https://django-extensions.readthedocs.io/en/latest/graph_models.html#graph-models

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by lfrohlich** [comment]
Duplicate; merged with #253
