### ISSUE TITLE
CircleCI Security Incident Response

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2336]
## Description
![image](https://user-images.githubusercontent.com/84722778/210823266-c3874fd7-f3d5-4eaa-bff9-99661db46397.png)

## Action Taken

On raft-tech circleci, deleted AMS secret, JWT_KEY, and non-dev passwords for Cloudfoundry.
On HHS circleci, deleted equivalently sensitive environment variables.

## Actions Still Needed

Rotation the keys with our various touchpoints (Login.gov, AMS, Titan, etc.)

Update both CircleCI instances with new values and retest each capability.

## Other Helpful Information

**Comment by lfrohlich** [comment]
For reference: https://github.com/HHS/TANF-app/blob/8acace8db8e05eda602114e074ae3448d7133d1e/docs/Technical-Documentation/secret-key-rotation-steps.md

**Comment by lfrohlich** [comment]
@ttran-hub and I deleted keys in TANF-app with coaching from @andrew-jameson.

**Comment by andrew-jameson** [comment]
Removed cloudfoundry prod password, ams secret, non-dev jwt_keys, ACFTitan key.

**Comment by andrew-jameson** [comment]
Change request submitted for Production Login.gov. Will generate new keys momentarily.

**Comment by ttran-hub** [comment]
New key requests for AMS and ACFTitan have been submitted to OCIO.

**Comment by ADPennington** [comment]
before this ticket closes, we will develop an incident response drill to save to the [repo](https://github.com/raft-tech/TANF-app/tree/develop/docs/Security-Compliance/Incidence-Response) that is focused on this issue. this should satisfy ocio's incident response tabletop requirement.

**Comment by lfrohlich** [comment]
From Alex: for titan keys, the process is for us to generate the new public private key pair and share the public key with OCIO (Harold). 

below is an example of how to generate new titan public/private key pair from git bash. two files called `filename_where_newtitan_keypair_saved` are created: one is the private key and the other is a public key (the latter is saved with a `.pub` extention). 
(note: the info below is not associated with any real keys)
```
apennington@HHSLBDSWL73 MINGW64 /
$ ssh-keygen -t rsa -b 4096
Generating public/private rsa key pair.
Enter file in which to save the key (/c/Users/apennington/.ssh/id_rsa): filename_where_newtitan_keypair_saved
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in filename_where_newtitan_keypair_saved
Your public key has been saved in filename_where_newtitan_keypair_saved.pub
The key fingerprint is:
SHA256:BY6Nl0hCjIrI9yZMBGH2vbDFLCTq2DsFQXQTmLydwjI apennington@HHSLBDSWL73
The key's randomart image is:
+---[RSA 4096]----+
| X*B*.. .        |
|+ O+=+ * o       |
|=oo* *+ = .      |
|Eo++B .. .       |
|.+=oo.  S        |
|   = o           |
|  o o            |
|   .             |
|                 |
+----[SHA256]-----+


```

**Comment by ADPennington** [comment]
> Change request submitted for Production Login.gov. Will generate new keys momentarily.

@andrew-jameson can you share the ticket number here?

**Comment by ADPennington** [comment]
1/11/2023 -- steps for rotating `prod` deployment credentials for circleci

0. verify existing credentials for `deployer` key in `tanf-keys` service instance (these are the values for `CF_USERNAME_PROD` and `CF_PASSWORD_PROD` in circleci project settings

```
# target prod space
cf target -o hhs-acf-ofa -s tanf-prod

# verify prod deployment credentials
cf service-key tanf-keys deployer
```

1. remove the current username associated the the `deployer` `tanf-key`  service instance from cloud.gov `prod` space (this is the same value as `CF_USERNAME_PROD` )

```
cf delete-user <<insert USERNAME value for deployer key>>
```


2. delete the `deployer` service key associated with `tanf-key` service instance ([reference](https://docs.cloudfoundry.org/devguide/services/service-keys.html))

```
# delete
cf delete-service-key tanf-keys deployer

# verify deletion
cf service-keys tanf-keys 
```

3. create new `deployer` service key within `tanf-key` instance (reference link above)

```
cf create-service-key tanf-keys deployer
```

4. add username for newly generated `deployer` service key to `prod` space as a user to prod space and assign as an org user and space developer

```
# add user
cf create-user <<insert USERNAME value for deployer key>>

# add as a user to org
cf set-org-role <<insert USERNAME value for deployer key>> acf-hhs-ofa OrgUser

# add as developer to prod space
cf set-space-role <<insert USERNAME value for deployer key>> acf-hhs-ofa tanf-prod SpaceDeveloper
```

5. test that the new deployment credentials work in circleci (re-run nightly scan workflow after adding `CF_USERNAME_PROD` and `CF_PASSWORD_PROD` back to hhs circleci with rotated values)

**Comment by andrew-jameson** [comment]
> > Change request submitted for Production Login.gov. Will generate new keys momentarily.
> 
> @andrew-jameson can you share the ticket number here?

2568. I have also forwarded you the chain.

**Comment by ADPennington** [comment]
@ttran-hub and I have verified that the newly rotated prod keys for AMS and Titan are working properly. we will meet again tomorrow to rotate the `deployer` keys as documented [here](https://github.com/raft-tech/TANF-app/issues/2336#issuecomment-1379449757)

cc @lfrohlich @andrew-jameson

**Comment by ADPennington** [comment]
> @ttran-hub and I have verified that the newly rotated prod keys for AMS and Titan are working properly. we will meet again tomorrow to rotate the `deployer` keys as documented [here](https://github.com/raft-tech/TANF-app/issues/2336#issuecomment-1379449757)
> 
> cc @lfrohlich @andrew-jameson

@ttran-hub and I successfully rotated the deployer credentials for prod and verified that they were successful by adding the new env vars to circleci and re-running the nightly scan workflow. 

![2336](https://user-images.githubusercontent.com/63075587/212168165-27f8a5e5-a691-4dea-bd02-3ec7cd7be430.PNG)


Also, sent a follow-up to login.gov to check that status of jwt rotation. once that is finalized, i'll open PR with documentation for this ticket for incident response. cc @lfrohlich

**Comment by ADPennington** [comment]
@andrew-jameson new jwt keys successfully tested in sandbox and prod logingov. the change request ticket can be closed. i'll update incidence response documentation to close out this issue.  cc: @ttran-hub @lfrohlich
