### ISSUE TITLE
As a OFA admin, I want to search and filter through user list

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#238]
#### Description:
This issue will deliver OFA admin searching and filtering through the list of TDP users

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

 

#### Supporting Documentation:

![Screen Shot 2020-11-06 at 6.55.28 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/10e6b346-7cbd-4722-90b8-97dc70f5c270)

#### Open Questions:
- Which fields are searchable and filterable?

**Comment by amilash** [comment]
This is something that we should build when we build the admin UI outside of Django

**Comment by robgendron** [comment]
@ADPennington @lfrohlich is this still needed? We may need to rewrite this ticket for Django.

**Comment by robgendron** [comment]
Deemed closed by team.
