### ISSUE TITLE
As an authenticated user, I can see my profile.

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#239]
**Description:**
This issue will deliver an authenticated but unassigned user to view his/her saved profile information in the 'Profile' page.   - first and last name, email and associated STT  

**Acceptance Criteria**: 
- [ ] As a logged in user, view first and last name, email, STT and [Region(based on response to open question)]
- [ ] STT User cannot edit their fields (only sysadmin?)
- [ ] New user story is created for authenticated with a user role to see my profile with an associated role. 

Tasks: 
- [ ] TBD

Frontend
- [ ] Add a card to the dashboard (for users who have been assigned a role)
- [ ] Add Profile tab to navigation
- [ ] Add My Profile header
- [ ] Card should contain: Name, email, STT, and (region?)

Frontend Points: 2

Backend
- [ ] Write unit tests for user get endpoint
- [ ] Ensure user has permission to view the data
- [ ] Add endpoint for getting user data

Backend Points: 2

Open Question
- Does this need to be delivered for OFA MVP?
  - No, but would be relatively easy to implement.
- Is displaying the region relevant to a new STT user? 
   - A: not necessarily. It might be helpful for knowing who to contact. 
- Can backend serve region(s)?
  - Yes

Notes:
- User cannot edit any of the profile information. That is addressed in #223. 
- Reset password CTA to be changed based on #318 (spike story for Reset Password CTA).
-  Not to implement unless waiting for gov review feedback. 

Supporting documentation:

[Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2657%3A12509)
![image](https://user-images.githubusercontent.com/28515874/134224458-cd5abb69-c827-4bb2-b8bc-b1bf698a05d8.png)

**Comment by shubhi-raft** [comment]
Add - placeholder for role - Role 'Pending'

**Comment by shubhi-raft** [comment]
@reitermb can you update the supporting docs in this issue with the new mockup for MVP that were created and shared during Sprint 6 review?

**Comment by abottoms-coder** [comment]
@reitermb Can you get update the above screenshot with latest?
