### ISSUE TITLE
As a user, I want to know what happens to my data when an idle session is automatically ended

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#240]
Description:
The app will automatically end the session after 15 mins of inactivity. It is unclear what happens to the data and how a user will be notified that their session has ended. 

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by kniz-raft** [comment]
Already done
