### ISSUE TITLE
[Django] Log Entry View - Being able to filter by STT

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2416]
**Description:**

This story is the result of the v3.0 pilot and the experiences for the Sys Admin.

**Related User Stories:**

—As a [Sys Admin] I want to be able to view log entries by STT Name so that I can quickly locate the information I need. 

**AC:**

- [ ] Add filter

**Tasks:**

**Supporting Documentation:**

**Comment by lhuxraft** [comment]
PLG is now in production, want to explore what we get from it first. May actually deprecate Django log entries in the distant future
