### ISSUE TITLE
As a STT, I need a way to view all API endpoints available in TDP to enable machine-to-machine interaction

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#242]
Description:
Use the `/api-schema.json` endpoint from the back-end to render the [OpenAPI](https://www.openapis.org/) compliant json into a visually pleasing and accessible API documentation.  We should be able to leverage work from https://github.com/Redocly/redoc

--to enable STT connection via end points.

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
@carltonsmith is this being documented somewhere?

**Comment by valcollignon** [comment]
This work has been done in #564. Ticket can be closed per @ADPennington in backlog refinement 11.23.21.
