### ISSUE TITLE
Document Retro feedback 9/1

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#243]
Description:
Document Retro action items from [9/1 Mural](https://app.mural.co/t/raft2792/m/raft2792/1595360542763/be32f1d40748d7d5be7656c38adeaf1f09f7026b) retro in [Teams](https://teams.microsoft.com/l/file/46129232-8B4C-4AC2-8D3A-6A2781DC4741?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FRetro%20Action%20Items.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) and create issues to address feedback.

AC: 
- [x] retro items action items have been documented 
- [x] Issues have been created for defining acceptance criteria for research feedback
- [ ] Task is added to current issues for including more annotation and documenting in code of why system is the way it is

Feedback already being implemented:
 - Smaller slices of user stories
 - Earlier check-ins and reviews
 - Raft sharing uninformed thoughts

 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by lfrohlich** [comment]
I see that issue #244 was created for defining acceptance criteria for research feedback

**Comment by lfrohlich** [comment]
@shubhi-raft  Has the task for annotation and documentation been added to current issues? /Has it been added to the template?

**Comment by shubhi-raft** [comment]
@lfrohlich Not really, but it has been added to the manual testing practice checklist #173. I think this aligns with our discussion on AC/DoD #221 and reviewing dev DoD at the Sprint level against the QASP.

**Comment by lfrohlich** [comment]
This was compelted
