### ISSUE TITLE
Define QASP review criteria for research and design feedback

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#244]
Description:
During 9/1 #241, there was a discussion on unclear acceptance criteria for research feedback. This ticket is for Raft team and Christine to discuss and create acceptance criteria for reviewing and documenting acceptance criteria for research outcome and outputs of the current and future research issues. 

10/6 Update: Per review of design and research heuristics in the 

AC
- [ ] Acceptance criteria for research issue is documented someplace logical
- [ ] Research & Design issue templates are updated (if needed)
- [ ] This checklist is compared with research and design heuristics checklists (see dependencies below) 

Tasks
- [x] Conversation with Design/Research team, Christine, and Lauren
- [x] Document Guidance/instructions 
- [x] Update research and design issue templates if necessary (No updates were necessary)

Draft document can be found [here](https://teams.microsoft.com/l/file/E2972102-6FB6-4771-94DD-256B9931F1B8?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2F%23244%20-%20Raft%20XD%20Standards%20for%20the%20TDRS%20project.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

**Comment by cmajel** [comment]
@shubhi-raft @matthewjdoty here's where the [ACs and expected tasks for research issues](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/.github/ISSUE_TEMPLATE/research-issue-template-.md) are stored. 

I'm not sure https://github.com/raft-tech/TANF-app/pull/241 is where there was an issue with research AC - is this meant to be something else? Seeing where there was confusion can help us figure out what needs adjusting.

**Comment by shubhi-raft** [comment]
@cmajel Thanks! Based on the feedback thus far, we have been creating an internal checklist for research issues before they are submitted for gov review. We would like to review the checklist with you so that we are all on the same page and are not missing anything. 

>I'm not sure https://github.com/raft-tech/TANF-app/pull/241 is where there was an issue with research AC - is this meant to be something else? Seeing where there was confusion can help us figure out what needs adjusting.

Not sure if this is the correct link? I think the research template is helpful on what the checklist for research plans/ looks like. I think what it is missing is, something we ran across in the past sprints. For example, when delivering the high level findings vs top-line synthesis, what it means to us, and what is the expectation when we are delivering them for gov review. 

cc @matthewjdoty

**Comment by shubhi-raft** [comment]
Review heuristics to check whether this is even needed. This maybe a duplication of effort.

**Comment by matthewjdoty** [comment]
I've uploaded the draft Raft Standards for the TDRS project and included the link in the description

**Comment by matthewjdoty** [comment]
Per sprint 5 raft review, Shubhi is working on incorporating lessons learned from other Raft client work into the "Analysis and Synthesis" Section.

**Comment by matthewjdoty** [comment]
UPDATE: Per conversation with @shubhi-raft, I'm making some final updates to the "Analysis and Synthesis" section

**Comment by kniz-raft** [comment]
@shubhi-raft is this still blocked? How can I help?

**Comment by shubhi-raft** [comment]
This can be closed. the team is in sync for the QASP criteria
