### ISSUE TITLE
Spike: brainstorm on patches/only-build-once for feature branches

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2460]
**Description:**
As follow on to #2458, we want to optimize our builds and promotions via nexus labelling and how to do this intelligently. This ticket is to come up with that workflow and implementation path.

**Acceptance Criteria:**
- [ ] Placeholder
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Placeholder
- [ ]

**Comment by robgendron** [comment]
Backlog Refinement, Dev Team deemed no longer needed.
