### ISSUE TITLE
as acf ocio, i need the TDP boundary diagram updated to reflect traffic/security changes

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2488]
With the merge of PR #2449 , we added a proxy server to handle where traffic to the system can come from. a visual of this process is [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/Technical-Documentation/diagrams/tdp-environments.png) and [here](https://github.com/raft-tech/TANF-app/tree/develop/tdrs-frontend/nginx). Using these as guides, we should update the [boundary diagram](https://github.com/raft-tech/TANF-app/blob/develop/docs/Security-Compliance/boundary-diagram.md)

**Comment by Smithh-Co** [comment]
Potential to include SendGrid service in boundary diagram via this ticket as well, @jtimpe generating ADR update in parallel.

cc: @ADPennington @andrew-jameson
