### ISSUE TITLE
As a data prepper, I want to know what my new task flow looks like

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#25]
Description:
For the new TDRS system, as a data prepper, I want to understand what my new task flow looks like. Expected outcome of research with STT. 

AC: 
- [ ] 

Tasks: 

- [ ] Document beyond the process maps what the task flow looks like at a granular level.
- [ ] Propose a task flow in line with the user stories in the roadmap

DoD: 
 - [ ] Task flow is shared with the PO for feedback

**Comment by shubhi-raft** [comment]
potentially similar to #211

**Comment by dk-ui** [comment]
Is this different from #211?

**Comment by matthewjdoty** [comment]
@lfrohlich, this has been marked as a duplicate, can we close it?

**Comment by lfrohlich** [comment]
CLose because duplicate
