### ISSUE TITLE
As a compliance person, I want to see a Physical Data Model/database erd

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#253]
Description: 
As part of the SDLC process, OCIO asks for a Physical Data Model. This artifact is required for the 10/1 technical review board meeting. Can this be autogenerated? @lauraGgit shared this example: https://github.com/HHS/TANF-app/blob/main/upload/models.py
Generate an erd automatically from the django models, potentially in CI, but as a minimum in a off-off command.

Note: looks like this should be relatively easy using this django library: https://django-extensions.readthedocs.io/en/latest/graph_models.html#graph-models

***AC***: 
 
- [ ] We have summary level or key information of a physical data model to present to OCIO by the next Technical Review Board meeting (9/24)
 
***Tasks***: 
 
- [x] Install pydot
- [x] Install pygraphviz
- [x] Configure settings
- [x] Generate PNG

***Notes***:
1. We are looking to use the Django Extension Graph Models to generate the ERD, based on the recommendation above
2. The documentation indicates that there could be some problems in installation, which may or may not come up, but could potentially take more time than expected to resolve

***Open Questions***:
1. Are there any specific requirements on this documentation from OCIO?
2. Is there a particular format we should use to deliver the documentation? This package will create PNG files or something called a "dot file." Is a PNG acceptable?

**Comment by shubhi-raft** [comment]
1. Are there any specific requirements on this documentation from OCIO? No
2. Is there a particular format we should use to deliver the documentation? This package will create PNG files or something called a "dot file." Is a PNG acceptable? PNG is acceptable

**Comment by lfrohlich** [comment]
This is done. We discussed that @carltonsmith  will generate the ERD as needed
