### ISSUE TITLE
[bug] SSP data files are not returned in API 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2533]
## Description

As an approved sys admin, I cannot see SSP data files that have been submitted in the API response. 

*sys admin*
![2533p3](https://github.com/raft-tech/TANF-app/assets/63075587/d09afcd2-dbab-4973-8e1a-7168884f634b)
*sttid = 46 (Vermont)*
![2533p0](https://github.com/raft-tech/TANF-app/assets/63075587/ca8bfe81-d0ab-4712-8666-4c67a0a00c25)
*SSP files submitted on `develop` site for sttid = 46*
![2533p1](https://github.com/raft-tech/TANF-app/assets/63075587/6b324abc-4055-492c-8f31-e9eab9cf7e62)
*API response for datafiles belonging to sttid=46*
![2533p2](https://github.com/raft-tech/TANF-app/assets/63075587/cc66d2ab-5113-4dde-990f-6823c976a41a)

## Action Taken

- submitted data as an approved, ofa admin/developer/data analyst on `develop` site
- changed role to `ofa system admin` on `develop` site
- navigated to `develop` api (via `/swagger` or `/v1/data_files/?stt=46`

## What I expected to see

I expected to see a response that included the SSP files for sttid = 46 (Vermont)

## What I did see

200 response with no files (note: for this test, only SSP files had been submitted for this sttid in `develop` environment ). 

## Other Helpful Information

- i did verify that any TANF files for tribes, states, and territories are returned in the response. 
- [`develop_API.py`](https://gorafttech.sharepoint.com/:u:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/develop_API.py?csf=1&web=1&e=KZxMGM) for testing :lock:

**Comment by ADPennington** [comment]
@andrew-jameson @elipe17 @Smithh-Co  I figured out what's going on here. 

[`get_queryset()`](https://github.com/raft-tech/TANF-app/blob/8fe5d9414d72afb94cb5841fb05a3264aced47e6/tdrs-backend/tdpservice/data_files/views.py#L123L130) is filtering out SSP files in the response unless these are passed in the query params.  

when i include the following params for VT, i get all the SSP files:

```
query_params = {'stt': 46,
                        'file_type':'ssp-moe'}
```

also reflected in the DRF:
![sspfiles](https://github.com/raft-tech/TANF-app/assets/63075587/f43631f3-1bd0-4b9b-a151-7a229b74cc4f)

So this no longer seems like a bug to me, but if `dev` team feels like filtering this way is not the kind of behavior we should expect, we can add it to backlog.

**Comment by andrew-jameson** [comment]
Discussed in dev sync 5.24, will create optimization ticket per @jtimpe
