### ISSUE TITLE
As a compliance person, I want to see documentation of the system design

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#254]
Description: In advance of the 10/22 technical review board meeting, we need to produce something to satisfy the system design document requirement (in Teams under compliance ). 

Acceptance Criteria: 

- [x] We have something to share with OCIO as part of the Preliminary Design Review
- [x] The wiki and GitHub, and any other existing artifacts, are leveraged as much as possible

Tasks: 

- [x] Meet to discuss which sections can be adapted, which need to be created, which aren't a good fit.
- [x] Create separate issues for items that need to be created

**Comment by shubhi-raft** [comment]
@rahearn to update this issue after sprint planning. There is a draft of this doc in the compliance channel.

**Comment by kniz-raft** [comment]
@lfrohlich @shubhi-raft Do either of you know if the system design doc draft mentioned above was moved out of the compliance channel? I can't seem to find it. Thanks!

**Comment by lfrohlich** [comment]
System Design Document was approved as part of the 1/21 CDR
