### ISSUE TITLE
(Internal) Archive TANF-app Prototype Files 

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#263]
Description:

Having the root directory populated with the prototype work is no longer necessary given the progress of the new development. The proposed plan is to save these files into a folder so the work is not lost but to prevent it from clashing with new development. 
Repo is here: https://github.com/HHS/TANF-app-archive

AC: 

- [ ] All TANF-app prototype work is migrated to an archive folder in a new HHS repo
- [ ] Work from the prototype is accessible for reference when needed

Tasks: 

- [x] Work with Lauren on getting a new HHS repo to move the prototype too
- [ ] Move prototype files to new repo
- [ ] Document the move

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @alexsoble  has reviewed and signed off

**Comment by lfrohlich** [comment]
Got access to the new repo: https://github.com/HHS/TANF-app-archive

**Comment by shubhi-raft** [comment]
@carltonsmith can you confirm if you have access to [the new repo](https://github.com/HHS/TANF-app-archive)?

**Comment by shubhi-raft** [comment]
@lfrohlich @alexsoble @carltonsmith  I know this is necessary and an easier lift, but wondering if this can be pushed post OFA MVP?

**Comment by alexsoble** [comment]
@shubhi-raft Apologies for the delayed response; must have missed this question! 

My perspective is that the current state of the repo is confusing to a developer because it contains documentation and code from the prototype and the Raft apps mixed together. 

That makes it difficult for a developer who's onboarding to know what code and documentation is active and up-to-date, and what belongs to the early prototype. 

Since clear documentation is a QASP requirement, this feels important to have in place before MVP. Just my perspective.

**Comment by alexsoble** [comment]
Also noting that @carltonsmith and I are meeting with Tim for a tour of the prototype code, Tim is showing us that a copy of the prototype repo is stored here: https://github.com/18F/tanf-prototype

**Comment by alexsoble** [comment]
Key file for data parsing in the prototype repo is `tanfDataProcessing.py`. cc @carltonsmith

**Comment by alexsoble** [comment]
Also `upload/models.py`

**Comment by alexsoble** [comment]
Quick update on the prototype-archiving work:
 
— There is an archived version of the prototype code as of Feb 25, 2020 here: https://github.com/18F/tanf-prototype
— Tim made a few more commits to the prototype after that, the latest commit was on Mar 26, 2020
— I'll archive all Tim's prototype commits up til Mar 26, 2020 here: https://github.com/HHS/TANF-app-archive
— Then I'll finish up & submit this PR removing prototype-related files from the repo: https://github.com/HHS/TANF-app/pull/119
 
Note that even files removed from a repo still remain in the git history. So the prototype code will be stored lots of places and there's essentially zero risk it will be lost forever.
