### ISSUE TITLE
Add authentication bypass for local backend development 

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#264]
Description:

Using Login.gov in our authentication process makes it difficult for backend development due to this authentication process being designed for frontend interfaces. This will provide an easier environment for development without hindering velocity. 

AC: 

- [ ] Leveraging Djangos settings to create bypass flag for local development 
- [ ] Developers can make API calls unhindered **ONLY** while in a local development environment

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
@carltonsmith is this done?

**Comment by amilash** [comment]
@abottoms-coder @jtwillis92 Is this done or needed, can I close it?

**Comment by jtwillis92** [comment]
https://github.com/raft-tech/TANF-app/pull/1080 will close this one as well.

**Comment by amilash** [comment]
Thanks John. Closing this one as a dupe.
