### ISSUE TITLE
As a user , I need well maintained API documentation 

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#265]
Description:

We need an automated API documentation solution to keep track of changes to the backend so users are aware of how the UI is interacting with the backend. Manually updating documents like this as the code base grows will become difficult to maintain. 

AC: 

- [ ] API documentation generated is supported by OpenAPI
- [ ] Documentation is well defined and describes each API  call operation in detail.

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by jtwillis92** [comment]
This ticket was technically here first, but achieves the same goal as #564 which is currently in review so I will close this one as the duplicate.
