### ISSUE TITLE
[SPIKE] Investigate OWASP nightly scan findings 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2663]
### Description 

With the merge of #2644, zap scanner version has been updated, and there are also new scan findings that need to be reviewed and potentially resolved, and/or flagged as false positive

> ![26644p2](https://user-images.githubusercontent.com/63075587/260545247-e6f2493e-0cdb-47e8-aefb-a452c41fd0dd.PNG) ![26644p1](https://user-images.githubusercontent.com/63075587/260545254-a200a073-8439-4e70-9b82-d4cad8ce62ea.PNG)

I believe the medium vuln around the 403 bypass is bogus because we saw this before and/or with 401. On the CORS misconfig front, we'll have to check it.

_Originally posted by @andrew-jameson in https://github.com/raft-tech/TANF-app/issues/2659#issuecomment-1678954184_

**Comment by ADPennington** [comment]
nightly scan results from 8/15/23

@Smithh-Co @andrew-jameson 

https://output.circle-artifacts.com/output/job/6b4912d1-10d1-436d-9a2a-09c6e4aa97ef/artifacts/0/tdrs-backend/reports/owasp_report.html

**Comment by George-Hudson** [comment]
There's some shenanigans going on here... I'm seeing completely different findings on this morning's report and don't think the site changed that much overnight... The CORS issues are not showing up and not a bunch of SQL injection issues are showing...

This is going to make finding and fixing the issues difficult if we cannot get consistent reports... Am I using the tool wrong?

@ADPennington I'm not able to find the nightly pipeline that created the first report. Looks like 2 days ago, the pipeline was still broken. Which pipeline generated the August 14th report?

**Comment by ADPennington** [comment]
> There's some shenanigans going on here... I'm seeing completely different findings on this morning's report and don't think the site changed that much overnight... The CORS issues are not showing up and not a bunch of SQL injection issues are showing...
> 
> This is going to make finding and fixing the issues difficult if we cannot get consistent reports... Am I using the tool wrong?
> 
> @ADPennington I'm not able to find the nightly pipeline that created the first report. Looks like 2 days ago, the pipeline was still broken. Which pipeline generated the August 14th report?

@George-Hudson i was looking here: https://app.circleci.com/pipelines/github/raft-tech/TANF-app?branch=develop

**Comment by George-Hudson** [comment]
@ADPennington hmmm. I am too. The run from [last night](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/15311/workflows/17e45686-f6e1-463a-b9ff-4072bc1da74e/jobs/45817) (17 hours ago) produces the [report](https://output.circle-artifacts.com/output/job/6b4912d1-10d1-436d-9a2a-09c6e4aa97ef/artifacts/0/tdrs-backend/reports/owasp_report.html) I see with lots of SQL injection susceptibility, but the [run before that](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/15272/workflows/1dab2734-575a-41b1-b279-7b515b25464e/jobs/45699/steps) (2days ago) I am not seeing a real [report](https://output.circle-artifacts.com/output/job/2b9da691-76a1-4c24-967e-3a593d13171e/artifacts/0/tdrs-backend/reports/owasp_report.html) generated because the pipeline broke (from not having the fix merged yet)

**Comment by ADPennington** [comment]
> @ADPennington hmmm. I am too. The run from [last night](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/15311/workflows/17e45686-f6e1-463a-b9ff-4072bc1da74e/jobs/45817) (17 hours ago) produces the [report](https://output.circle-artifacts.com/output/job/6b4912d1-10d1-436d-9a2a-09c6e4aa97ef/artifacts/0/tdrs-backend/reports/owasp_report.html) I see with lots of SQL injection susceptibility, but the [run before that](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/15272/workflows/1dab2734-575a-41b1-b279-7b515b25464e/jobs/45699/steps) (2days ago) I am not seeing a real [report](https://output.circle-artifacts.com/output/job/2b9da691-76a1-4c24-967e-3a593d13171e/artifacts/0/tdrs-backend/reports/owasp_report.html) generated because the pipeline broke (from not having the fix merged yet)

@George-Hudson i wonder if the difference is the merge of your PR?

![nightly-issue](https://github.com/raft-tech/TANF-app/assets/63075587/87f62bb2-0e85-40d7-bfcc-a04a50c6aef1)

**Comment by George-Hudson** [comment]
@ADPennington That might make sense to change a few things around... we updated to v2.13.0 from 2.11.0, but I wouldn't think it would be that drastic of changes... but I am still not able to find the pipeline that generated the report you screenshot originally from August 14th. 

Thank you for responding right away

**Comment by ADPennington** [comment]
> @ADPennington That might make sense to change a few things around... we updated to v2.13.0 from 2.11.0, but I wouldn't think it would be that drastic of changes... but I am still not able to find the pipeline that generated the report you screenshot originally from August 14th. 
> 
> Thank you for responding right away

 @George-Hudson Oh my apologies I think I misunderstood. I grabbed it from the circleci link in your PR. 

https://app.circleci.com/pipelines/github/raft-tech/TANF-app/15244/workflows/77e65bb0-ade1-4af7-af49-6b3140e9eda7/jobs/45620/artifacts

**Comment by George-Hudson** [comment]
oh! huh... that IS strange... it shouldn't have changed a thing between runs... because that run was pointed at develop env still and had my changes included... 

I think we should still treat it as an anomaly and look for tomorrow's report to be in line with today's...

Thank you again!

**Comment by ADPennington** [comment]
@Smithh-Co @George-Hudson can you remind me where we are on this? 

the nightly scan workflow failed on HHS:main for sprint 79 release. Cc: @ttran-hub

**Comment by George-Hudson** [comment]
> @Smithh-Co @George-Hudson can you remind me where we are on this?
@ADPennington 
I'm working with Mo (back tomorrow) to reconfigure the tests so that we only get fails and warnings for things that pertain to our site. We may have to ignore some of the tests that come back with false positives.

**Comment by George-Hudson** [comment]
<img width="862" alt="Screenshot 2023-08-24 at 12 01 13 PM" src="https://github.com/raft-tech/TANF-app/assets/4259003/66f84a02-44a2-4714-acb6-8f60708662b4">

SQL injection actually gets a 403 when tested with postman, which is the desired behavior. The link in the report also reflects this, so not sure why it shows as a failure. Will set this test to IGNORE `40018 IGNORE (SQL Injection - Active/release)` as a secondary note, we use PostgreSQL, not Active, and will be leaving tests specific to our database type: `40022 FAIL (SQL Injection - PostgreSQL - Active/beta)` 

<img width="855" alt="Screenshot 2023-08-24 at 12 02 51 PM" src="https://github.com/raft-tech/TANF-app/assets/4259003/31bb25f1-5fe7-40cd-bb7e-64e5b5b0bc43">
Similar to the above, the hidden file failure we are getting seems to be a false positive. The report says it's getting a 301, but the link in the report goes to a 403 and repeating the test using Postman also shows 403. Will be ignoring for now.

`40035 IGNORE (Hidden File Finder - Active/beta)`

@ADPennington does the above make sense, and do you agree with our logic for why we are ignoring these specific tests from the OWASP Zap scan?

@raftmsohani thanks tons for your help good sir.

**Comment by George-Hudson** [comment]
https://github.com/raft-tech/TANF-app/pull/2679

**Comment by George-Hudson** [comment]
@andrew-jameson I think we are ready to close this ticket. WIth #2683 up next to schedule and look at to start making sure our ZAP configuration is geared to our use case.
