### ISSUE TITLE
Chunk multi-record lines prior to parsing

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2705]
**Description:**
Stub ticket out of 9/18 office hours re:section 4. Given the loop within the t7 SchemaManager generation, this highlights a fundamental assumption made that one line/row corresponds to one database object which isn't true for this and a couple other line types. Looking up at how the line is given to `RowSchema::parse_and_validate()`, it does seem like we should be able to chunk up the line and feed these chunks down to `parse_line` or `Field::parse_value()` to more efficiently handle this use-case to check for multiple DB objs per line as opposed to solving this downstream in the SchemaManager as we might continue to have other implementations for different record types.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- We might not

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by jtimpe** [comment]
Closing per discussion in refinement 11/28 - need to pass the entire line to parse each schema as there is shared information at the beginning of the row that every schema tries to parse
