### ISSUE TITLE
Styling changes requested by Christine in Sprint 3 Review

### ISSUE THREAD

**Issue by hilvitzs** [raft-tech/TANF-app#271]
Description:
- Fix grid layout for resource cards
- Add correct colors
- Add correct fonts
- Change email to link

AC: 

- [x] Fix grid layout for resource cards
- [x] Add correct colors
- [x] Add correct fonts
- [x] Change email in resources section to actual link to email  

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
This is complete with [Sprint 3 PR](https://github.com/HHS/TANF-app/pull/55).
