### ISSUE TITLE
[draft] TANF Section 3 validation enhancements

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2713]
**Description:**
_Provide a brief background and justification for this issue_

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
i did a quick test of TANF Section 3 parsing on develop branch using a file from an STT that uses FTANF.exe (a tool that space-fills). for example: total number of applications is 8 digits (e.g. `00001597` appears as `    1597` in the file, and so on....). TDP correctly parses the file (see below). 

to be sure, i also tested a section 3 file with zero-filling and it also correctly parsed. 

I believe we can, therefore close this ticket since we are getting the desired behavior. do you agree @jtimpe @elipe17 @Smithh-Co @reitermb ?


![2713p1](https://github.com/raft-tech/TANF-app/assets/63075587/dc8fe82d-9662-4020-b388-b8a3e0a3df56)

**Comment by elipe17** [comment]
@ADPennington I just want to verify that this space/zero fill is separate from #2695. We are only validating that fields are parsed correctly when partially space/zero filled? Even if they were completely space/zero filled everything will still parse correctly, I just want to make sure you aren't encapsulating the the scope of 2695 under this with respect to section 3.

**Comment by ADPennington** [comment]
for #2695 i think we are trying to capture instances in TANF Section 1 where certain data elements can take on space-filled values. here, we were capturing scenarios where an STT would *partially* space-fill for certain data elements in TANF Section 3. complete space-filling for any data elements in section 3 should still throw an error. as far as i can tell, this is the current behavior. @elipe17

**Comment by elipe17** [comment]
@ADPennington, perfect that's what I was verifying. That is the current behavior and this can be closed in that case. I will ping Connor.

**Comment by ADPennington** [comment]
this can be closed.
