### ISSUE TITLE
Sprint 3 Backend Remediations

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#272]
Description:
This issue is to track requested changes and updates to the backend based on the PR review comments found here :

https://github.com/HHS/TANF-app/pull/55

AC: 

- [ ] Additional test cases for the set_profile endpoint 

  Examples:
```
{"first_name": "John", }
{"first_name": "John", "last_name": "Thomas",  "middle_name":"Forster"}
```

- [ ]  Leveraging UserSerializer and nest the returned JSON in the `auth_check` endpoint logic

- [ ] DRYer ( do not repeat yourself)  Code in login.py

- [ ] Updates to README.md local development  in response to file permission issues.

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 - [ ] @lauraGgit has reviewed and signed off
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
@carltonsmith is this complete?

**Comment by shubhi-raft** [comment]
Per @carltonsmith, this was completed in Sprint 3.
