### ISSUE TITLE
Spike - fix production owasp scan reporting

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2768]
**Description:**
Per [2766](https://github.com/raft-tech/TANF-app/issues/2766#issuecomment-1841558675), the failure of the owasp scan job in the pipeline means the scan report is not being uploaded to the django admin console. The report should be uploaded any time the scan completes, regardless of findings that cause the scan to fail.

**Deliverable(s):** 

- [ ] Investigate allowing the zap scan report to be uploaded to the django admin console, whether the scan contains errors or not
    - 4 hour timebox

**Comment by andrew-jameson** [comment]
Irritated that my solution works for the steps intended and getting an unrelated failure for authentication that works when I run said steps manually:

What am I missing?
```BASH
circleci@ip-10-0-24-92:~/tdp-apps/scripts$ cf login -a https://api.fr.cloud.gov -u $CF_USERNAME_STAGING -p $CF_PASSWORD_STAGING -o $CF_ORG -s tanf-staging
API endpoint: https://api.fr.cloud.gov
EOF
FAILED
circleci@ip-10-0-24-92:~/tdp-apps/scripts$ cf login -u $CF_USERNAME_STAGING -p $CF_PASSWORD_STAGING -o $CF_ORG -s tanf-staging
API endpoint: https://api.fr.cloud.gov


Authenticating...
OK

Targeted org hhs-acf-ofa.

Targeted space tanf-staging.

API endpoint:   https://api.fr.cloud.gov
API version:    3.156.0
user:           1c974c98-b239-441a-a1e9-3c23bad24d3f
org:            hhs-acf-ofa
space:          tanf-staging
```

**Comment by andrew-jameson** [comment]
@ADPennington Had a [failure](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/20265/workflows/94186c8b-30ac-473b-90c7-4c1292b6de3e/jobs/60325) in staging that needs investigation. Should have been caught but wasn't.

**Comment by ADPennington** [comment]
> @ADPennington Had a [failure](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/20265/workflows/94186c8b-30ac-473b-90c7-4c1292b6de3e/jobs/60325) in staging that needs investigation. Should have been caught but wasn't.

first successful workflow from my branch: [here](https://app.circleci.com/pipelines/github/ADPennington/TANF-app/357/workflows/32d6f8ef-9313-46f7-a714-8fd11738ffef/jobs/1008). not yet saving in DAC.
