### ISSUE TITLE
As a developer I want parser tests to run without error

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2780]
## Description

While running the tests from the root app succeeds, running some of the specific apps such as ```parsers/test``` fail, throwing duplicate key value error. This looks like a dependency issue. 

## Action Taken

The error can be reproduced by running the following command from ```commands.sh``` scripts:
```
tdrs-run-pytest -s -vv tdpservice/parsers/test/
```

This looks like a fixture dependency issue created from some the parsing test file fixtures being recreated in different test files. when a fixture is used in multiple apps/tests, it's better to move these fixtures to a higher level conf file. However, when I tried to resolve the issue by this approach, I received import errors.

## What I expected to see

Expectation is: one can run tests in each app separately and pass all tests, e.g:

```
- tdrs-run-pytest -s -vv tdpservice/parsers/test/
- tdrs-run-pytest -s -vv tdpservice/users/test/
...
```
## Notes

- Possibly wrap `parsers/tests/factories.py` classes in a singleton to prevent them creating multiple conflicting records per test run

**Comment by robgendron** [comment]
#2641 fixed this, closing ticket.
