### ISSUE TITLE
Retro 9/15 Commitments

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#279]
**Description:**
Document Retro action items from [9/15 Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1597246506278/c0b65d05365f6c6318e55804745ac99804a879ca) and create issues to address feedback.

**AC:**
- [x] retro items action items have been documented 

Tasks:
- [x] Schedule and hold a follow-up retro meeting to finish out the retro items
- [x] Schedule meeting to discuss the "iron triangle" process/QASP, velocity, flexibility
- [x] Discuss making sprint retro sessions longer or having planned follow-ups
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
Meeting notes from iron triangle meeting are documented [here](https://teams.microsoft.com/l/file/3E273758-697F-4098-8343-DF8E085E9401?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FIron%20Triangle%20Convo.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock:. Team charter will be updated after selena and shubhi pairing session.

**Comment by lfrohlich** [comment]
Looks good -- one note that instead of having longer retros we are going to try voting for what to discuss during retro.
