### ISSUE TITLE
Create User Research Plan for first round of user research

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#28]
Description:
Create a user research plan to conduct next round of research (August 2020) with STT and OFA. 

AC: 

- [ ] Draft research plan contains research goals, method(s), recruitment criteria, ethics, privacy concerns, expected outcome, interview guide, and timeline. 

Tasks: 

- [ ] Create a draft research plan that addresses epics - Users can easily upload data and User can view uploads

DoD: 
 - [ ] Documentation: Draft research plan has been shared with the PO and team for feedback

**Comment by shubhi-raft** [comment]
@lfrohlich based on our discussion from yesterday, created this new issues on research plan but have not moved it the to do column yet. Could you please review the AC and DoD and if it looks good, please move it to 'To Do' column. We are working on this right now and will have more to share on Monday.

**Comment by shubhi-raft** [comment]
fyi @cmajel

**Comment by cmajel** [comment]
@shubhi-raft does this research plan include the OFA shadowing plus STT concept testing, or do we think that these will be tracked separately?

**Comment by shubhi-raft** [comment]
@cmajel in the spirit of breaking down issues into small stories, i think we should track them separately.

**Comment by lfrohlich** [comment]
Separate research plans for OFA and STT.

**Comment by shubhi-raft** [comment]
Broke this out into #62  and #63 and closing this issue to avoid duplication.
