### ISSUE TITLE
Complete cat4 validation implementation

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2842]
**Description:**
#2536 laid the foundation for cat4 validation design and implemented the "header/records" validator, implement the remaining validators

Set 1 - t1/t2/t3 records are related, t1 has a matching family affiliation, t4/t5 records are related
- Every T1 record should have at least one corresponding T2 or T3 record with the same RPT_MONTH_YEAR and CASE_NUMBER.
- Every T2 record should have at least one corresponding T1 record with the same RPT_MONTH_YEAR and CASE_NUMBER.
- Every T3 record should have at least one corresponding T1 record with the same RPT_MONTH_YEAR and CASE_NUMBER.
- Every T1 record should have at least one corresponding T2 or T3 record with the same RPT_MONTH_YEAR and CASE_NUMBER, where FAMILY_AFFILIATION==1
- (section 2) header YEAR + header QUARTER must be consistent with RPT_MONTH_YEAR
- Every T4 record should have at least one corresponding T5 record with the same RPT_MONTH_YEAR and CASE_NUMBER.
- Every T5 record should have at least one corresponding T4 record with the same RPT_MONTH_YEAR and CASE_NUMBER.

Set 2 - 
- adults in territories must have a valid value for 19C
   - stt codes for territories in the codebase, calculate age based on DOB and rpt_month_year
   - `REC_AID_TOTALLY_DISABLED` must be 1 or 2 (not 0)
- people in states shouldn’t have value of 1 
   - alex will follow up, may not implement. no age calculations
- people in states must have valid value
    - for states if FAMILY_AFFILIATION == 1, must have `REC_SSI==2`
    - for territories, `REC_SSI==2` (don't check family affiliation)
- if case closure reason = 01:employment, then at least one person on the case must have employment status = 1:Yes in the same month
- if closure reason = FTL, then at least one person who is HoH or spouse of HoH on case must have FTL months >=60 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Implement the remaining validators (set 1)
- [ ] implement the remaining validators (set 2)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Supporting Documentation:**
- [Cat4 workbook](https://gorafttech.sharepoint.com/:x:/s/TDRSResearchDesign/Ebcv7lByTM1Dk3VX4OZaTf0BvBSqAJnv6n9IFvkKVSqd-g?e=3SAnHZ)

**Comment by ADPennington** [comment]
@jtimpe -- i spoke to @ysong001 about 19C, section 2. takeaways are as follows:

- if a territory and an adult, 19C must be 1 or 2
- if a state, 19C must be 2.

**Comment by ADPennington** [comment]
@jtimpe coding instructions for TANF Section 2, 19C and 19E are captured below:
![19CandE_Sect2](https://github.com/raft-tech/TANF-app/assets/63075587/30f5deac-cca6-4b4f-9840-775b2a8ddb38)

**Comment by reitermb** [comment]
~2 pts remaining
