### ISSUE TITLE
User upload file e2e test fails

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2844]
## Description

The e2e test is failing at the  _"A user can upload a file"_ step. 

Note: Although the test fails, the user can still upload files in the app.

## Action Taken

The test is failing both locally and in circleci.

## What I expected to see

Successful pass for all e2e tests

## What I did see

Screenshot

![Screenshot 2024-02-15 at 8 53 24 AM](https://github.com/raft-tech/TANF-app/assets/97037188/acda4c49-6942-443b-a299-dfb3a2727260)

## Other Helpful Information

+ [file upload test](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-frontend/cypress/e2e/integration/file_upload.js)

**Comment by raftmsohani** [comment]
tested from local running command:
```
npm run test:e2e-ci -- --config baseUrl="https://tdp-frontend-develop.acf.hhs.gov" --env cypressToken=$CYPRESS_TOKEN,apiUrl="https://tdp-frontend-develop.acf.hhs.gov/v1",adminUrl="https://tdp-frontend-develop.acf.hhs.gov/admin"
```

and from circleci: https://app.circleci.com/pipelines/gh/raft-tech/TANF-app/19246/workflows/7e09b22e-f19e-40c8-96a4-4f67d4269e4d/jobs/59711

Can close this ticket now

**Comment by jtimpe** [comment]
this fails for the same reason we occasionally lose connection to kibana, as described in #2839 

when services are redeployed, the nginx proxy loses connection to the clamav service. it either needs to be restarted or the connection maintained between deploys
