### ISSUE TITLE
As tech lead, I need buildpack updated for `tdp-projects-updates`

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2858]
**Description**

from cloud.gov on 2/22/2024:

>We recently updated the buildpack in use by your application. You should restage or redeploy your application to take advantage of the update.

>A rolling restage operation is the quickest way to upgrade without incurring downtime. You may still want to leverage your deployment infrastructure to perform the upgrade if you have compliance requirements for redeployment operations.

>You can restage your application by opening the command line and entering the following commands:

>  `cf target -o hhs-acf-ofa -s tanf-dev ; cf restage --strategy rolling tdp-project-updates`

>For more information about the buildpack update(s), please see the following release notes:

>  go_buildpack v1.10.16: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fgo-buildpack%2Freleases%2Ftag%2Fv1.10.16&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744655332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=5IQxGqsXhP45YYG%2FkBNygC7i59mP%2B4ehCrZF2Zt9wdk%3D&reserved=0

>  nodejs_buildpack v1.8.22: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fnodejs-buildpack%2Freleases%2Ftag%2Fv1.8.22&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744662316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xRsYRPxM57hfYbe%2F5Qz9RTZNs8UvggoxFKr1CeR4oLU%3D&reserved=0

>  staticfile_buildpack v1.6.10: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fstaticfile-buildpack%2Freleases%2Ftag%2Fv1.6.10&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744667450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=5W6%2BLLZfzoJNP%2FuQC03jDe5PlAn4r9ZVNrJqASAUK5o%3D&reserved=0

>  java_buildpack v4.66.0: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fjava-buildpack%2Freleases%2Ftag%2Fv4.66.0&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744671736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=cQG8VaYC1hqH9ljeIvI8nxN5OnXoU4z6lWaCma1OjYI%3D&reserved=0

>  ruby_buildpack v1.10.9: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fruby-buildpack%2Freleases%2Ftag%2Fv1.10.9&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744675678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=zd5o9qt8F8f0IBx5CbWh9Yi%2ByNwLgn3kDYMxTZXsBoM%3D&reserved=0

>  dotnet_core_buildpack v2.4.23: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fdotnet-core-buildpack%2Freleases%2Ftag%2Fv2.4.23&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744682424%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=XluwQ3yDuXpTmNRa08bGB%2FF1Pw4H4a09MSkzhy2fMHE%3D&reserved=0

>  nginx_buildpack v1.2.11: https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fnginx-buildpack%2Freleases%2Ftag%2Fv1.2.11&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744687219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ap0pU6Adg197BiQozc%2F2NeqNToeSeSGWISKKH4nFhqQ%3D&reserved=0

> For more information on keeping your application updated and secure, see: 
https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.gov%2Fdocs%2Fgetting-started%2Fapp-maintenance%2F&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7C2301d7606b5b4353e6d808dc33a47b34%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638442028744691227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qQBhM%2BPI%2BpmlNouIqioAjpS4Wgx2hE5JtRkK1RPEa9s%3D&reserved=0

>If you have questions, you can email us at [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov).

**Acceptance Criteria**

- [ ] ~~[project updates manifest](https://github.com/raft-tech/TANF-app/blob/382c856707ad91e6c58c358d19640a61dcf05778/product-updates/manifest.yml#L6) is using latest buildpack.~~
- [ ] ~~TDP Knowledge Center deploys successfully~~
- [ ] TDP Knowledge Center on new buildpack is reviewed for bugs/issues and any that are found are tracked in new issue
- [ ]  Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Comment by ADPennington** [comment]
@reitermb @andrew-jameson 🆙

**Comment by jtimpe** [comment]
tdp-project-updates manifest does not pin versions, so restaging the app should be sufficient to pull in the new buildpacks. application still needs review/testing

**Comment by jtimpe** [comment]
@reitermb has conducted a quick test and the project updates site appears functional

notes - there is one broken link, captured by #2847 and #2846
