### ISSUE TITLE
As tech lead I need file transfer bug resolved

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2871]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

An STT submittted files yesterday and those files were not transferred to ACFTitan. 

## What I expected to see

I expected to see a `Completed` result when in `/admin/data_files/legacyfiletransfer`

## What I did see

`Error` result:
![file_transfer_bug](https://github.com/raft-tech/TANF-app/assets/63075587/df5480d6-39e6-4b16-b927-0720ba4fa5bf)

also cloud.gov logs said the following:

![file_transfer_bug2](https://github.com/raft-tech/TANF-app/assets/63075587/b9bdc96c-f3d5-4a31-a29e-c2bb0d8861e7)

I re-submitted the files (reflected in the screenshot) and it transferred fine. Other STTs have since submitted files to with no issue. 

## Other Helpful Information

+ URL of the page I was on: `/admin/data_files/legacyfiletransfer`
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: no
+ Has the issue occurred more than once?: no
+ [stackoverflow discussion of issue](https://stackoverflow.com/questions/25609153/paramiko-error-reading-ssh-protocol-banner)
+ [Paramiko documentation](https://docs.paramiko.org/en/latest/api/client.html)

**Comment by raftmsohani** [comment]
Discussed the issue with Alex, looks like Paramiko had timed out on waiting for SSH banner. It can happen when server is busy responding to other request and is delayed in responding to the request.
The default is normally set to 15sec and the solution is to increase the timeout to 30sec.
