### ISSUE TITLE
Invite new 18Fers to stuff

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#288]
ryan.ahearn@gsa.gov
alex.soble@gsa.gov

Let's get them in the next round of sprint ceremonies 9/29-30

- [x] MS Teams
- [ ] 18F TANF repo
- [x] HHS repo
- [ ] Raft repo

**Comment by SelenaJV** [comment]
@lfrohlich Just added this issue so you can get to it when you have time this week.

**Comment by kniz-raft** [comment]
Closing since these tasks appear to be done
