### ISSUE TITLE
TEST for notifications

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#29]
Description:
This is a test

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by SelenaJV** [comment]
@lfrohlich How about peanut butter?
