### ISSUE TITLE
UX—TDP 3.4 Readiness

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2905]
Tracker for all UX work prioritized for completion by the decommissioning date of the legacy TDRS system / release of 3.4 functionality

**Comment by robgendron** [comment]
Is the release number in the titling needed @reitermb?

**Comment by reitermb** [comment]
> Is the release number in the titling needed @reitermb?

I'd say yes since these UX epics are intended as easy high level UX lift trackers per release
