### ISSUE TITLE
In-App Error Reports

### ISSUE THREAD

**Issue by robgendron** [raft-tech/TANF-app#2917]
**Notes**:
Old UX Tickets for reference here (please do not delete this note): https://github.com/raft-tech/TANF-app/issues/1200

**Comment by andrew-jameson** [comment]
@lfrohlich @ADPennington Can we close this empty epic until we are more ready to proceed?

cc @vlasse86 @reitermb

**Comment by reitermb** [comment]
> @lfrohlich @ADPennington Can we close this empty epic until we are more ready to proceed?
> 
> cc @vlasse86 @reitermb

No strong feelings one way or another on closing vs leaving here. Just curious though, what's the utility of closing it?

**Comment by lhuxraft** [comment]
Closing as part of epic reorganization
