### ISSUE TITLE
fTANF Replacement

### ISSUE THREAD

**Issue by robgendron** [raft-tech/TANF-app#2921]
Initial ideas here:
https://app.mural.co/t/gsa6/m/gsa6/1584630282345/3231f53b89fe9cfb67b89aab9f3bde4c32676e81

**Comment by andrew-jameson** [comment]
@lfrohlich @ADPennington Can we close this empty epic until we are more ready to proceed?

cc @vlasse86

**Comment by lhuxraft** [comment]
Closing as part of epic reorganization
