### ISSUE TITLE
Placeholder: Validation Ideas Stemming from #115 and #275 Conceptual Mockups

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#295]
Problem Statement: We would like to create mockups to evaluate file format that would lead to parsing error, section validation. 
Questions: TBD
This is a follow-on to #115 & #275

Figma link to iterations: ([Link](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=1412%3A9795))

AC: 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [ ] 
- [ ] Check for accessibility 

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @cmajel has reviewed and signed off
- [ ] @lfrohlich has reviewed and signed off

**Comment by cmajel** [comment]
@dk-ui I see this as a follow on for the conceptual mocks but I'm not sure what the goal is here. Is this more iteration on the metadata validation / reconciliation for after our next round of research? Or something else? 

 Can you say more about the problem this would tackle?

**Comment by amilash** [comment]
Agreed. @dk-ui Can you clarify the intent and description for this work?

**Comment by reitermb** [comment]
Duped at this point
