### ISSUE TITLE
Offboard Laura, Selena, Christine

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#297]
Tasks: 

- [x] Remove from HHS repo
- [ ] Remove from Raft repo
- [x] Remove from Cloud.gov
- [x] Remove from MS Team
- [x] Remove Christine from design and research template (DoD)
- [ ] @alexsoble to review existing dev template to provide feedback if anything needs to be updated.

**Comment by alexsoble** [comment]
Switched over Snyk yesterday.

**Comment by lfrohlich** [comment]
This is done!
