### ISSUE TITLE
[bug] signing into frontend is not possible after cloud.gov maintenance. 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2973]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

As noted in #2839, cloud.gov's maintenance schedule mangles the routes to TDP apps. This includes the route between the frontend and the backend. After maintenance occurs, when users attempt to sign into TDP, they are redirected to the following screen:

![maintlogin](https://github.com/raft-tech/TANF-app/assets/63075587/953d26cf-0eba-4298-883b-323918ed8709)
 Admins have to restart the frontend to resolve this and are not aware when this happens unless continuously monitoring access to the system. 

## Action Taken

- navigating to the frontend website via browser
- clicking either of the sign-in buttons
![loginscreen2](https://github.com/raft-tech/TANF-app/assets/63075587/2051d0f0-e0ab-45ae-a70b-7c76476d6b0f)

## What I expected to see

I expected to see one of the two sign-in screens:
![loginscreen](https://github.com/raft-tech/TANF-app/assets/63075587/2fdefdbd-cba8-4592-8123-50fa8f6177ef)

## What I did see

![maintlogin](https://github.com/raft-tech/TANF-app/assets/63075587/953d26cf-0eba-4298-883b-323918ed8709)

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version: chrome, edge, firefox, etc. 
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

**Comment by jtimpe** [comment]
@ADPennington does this only apply to prod, or the lower environments as well?

**Comment by ADPennington** [comment]
> @ADPennington does this only apply to prod, or the lower environments as well?

All envs.
