### ISSUE TITLE
As a developer I need improved acceptance criteria and functional requirements

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2986]
**Description:**
During working on #2757, a table was developed that represented detailed acceptance criteria for the issue in question (see tables in #2757). Each row in the table shows one acceptance criteria either directly or indirectly. Although the table helped developing the logic, qasp revealed one of the ACs (row 3) was missed.

This ticket is created to improve listed ACs by adding associated test cases to each AC such that dev team can easily test each AC and further improve both reliability and development speed.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Can we agree on some standard language like the cucumber/gherkin format?
-   Scenario: Sunday isn't Friday
    Given today is Sunday
    When I ask whether it's Friday yet
    Then I should be told "Nope"
- do we want this ticket to make a datafile generator based on above and/or incorporating our unit test factories?

**Comment by andrew-jameson** [comment]
Implementing this ticket would vastly improve the test code related to #2970 for example.
