### ISSUE TITLE
As a user, I need to be able to log in

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#3]
AC:
- [ ] Authentication via Login.gov 
- [ ] Authorization via API service 
- [ ] The UI renders unauthenticated login/registration page

 Tasks : 
- [ ] Install and configure sorcery gem
- [ ] Add roles model/migration
- [ ] Define user/role relationship
- [ ] Add validations for user and role models
- [ ] Install JWT gem
- [ ] Determines after authentication if a user is new to the system or if they exist and have assigned roles
- [ ] Register new users into unassigned role
- [ ] Returns a permission object, user object, and auth token via API call
- [ ] Data should be wrapped in a JWT token

DoD:
- [ ]  minimum 90% code coverage test
- [ ] 0 linting errors and warnings
- [ ]  0 accessibility errors
- [ ]  deployed to a dev environment
- [ ]  all significant changes have been documented
- [ ]  free of high and medium security vulnerabilities

Resources: 
https://developers.login.gov/oidc/

**Comment by lfrohlich** [comment]
Rewrote title to frame as user story. 
AC look good to me.

**Comment by adamcaron** [comment]
Resources: 
- [https://medium.com/@franciscopa91/how-to-implement-oidc-authentication-with-react-context-api-and-react-router-205e13f2d49](https://medium.com/@franciscopa91/how-to-implement-oidc-authentication-with-react-context-api-and-react-router-205e13f2d49)
- [https://www.npmjs.com/package/oidc-client](https://www.npmjs.com/package/oidc-client)
- [https://github.com/frankieali/react-login-gov/tree/master/src](https://github.com/frankieali/react-login-gov/tree/master/src)

**Comment by RafterGit** [comment]
broken down in to frontend and backend issues
