### ISSUE TITLE
DAC Datafile Parser Errors Filtering

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3001]
## Description

ParserErrors link from Datafile page in DAC correctly redirects but does not correctly filter the ParserError objects.

## Action Taken

- Submit datafile
- Go to Datafiles page in DAC
- Click the appropriate link under the `ERROR REPORT LINK` column
- See that you are correctly redirected but that the errors arent filtered. Screenshot below:
<img width="1723" alt="Screenshot 2024-05-21 at 2 10 24 PM" src="https://github.com/raft-tech/TANF-app/assets/125676261/63ac9415-0b12-442b-9635-928b90056461">

Note: this issue (filtering) seems to be occurring with most filters on every page of the DAC.

## What I expected to see

Correctly filtered parser error objects

## What I did see

All parser error objects, and the error query string `?e=1`

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version: `https://tdp-frontend-qasp.app.cloud.gov/admin/parsers/parsererror/?e=1`
+ Operating System: Windows | MacOS X
+ Is the issue repeatable?: Yes
+ Has the issue occurred more than once?: Yes

## Note:
+ Possibly back up by release 
+ Puts QASP review at risk
+ Timebox - due date 5/23

**Comment by robgendron** [comment]
1 point remaining.
