### ISSUE TITLE
Spike - Cat2 Validator Improvement

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#3016]
**Description:**
#2963 makes updates to cat2 validators to include information about the record/field (schema, item number, and friendly name) within the error message. This has a little side effect when the same cat2 validator functions are used within cat3 if/then validators - the item numbers are wrong and the error message contains the extra information for each field and becomes overwhelming/hard to read
- example: `if family affiliation :1 validator1 passed then social security number T2 Item -1 (social security number): 000000000 is in ['000000000', '111111111', '222222222', '333333333', '444444444', '555555555', '666666666', '777777777', '888888888', '999999999'].`

Investigate cleaning up the cat3 error messages. Some possible approaches:
- pass a "ignore_error_message=True` to the cat2 validator from the cat3 validator, have the cat2 validator returned a simplified error or no error (to be filled in by the cat3 validator)
- simply ignore the cat2 validator message and have the cat3 validator create a new message

**Support References**
- #2792
- Errors audit guide - https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/lIHaHcbpsiyAKVhaisxx/error-style-guide

**Open Questions:**
_Please include any questions, possible solutions or decisions that should be explored during work_ 

- What format should the cat3 validators take?

**Deliverable(s):** 
_Create a list of recommendations or proofs of concept to be achieved to complete this issue_

- [ ] An approach (either completed or outlined in a new ticket) for updating the cat3 validator messages to be more human-readable

**Comment by jtimpe** [comment]
In order to appropriately format all the error messages regardless of how they're used (cat2 or cat3), i'm going to implement different options for the `format_error_context` function, i.e.

```python
def format_error_context(row_schema, friendly_name, item_num, format='prefix'):
    """Format the error message for consistency across cat2 validators."""
    match format:
        case 'inline':
            return f'Item {item_num} ({friendly_name})'

        case 'prefix' | _:
            return f'{row_schema.record_type} Item {item_num} ({friendly_name}):'
```

this will require a lot of changes (the context needs to be passed along to all of the validators and used in the `format_error_context` call) but should allow us to continue to use the same validator functions, and make all of the cat2 validator functions available to the cat3 `if_then_validator`.

getting the `field` information from the row schema within `if_then_validator` turned out to be simple:

```python
field = row_schema.get_field_by_name(condition_field_name)
```
which allows the `field.friendly_name` and `field.item` to be passed to the cat2 validator functions (along with the new `'inline'` option)

```python
validator1_result = condition_function(value1, row_schema, condition_field.friendly_name, condition_field.item, 'inline')
```

Together, these changes should set up #2792 to be completed relatively easily. So far I have both implemented, but have roughly 2 points remaining to finish out the tests.

**Comment by robgendron** [comment]
3 points remaining.

**Comment by robgendron** [comment]
2 points remaining, PR coming soon.

**Comment by robgendron** [comment]
Pending 1 more Raft review.

**Comment by robgendron** [comment]
Update: Cleaned up merge conflicts, re-requested reviews
