### ISSUE TITLE
Spike - As an STT user I need better guidance on selecting the appropriate fiscal period to submit my quarterly files

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3017]
**Description:**

STT users are having challenges figuring out which quarters of data to submit. the calendar-to-fiscal period mapping on the home page (for approved users) has been somewhat helpful, but we may need to consider a more guided/dynamic approach.

**Open Questions:**
-  When should we schedule the next round of UX research on this? especially for tribes
- How challenging would it be to update the data files page to ask the user to select the calendar period they would like to submit data for, and dynamically make the fiscal period selections based on this? 
   - If we move away from manual selections of fiscal period would we run into problems elsewhere (e.g. the header attribute for fiscal quarter)

**Deliverable(s):** 
- [x] Tickets created for low & heavier lift next steps
- [x] Any solution focused ideations are documented and referenced in relevant tickets
- [x] Follow-up discussion of recommendations has occurred in UX sync

**Supporting Documentation:**
- [Original process](https://app.mural.co/t/raft2792/m/raft2792/1718739423199/ed42a2fa979a5d63876ab96bd9399458f390f725?sender=ufa4902beba666df5bec09412)

**Comment by ADPennington** [comment]
per ux sync on 6/172024 -- handing over to @reitermb for refinement. cc: @robgendron 

also related ticket: #2406

**Comment by robgendron** [comment]
Refinement scheduled for tomorrow, plan is to bring it into next sprint.

**Comment by robgendron** [comment]
Spin off tickets will be developed by end of sprint.

**Comment by reitermb** [comment]
Closing now that #3057 is spun up
