### ISSUE TITLE
[Placeholder] As a STT, I want to the system to create metadata

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#302]
**Description:**
Follow on to #248. This issue will document the information needed to automatically create metadata during manual entry. 
Continued research (both user research and technical research) is needed to determine the feasibility of auto validation for encryption (SSNs). The feasibility of auto validating edit indicators will be (in part) investigated by Phase III research, as well Update and Delete use cases on the Edit Indicator property. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by abottoms-coder** [comment]
@lfrohlich @ADPennington I propose we close this stub ticket -- the description is unclear to me and I'd like to avoid this throwing off any sort of metrics as it hasn't been prioritized in over a year. Any issues with closing?

**Comment by ADPennington** [comment]
Sounds good to me. The description suggests work related to replacing FTANF which has been de-prioritized until release 4+
