### ISSUE TITLE
Bug - investigate codecov failure in build-and-test workflow

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3027]
**Description:**

I received an email alert that the build-and-test workflow failed on the master branch due to codecov ssl certificate. 
![codecovfail](https://github.com/raft-tech/TANF-app/assets/63075587/4ae5c372-1c3b-43e9-b9fa-5dae4cecb3cb)

**Open Questions:**
_Please include any questions, possible solutions or decisions that should be explored during work_ 

- why does this run in prod as part of the nightly scan workflow? is this necessary?
- does `CODECOV_TOKEN` need to be updated? 

**Deliverable(s) / Tasks:** 
_Create a list of recommendations or proofs of concept to be achieved to complete this issue_
- [ ] run workflow from dev's repo 
- [ ] identify root cause
- [ ] plan for fix
- [ ] _Outcome 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- ran the workflow on another PR in qasp to check if this issue is reproducible from dev circleci: [see here](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/25126/workflows/63047ba6-96c8-46b5-b426-30076ea68f59/jobs/74214)
- _Doc 2_

**Comment by robgendron** [comment]
@ADPennington is this preventing the pipeline or releases or is this an alert? This works on the Raft side.

**Comment by ADPennington** [comment]
> @ADPennington is this preventing the pipeline or releases or is this an alert? This works on the Raft side.

@robgendron please review supporting documentation.

**Comment by robgendron** [comment]
@ADPennington are we still seeing this in the pipeline?

**Comment by ADPennington** [comment]
@robgendron @elipe17 just to share an update, i didnt observe this issue again on hhs' circleci when sprint 101 was released today (7/5). i will monitor again when the nightly scan workflow is re-enabled in prod.

**Comment by robgendron** [comment]
Still not an issue on the HHS or Raft side - deemed closed.
