### ISSUE TITLE
As a compliance person, I need to know the accessibility plan (Section 508 PAT)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#303]
Description: 
In advance of the next Technical Review Board (tentatively 10/15), we need to fill out the Section 508 Product Accessibility Template (PAT)*
https://www.hhs.gov/web/section-508/contracting/technology-products/vpath-instructions/index.html 

Acceptance Criteria: 
 - [x] We have something to share with OCIO as part of the Preliminary Design Review

Tasks: 
- [x] Update the HHS Section 508 Template 

Notes:
-  The wiki and GitHub, and any other existing artifacts, are leveraged as much as possible

Deliverable(s):
- Updated Section 508 PAT template can be found [here](https://teams.microsoft.com/l/file/AA3B6BBA-7D63-41D4-A33F-33230CAAECB7?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FHHS%20Section%20508%20Evaluation%20Template.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

**Comment by shubhi-raft** [comment]
@lfrohlich this is ready for QASP review.

**Comment by lfrohlich** [comment]
This was completed with Sprint 5 and shared with TRB on 10/22

**Comment by shubhi-raft** [comment]
Reopening this issue. The a11y plan was created using an older template. We have the new template and will use it to create the new plan.

**Comment by lfrohlich** [comment]
This was accepted by OCIO's 508 officer.
