### ISSUE TITLE
As a compliance person, I need to see a system security plan (SSP)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#304]
Description: For the next TRB (tentatively 10/22) we need a DRAFT System Security Plan (SSP):
- Boundary Diagram
- Security Control Selections
-Business Impact Analysis (BIA)
- Service Level Agreements/Contracts
Acceptance Criteria: 

Tasks:

**Comment by shubhi-raft** [comment]
@alexsoble Should this also be in the compliance docs for Nov epic?

**Comment by kniz-raft** [comment]
@lfrohlich is tomorrow's IPT - Security Checkpoint 1 the next step for this issue?

**Comment by lfrohlich** [comment]
Closing after Security Checkpoint 1 1/15/21
