### ISSUE TITLE
  bug: ES docker image for non-dev spaces stored in personal dockerhub

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3062]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

dev environment has elastic docker image stored in vendor's hub, but higher environments has image stored in personal dev's hub.

## Action Taken

- login to cf dashboard
- check deployment info for tdp-elastic-proxy-<space> for all spaces

## What I expected to see

something that matches dev environment:
![Screenshot 2024-07-05 130812](https://github.com/raft-tech/TANF-app/assets/63075587/35400e8a-8b79-435e-852c-8dcafa2b4211)

## What I did see

in 2 of 3 environment/spaces: 
![Screenshot 2024-07-05 131352](https://github.com/raft-tech/TANF-app/assets/63075587/a56942ed-3fe4-431d-946f-e29ad3af3011)

## Other Helpful Information

+ previous ticket: #2877 
+ URL of the page I was on:
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

**Comment by robgendron** [comment]
Action: See if we can swap/test the docker image with the Raft repo.

**Comment by elipe17** [comment]
Staging changed (deploying soon), 1 point remaining (prod deployment).

**Comment by ADPennington** [comment]
> Staging changed (deploying soon), 1 point remaining (prod deployment).

@raftmsohani i deployed sprint 102 release to staging this afternoon, and it was successful.

**Comment by ADPennington** [comment]
@raftmsohani deployed sprint 102 release to prod and it was successful. any documentation to capture in this ticket before it's closed?

**Comment by raftmsohani** [comment]
This ticket is a task ticket, there is really no documentation needed.
