### ISSUE TITLE
[bug] TDP is raising cat 4 error on TANF/SSP closed case files that is not present

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3073]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

- 65% of the TANF and SSP closed case files that were resubmitted for FY23 for states and territories were rejected
- review of the top 20 errors by section and error type  show that `T5 People in states must have a valid value for REC_SSI.` and `M5 People in states must have a valid value for REC_SSI.` were the most common cat 4 errors (Note: see Closed_4 and SSP_Closed_4 worksheets). 
- Manual review of a sample of these files show that the values reported for REC_SSI are correct. 

## Action Taken

- resubmitted a closed file in an environment that mirrors prod (sprint release 101)
- reviewed error report
- manually inspect a few case records where the abovementioned error message is raised

## What I expected to see

- evidence of an out of range value for REC_SSI for at least some person-level records on the closed case file for a state/terr 

## What I did see

- [TANF closed file](https://gorafttech.sharepoint.com/:t:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/Test_Files/Resubmission_Task_FY2023/MI_TANFClosed_anon.txt?csf=1&web=1&e=rhxeCC) with no evidence of an out of range value for REC_SSI. The screenshot below is a sum of records by REC_SSI value. 

![3073p1](https://github.com/user-attachments/assets/bd2a869a-3a52-43a9-8c05-b5a2c81776bc)

- [SSP closed file](https://gorafttech.sharepoint.com/:t:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/Test_Files/Resubmission_Task_FY2023/IN_SSPClosed_anon.txt?csf=1&web=1&e=y5JqVQ) with no evidence of an out of range value for REC_SSI. The screenshot below is a sum of records by REC_SSI value. 
![3073p2](https://github.com/user-attachments/assets/632303f0-66a0-46d2-8f8a-a5766b611508)

## Other Helpful Information

+ [Resubmission results](https://gorafttech.sharepoint.com/:o:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7Bc9d41a72-bff8-4eba-b245-bb04ba265e12%7D&action=edit&wd=target(Dev%20Notes.one%7C567fc274-f86b-0a48-901d-543bdc5250ac%2FManual%20Resubmission%20Results%7C3ff147be-7c9a-4ef3-90cd-9e37e32407a5%2F)&wdorigin=NavigationUrl)
+ Is the issue repeatable?: ( yes | no | don't know ) yes
+ Has the issue occurred more than once?: yes

**Comment by robgendron** [comment]
Will be ready to discuss next week or during an office hours.
