### ISSUE TITLE
[Design Spike] In-app banner for submission history pages w/ data parsed before May 2024

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3114]
**Description:**
Delivers banner design and some ideative work to support #3014 

**Open Questions:**
- Can we make the banner contingent upon the presence of a pre-May error report? (without significant dev lift)
   - Yes, as per Andrew in sync on Jul 29

**Deliverable(s):** 
- [x] [Banner design Figma file](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8993-259)
- [x] 3014 is re-refined to deliver banner
- [ ] Ideations on heavier lift possibilities to better communicate current vs historical row entries in submission history

**Comment by victoriaatraft** [comment]
Hi @ADPennington attached are two banner designs with content options of the following:

Opt 1: Please note that error reports and submission history content for files submitted prior to
May 2024 may be inaccurate. Please resubmit to get access to updated information.

Opt 2: Error reports and submission history content for files submitted before May 2024 may be inaccurate. Please resubmit to access updated information.

[Banner design Figma file](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8993-259) is also here. The request seemed straight forward in giving a disclosure about the files prior to May 2024, but let me know if I have missed anything.

![New Report - Section 1 and 2 Upload (Submission Error) - 2](https://github.com/user-attachments/assets/47c3771d-e6b6-48dc-be82-7e014630799e)
![New Report - Section 1 and 2 Upload (Submission Error) - 1](https://github.com/user-attachments/assets/726e57a7-0db0-49bc-92a0-ff845c8f8c87)

cc:  @andrew-jameson

**Comment by ADPennington** [comment]
@victoriaatraft how do we feel about "outdated" instead of "inaccurate" to describe older feedback reports?

**Comment by victoriaatraft** [comment]
> @victoriaatraft how do we feel about "outdated" instead of "inaccurate" to describe older feedback reports?

@ADPennington Hmm.. are we trying to say the data is just obsolete or old rather than incorrect? If so, outdated works.

Thoughts if disclosing as to why the information would be outdated be overkill? Example:
`Error reports and submission history content for files submitted prior to May 2024 may be outdated because they were processed on the legacy system (TDRS) that is no longer in use. Please resubmit to access updated information.`

**Comment by ADPennington** [comment]
> > @victoriaatraft how do we feel about "outdated" instead of "inaccurate" to describe older feedback reports?
> 
> 
> 
> @ADPennington Hmm.. are we trying to say the data is just obsolete or old rather than incorrect? If so, outdated works.
> 
> 
> 
> Thoughts if disclosing as to why the information would be outdated be overkill? Example:
> 
> `Error reports and submission history content for files submitted prior to May 2024 may be outdated because they were processed on the legacy system (TDRS) that is no longer in use. Please resubmit to access updated information.`
> 
> 

Good q! I think one of the key things we're trying to communicate is that the error report has changed (because we've refined the terminology, and in some cases underlying logic). prior to the end of May, most STTs weren't even paying attention to the error report because they were still getting the TDRS-generated reports. now that that system has been retired, they are relying on this one.

**Comment by victoriaatraft** [comment]
Moving to raft review and adding this as a walk on for next UX sync to tighten up the language.

**Comment by victoriaatraft** [comment]
Updated the wording to reflect `outdated` @ADPennington @reitermb cc @lfrohlich 

opt1:
`Error reports and submission history content for files submitted prior to May 2024 may be outdated. Please resubmit to access updated information.`

opt 2:
`Please note that error reports and submission history content for files submitted prior to May 2024 may be outdated. Please resubmit to get access to updated information.`

**Comment by victoriaatraft** [comment]
Agreed on Opt 1

![New Report - Section 1 and 2 Upload (Submission Error) - 1](https://github.com/user-attachments/assets/0a0a9f85-39d2-46bf-bd7d-3898e786c522)

**Comment by ADPennington** [comment]
approved @victoriaatraft @reitermb

**Comment by reitermb** [comment]
Closeable once mockup is added to dev ticket
(action item for me)

**Comment by ADPennington** [comment]
#3014 tracks the dev portion of this feature.
