### ISSUE TITLE
[bug] csv exports not including all records selected

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3138]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

When attempting to export the latest TANF T1 records for FY2023Q1 (record count ~ 444K), the export only included 23K records for 3 STTs, but we expected to see 444K records for 50  STTs

## Action Taken

- navigate to search indices table for TANF T1
- select fiscal period FY2023 Q1
- select `apply filters`
- select all records at the top of the table
- further specify intention to select all 400K+ records
- select csv export and `go` 

## What I expected to see

csv export with 400K+ records for 50 STTs
![Screenshot 2024-08-09 105355](https://github.com/user-attachments/assets/1c8b0278-f9e2-497e-a645-822f0f1d7713)

## What I did see

23K records for 3 STTs: 
![Screenshot 2024-08-09 105412](https://github.com/user-attachments/assets/ba8630b8-27b8-406c-8e9a-44c8d03bd318)

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

**Comment by andrew-jameson** [comment]
Might be solved in #3137 , will pause on refinement here until we re-test that solution

**Comment by andrew-jameson** [comment]
Closed per Backlog Refinement 9/24.
