### ISSUE TITLE
Migrate Team Charter to GH docs folder

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#315]
Move the charter to GitHub docs.

**Comment by SelenaJV** [comment]
@lfrohlich I just spun up this new issue because it didn't really fit into the single source of truth ACs.

I created [this branch](https://github.com/HHS/TANF-app/pull/59) off HHS repo, divided the charter into chunks, and moved over. Can you give it a quick review and merge? I think Our Workflow file will need some more revision but I think that you be a separate issue/branch that you or @shubhi-raft owns.

**Comment by lfrohlich** [comment]
this was completed in PR #59
