### ISSUE TITLE
Spike - Prioritized Errors

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3155]
**Description:**
Intended to develop a technical strategy for #3026 and ensuring a smoother UX for error report access. Also relates to #3075 for sys admin experience.

**Open Questions:**

- Is this intended to prevent creation of lower-tier cat2/4 errors on the order of hundreds of thousands to improve backend performance? No, we will not prevent creation.
- Do we want to halt parsing or continue through? No, we will not halt parsing. 

**Deliverable(s):** 

- [ ] Development Design Document [need link]
- [ ] Solution must ensure that error reports can be accessed by STT users regardless of parser error count

**Supporting Documentation:**
- [Proposed List of Validators](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc={c9d41a72-bff8-4eba-b245-bb04ba265e12}&action=edit&wd=target%28Dev%20Notes.one%7C61602a1e-e3d8-4f2e-8744-c4fc299cb56b%2FProposed%20TDP%20Validation%20Strategy%20%28in-progress%5C%29%7Cd222863c-1c4a-4e0e-b87a-d5625455e357%2F%29&wdorigin=NavigationUrl) -- has links to HHS resources, there are local copies below:

- [Manual Resubmission Results](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc={c9d41a72-bff8-4eba-b245-bb04ba265e12}&action=edit&wd=target%28Dev%20Notes.one%7C61602a1e-e3d8-4f2e-8744-c4fc299cb56b%2FManual%20Resubmission%20Results%7C3ff147be-7c9a-4ef3-90cd-9e37e32407a5%2F%29&wdorigin=NavigationUrl)
- [Top 20 errors summary](https://github.com/user-attachments/files/16752446/FY2023_top20_errors_summary.1.xlsx)

**Comment by lhuxraft** [comment]
11/13/2024: Eric made code changes, reviewing with Alex before dev team re-review

**Comment by lhuxraft** [comment]
11/15: Feature changes discussed with Alex/Kathryn, needs one more review @andrew-jameson

**Comment by lhuxraft** [comment]
11/18: Miles and Victoria to take a look

**Comment by lhuxraft** [comment]
11/20: Miles/Victoria reviewed, Andrew to provide final review today

**Comment by lhuxraft** [comment]
11/25: Met with Kathryn on Friday, made a minor suggestion on capping the critical errors / assigning file status. Comment documented in the PR. Review will continue this week

**Comment by lhuxraft** [comment]
12/2: Testing since Wed morning, continuing to finish testing. Getting a sense of different types of errors
