### ISSUE TITLE
[Spike] As a STT user, I would like to clearly understand where to go to reset my password

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#318]
Description:
'Reset password' on 'My profile' screen (see supporting documentation) can be confusing to a user since the password will be reset through login.gov and not through the TDP system. The issue will deliver whether to keep 'Reset Password' CTA, or update the button to something that clearly tells users that managing password will be done via Login.gov or removing the 'Reset Password' CTA

AC:
- [ ] 'Reset Password' CTA is updated or an alternative is finalized. 

Tasks
- [x] Research on production systems that use login.gov
- [x] Update #239, if necessary  

Notes: 
 - Time box to 4 hours (with OFA MVP in mind)
 - Resource: Login.gov slack channel 

Deliverables:
- Breakdown of other systems that use Login.gov: ([Link] (https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/Shared%20Documents/Design/%23318%20Reset%20Password%20using%20Login.gov.docx?d=wa4aaafc964c34f5e81e05916977686c1&csf=1&web=1&e=sjEa3H))

Supporting Documentation:
- Current mockup:
![Screen Shot 2020-10-09 at 11.09.36 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/5bb9113a-cc12-4629-b40f-db54602955bb)

- Examples of sites that use login.gov to edit/reset passwords:
https://openforest.fs.usda.gov/ (via sign in with login.gov to apply)
https://www.usajobs.gov/ (via sign in)
https://ttp.cbp.dhs.gov/ (via log in)

USAJOBS
![Screen Shot 2020-10-09 at 9.36.34 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/231da496-4b56-420b-9226-088be237de76)
![Screen Shot 2020-10-09 at 9.36.05 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/8e4366c2-8c96-44ee-96e8-39e687c582cf)

**Comment by dk-ui** [comment]
Plan of attack for this ticket:

@dk-ui  Document how the following sites do reset password:

https://openforest.fs.usda.gov/ (via sign in with login.gov to apply)
https://www.usajobs.gov/ (via sign in)
https://ttp.cbp.dhs.gov/ (via log in)

After that is done then @reitermb will use the gov slack channel to relay our findings and question if this is the proper way we should proceed.

Once we get feedback from the slack channel we will then present findings to 18F and Lauren to form a consensus, closing this ticket.

**Comment by lfrohlich** [comment]
@dk-ui  sounds like a good plan!

**Comment by lfrohlich** [comment]
Have the mockups been updated and incorporated into dependent issues? I think so?  #223 If so I can close out.
@shubhi-raft

**Comment by shubhi-raft** [comment]
@lfrohlich this is complete.
