### ISSUE TITLE
Reducing Number of Errors in STT Report

### ISSUE THREAD

**Issue by vlasse86** [raft-tech/TANF-app#3208]
- Dropping certain validation checks
- Adding new validation checks
- Relaxing some validation checks
- Suppressing some validation checks (?)

References:
- https://gorafttech.sharepoint.com/:o:/s/TDRSResearchDesign/EnIa1Mn4v7pOskW7BLomXhIBxUMlYLRU_f1C0dxemW7dWw?e=7Kt6PT

**Comment by lhuxraft** [comment]
Closing as part of epic reorganization
