### ISSUE TITLE
sprint-109-summary

### ISSUE THREAD

**Issue by vlasse86** [raft-tech/TANF-app#3221]
# sprint-109-summary

9/24/2024 - 10/08/2024

Dev:
Re-parsing, Admin Console Improvements, and Application Health Monitoring work
#3106 — Re-Parse Django Action 
#3108 Additional datafile filters 
#2990 — Notification for stuck files
#3060 — As a TDP user, I need to stay logged in when I'm actively using the system
#3182 - 3060 active session
#3180 - Re-add Error Type column to Error Reports
#3157 – Reparse Model Field Additions
#3199 - Performance Monitoring ADR (to be discussed during 9/25 Office Hours)

DevOps:
Successful deployments across environments and pipeline stability investments
#3046/#3192 —PLG  deployed in cloud.gov
#3141/#3194 test-deployment-e2e is failing integration test 
Design:
Support reviews, continue research planning, continur Error Audit (Cat 4)
#2968  —  [Design Deliverable] Update Error Audit for Cat 4 / QA
#3193  – [Research Facilitation] Yun & DIGIT Data Cleansing & Reporting Research
#3100   —  [Design Deliverable] Update stakeholders & personas document 
Release Notes Knowledge Center Updates and Email

### Completed/Merged

* #2458 Integrate Nexus into CircleCI
* #2883 Pre-Made Reporting Dashboards on Kibana
* #2965 As tech lead, I want a database seed implemented for testing
* #2990 Sys-admin notifications for files stuck in processing
* #3099 [bug] redirect parameter bug present when ACF users attempt to logout of TDP
* #3170 Reparse Command Fails when Queryset is Larg
* #3179 Spike - How We Work / Hopes & Fears Workshop prep
* #3180 Re-add Error Type column to Error Reports

### Submitted (QASP Review, OCIO Review)

* #3181 [Design Deliverable] Update Knowledge Center with Error Type guidance and Release Notes Email
* #3108 Additional datafile filters

### Ready to Merge

*

### Closed (Not Merged)

*

### Moved to Next Sprint&#x20;

**In Progress**&#x20;

* #3075 [Spike] Investigate latency when clicking into the parsing errors column on DAC data files page
* #3157 Reparse Model Field Additions
* #3171 CircleCI pipeline utilizes internal Nexus infrastructure
* #3193 [Research Planning] Data Reporting Research

#### Blocked

* #3141 test-deployment-e2e is failing integration test

**Raft Review**

* #3100 [Design Deliverable] Update stakeholders & personas document
* #31086 Re-Parse Django Action
* #3199 Performance Monitoring ADR
* #3046 PLG deployed in Cloud.gov
* #3060 As a TDP user, I need to stay logged in when I'm actively using the system

**Comment by lfrohlich** [comment]
I think we want to close this because it was moved to gitbook? @vlasse86

**Comment by vlasse86** [comment]
> I think we want to close this because it was moved to gitbook? @vlasse86

Yes, apologies! I'll be cleaning up the sprint summaries today.
