### ISSUE TITLE
As an STT user, I want to participate in research (round 3)

### ISSUE THREAD

**Issue by matthewjdoty** [raft-tech/TANF-app#324]
Description: 
This issue will deliver conducting and recording of Round 3 of research with STT participants. 

AC: 

- [x] All research sessions for round 3 are complete
- [x] Raw notes are uploaded to the secure folder (user research) in teams

Tasks: 
 - [x] Finalize observers for each session
 - [x] Follow interview protocol logistics to send out emails to STTs 1 day prior to the session
 - [x] Record Video if applicable
 - [x] Record verbatim notes in the notes template 
 - [x] Upload Raw notes to the secure folder in teams
 - [x] Legend is created to anonymize raw notes
 
Note: 
- This is will completed in Sprint 6 and 7. By sprint 6, we hope to complete 5 interviews.

**Deliverables:**

Raw Notes Folder: ([Link](https://teams.microsoft.com/_#/files/User%20Research?threadId=19%3A3bb622256c0b4792976dc5f1f4654fca%40thread.skype&ctx=channel&context=STT%2520Interview%2520Raw%2520Notes&rootfolder=%252Fsites%252FTANFDataPortalOFA-UserResearch%252FShared%2520Documents%252FUser%2520Research%252FSTT%2520Research%2520September%25202020%252FSTT%2520Interview%2520Raw%2520Notes)) :lock:
Recorded Interview Sessions: ([Link](https://teams.microsoft.com/_#/files/User%20Research?threadId=19%3A3bb622256c0b4792976dc5f1f4654fca%40thread.skype&ctx=channel&context=STT%2520Interview%2520Recordings&rootfolder=%252Fsites%252FTANFDataPortalOFA-UserResearch%252FShared%2520Documents%252FUser%2520Research%252FSTT%2520Research%2520September%25202020%252FSTT%2520Interview%2520Recordings)) :lock:

**(Legend) How To Decode Participants:**
- Name of Participant and STT Participation Code : [Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B4D2B3627-7439-4C8A-91A3-9F896BDA0F2A%7D&file=STT%20Contact%20List.xlsx&action=default&mobileredirect=true) :lock:
- STT Participation Code and STT name : [Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7BE83F84F1-71A0-459F-80A4-0D39BC250BE9%7D&file=STTs%20Attributes%20(Used%20for%20this%20research).xlsx&action=default&mobileredirect=true) :lock:

**Comment by lfrohlich** [comment]
This is complete
