### ISSUE TITLE
(INTERNAL) Round 3 Research Synthesis Workshop(s)

### ISSUE THREAD

**Issue by matthewjdoty** [raft-tech/TANF-app#325]
Description: Prepare and conduct synthesis workshop(s) based on observations made in #324
 
AC: 
- [x] Themes supported by raw notes are co-created by workshop participants are documented in research workshop mural

Tasks:
- [x] Gather all notes and fill in gaps with video recording
- [ ] ~~Delete video recording once notes are completed~~
- [x] De-identify data 
- [x] Prep materials and activities for synthesis workshop(s) according to [Raft UX standards doc](https://teams.microsoft.com/l/file/E2972102-6FB6-4771-94DD-256B9931F1B8?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2F%23244%20-%20Raft%20UX%20Standards%20for%20the%20TDRS%20project.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)
- [x] Schedule synthesis workshop(s) ccording to [Raft UX standards doc](https://teams.microsoft.com/l/file/E2972102-6FB6-4771-94DD-256B9931F1B8?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2F%23244%20-%20Raft%20UX%20Standards%20for%20the%20TDRS%20project.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)
- [x] Conduct synthesis workshop(s) ccording to [Raft UX standards doc](https://teams.microsoft.com/l/file/E2972102-6FB6-4771-94DD-256B9931F1B8?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2F%23244%20-%20Raft%20UX%20Standards%20for%20the%20TDRS%20project.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

Deliverable:
- Documentation - [Synthesis Workshop  Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1605279076254/8ba4f36f5bc1b2d724fd8c61daf6dc18da096e97) 🔒
- Note: Spun out the deletion of video recordings into a separate issue so as to allow for more time to synthesize insights in them (largely around tools that were screen shared) See #441

**Comment by lfrohlich** [comment]
The themes looks really good to me! Makes sense to separate out deletion but it should follow closely behind synthesis documentation. CLosing this out --thanks.
