### ISSUE TITLE
[bug] DAC reparse action confirmation pop-up does not include total # files selected if GT 100 files

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3269]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

- sys admin selected greater than 100 files to reparse via DAC and the pop-up indicates 100 files were selected for reparsing. 
- after triggering the reparse action button, the logs verify that GT 100 files were selected. 

## Action Taken

- sign-in as sys admin
- navigate to DAC data files page
- select greater than100 files to reparse
- review pop-up 
- pop-up confirmation inconsistent with selections when selecting more than 100 files to reparse via DAC data files page 

## What I expected to see

pop-up indicating 679 files were selected for reparsing
![bug1_679](https://github.com/user-attachments/assets/debb2574-1b20-4b62-8529-eff9676d1a9e)

## What I did see

- pop up indicating100 files were selected for reparse

![bug2_679](https://github.com/user-attachments/assets/fd3c828f-0cce-4f95-8615-7ddc92740149)

- logentries with evidence of gt 100 (i.e. N=679) files selected for reparse
![bug3_679](https://github.com/user-attachments/assets/08c57eb9-2172-407f-99cf-5a401e1acde6)

 - reparse model with evidence of gt 100 (i.e. N=679) files selected for reparse
 
![bug4_679](https://github.com/user-attachments/assets/633e352c-b44e-4cb4-b99b-cf106b431878)

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version: 
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know ) yes
+ Has the issue occurred more than once?:

**Comment by lhuxraft** [comment]
11/13/2024: Started work on this morning, planning to wrap up soon

**Comment by lhuxraft** [comment]
11/18: Need one more review

**Comment by lhuxraft** [comment]
Merged
