### ISSUE TITLE
As an admin, I want to see dev-ready mockups of deactivating users from the TDP system

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#327]
Description/Problem Statement: 
For OFA MVP, an admin needs to ~~remove~~ deactivate users from the TDP system. This issue delivers dev ready mockups for ~~removing~~ deactivating users from the TDP system. 

AC: 
- [x] The problem we are trying to solve is clearly stated, as are questions we still have 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [x] The design is usable, meaning... 
   - [x] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [x] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [x] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [x] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [x] Review [ACF access control policy](https://app.zenhub.com/files/281707402/7c409b5d-9bcc-4a4c-8da4-1ffcbd2f804c/download) to understand do's and don'ts and pair with dev team to see if the solution to works for OFA MVP
- [x] Create low-fi mockups (if needed) to share w/ Lauren/OFA data team (will this work for OFA/RS), dev (technically feasible), and OCIO/IPT(is in line with ACF's access control policy) to get feedback
- [x] Draft mockups for sharing and early feedback with team
- [x] Refine and create dev ready mockups
- [x] Check for accessibility against the manual QASP review checklist
- [x] ~~Create ticket for revising remove user functionality based on edge cases (ex. what happens to files/sections that a user is working on when they are removed?)~~ Removed given pivot to deactivation over deletion

Questions:
 - Does unassign and remove users mean the same thing for UI or are they different thing?
-- Different thing, decision made to pursue deactivate (unassign) rather than a full removal (for compliance with audit requirements)
- Is REactivation of users a necessary (ATO)MVP function? It could conceivably be handled on the back end (as a dev ticket service), but this depends on whether OCIO requires all elements of the Access Policy (like 60 day auto deactivation), and what kind of processes they want the product owner to establish—whether those can be manual or must be features in the product.

Supporting Documentation:
- [Figma Mockups](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

DD
- [x] Documentation: Design has been shared with the PO and team for feedback
- [x] @lfrohlich has reviewed and signed off

**Comment by lfrohlich** [comment]
This looks really good!
