### ISSUE TITLE
As an admin, I want to see mockups to change a user role 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#328]
Description/Problem Statement: 
This issue delivers dev ready mockups to change a given user role. A user role can be changed to another existing role or be unassigned.

AC: 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [ ] Review ACF's Access Control Policy to understand do's and don'ts
- [ ] Create low-fi mockups to share w/ Lauren/OFA data team (will this work for OFA/RS), dev (technically feasible), and OCIO/IPT(is in line with ACF's access control policy) to get feedback
- [ ] Refine and create dev ready mockups
- [ ] Check for accessibility against the manual QASP review checklist

Open Questions:
 -

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by amilash** [comment]
This functionality is done and delivered via Django admin console. Closing as done. We can reopen new tickets for when we do work to build permissions management into the TDP UI.
