### ISSUE TITLE
[Example][Backend] Create endpoint that provides data

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#343]
### Tasks
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

### How can I tell this is done?
- [ ] Demonstrated `GET` request will result in a dataset like the following:
```
{
  "id": 1,
  "first_name": "John",
  "last_name": "Doe"
}
```
### Notes
- [ ] Any notes on the item before or during development

**Comment by shubhi-raft** [comment]
Issue was created to demo #329
