### ISSUE TITLE
[Example][Backend] Create endpoint that updates data

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#345]
### Tasks
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

### How can I tell this is done?
- [ ] Demonstrated `PATCH` request with the following body
```
{
  "id": 1,
  "first_name": "John",
  "last_name": "Doe"
}
```
will respond with the following:
```
{
  "id": 1,
  "first_name": "John",
  "last_name": "Doe",
  "message": "User successfully updated!"
}
```
### Notes
- [ ] Any notes on the item before or during development

**Comment by shubhi-raft** [comment]
Issue was created to demo #329
