### ISSUE TITLE
[Example][Backend] Create endpoint that deletes data

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#346]
### Tasks
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

### How can I tell this is done?
- [ ] Demonstrated `DELETE` request with the following body
```
{
  "id": 1
}
```
will respond with the following:
```
{
  "message": "User successfully deleted!"
}
```
### Notes
- [ ] Any notes on the item before or during development

**Comment by shubhi-raft** [comment]
Issue was created to demo #329
