### ISSUE TITLE
(INTERNAL) Round 3 synthesis documentation

### ISSUE THREAD

**Issue by matthewjdoty** [raft-tech/TANF-app#350]
Description: Synthesize and document Round 3 research findings & recommendations based on the outcomes of the synthesis workshop (#325)
 

AC: 

- [x] Research synthesis has been documented and shared with PO and team in accordance with the tasks outlined below

Tasks: 

- [x] Draft synthesis document based on workshop outcomes (#325) and notes - What we wanted to learn; Who we talked to; What we tested; and What we learned; 
- [x] Post the draft document in the user research channel in Teams - [Hackmd](https://hackmd.io/7jKG_TiaQZuGOZn2mUIcSA?both#2020-Fall---Understanding-STT-Roles-Source-of-Truth-and-Metadata)
- [x] Solicit feedback on the draft (prior to raft review) from the Product Owner and Raft Development Teams (Can be async if needed)
- [x] Make any revisions necessary
- [x] Submit for QASP review

Deliverables:
Documentation of Round 3 synthesis: [PR](https://github.com/HHS/TANF-app/pull/99)

NOTE: this will likely start at the end of sprint 8 but not finish until sprint 9

DoD:
- [ ] Documentation: Synthesis has been shared w/ PO and PR to add research syn in docs has been created 
- [ ] @lfrohlich has reviewed and signed off

**Comment by lfrohlich** [comment]
Merged 12/14
