### ISSUE TITLE
[Frontend] Test Role Assignment Component

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#359]
### Description
This issue will be completed when the new Role Assignment component has been fully tested.

### Tasks
- [ ] Add tests for role assignment component

### Acceptance Criteria
- [ ] Tests can be checked by looking at the Circle CI deployment steps which will only pass when tests are passing and the testing percentage is passed the 80% threshold.

### Notes
- Notes

**Comment by shubhi-raft** [comment]
@hilvitzs this can be closed once the estimates for the other frontend issues in this epic have been updated.

**Comment by hilvitzs** [comment]
The decision was made to have tests in each individual issue attached to the epic rather than in an issue on the epic by itself.
