### ISSUE TITLE
[Bug] Clearing a selected STT in Combo box does not clear selection 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#370]
[PR 72 for 230](https://github.com/HHS/TANF-app/pull/72#issue-510912633) noted on clearing selection in combo box and then blurring out of the element, it looks like Alabama is selected even though it is not.

AC
- [ ] Clearing combo box clears the selection

**Comment by hilvitzs** [comment]
This has been fixed with the addition of a blank value as the first option in the select on #230.
