### ISSUE TITLE
(Internal) Update existing UX artifacts based on Round 3 research

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#371]
**Description**:
 This issue will deliver an update of existing user research artifacts and design spec based on insights from round 3 research. The concept mockups will likely not translate screen for screen into dev-ready mockups, but we will deliver dev-ready mockups for key parts of the flow the concept mockups illustrate. e..g metadata collection and other elements of setting up a TANF report.

AC: 
- [x] Existing research artifacts are updated. 
- [x] Dev ready mockups are delivered
- [ ] Product roadmap is updated, if necessary
- [x] Research recordings from round 3 are deleted

Tasks: 
- [x] Update STT attributes 
- [x] Update user persona docs
- [x] Update process maps
- [x] Create dev ready mockups 
- [x] Review mockups w/ Lauren + OFA data team
- [x] Reviewing product vision and product roadmap with outcomes from round 3 research

DoD: 
 - [ ] Documentation: Artifacts have been updated and shared with team
 - [ ] @lfrohlich has reviewed and signed off

Deliverables:
- STT Attributes Spreadsheet: [Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/doc2.aspx?sourcedoc=%7BF34F9CF0-70F3-46B4-A708-1764C5B3F4BC%7D&file=STTs%20Attributes%20(Current%20Version).xlsx&action=default&mobileredirect=true) 🔒 
- [Updated Persona Docs](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/User-Types.md) 
- [Updated Process Map](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1608314993566/5724cd3c3e5e964ab9c85743e5b8e1d89c767788) 🔒 
- Dev ready mockups #427 and #415

NOTE: 
- This will likely be completed in sprint 10

**Comment by shubhi-raft** [comment]
Note: No changes were made to the product roadmap.

**Comment by lfrohlich** [comment]
This was completed
