### ISSUE TITLE
[SPIKE] As a dev, I want to know how to implement integration test for authentication (Cypress testing with login.gov)

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#377]
**Description:**
We need to find a way to create integration tests with Cypress that allow us to login via login.gov. The problem with this, mainly, is properly simulating the MFA functionality. We'll need to take some time to explore possible solutions.

**Timebox**
4 hours

**Acceptance Criteria:** 

- [x] Document findings in a logical place
- [x] Update tasks on #310 based on findings
- [x] Lauren confirms whether #310 will be part of the OFA MVP by updating #310 with OFA MVP tag, if necessary

**Notes:**
- Looking at [cypress-otp](https://www.npmjs.com/package/cypress-otp) as a possible part of the solution
- Looking at mocking strategies as well

Deliverable:
- ~~Findings are documented via [PR](https://github.com/raft-tech/TANF-app/pull/445/files)~~
- Findings documented PR to HHS

**Comment by shubhi-raft** [comment]
@riatzukiza @carltonsmith @alexsoble to schedule a breakout conversation to discuss Aaron's findings.

**Comment by kniz-raft** [comment]
This work was done, #310 was updated, just didn't get pulled into the sprint in which it was worked. Closing now.
