### ISSUE TITLE
As an OFA admin, I want to change an assigned user role

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#399]
#### Description
This issue will deliver admin changing or removing an assigned role to an approved TDP user

#### AC:
- [ ] Update role by selecting from the drop down
- [ ] Success notification is served

**Comment by amilash** [comment]
This functionality is done and delivered via Django admin console. Closing as done. We can reopen new tickets for when we do work to build parmissions management into the TDP UI.
