### ISSUE TITLE
How do STTs want to manage their own teams within TDP?

### ISSUE THREAD

**Issue by cmajel** [raft-tech/TANF-app#40]
**Description:**
During 8/4 sprint review, there was discussion about how some STTs may want to be able to administer their own user permissions within their STT group. Some actions we discussed included:
* being able to remove someone who no longer works for that state
* add a new employee
* providing ways for others within the STT to view data submissions
* How will OFA admins help STT administer their users?
* How account invitations work and who will they come from?

This issue is a placeholder for future design discovery and research with STTs. Needs refinement before it is worked on!

---

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
thanks @cmajel . Noting an additional pain point that was brought up during 8/4 review: county cannot view the data being submitted.

**Comment by carltonsmith** [comment]
There was a discussion during Sprint Planning around the creation of users. When a new user attempts to log in to the system, how do we want to handle it? Does the system reject users who have not yet been assigned to a group or does it keep them and display a message letting them know they will be assigned if appropriate?

**Comment by amilash** [comment]
@dk-ui  Should we focus on researching this in advance of the V2 Tribes release, so we can come up with dev-able features? If so, can you factor it into your upcoming research plan?

cc @lfrohlich

**Comment by lfrohlich** [comment]
I don't think we need this before V2. If anything, I think this would be a future enhancement @amilash  @dk-ui @ADPennington

**Comment by ADPennington** [comment]
> I don't think we need this before V2. If anything, I think this would be a future enhancement @amilash @dk-ui @ADPennington

@reitermb could you remind us where this fits in the research roadmap?

**Comment by valcollignon** [comment]
Dupe of #1201 and #214. Closing per backlog refinement 12.14.21
CC: @lfrohlich
