### ISSUE TITLE
As an admin, I want to see dev-ready mockups of reactivating users from the TDP system 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#404]
Description/Problem Statement: 
For OFA MVP, an admin needs to reactivate users in the TDP system, restoring their access after it's been manually or automatically removed. This issue delivers dev ready mockups for reactivating users in the TDP system. 

AC: 
- [x] The problem we are trying to solve is clearly stated, as are questions we still have 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [x] The design is usable, meaning... 
   - [x] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [x] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [x] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [x] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [x] Check against ACF Access Policy guidelines / previous decisions around how to adhere to them from [#327](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/327)
- [x] Draft mockups for sharing and early feedback with team
- [x] Refine and create dev ready mockups
- [x] Check for accessibility against the manual QASP review checklist

Questions:
- Do we need or want to support manual reactivation regardless of whether the user has requested reactivation?
   - Not in MVP. This could be achieved via XMS NextGen
- Do we need or want to support denying reactivation?
  - Not in MVP. This could be achieved via XMS Next Gen

Notes: 
- XMS developments may reduce/remove the need to develop many elements of user management including reactivation. This also affects the open questions listed above.

Supporting Documentation:
- See [Figma Mockup](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

DD
- [x] Documentation: Design has been shared with the PO and team for feedback
- [x] @lfrohlich has reviewed and signed off

**Comment by lfrohlich** [comment]
This looks great! As noted above, implementation will depend on NextGen XMS discussion.

**Comment by lfrohlich** [comment]
This was closed as of 11/24/20
