### ISSUE TITLE
Document review process for future issues

### ISSUE THREAD

**Issue by cmajel** [raft-tech/TANF-app#41]
Description:
From our 8/4 retro, we'd like to have a clear, shared understanding of how issues are reviewed by gov team members.

AC: 

- [x] [Review process is documented in our team charter](https://teams.microsoft.com/_?tenantId=d58addea-5053-4a80-8499-ba4d944910df#/docx/viewer/aggregatefiles/https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA~2FShared%2520Documents~2FGeneral~2FTeam%2520Meetings%2520+%2520Presentations~2FTeam%2520Charter%2520and%2520Norms.docx?baseUrl=https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA&fileId=a7f48edc-8e8e-45f7-aae8-57ad4e9c3c57&ctx=aggregate&viewerAction=view) and shared with the team

Tasks: 

- [x] Git issue template updated to include reviewers
- [x] Conversation scheduled between 18F leads, Raft leads and Lauren
- [x] Issues for active sprint are updated with a clear reviewer

DoD: 
- Documentation: Team Charter

**Comment by lfrohlich** [comment]
We now have Govt Review and Raft Review columns. Discussed this in sprint retro 8/18. Only thing left is PR to update issue template

**Comment by lfrohlich** [comment]
Issue templates include reviewers. This is done.
