### ISSUE TITLE
[Frontend] Add a download button to the Data Files view

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#416]
#### Description:
Add buttons to download different sections of the uploaded TANF data files

AC: 

- [ ] _Download Buttons_ are added to the page 
- [ ] Clicking on _Download_ downloads the correct section
- [ ] Frontend matches delivered and accepted mockup (link to figma below)
- [ ]  All tests are passing
- [ ]  Test coverage exceeds 90%

Tasks:
- [ ] Create 4 buttons on the data files page, one for each section of a quarterly report
- [ ] Implement a `GET` request to the database to retrieve files uploaded for that year and user.
- [ ] Implement a `GET` request to the database to retrieve a list of the sections for which there are files available.
- [ ] IF files are available for that section, add a `Download Section ${number}` button that slightly displaces the upload section. 
- [ ] ELSE show nothing, the page should look the same as it did before introducing download logic.
- [ ] On click of `Download Section ${number}`, implement a request to mirage that gets a text file.
- [ ] There is a task created to replace the mirage calls to `get-file` once there is a backend endpoint

Supporting Doc:
- https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4124%3A0

**Comment by carltonsmith** [comment]
**Note**

Issue description, tasks and acceptance criteria will be added once the mockup is accepted and reviewed

**Comment by lfrohlich** [comment]
is the design of this dependent on whether we're uploading separate sections?

**Comment by kniz-raft** [comment]
@jorgegonzalez & @carltonsmith This might need additional changes based on the new mock-ups, but I updated as much as I could

**Comment by riatzukiza** [comment]
Now that we can stub endpoints and are using local stack for s3, this is no longer blocked by any backend issue. We can develop this as if there was an endpoint, as long as we have an issue to go back later and connect this work to the backend when that endpoint is ready.
