### ISSUE TITLE
In mobile menu, signout and profile links are not keyboard navigable

### ISSUE THREAD

**Issue by hilvitzs** [raft-tech/TANF-app#425]
EXPECTED: When you are on a mobile size screen and click on the `Menu` button and then tab through the options, user should be able to select profile link or sign out link using the keyboard.

ACTUAL: The tabbing on the open `Menu` does not allow profile link or sign out link to be selected using the keyboard. Tabbing only moves between the `Close` menu button and the `Welcome` link.

**Comment by lfrohlich** [comment]
This was merged 11/25 as part of [PR 197 session timeout #86](https://github.com/HHS/TANF-app/pull/86)
