### ISSUE TITLE
[Design] As an OFA admin, I want to see dev-ready mockups to download each section each section of a new TANF report

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#428]
Problem Statement:
For OFA MVP, test users acting as a STT or an OFA admin need to download each section each section of a new TANF report. This issue delivers dev ready mockups for downloading each section each section of a new TANF report.

Questions:
This is a follow-on to #

AC: 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 
- [ ] [User flow is updated](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

Tasks
- [ ] 
- [ ] Check for accessibility 

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by shubhi-raft** [comment]
dupe to #427

**Comment by kniz-raft** [comment]
415 is the front end dev work, this is the design work that enables the front end - removing dupe tag

**Comment by kniz-raft** [comment]
Closing as the dupe was also closed
