### ISSUE TITLE
Refine KPIs for Goal 1 and document how they are used

### ISSUE THREAD

**Issue by cmajel** [raft-tech/TANF-app#43]
Description:
From our 8/4 retro, we had questions about the [state of our KPIs](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1595883123926/fb22e7eaf764a84145b3aae06552d83bb2085d7e) and how we want to use them going forward in our work. To help track our epic-level progress? To add as ACs on certain issues?
Refine KPIs for login, upload, and access (Goal 1)

>> Consider adding KPI controls now??

AC: 

- [ ] We know how we're going to use the KPIs to measure our progress
- [ ] We have documented how we're going to do that (wiki/teams)

Tasks: 

- [ ] Meeting scheduled to refine KPIs further
- [ ] Decide where KPIs are documented
- [ ] Process socialized with the team 

DoD: 
 - [ ] Documentation: we have document how we're going to use them
 - [ ] KPIs approved by Lauren

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by lfrohlich** [comment]
Are these KPIs for the Phase 1 MVP:
