### ISSUE TITLE
Reorganize workspaces 

### ISSUE THREAD

**Issue by cmajel** [raft-tech/TANF-app#44]
Description:
18F and OFA currently document some high level project management tasks in our [old Trello board](https://trello.com/b/eREZYv2O/ofa-18f-project-management-board). Tasks include things like...
* Create templates for future assisted aquisitions
* 18F transition planning
* ATO documentation

Reorganize three workspaces: 
* Sprint backlog
* Product backlog
* OFA/18F Project Management (currently Trello) 

AC: 

- [x]  Team charter details what belongs in what workspace
 - [x] 3 workspaces exist

Tasks: 

- [x] Create product backlog and project management workspaces
- [x] Collaborate to find a mutually agreeable pattern

DoD: 
 - [x] Done

**Comment by shubhi-raft** [comment]
We will be keeping OFA/18F Project Management in Trello.

**Comment by lfrohlich** [comment]
This is done, Shubhi has permissions
