### ISSUE TITLE
[Internal Placeholder] Round 3 Research video deletion

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#441]
Description:
Followup issue on #325 so as to allow for more time to synthesize insights in them (largely around tools that were screenshared by participants)

AC:

- [ ] Research recordings from round 3 are deleted
- [ ] Process maps are updated

Tasks
- [ ] Document findings from participant screen sharing (possibly via task flows?)
- [ ] Delete video files

Documentation -

DoD:
 - [ ] Documentation: [Draft research plan has been shared with the PO and team for feedback]/ [Interviews have been conducted] / [Research synthesis has been documented and shared with PO and team]
 - [ ] @lfrohlich has reviewed and signed off

**Comment by shubhi-raft** [comment]
dupe #371
