### ISSUE TITLE
Create a research plan for Round 4 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#447]
Description:
This issue will deliver a research plan to fill knowledge gaps and test assumptions. It may involve talking to 3rd party vendors and any other personas as appropriate. Its structure will be modeled off of past plans (see supporting documentation)

AC:
- [x] Research plan is drafted and is informed by journey maps

Proposed Tasks:
- [x] Create a draft research plan that includes 
   - [x] List and review research goals with OFA and product team
   - [x] Determine method(s)
   - [x] Develop recruitment criteria
   - [x] Document ethics, privacy concerns
   - [x] Draft expected outcome with actionable learnings including outputs (diagrams, documents, etc.)

DoD:
 - [x] Documentation: Draft research plan has been shared with the PO and team for feedback
 - [x] @lfrohlich has reviewed and signed off

Note:
- Round 4 research plan outputs will include final current state journey maps (follow-on to #165)
- Collaborative design workshop will be shorter and smaller than 3 hours based on @lfrohlich feedback
- Update recruitment criteria to include screeners. We are targeting 2-3 STTs and 1-2 OFA participants. 

Supporting Documentation:
- [Round 3 Research Plan](<https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/Shared%20Documents/User%20Research/STT%20Research%20September%202020/%2363%20User%20Research%20Plan%20STTs.docx?d=w2e300237f6454446b191a9ee509026ef&csf=1&web=1&e=pAteXb>) 🔒

Deliverables:
- [Round 4 Research Plan](<https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA-UserResearch/_layouts/15/doc2.aspx?sourcedoc=%7B7D2578C5-7B7B-4877-88CE-00F2D542CC85%7D&file=Research%20plan%20Round%204.docx&action=edit&mobileredirect=true&wdPreviousSession=ae4069c0-d20b-4dc2-93cf-23196b886ead&wdOrigin=TEAMS-ELECTRON.teams.undefined>) 🔒

**Comment by kniz-raft** [comment]
![research round 4 timeline_2021.01.26.png](https://images.zenhubusercontent.com/5ffcb9fc3b60414562c1f655/f8a83b05-99ea-4ae4-b7ab-86d5021fda40)

**Comment by lfrohlich** [comment]
Thanks for working with me on the edits, @jenewingpierce ! Good to go!
