### ISSUE TITLE
[Research] Workshop facilitation guide for Round 4 research

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#448]
Description:
This issue will deliver a conversation guide and interview protocol for #447

AC:
- [ ] Conversation guide and interview protocol is drafted and feedback from PO is incorporated.

Proposed Tasks:

- [ ] Draft conversation guide
- [ ] Determine logistics for conducting interviews
   - [ ] Draft timeline with activities, and team participation
   - [ ] Schedule interviews and confirm participation
   - [ ] Create email language template (if applicable)
   - [ ] Create template for recording interview notes
   - [ ] Dry run

DoD:
 - [ ] Documentation: Draft conversation guide has been shared with the PO for feedback
 - [ ] @lfrohlich has reviewed and signed off

Note:
- Sprint 10 backlog. Most likely worked in sprint 11.

Supporting Documentation: 
- [Round 3 Conversation Guide / Protocol](<https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B0333313b-0f88-406b-b894-07687d32921b%7D&action=view>) 🔒

Deliverables:
- [Round 4 Conversation Guide & Protocol](<>) 🔒

**Comment by kniz-raft** [comment]
Removing this one in favor of #506
