### ISSUE TITLE
(Internal) Create a journey map to document an unauthorized users' journey 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#454]
**Description:**
Create journey map for an evil actor persona to document. Do time-boxed deep dive on evil users (hackers and non-authorized users of the app)and plumb potential, established, and emerging motivations for evil users to expose security vulnerabilities so that prevention can be incorporated into design.  

**Acceptance Criteria:** 
- [x] results of secondary research and dev-ux sync are reported to @lfrohlich 

**Proposed Tasks:**

- [x] prepare secondary research 
- [x] meet to discuss useful scenarios with dev 

Documentation DoD:
- [x] @lfrohlich has signed off

Additional information:
- The slides that were presented can be found on [teams](https://teams.microsoft.com/l/file/bcc90a28-a1cf-49c3-ba67-4ca4dfd3ee30?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=pdf&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch%2FShared%20Documents%2FUser%20Research%2FEvil%20User%20Journey%20Map-2.pdf&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch&serviceName=teams&threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&messageId=1617033154567&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) 🔒 
- Additional stories will be created as a result of this ticket once the team prioritizes them

**Comment by kniz-raft** [comment]
slated for Round 5 (Sprints 16-18)

**Comment by jenewingpierce** [comment]
@kniz-raft please check to see if it needs more refinement.

**Comment by kniz-raft** [comment]
The slides that were presented can be found on teams 🔒

**Comment by lfrohlich** [comment]
Next steps with #799
