### ISSUE TITLE
Combo Box Component - Input ID and Label ID were mismatched to prevent dropdown from staying open on selection

### ISSUE THREAD

**Issue by hilvitzs** [raft-tech/TANF-app#473]
**Description:**
There was an issue on the Combo Box component from USWDS where if the ID's match on the input and the label, the dropdown won't close when the user makes a selection. In order to circumvent this issue, I simply changed one of the ID's.

This issue is to find a more permanent fix to the accessibility issue of having mismatched ID's.

**Acceptance Criteria:** 
- Makes combo box bold
- Solves a11y issue where combo box was sticking
- Label `for` and select `id` now match

**Notes:**

I took Robert Jolly's suggestion of making the label ID implicit rather than explicit and also restructured the label inside the component so that it a sibling of the `select` element rather than wrapping it.

For some reason in React wrapping the label around the combo box component caused a click event to be fired without any actual click.

**Comment by lfrohlich** [comment]
This met the ACs and was merged 1/12/21
