### ISSUE TITLE
Focus is not triggering user activity

### ISSUE THREAD

**Issue by hilvitzs** [raft-tech/TANF-app#474]
**Description:**
Robert Jolly mentioned in one of his reviews that when users are using a screen reader to navigate through the `Edit Profile` form, focusing on the inputs is not triggering a user action to prevent the idle timeout modal from popping up.

With the addition of the `focus` event and with the amount of events that a user can trigger to prevent idleness, it is also a good idea to batch the events so that it doesn't affect performance.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Focus does trigger activity and user will not be timed out if a `focus` event is triggered.
- [ ] Testing Checklist has been run and all tests pass

**Notes:**
- We decided on 1 minute for the batched event handlers.

**Open Questions:**

- I'm not sure how exactly to demo this.

**Comment by lfrohlich** [comment]
Merged 1/13/21
