### ISSUE TITLE
Document existing quantitative research into the STT Attributes Guide

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#489]
Description: In sprint 10 we started documenting quantitative research within the STT Attributes Guide however there are many more data sets within the STT Attributes Spreadsheet to document. This ticket finishes the documentation of remaining attributes.

AC:

- [ ] [Draft research plan]/[user interviews]/[synthesis] is complete.

Proposed Tasks:

Research plan
- [ ] Create a draft research plan that addresses the following epics - [...]
   - [ ] List research goals
   - [ ] Determine method(s)
   - [ ] Develop recruitment criteria
   - [ ] Draft timeline with activities, timeline, and team participation
   - [ ] Document ethics, privacy concerns
   - [ ] Draft expected outcome with actionable learnings including outputs (diagrams, documents, etc.)
   - [ ] Write interview guide
- [ ] Determine logistics for conducting interviews
   - [ ] Schedule interviews and confirm participation
   - [ ] Create email language template (if applicable)
   - [ ] Create template for recording interview notes
   - [ ] Dry run

Conduct Interviews
 - [ ] Email privacy statement to participants 1 day in advance
 - [ ] Record Video if applicable
 - [ ] Record verbatim notes in the notes template

Synthesis
- [ ] Gather all notes and fill in gaps with video recording
- [ ] Delete video recording once notes are complied
- [ ] Deidentify data
- [ ] Perform topline synthesis
- [ ] Synthesis workshop with PO/stakeholders
- [ ] Document synthesis - Scope (research goal(s)), High-level findings, Actionable learnings, Issues that have to be added to Zenhub, Takeways for future research

Documentation -
- [ ] Document 'What we wanted to learn', 'Who we talked to', 'What we tested', 'What we learned' and add URL for full research plan (living in User research folder in  Teams) in Code<> docs.

DoD:
 - [ ] Documentation: [Draft research plan has been shared with the PO and team for feedback]/ [Interviews have been conducted] / [Research synthesis has been documented and shared with PO and team]
 - [ ] @lfrohlich has reviewed and signed off

**Comment by jenewingpierce** [comment]
@dk-ui does this still seem like a useful ticket?

**Comment by amilash** [comment]
@dk-ui  is this still needed? Its listed as not. If not, can we close as 'will not do'?

**Comment by dk-ui** [comment]
@amilash Yes this one is no longer needed. We do this work as we go.

**Comment by amilash** [comment]
Thanks. Closing
