### ISSUE TITLE
(Internal) Document findings from OFA journey map workshop as user stories

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#492]
Description: 
This issue will deliver new user stories that are added to the product backlog that came through as findings from the [OFA journey map workshop](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1608238114372/191c53b8ef538838bc8c179daa238dd5c5dcc9e8)

AC:
- [ ] User stories are added to the product backlog
- [ ] User stories are added to product roadmap, if necessary

 Tasks:
- [ ] Raft's UX team has a breakout session to discuss and add user stories that came from findings of the OFA workshop 
- [ ] Evaluate user stories to add to product roadmap 

Supporting documentation:
- [OFA Workshop - Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1608238114372/191c53b8ef538838bc8c179daa238dd5c5dcc9e8)

DoD:
 - [ ] Documentation: Findings have been documented and shared with PO and team
 - [ ] @lfrohlich has reviewed and signed off

**Comment by shubhi-raft** [comment]
this is dependent on STT workshop which will be completed in Round 4.

**Comment by jenewingpierce** [comment]
@reitermb we can kick these in now now problem. let me know if you need help on this.

**Comment by kniz-raft** [comment]
dupe to #671
