### ISSUE TITLE
Plan and schedule OFA interviews

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#50]
Description:
For August 2020 research cycle, plan, recruit and schedule interviews.

AC: 

- [x] Interviews are scheduled. 

Tasks: 

- [x] Define and confirm timeline (given WPR release)
- [x] Define remote interview logistics 
- [x] Schedule interviews and confirm participation
- [x] Determine who will take notes.

DoD: 
 - [x] Interviews are scheduled and confirmed. 
- [x] Team knows when interviews are generally happening.

**Comment by shubhi-raft** [comment]
Update:

90 min session scheduled with Yun on Friday, 8/14 - 1:30-3pm.

**Comment by shubhi-raft** [comment]
Second 90 min session: Tuesday, 8/18, 10-11:30
Third 90 min session: Thursday, 8/20, 11-12:30

**Comment by lfrohlich** [comment]
Interviews have been scheduled~ this is done
