### ISSUE TITLE
(Internal) Update Research Activities overview to reflect round 3 research

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#501]
Description:
Follow-on to [#371](https://github.com/raft-tech/TANF-app/issues/371) to tie up other documentation loose ends we flagged while updating other artifacts.

This issue will deliver an update the [research activities overview document](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/Overview%20of%20Research%20Activities.md). It adds a table of content, an overview of Round 3 research, and adopts tagging password protected content links with a :lock:. 

AC:
- [x] Document is updated
- [x] PR is opened to merge the change to code docs

Tasks:

 - [x] Add table of contents
 - [x] Add round 3 research overview
 - [x] Add protected link styling
 - [x] Open PR once [changes](https://github.com/reitermb/TANF-app/blob/main/docs/User-Research/Overview%20of%20Research%20Activities.md) are approved 

DoD:
 - [ ]  Documentation: Artifacts have been updated and shared with team
 - [x] @lfrohlich has reviewed and signed off

Deliverables:
- [PR to HHS repo](https://github.com/HHS/TANF-app/pull/120)

**Comment by lfrohlich** [comment]
Looks great~ 
This was merged on 1/7/21
