### ISSUE TITLE
(Internal) Update code docs with flat file metadata document

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#502]
Description:
This issue will deliver a markdown version of [the flat file metadata document](<https://teams.microsoft.com/l/file/1DFCC4C4-9A7C-4F97-8489-713AC8B85C4F?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch%2FShared%20Documents%2FUser%20Research%2FSTT%20Research%20September%202020%20-%20Round%203%20Fall%2F%23248%20-%20Document%20Flat%20File%20Metadata.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA-UserResearch&serviceName=teams&threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287>) to make the information it contains more easily accessed by the team.

AC:
- [x] Document is converted to markdown
- [ ] PR is opened to merge the change to code docs

Tasks:

 - [x] Move content to markdown document
 - [x] Open PR once [changes](https://github.com/reitermb/TANF-app/blob/main/docs/User-Research/Flat%20File%20Metadata%20Guide.md) are approved 

DoD:
 - [x]  Documentation: Artifacts have been updated and shared with team
 - [x] @lfrohlich has reviewed and signed off

Deliverables:

- Updated Overview of metadata document: [Link](https://github.com/HHS/TANF-app/blob/c2e9d2e218ce76853cceb4457416ba578bcc64c5/docs/User-Research/Flat%20File%20Metadata%20Guide.md)

**Comment by shubhi-raft** [comment]
@reitermb the markdown looks good, I made minor tweaks. I was not clear whether you wanted to use example or excerpt for header and trailer structure. leaving that up to you. Thanks!

**Comment by reitermb** [comment]
@shubhi-raft Thanks! Just to be sure I loop all the changes in, where did you make the tweaks?

**Comment by shubhi-raft** [comment]
@reitermb the changes look good! thanks! could you create a PR for it the HHS repo and push this over to QASP review?

**Comment by lfrohlich** [comment]
This was merged 1/25/21
https://github.com/HHS/TANF-app/blob/c2e9d2e218ce76853cceb4457416ba578bcc64c5/docs/User-Research/Flat%20File%20Metadata%20Guide.md
