### ISSUE TITLE
(Internal) Update Design Guide document in docs with Figma links

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#503]
Description:
This issue will deliver an updated version of the [Design Guide document in code docs](<https://github.com/HHS/TANF-app/blob/main/docs/Design/Design-Guide.md>) to reflect and organize design deliverables on various pages of Figma. This will include notes on design decisions and other rationale (where applicable) and a centralized place that relates and links issues to deliverables in Figma. (Think figma table of contents)

AC:
- [x] Document is updated
- [x] Document includes links to gov reviewed mockups and their github tickets
- [x] Document includes an overview of user flows in figma / how they are used
- [x] PR is opened to merge the change to code docs

Tasks:

 - [x] Add table of contents
 - [x] Add Figma artifacts section
 - [x] Add updated content / links for user flows and mockups & prototypes subsections
 - [x] Open PR once [changes](https://github.com/reitermb/TANF-app/blob/main/docs/Design/Design-Guide.md) are approved 

DoD:
 - [x]  Documentation: Artifacts have been updated and shared with team
 - [x] @lfrohlich has reviewed and signed off

Deliverables:

- HHS PR

**Comment by shubhi-raft** [comment]
@reitermb this looks good! ready to be shipped!

**Comment by kniz-raft** [comment]
Pull request into HHS: https://github.com/HHS/TANF-app/pull/179

**Comment by lfrohlich** [comment]
This was merged 2/18
