### ISSUE TITLE
As a Tadpole, I want to start a style guide for documentation so that the documentation is consistent

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#505]
Description:
This issue will deliver a cohesive documentation style guide to the [Design Guide document in code docs](<https://github.com/HHS/TANF-app/blob/main/docs/Design/Design-Guide.md>) to ensure we have consistency across all of our documentation. 

AC:
- [x] Document is updated/added
- [x] PR is opened to merge the change to code docs

Tasks:

- [x] Review [ACF's content and formatting guidelines](https://web.archive.org/web/20201018014141/https://www.acf.hhs.gov/digital-toolbox/content/editorial-style-guide/words-usage) 
 - [x] Evaluate whether this belongs in the design guide or its own document
 - [x] Document patterns for code-docs, resources for terminology, 
 - [x] Open PR once [changes](https://github.com/reitermb/TANF-app/blob/main/docs/Design/Design-Guide.md) are approved in raft review

DoD:
 - [x]  Documentation: Artifacts have been updated and shared with team
 - [x] @lfrohlich has reviewed and signed off

Deliverables:
- Updated Design Guide document: [Link](https://github.com/HHS/TANF-app/blob/main/docs/Design/Design-Guide.md)

Notes: 
- An example of how we've done a broader style guide in the past can be found [here](https://github.com/raft-tech/cfgov-refresh/wiki/Content-Strategy-and-Style-Guide)
- May lead to a later follow on document covering a broader scope of material, e.g. content in TDP as well as content in documentation

**Comment by kniz-raft** [comment]
Should head into Raft Review by EOD 2/1

**Comment by lfrohlich** [comment]
This is done and demoed 2/16
