### ISSUE TITLE
[Research] Plan Round 4 (Sprints 13-15) workshop format

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#506]
Description:
This issue will deliver our plan to conduct States and Territories (ST) workshop to validate user flow. 

AC:

- [x] Workshop agenda/format/other relevant details are planned
- [x] Mural board is ready for workshop

Proposed Tasks:
- [x] Create workshop mural board in OFA room
- [x] Plan agenda
- [x] Add artifacts generated by #
- [x] Dry run workshop
- [x] Move final Mural to OFA Mural

DoD:
 - [x] @lfrohlich has reviewed and signed off

#### Deliverable(s):
- [OFA mural link](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1613491508274/7cf6d22e727671899d3d1417c2b7e9505eee7f38)
- [Link to facilitation guide](https://hackmd.io/Ful-2KY9TAOjgATDvBchSQ)

**Comment by kniz-raft** [comment]
Per @lfrohlich, mural board is in an okay shape as of now.

**Comment by kniz-raft** [comment]
Add mural link when it's ready for Lauren's review

**Comment by jenewingpierce** [comment]
[https://app.zenhub.com/files/281707402/fb28183c-4310-41ec-bf09-e386af4dc45f/download](https://app.zenhub.com/files/281707402/fb28183c-4310-41ec-bf09-e386af4dc45f/download)

**Comment by lfrohlich** [comment]
This was completed with 2/12 workshop
