### ISSUE TITLE
Conduct OFA Interviews

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#51]
Description:
For august research cycle, the interviews are conducted. 

AC: 

- [x] Interviews are conducted. 

Tasks: 

- [x] Conduct the interview with the recruited participants
   - Moderator
   - Note taker(s)
   - Observer(s)
- [x] Consolidate notes if there was more than one note taker
- [x] Record and store notes in permission restricted folder

DoD: 
 - [x] Documentation: notes are stored in a secure, restricted folder

**Comment by shubhi-raft** [comment]
@matthewjdoty for your review/feedback.

**Comment by lfrohlich** [comment]
I was able to remove visitors, the only one I can't remove is the SharePoint administrator.

**Comment by matthewjdoty** [comment]
@lfrohlich based on your last comment, I'm assuming I can just upload to Teams without a password. Is this correct?

**Comment by matthewjdoty** [comment]
I've uploaded the raw, consolidated notes to Teams in the User Research folder

**Comment by matthewjdoty** [comment]
CORRECTION the notes are now in the Design Folder - https://teams.microsoft.com/l/file/20E8D600-8BEB-46F1-BA04-96D60D22D10A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=xlsx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2FResearch%20August-September%202020%2FOFA%20Interview%20Notes%20CONSOLIDATED%20RAW%20NOTES.xlsx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287

**Comment by lfrohlich** [comment]
@matthewjdoty  files in the User Research channel don't need a password -- that is the most secure since it is limited to a subset of Raft, OFA, and 18F.

**Comment by matthewjdoty** [comment]
@lfrohlich I'm happy to put them back there but I was recently advised to move them to the Design channel (see above). Just to be clear, You want them in the Research channel (the one with the little lock icon next to it) right? If so, do you want all of our research files to be here as well (there are quite a few in the design channel)?

**Comment by lfrohlich** [comment]
@matthewjdoty  once research starts with STT, I think those notes should go in the Research channel, which is locked. The rest can stay where it is, thanks! Closing this out.
