### ISSUE TITLE
As a dev, I would like to be able to assign super user status without SSH

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#519]
**Description:**

The staging and prod sites will not support SSH access, so we'll need to implement a way to set the superuser without SSH access in those environments. A data migration might provide a way to accomplish this, a Cloud Foundry CLI task might be another way to accomplish the same task.

**Potentially useful references:**

Data migration:

- https://stackoverflow.com/a/53555252
- https://stackoverflow.com/a/59467533

Cloud Foundry task:
http://cli.cloudfoundry.org/en-US/v7/run-task.html

**Acceptance Criteria:** 

- [ ] Superuser set via data migration or CF CLI task; demonstrate this locally or in the dev environment to PO and tech lead
- [ ] `user_role_management.md` documentation updated
- [ ]  ADR created to document this decision

**Comment by alexsoble** [comment]
@carltonsmith The other week we talked about Cloud Foundry tasks — http://cli.cloudfoundry.org/en-US/v7/run-task.html — I wonder if a CF task is a better approach than a data migration for creating super users. 

More flexible and simple, can be run as a one-off CLI task as opposed to a migration which has way more moving parts. 

And would still preserve an audit trail since you have to be logged in as a CF user to run a CF task.

**Comment by carltonsmith** [comment]
Interesting - I will definitely give that a look! The one nice thing about migrations is they are documented in the repo history, but if this is easier and satisfies requirements then it sounds good to me.

**Comment by alexsoble** [comment]
@carltonsmith You're right! That is an advantage of using a migration. If we use a CF task instead we'd need to document it somewhere -- how to run it, what arguments to pass in, etc.

**Comment by alexsoble** [comment]
@riatzukiza Since you are picking this one up now, wanted to share a thought relating to the "CF CLI task" versus "data migration" discussion above: 

* If we envision only one or two superusers with access to the Django Admin dashboard, and those users never or extremely rarely changing over the lifecycle of the app, a data migration might make more sense 
* If we envision more users with access to the Django Admin dashboard, and those users changing from time to time over the lifecycle of the app, a CF CLI task makes more sense 

cc @carltonsmith, curious if you'd agree! 

@riatzukiza part of this work can also be investigating the two possible approaches here and seeing which is the better fit. 

I'll update the issue description itself to be a bit more agnostic about how we accomplish this task.

**Comment by lfrohlich** [comment]
FYI I added an acceptance criteria that an ADR is created to document this decision

**Comment by carltonsmith** [comment]
Merged to HHS!
