### ISSUE TITLE
(Internal) Accessibility review of Django Admin Console

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#528]
https://github.com/HHS/TANF-app/pull/121#issuecomment-758250828

We deferred the accessibility review of the Django Admin Console because it is backend only and will only be used by a few users. In addition, other developers are continuing to make accessibility improvements. We will revisit this in a later sprint.

**Comment by iamjolly** [comment]
That sounds fine so that other work can be prioritized. If the backend admin users change, we could move this a11y review work up to accommodate.

**Comment by amilash** [comment]
@reitermb  is this still needed, or does our ongoing a11y review cover this work?

**Comment by amilash** [comment]
I think this ticket is a dupe now of the linked 508 epic. Im closing.
