### ISSUE TITLE
As a Product Owner, I want to have confidence that the project's Dockerized CI/CD layer has been hardened

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#542]
This Epic groups together issues in the backlog that relate to hardening our Docker configuration, making it more secure as we move from development closer to a production environment. 

These stories would be great as Evil User Stories to help frame potential Docker-related security risks and show how we've hardened our Docker setup against them.

## AC

+ [ ] As a Product Owner, I want have confidence that the project's Docker layer has been hardened before going to production

## Sub-tasks 

See individual issues grouped under this Epic.

**Comment by kniz-raft** [comment]
No longer needed as the recommendation is to move away from docker.

**Comment by amilash** [comment]
@abottoms-coder can we close this? It seems like its either done or will not do.

**Comment by lfrohlich** [comment]
@ADPennington  can this be closed?

**Comment by ADPennington** [comment]
> @ADPennington can this be closed?

yes @lfrohlich
