### ISSUE TITLE
As a backend dev, I want to have a .dockerconfig file as an extra layer of security against accidentally leaking secrets

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#544]
## Context 

+ Now that the team is switching over to Cloud.gov buildpacks rather than custom Docker Images, this is slightly less high priority than before because we won't be publishing a public Docker Image to Docker Hub
+ However, we are still using Docker for local development and CI/CD. Our current automated test setup requires the use of a Login.gov secret JWT token. So implementing this change would have some security benefits, and could also possibly help speed up our CI/CD builds. 

## Acceptance Criteria

+ [ ] `.dockerconfig` file added to backend repo with appropriate configuration to reduce Docker image size and protect against accidentally leaking secrets 
+ [ ] Backend developers have reviewed `.dockerconfig`, made any suggestions, and approve

**Comment by alexsoble** [comment]
## ACs

+ [ ] `.dockerconfig` file added to backend repo with appropriate configuration to reduce Docker image size and protect against accidentally leaking secrets 
+ [ ] Backend developers have reviewed `.dockerconfig`, made any suggestions, and approve

**Comment by amilash** [comment]
as per @abottoms-coder we can close this since its intent is covered in the Secret Key Epic: https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/972
