### ISSUE TITLE
As a user I need to log in (frontend)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#56]
AC:
- [x] A user can log in via login.gov (e.g. authentication)
- [x] The UI renders unauthenticated login/registration page before log in
- [x] The UI renders and authenticated page after log in 

 Tasks : 
- [x] Build the unauthenticated UI
- [x] ~~Make call to login.gov~~
- [x] ~~Handle callback ~~
- [ ] ~~verify state code~~
- [ ] ~~encrypt auth code and send to API~~
- [ ] ~~Receive tokenized version of the user info~~
- [ ] ~~Render authenticated UI~~
- [x] Redirect to backend `/login/oidc`
- [x] Handle backend's redirection to the UI by adding a "callback" component, that then dispatches an `auth_check` request to the backend, having received the `http_only` cookie on the frontend.
- [x] Receive user info, reduce into store, and render authenticated UI
- [x] verify login/logout python endpoints are committed on this branch
- [x] secure cookie (currently set to insecure, for testing purposes)
- [x] add an auth check endpoint on this branch for the python backend
- [x] actually hit the auth check endpoint with the frontend
- [x] test all the frontend components
- [x] deploy to cloud.gov and ensure the frontend url variable for dev and friends is set.

DoD:
- [ ]  minimum 90% code coverage test
- [ ] 0 linting errors and warnings
- [ ]  0 accessibility errors
- [ ]  deployed to a dev environment
- [ ]  all significant changes have been documented
- [ ]  free of high and medium security vulnerabilities

Resources: 
https://developers.login.gov/oidc/

**Comment by RafterGit** [comment]
Progress was blocked to confirm best practices were being implemented,  the following authentication flow will be used:

1.)  Frontend triggers the backend to Authenticate via Login.gov

2.)  The backend will redirect to the frontend as part of the final login.gov authentication step

3.)  From here the frontend will have an httpOnly cookie which it will use to make a secured api call for user info from the backend (which has already associated the httpOnly cookie with a user as part of the Login.gov step). 

4.)  The backend will then be able to use the  httpOnly cookie to find the  user and create a response for the userinfo

5.) Subsequent API calls to the backend will use steps 3 & 4 until the user closes their browser / logs out and the sessions are lost

**Comment by lfrohlich** [comment]
This was completed
