### ISSUE TITLE
[Design] Draft workshop artifacts to support Round 4 research

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#560]
Problem Statement:
Supports [#506](https://github.com/raft-tech/tanf-app/issues/506) by adding content concerning the STT user journey / user flow. This issue will deliver ST workshop mural board and facilitation guide that we will use to conduct the ST workshop planned for Feb 12.
Saved here: [Mural] (https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1613491508274/7cf6d22e727671899d3d1417c2b7e9505eee7f38)
AC: 
- [x] The problem we are trying to solve is clearly stated, as are questions we still have 
- [x] Facilitation guide accompanies ST workshop mural board 

Tasks
- [x] STT related journey map
- [x] STT related user flow
- [x] Problem framing section
- [x] Facilitation guide
- [x] Place journey map, user flow, and problem framing on mural board 

DD
- [x] Documentation: [Facilitation guide](https://hackmd.io/Ful-2KY9TAOjgATDvBchSQ) and [Mural board](https://app.mural.co/t/raft2792/m/raft2792/1611589331046/afcaddac81d3da8ebb0a81349da3939957608807) has been shared with the PO and team for feedback
- [x] @lfrohlich has reviewed and signed off

**Comment by jenewingpierce** [comment]
We are ready for a squishy look at #560 @lfrohlich we will continue refining, likely until the day of the workshop as is our way!

**Comment by jenewingpierce** [comment]
@dk-ui @reitermb sign off that this is ready to go

**Comment by kniz-raft** [comment]
Link to the workshop board: https://app.mural.co/t/raft2792/m/raft2792/1611589331046/afcaddac81d3da8ebb0a81349da3939957608807

**Comment by jenewingpierce** [comment]
@dk-ui can you add pictures and titles to the mural board for: 

Lauren Frolich, Kniz, Jennifer, yourselves, and Shubhi? thank you

**Comment by lfrohlich** [comment]
Have reviewed this and looked good
