### ISSUE TITLE
[Research] As an STT user I want to participate in research (Round 4/Sprints 13-15)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#561]
Description: 
This issue will deliver conducting and recording of Round 4 of research with STT participants. 

AC: 

- [x] All research sessions for round 4 are complete
- [x] Raw notes are stored securely

Tasks: 
 - [x] Finalize observers for each session
~~- [ ] Record Video if applicable~~ Workshop was not recorded
~~- [ ] Record verbatim notes in the notes template~~ Mural was used to document notes 
 ~~- [ ] Upload Raw notes to the secure folder in teams~~Stickies contain information STs wrote or shared during the workshop
 ~~- [ ] Legend is created to anonymize raw notes~~ No PII was stored in the stickies
 
Note: 
-

**Deliverables:**
- [ST Workshop Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1613491508274/7cf6d22e727671899d3d1417c2b7e9505eee7f380):lock: contains the raw notes from the ST workshop

**Comment by lfrohlich** [comment]
This is done
