### ISSUE TITLE
As a Tadpole, I want to know the difference between work states (accepted, delivered, submitted, proposed)

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#562]
Description:
This issue will deliver updating docs with agreed upon definitions for work states (accepted, delivered, submitted, proposed)

Acceptance Criteria:
- [x] Tasks below have been completed

Tasks
- [x] Update [Team Charter>Communication Tools](https://github.com/HHS/TANF-app/blob/main/docs/How-We-Work/team-charter/communication-tools.md)

Notes:

**Comment by alexsoble** [comment]
@kniz-raft Can we include "submitted" and "proposed" here too? In the context of "submitted for QASP review"?

**Comment by kniz-raft** [comment]
> @kniz-raft Can we include "submitted" and "proposed" here too? In the context of "submitted for QASP review"?

Yes! Will add

**Comment by alexsoble** [comment]
Thanks! Have a great weekend! 😄

**Comment by kniz-raft** [comment]
Based on what was submitted to the [mural board](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1611867245746/c353d0b7bc6b58ebc4ac9572ab3703c55da056b4), I'm suggesting the following:
Proposed: Development PR in Raft Review/document in draft, waiting to be reviewed
Submitted: Submitted for QASP review and AC review by Lauren/PO
~~Delivered~~: will no longer use
Accepted: Passed QASP review and issue closed or PR merged or if UX final

**Comment by kniz-raft** [comment]
https://github.com/HHS/TANF-app/pull/189
Has been merged in
