### ISSUE TITLE
As a dev, I want a README for the /scripts folder that describes what each script is for and how it is used in the CI process. 

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#573]
AC:
- [ ] @abottoms-coder has verified the documentation is adequate
- [ ] High-level and concise overview of each script explains their usage and importance

Tasks:
- [ ] In the scripts/ folder, create a markdown to document and explain each script present. 
- [ ] Each script has at least two sentences describing their utility and also a brief usage demo.

**Comment by amilash** [comment]
@abottoms-coder @jtwillis92 do we already have docs that cover this, and I can close?

**Comment by abottoms-coder** [comment]
I don't believe we do, no. This is probably a good idea to pay down technical debt, honestly.

**Comment by valcollignon** [comment]
@riatzukiza put hackmd link in this ticket

**Comment by riatzukiza** [comment]
https://hackmd.io/yHEsEgT1RkOTLw3z6wfwOQ

**Comment by ADPennington** [comment]
per 12/17 tech sync, decided to review #1437  without tabletop cc: @valcollignon @abottoms-coder @riatzukiza
