### ISSUE TITLE
As a Tadpole, I want to know what the Research Strategy is for this project

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#578]
Description:
Tasks to improve and document research strategy

AC:

- [x] The following tasks are complete.

Proposed Tasks:

Research Strategy Roadmap Updates
- [x] Add in 2 workshops, option for 3rd
- [x] Add clear deliverables for each step
- [x] R & D Strategy Roadmap is cross-referenced and integrated into Product Roadmap 
- [x] Design and Accessibility Review of artifact 

Items to deliver to PO
 - [x] Generic annotated hi-fi wire frame artifact

Round 4 Research Plan Revisions
- [x] Answer final comments from PO
- [x] Move schedule out of plan and into separate document to be referenced in plan
- [x] Designate length of time for the research plan in sprints
- [x] Final plan shared with team

DoD:
 - [x] Documentation: Submitted to QASP 
 - [x] @lfrohlich has reviewed and signed off

**Comment by jenewingpierce** [comment]
what form do you want final share to take? 

has the RP been integrated into the roadmap?

This is otherwise ready for QASP. 

(SHould we call these R & D Pathways, to not get mixed up with Roadmap?)

**Comment by jenewingpierce** [comment]
@mreiter and @dk-ui can you conduct a design and accessibility review of the STT Pathway to MVP
