### ISSUE TITLE
As a product owner, I want a POAM document for the ATO process

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#579]
Description:
for the MVP, we need to have a document for the SSP that includes controls in the POAM state. This document needs to be created and easily accessible by the team

AC:
- [x] Document is created and location shared with team

**Comment by rnafarrete** [comment]
POAM uploaded to Teams: https://teams.microsoft.com/l/file/375C3E5F-052B-40C9-A2CB-8ED752362CBC?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=xlsx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FSystem%20Security%20Plan%2FTANF-POAM-2021.xlsx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287

- deleted old poam items (left one row in for an example)
- this will be filled in conjunction with the security controls (as well as after the assessment should there be any findings)

**Comment by carltonsmith** [comment]
@kniz-raft Not sure why this is assigned to me, but I do see the file there

**Comment by lfrohlich** [comment]
This was done
