### ISSUE TITLE
Create two concept prototypes for user research discussions

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#58]
Description:
Data upload and view prototypes in a linear guided vs. single page form. 

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Use research synthesis from OFA and STT interviews to create two alternate version of prototype
- [ ] 

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by cmajel** [comment]
Adding this thought while it's in my head. I'm still unclear on what the difference would look like between this linear and single page approach. The idea though of generating concepts to share or co-create on with STTs does sound useful.

**Comment by lfrohlich** [comment]
OFA analyst interviews have suggested that more investigation is necessary before working on this.

**Comment by matthewjdoty** [comment]
@lfrohlich, this has been marked as a duplicate, can we close it?

**Comment by lfrohlich** [comment]
close because duplicate
