### ISSUE TITLE
AC-05: Separation of Duties

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#587]
AC:
- [x] Control implementation statement has been reviewed by Raft for technical accuracy
- [x] Control implementation statement has passed QASP review

DoD:
- [x] Control implementation statement has been documented in GitHub

**Control Description:**
The organization:
 a. Separates [at a minimum, data creation and control, software development and maintenance, and security functions];
 b. Documents separation of duties of individuals; and 
 c. Defines information system access authorizations to support separation of duties.

**Comment by rnafarrete** [comment]
- Updated AC-05 with feedback from the team
- will need to create a separate branch before creating the pull request.

**Comment by rnafarrete** [comment]
Updated based on comments/feedback from team.
