### ISSUE TITLE
AC-02(05): Account Management | Activity Logout

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#590]
AC:
- [x] Control implementation statement has been reviewed by Raft for technical accuracy
- [x] Control implementation statement has passed QASP review
DoD:
- [x] Control implementation statement has been documented in GitHub

**Control Description:**
The organization requires that users log out when [Assignment: organization-defined time-period of expected inactivity or description of when to log out].

AC-2 (5) Additional FedRAMP Requirements and Guidance:
Guidance: Should use a shorter timeframe than AC-12

**Comment by rnafarrete** [comment]
Updated implementation statement to include logout conditions/actions.
Attaching screenshots for the update.

![Screen Shot 2021-01-28 at 1.24.08 PM.png](https://images.zenhubusercontent.com/5fff08afd883b30c8b58dc71/ba523e01-03db-4498-b774-050c7b589502)

![Screen Shot 2021-01-28 at 1.43.47 PM.png](https://images.zenhubusercontent.com/5fff08afd883b30c8b58dc71/4cbd3f9c-2084-46c1-80d9-d3442f521023)

![Screen Shot 2021-01-28 at 1.47.19 PM.png](https://images.zenhubusercontent.com/5fff08afd883b30c8b58dc71/decb1847-597f-415a-939c-a2ea838f9711)

**Comment by lfrohlich** [comment]
This can be found here: https://github.com/HHS/TANF-app/blob/main/docs/controls/access-controls/AC-02(05).md
