### ISSUE TITLE
Usability Testing Strategy for post OFA MVP launch

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#592]
Description: Strategy to identify loose ends for OFA MVP

AC:

- [ ] Internal audit complete
- [ ] Annotations on OFA MVP prototype 
- [ ] Checklist for refinements to be done for MVP and refinements for later sprints, prioritized 
- [ ] Shared with team as appropriate

Proposed Tasks:

Research plan
- [x] Run a dev/design audit of deliverables and spec for OFA MVP 
- [x] Conduct round of internal user tests for insight on refinements and further testing strategies
- [ ] 

Documentation -
- [ ] Link to[ figma page](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4043%3A20688) with annotations and testing strategy
- [ ] Create user stories and other tickets to address items identified in the workshop

DoD:
 - [ ] All above tasks are completed 
 - [ ] @lfrohlich has reviewed and signed off

**Comment by jenewingpierce** [comment]
@lfrohlich is this sufficient? 

And grammarly has determined that the tone of this ticket is joyful. I'd like to aim for a joyful tone in everything I do. ;)

**Comment by jenewingpierce** [comment]
@mreiter do you have any deliverables from the internal user testing we conducted last week ready for squishy Raft Review?

**Comment by jenewingpierce** [comment]
@kniz-raft Will this go into next sprint? Or will it still make it into this sprint?

**Comment by kniz-raft** [comment]
> @kniz-raft Will this go into next sprint? Or will it still make it into this sprint?

Once it is refined and ready to go and if your team has capacity, feel free to bring it in to this sprint.

**Comment by reitermb** [comment]
> @reitermb do you have any deliverables from the internal user testing we conducted last week ready for squishy Raft Review?

Hoping to have those in a good place by EOD today

**Comment by jenewingpierce** [comment]
@reitermb was this ever completed?

**Comment by amilash** [comment]
Closing, as per @reitermb this is a dupe and done.
