### ISSUE TITLE
AC-02(07): Account Management | Role-based schemes

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#604]
AC:
- [x] Control implementation statement has been reviewed by Raft for technical accuracy
- [x] Control implementation statement has passed QASP review

DoD:
- [x] Control implementation statement has been documented in GitHub

**Control Description:**
The organization:
(a) Establishes and administers privileged user accounts in accordance with a role-based access scheme that organizes allowed information system access and privileges into roles;
(b) Monitors privileged role assignments; and
(c) Takes [Assignment: organization-defined actions] when privileged role assignments are no longer appropriate.

**Comment by lfrohlich** [comment]
Completed here: https://github.com/HHS/TANF-app/tree/main/docs/Security-Compliance/Security-Controls/ac-2-7
