### ISSUE TITLE
As a dev, I want an automated, documented CI process to provision Cloud.gov brokered services

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#609]
**Description:**

This project plans to use Cloud.gov-brokered S3 buckets for TANF data file storage (sensitive PII data) and for Django Admin static assets (public). (See boundary-diagram.md for more about how S3 fits within our architecture.)

In the current state, there are no scripts to provision and secure these S3 buckets and no dev documentation on to deploy them, secure them, and verify that they are configured correctly.

Additionally this same initial provisioning must be done for any additional services such as the RDS PostgreSQL service.

**Acceptance Criteria:** 

- [ ] When deployments are done by the CI pipeline a step is run to check if Cloud.gov brokered services are already set up and create them if not
- [ ] As a dev, I can run a script that automatically provisions the above referenced brokered services - this should be the same script or a close representation of what is done in CI.
- [ ] As a dev, I have access to documentation about how we secure and verify the security of our Cloud.gov-brokered S3 buckets, including:
  - encryption of data at rest and in transit
  - access controls
  - any other security settings and controls relevant to S3 provisioning 
- [ ] As a writer of security controls, I have access to documentation about how we secure and verify the security of our Cloud.gov-brokered S3 buckets, including all the categories mentioned above.

**Proposed Tasks:**
 - [ ] Create ADR outlining TerraForm solution

**Notes:**

The deploy script for this project (`./deploy-cloudgov-docker.sh`) deploys a frontend and backend app. To run, the backend app requires S3 bucket configuration.  

In its current state, a dev can use the deploy script to automatically deploy a frontend and backend app, but the backend will remain in a crashed state unless it is supplied with credentials for an associated Cloud.gov-brokered S3 bucket. 

This is a blocker for #521, "As a developer, I want a staging site and I want to know how to deploy to it", unless we decide to go for some kind of alternate, possibly hacky strategy for the vendor staging site for now, like having it share S3 buckets with the dev site. 

https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/521

This step should not overwrite any existing services

Make sure the databases exist before this is done since the apps rely on them

**Comment by jtwillis92** [comment]
Will update this comment with more info - but we should definitely look into using Terraform for this. Cloud.gov recommended this approach in a recent tech talk attended with @alexsoble and @ADPennington
