### ISSUE TITLE
As a user, I can log out from the UI (mostly frontend)

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#61]
Description:
(please define the reason as to why this issue is being created )

AC: 

- [x] User can log out with a button
- [x] UI blocks restricted views from logged out user

Tasks: 

- [ ] Add button to log out
- [ ] Hit API with logout request
- [ ] Handle successful logout from API
- [ ] Handle gracefully if API does not respond or is not available. 

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by lfrohlich** [comment]
This was completed
