### ISSUE TITLE
Create user research plan for OFA

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#62]
Description:
Create a user research plan to conduct next round of research (August 2020) with OFA. 

AC: 

- [x] Draft research plan is complete. 

Tasks: 

- [x] Create a draft research plan that addresses epics - Users can easily upload data and User can view uploads
- [x] List research goals
- [x] Determine method(s)
- [x] Develop recruitment criteria
- [x] Document ethics, privacy concerns
- [x] Draft expected outcome
- [x] Write interview guide
- [ ] Create email language template (regional staff)
- [x] Draft timeline

DoD: 
 - [x] Documentation: Draft research plan has been shared with the PO and team for feedback
 - [x] @cmajel has reviewed and signed off
 - [x] @lfrohlich has reviewed and signed off

**Comment by shubhi-raft** [comment]
@cmajel @lfrohlich Attached is the draft user research plan and conversation guide for your review. 

- [User Research Plan - OFA](https://app.zenhub.com/files/281707402/d5437f19-209a-4dbf-8085-694de5dfb46e/download)

- [Conversation Guide - OFA](https://app.zenhub.com/files/281707402/4be0b442-c023-4cf7-93e6-03124a7b721f/download)

**Comment by lfrohlich** [comment]
Thanks @shubhi-raft ! Lots of good questions in there and a solid plan.  @cmajel and I have added comments to both documents. @cmajel not sure if you are done reviewing.

**Comment by cmajel** [comment]
Yes, added my comments!

**Comment by shubhi-raft** [comment]
All tasks were complete except for 'Create email language template (regional staff)' since we did not include any regional staff in this round. Proposed comments in research plan and conversation guide have been incorporated.

**Comment by lfrohlich** [comment]
I took another look and made one comment about pain points for OFA analysts.

**Comment by cmajel** [comment]
@shubhi-raft @reitermb 

I see two things that are still missing:
* Clarification on roles during interviews (who moderates, who takes notes, who observes). This can be general (eg, Raft designer) but it is helpful to state who you expect to be involved in research (for example, other Raft team members may observe).
* A link to the prototype we are testing in the conversation guide. This will help us track over time what is tested, and helps the moderator run the interview.

With those two additions I'm good to go. 

And for next time:
* Thanks for incorporating some of the suggestions on the conversation guide. Some of the questions could still be written more clearly to give simpler, productive prompts to participants. I've added resources to our [UX Guide wiki](https://github.com/HHS/TANF-app/wiki/User-research-guide) for the next plan we work on. 
* For next time, research plans and assets should be reviewed by @lfrohlich before interviews begin.

**Comment by shubhi-raft** [comment]
@cmajel - Made the changes in #1 and #2. 

and, agreed on recommendations for the next time.

**Comment by cmajel** [comment]
@shubhi-raft I still don't see the prototype link that's shared with participants. Once it's added you can check off my review!

**Comment by shubhi-raft** [comment]
Ha! I just added it. I wonder if the word desktop version didn’t sync changes to the main version. Let me open and try again! 

--
Best,
Shubhi Mishra
HealthStar Informatics
1801 Old  Reston Avenue, Suite 102,
Reston, VA, 20190
301-395-6823
http://healthstarinfo.com/

**Comment by reitermb** [comment]
@cmajel Link added to the conversation guide as well now!

**Comment by lfrohlich** [comment]
these look good to me! thanks
