### ISSUE TITLE
[Research Facilitation] Concierge Test Sec 1 Error Guidance (v3.0 Pilot)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#626]
Description:
Drafts an approach/strategy for either concierge or wizard of oz testing concerning data validation errors. These methods present a potential way to tackle "How might we provide an STT user with clear and actionable errors?" in a real validation scenario. This would play a significant role in addressing knowledge gaps concerning the following roadmap stories:
- As a data prepper, I need to know why and where errors are happening so I can resolve them.
- As a data prepper, I need plain-language guidance on how to remedy errors, so I can fix them.
- As an OFA analyst, I can see the validation errors for a file so that I can help the data prepper troubleshoot.

We put testing plans in place early in the process of designing so that we have a structure for the insights that we gather in the workshop. 

AC:
- [x] Concierge or Wizard of Oz testing strategy is documented

Tasks:
- [x] Session 1, 1/5/2023 - Tribe
- [x] Session 2, 1/5/2023 - Tribe
- [x] Session 3, 1/6/2023 - State
- [x] Session 4, 1/9/2023 - State
- [x] Session 5, 1/10/2023 - Tribe - No Show
- [x] Session 6 , 1/11/2023 - Tribe
- [x] Session dropin 1/12/2023 - State
- [x] Session 7, 1/13/2023, State - Cancelled

Documentation
- Mural

**Comment by jenewingpierce** [comment]
@reitermb can I get an estimate on when this is ready for raft review?

**Comment by amilash** [comment]
@reitermb @dk-ui  This ticket now seems like a duplicate I can close. What do you think?

**Comment by amilash** [comment]
@dk-ui feel free to factor this into your research plan and or close this.

**Comment by stevenino** [comment]
The recruiting scope that was originally a part of this tix was spun out into #2184
