### ISSUE TITLE
[SPIKE] Adding quarters to upload process

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#627]
Time box: 60 minutes
What tasks would be needed and how big of a lift would it be to allow users to select year and quarter as part of the report upload process?

AC:
- [x] Documented list of tasks needed with estimates in a zenhub issue #738

Mockups to be attached and/or developed - not sure if what we had previously will work or not

**Comment by jenewingpierce** [comment]
https://hackmd.io/EuOE7k4rTQ64nDKIkPCZcw

**Comment by jenewingpierce** [comment]
@kniz-raft can you clarify if anything else is needed from me here?

**Comment by kniz-raft** [comment]
@jenewingpierce I don't think so, I removed you from the ticket.

**Comment by lfrohlich** [comment]
THis is complete
