### ISSUE TITLE
[SPIKE] Options for limited release/user sign up

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#629]
Timebox: up to 3 hours
When we release, we might have fake/invalid accounts being created to access our system, what are our options to prevent/minimize that from happening? What can we do now with a smaller audience vs. what do we do with a bigger audience? Try to keep rework to a minimum

AC:
- [ ] Documented ideas with estimates of time to implement in a zenhub issue

**Comment by abottoms-coder** [comment]
Previous ideas:
1. Exhaustive bucket of email domains to automatically check against (e.g., *@acf.hhs.gov, *@florida.gov)
2. Approved-list of STT user emails given by Regional/OFA (e.g., jsmith@florida.gov as approved by Southeast Manager aka Region 4 Manager)

**Comment by valcollignon** [comment]
@lfrohlich to talk to regional staff about this

**Comment by stevenino** [comment]
Closed as OBE per backlog refinement on 7/12/22
