### ISSUE TITLE
AU-02: Auditable Events

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#632]
**Note**
This might be inherited from cloud.gov. If so, this wouldn't need to be documented in github. 

AC:
- [ ] Control implementation statement has been reviewed by Raft for technical accuracy
- [ ] Control implementation statement has passed QASP review

DoD:
- [ ] Control implementation statement has been documented in GitHub

**Control Description:**
The organization:
a. Determines that the information system is capable of auditing the following events: [i. The following events must be identified within server audit logs: 
• Server startup and shutdown;
• Loading and unloading of services;
• Installation and removal of software;
• System alerts and error messages;
• User logon and logoff;
• System administration activities;
• Accesses to sensitive information, files, and systems
• Account creation, modification, or deletion;
• Modifications of privileges and access controls; and,
• Additional security-related events, as required by the System Owner (SO) or to support the nature of the supported business and applications.
ii. The following events must be identified within application and database audit logs:
• Modifications to the application;
• Application alerts and error messages;
• User logon and logoff;
• System administration activities;
• Accesses to information and files
• Account creation, modification, or deletion; and,
• Modifications of privileges and access controls.
iii. The following events must be identified within network device (e.g., router, firewall, switch, wireless access point) audit logs:
• Device startup and shutdown;
• Administrator logon and logoff;
• Configuration changes;
• Account creation, modification, or deletion;
• Modifications of privileges and access controls; and,
• System alerts and error messages.];
b. Coordinates the security audit function with other organizational entities requiring audit-related information to enhance mutual support and to help guide the selection of auditable events;
c. Provides a rationale for why the auditable events are deemed to be adequate to support after-the-fact investigations of security incidents; and
d. Determines that the following events are to be audited within the information system: [Unsuccessful log-on attempts that result in a locked account/node;  Configuration changes;  Application alerts and error messages; System administration activities; Modification of privileges and access; and Account creation, modification, or deletion].

For CSP Only
AU-2 (a) [Successful and unsuccessful account logon events, account management events, object access, policy change, privilege functions, process tracking, and system events For Web applications: all administrator activity, authentication checks, authorization checks, data deletions, data access, data changes, and permission changes]
AU-2 (d) [organization-defined subset of the auditable events defined in AU-2 a to be audited continually for each identified event]

AU-2 Additional FedRAMP Requirements and Guidance: 
Requirement: Coordination between service provider and consumer shall be documented and accepted by the JAB/AO.

**Comment by lfrohlich** [comment]
This was completed: https://github.com/HHS/TANF-app/tree/main/docs/Security-Compliance/Security-Controls/au-2
