### ISSUE TITLE
[SPIKE] Investigate using CircleCI to build Docker images

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#637]
**Description:**
In support of https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/635, see if using CircleCI to build Docker images (eliminating the need for DockerHub) is possible.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] A determination if using CircleCI to build Docker images is possible

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Research feasibility of using CircleCI to build Docker images

**Comment by lfrohlich** [comment]
This is moot, DockerHub or another registry is required for Docker based deploys
