### ISSUE TITLE
As a dev, I need to know which authentication service we're using (login.gov vs. NextGen XMS)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#638]
Lauren needs to review guidance from OCIO and make a decision

**Comment by kniz-raft** [comment]
Blocked waiting for memo to be released

**Comment by lfrohlich** [comment]
Got confirmation from Tijan 3/25 that we can move ahead with login.gov through ATO, and decide to implement NextGen XMS later if we decide to.

**Comment by kniz-raft** [comment]
For ATO, we are going forward with login.gov; but this should be discussed for another release

**Comment by amilash** [comment]
Pending documents from Next Gen XMS team so feasibility can be assessed then product can make a decision. Application for document sent to Next Gen team ~6/21ish.

**Comment by amilash** [comment]
@lfrohlich are we decided to move forward with NextGen, or is this still in progress?

**Comment by lfrohlich** [comment]
PLannign to implement NextGen XMS (straightforward integration) and  ACF AMS
