### ISSUE TITLE
As a user, I can view a placeholder page that is only tied to my role

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#64]
Description:
This issue will deliver OFA admin or test users acting as STT being able to view a placeholder page that is only associated with their role.  

AC: 
- [ ] Authenticated user views a placeholder page with their email address and assigned role

Frontend
- [ ] Add user role text with dynamic role (e.g. "Hi, you're a data prepper!" or Hi, you're an OFA Admin!")
- [ ] Add card with role information
- [ ] Add tests to cover

Open Questions:
- What roles are going to be populated based for OFA MVP?
   -  STT user (Test user) and OFA Admiin
- What security controls does this impact? @carltonsmith to add

Note:
- One page that will be dynamically served based on the role.
- Signed out button is not needed since user can sign out top right hand side of the page. 

Supporting Documentation:
![Screen Shot 2020-10-20 at 8.38.23 PM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/6b25b4fa-8a0d-43fe-87e0-f1915231fe33)

**Comment by kniz-raft** [comment]
Could this be covered by #530?

**Comment by lfrohlich** [comment]
we've discussed that this user story could be taken care of by the combo box and/or an Admin should see the Admin tab, whereas a user would only see reports @kniz-raft

**Comment by kniz-raft** [comment]
Yes, I remember that conversation. Did you want to wait until that story (#530) is complete before closing this one? We can just punt this back to the backlog for the time being.

**Comment by lfrohlich** [comment]
duplicate of #530
