### ISSUE TITLE
As a TDP user, I want to see a picture that better represents the program on the homepage

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#640]
Description:
The current picture on the TDP app does not meet TANF expectations and needs to be modified. From Lauren: For TANF, we usually look for images with families or people at work. It could also be a caseworker helping someone look for work, or something like that. 

Tasks:

- [x] Design provides new image to PO to approve
- [x] Purchase images for use
- [x] Upload them on HHS sharepoint
- [ ] PO or design, gets input from Regional Managers on image pics
- [ ] Dev updates image on front page with approved image

AC:

- [ ] New image shows on TDP home page

DoD:

- [x] @lfrohlich reviews and approves

References: 
[ACF Digital Toolbox - Images](https://www.acf.hhs.gov/digital-toolbox/visuals/images)

**Comment by kniz-raft** [comment]
@lfrohlich can you help Dmitri find a picture?

**Comment by kniz-raft** [comment]
ACF images do not have anything that is appropriate for our use. Can we use a free stock image? If we need to buy one, we can charge back to ODC.

**Comment by lfrohlich** [comment]
![Social Services Worker consulting with mother and infant (1).jpg](https://images.zenhubusercontent.com/5f19ca7a632be8361aab1300/1a97e5da-2dc2-45ff-a885-3998ecdba485)

**Comment by ADPennington** [comment]
i like it! maybe a grid of photos like this to highlight diversity? or a slideshow photos so users have a chance to see something different when they visit?

**Comment by lfrohlich** [comment]
I like that idea @ADPennington ! Maybe we have one more relevant image in the interim and plan to add a slideshow

**Comment by jorgegonzalez** [comment]
Do we have another image for a slideshow yet or are we proceeding with the one Lauren linked first?

**Comment by amilash** [comment]
@dk-ui @reitermb  Can you provide a few?
- Also can you link the approved sources to look from? (What are they?)

**Comment by lfrohlich** [comment]
ACF has a very limited stock photo bank but Raft can use whichever service they like and charge it as ODC.

**Comment by sreedevip** [comment]
@lfrohlich @reitermb @ADPennington a few suggestions for pictures for the homepage. If any of these look appropriate, I can ensure those pictures (or similar ones) meet the quality guidelines set in the [ACF Digital Toolbox](https://www.acf.hhs.gov/digital-toolbox/visuals/images)
[Image of Caseworker](https://www.shutterstock.com/image-photo/female-case-worker-visiting-woman-adopted-1857973948?id=1857973948&irclickid=0z%3AX%3AU0IdxyIW%3A%3Az-U1k-y9GUkBTDo21TwSawQ0&irgwc=1&utm_medium=Affiliate&utm_campaign=Elevated%20Logic%2C%20LLC&utm_source=426523&utm_term=STOCKSNAP_SEARCH-AUTHENTIC_API&c3ch=Affiliate&c3nid=IR-426523)
[Image of Dad & daughter](https://images.unsplash.com/photo-1580377968103-84cadc052dc7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80)
[Image of Mom & daughter](https://unsplash.com/photos/G_acucnTJNw)
[Image of hands & paper cut-out of a family](https://www.istockphoto.com/photo/adult-and-children-hands-holding-paper-family-cutout-family-home-foster-care-gm1169660432-323425859?utm_source=pixabay&utm_medium=affiliate&utm_campaign=SRP_image_sponsored&referrer_url=http%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fwelfare%2520family%2F&utm_term=welfare%20family)
[Image of caseworker 2](https://www.shutterstock.com/image-photo/social-worker-asks-questions-parents-child-1553472626?id=1553472626&irclickid=0z%3AX%3AU0IdxyIW%3A%3Az-U1k-y9GUkBTDvxNTwSawQ0&irgwc=1&utm_medium=Affiliate&utm_campaign=Elevated%20Logic%2C%20LLC&utm_source=426523&utm_term=STOCKSNAP_SEARCH-AUTHENTIC_API&c3ch=Affiliate&c3nid=IR-426523)

**Comment by sreedevip** [comment]
![Benji Aird Unsplash.jpg](https://images.zenhubusercontent.com/6128e5cc49cc434013953e35/0401e375-a8da-47e1-be9b-c15eb06de806)

**Comment by sreedevip** [comment]
@lfrohlich @ADPennington @reitermb 

A few more picture suggestions based on work and education programs

Community College pics
[Student attending class](https://www.shutterstock.com/image-photo/side-view-group-multiethnic-students-lecture-145685453)
[Students' group discussion](https://www.shutterstock.com/image-photo/educational-institution-friend-learning-school-concept-412520623)
[Adult Education classroom](https://www.shutterstock.com/image-photo/group-multiethnic-students-listening-speaker-190882643)
[Adult education session](https://unsplash.com/photos/oc_XTqWezp4)

Apprenticeship
[Carpentry apprentice](https://www.shutterstock.com/image-photo/multicultural-team-workshop-assembling-hand-built-1721658571)
[Engineering apprentice](https://www.shutterstock.com/image-photo/engineer-showing-female-teenage-apprentice-how-760415896)
[Auto mechanic apprentices] (https://www.shutterstock.com/image-photo/engineer-showing-female-teenage-apprentice-how-760415896)
[Auto mechanic trainee](https://www.shutterstock.com/image-photo/mechanic-male-trainee-working-underneath-car-531128755)

**Comment by lfrohlich** [comment]
Thanks @sreedevip ! Do we know how many pictures we should aim for to cycle through? The caseworker pics are on a good track but the setting is a bit off -- TANF meetings would be in an office instead of home/counseling settings. The current examples seem more like child welfare. The apprenticeship pics are also on a good track, but most TANF recipients are women :). I'm definitely overthinking this. So far, I'm leaning towards: 
1. this one you shared: https://www.shutterstock.com/image-photo/engineer-showing-female-teenage-apprentice-how-760415896
2. either the first pic I posted or this one: https://www.istockphoto.com/photo/young-mother-with-support-worker-gm1134045110-301207869
3. and maybe another family one like this? https://www.shutterstock.com/image-photo/happy-hispanic-people-parents-giving-children-139768567

**Comment by abottoms-coder** [comment]
@abottoms-coder Write a follow-on frontend-dev spike ticket that decides how to host image(s) used on landing page as well as "flipping the switch" for utilizing new image(s).

There are some prerequisite tasks such as buying image, etc.

**Comment by sreedevip** [comment]
@lfrohlich some info on pricing on the images: 

1.  https://www.shutterstock.com/image-photo/engineer-showing-female-teenage-apprentice-how-760415896 
2. either the first pic I posted or this one: https://www.istockphoto.com/photo/young-mother-with-support-worker-gm1134045110-301207869
3. and maybe another family one like this? https://www.shutterstock.com/image-photo/happy-hispanic-people-parents-giving-children-139768567

Images 1 & 3 above Shutterstock images - here's a link to their single and multiple users pricing plans https://www.shutterstock.com/pricing

Image 2 is from iStock and has a one-time purchase price of $33

Look forward to hearing your takes on purchase options. Thanks

**Comment by lfrohlich** [comment]
Thanks @sreedevip ! For shutterstock, let's go with the $49 5-pack standard license for now. For #2, before we buy the one from iStock lets just use the one I posted above from ACF's image library, since we already have the license for that!

**Comment by lfrohlich** [comment]
Awesome, thanks @sreedevip !

**Comment by lfrohlich** [comment]
Punting on RO feedback, Dev ticket #1330
