### ISSUE TITLE
As a user I can log out (backend)

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#65]
Description:
Users need to be logged out and the session destroyed on the back end when they click a logout button on the front end.

AC: 
- [ ] User can only see open content after logout

Tasks: 
- [ ] Create endpoint to log user out
- [x] Destroy user session/cookie at logout
- [x] Return success message to front end

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by lfrohlich** [comment]
This was completed
