### ISSUE TITLE
[Design] As a new TDP user I want a well organized first experience of TDP and insight into the status of my access

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#653]
User Stories:
As a new TDP user I want to see an indication of my pending access request when I visit my profile
As a new TDP user I don’t want to be confused by blank pages or navigation items that lead to content I can’t access.

AC: 
- [x] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, implementation notes are documented alongside mockups, etc.) 
- [x] Profile screens provide insight into the status of a pending access request
   - [ ] Profile screens are based off of a template that can serve all combinations of Access Request status/auth method
- [x] Documentation exists to support development of a new user experience which makes logical sense, i.e:
   - [x] Any page that's visible in the nav bar should be within the users' _current_ permissions (e.g. If you don’t have a role you don’t get the ‘Data Files’ or ‘Admin’ nav items—If you haven’t requested access yet then you shouldn’t see ‘Profile’)
   - [x] “Welcome” page should be renamed “Home”
   - [ ] Access request form should exist on “Home”, not “Profile”.
   - [x] Users should only submit request access form ONCE. Once submitted, their homepage content should be the status message confirming that they requested access. Once granted access, their homepage content should reflect their role/permissions in TDP.
   - [x] Once a request for access has been submitted, users should have access to their profile page

Tasks:
- [x] Sync with dev to determine documentation spec & ticketing gaps necessary for implementing the above AC in TDP
   - [x] Update docs/tickets/mockups to fill gaps—apply Usable Design AC to any follow-on design tickets created (update flow)
- [x] Update user profile mockup to illustrate what a user with a pending request for access sees
- [x] Update user profile management flow

DoD:
- [x] Documentation: Designs and related tickets & other documentation have been shared with the PO and team for feedback [Figma Link](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=5892%3A48657)
- [x] @lfrohlich has reviewed and signed off

**Comment by reitermb** [comment]
@ADPennington @lfrohlich — Added the figma link to the DoD, should be all set for comments/review!

**Comment by lfrohlich** [comment]
Added a question about roles

**Comment by valcollignon** [comment]
Demo by @reitermb 12.7.21

**Comment by reitermb** [comment]
@reitermb test

**Comment by lfrohlich** [comment]
this is complete

**Comment by reitermb** [comment]
https://user-images.githubusercontent.com/28515874/146063268-290ae9d2-9fd9-4db8-96cd-a7dae9169972.mp4

**Comment by reitermb** [comment]
![image](https://user-images.githubusercontent.com/28515874/146063861-57a9de59-8741-4517-8955-64138c470685.png)
