### ISSUE TITLE
AC-07 Unsuccessful Login Attempts

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#656]
AC:
- [x] Control implementation statement has been reviewed by Raft for technical accuracy
- [x] Control implementation statement has passed QASP review

DoD:
- [x] Control implementation statement has been documented in GitHub

**Control Description:**
The information system:
a. Enforces a limit of [five (5)] consecutive invalid logon attempts by a user during a [120-minute time period]; and
b. Automatically [locks the account and delays the next logon prompt for 15 minutes or until released by an administrator] when the maximum number of unsuccessful attempts is exceeded.

For CSP Only
AC-7(a) [not more than three]
 [fifteen minutes] 
AC-7(b) [locks the account/node for thirty minutes]

**Comment by lfrohlich** [comment]
Merged
