### ISSUE TITLE
[Usability Testing] OFA MVP Annotated Mockup (Prototype Concept) Upload/Download

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#661]
Description:
This issue will deliver findings that could be incorporated into the OFA MVP design prototype for uploading and downloading TANF files. 

AC:
- [x] Results and design rationale for proposed changes are presented to PO

Proposed Tasks:
- [x] Define a plan for how we will do the test
- [x] Complete the usability test 
- [x] Synthesize the findings and document them in the mural  or figma
- [x] Review feasibility with Tech Lead
- [ ] ~~Verify that the ACF color palette is being used in the figma prototype~~ _removing this task since this changed to be a lo-fi deliverable. Higher fidelity deliverables will be in the appropriate color palette_

Deliverables:
Proposal for changes based on usability test (synthesis): https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=3873%3A0
Annotated Mockups with proposed changes shown in mockups: https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=3588%3A800

DoD:
 - [x] @lfrohlich has reviewed and signed off

**Comment by dk-ui** [comment]
@jenewingpierce and @shubhi-raft ready for raft review

**Comment by shubhi-raft** [comment]
#671 follows this for making updates to the UI and delivering prototypes.

**Comment by kniz-raft** [comment]
Notation: changed title to better reflect the deliverable - a lower fidelity mock up that was reviewed with the PO on Friday 2/26.

**Comment by lfrohlich** [comment]
@dk-ui  can you add the link to the annotated mock up to the issue description? Thanks!

**Comment by dk-ui** [comment]
@lfrohlich I added the original proposal with the proposed changes not shown in the mockups and I added a link to the annotated mockups with the proposed changes shown in the mockups for easier viewing as per our discussions last week.

**Comment by lfrohlich** [comment]
Added comment about FY Quarters for dev ready mockup. Looks good to me!
