### ISSUE TITLE
Create Tribe Workshop Mural Placeholder 

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#665]
Description: This issue will deliver a Mural board which we will use for the facilitation of the Tribe STT-MVP User Flow Workshop 

AC:
- [x] Mural Board as Facilitation Guide 

Tasks
- [x] Tribe related journey map
- [x] Tribe related user flow
- [x] Problem framing section
- [x] Place journey map, user flow, and problem framing on mural board 

DD
- [ ] Documentation:  [Mural board]() has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by jenewingpierce** [comment]
@kniz-raft this was completed #746

**Comment by amilash** [comment]
Closing as duplicate
