### ISSUE TITLE
As a Researcher, I would like to have a plan for recruiting and scheduling STTs for upcoming workshops

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#667]
Description:  This issue will deliver a planning strategy and calendar for research rounds 5-7 (and beyond, possibly). 

AC:

- [x] Planning strategy and calendar are documented. 

Proposed Tasks:
- [x] Schedule a meeting with Lauren to determine strategy and cadence for at least the next 4-5 workshops
- [x] Incorporate lessons learned from previous workshops into this plan

DoD:
 - [x] Documentation: Planning strategy and calendar are documented in the Teams OneNote
 - [x] @lfrohlich has reviewed and signed off

**Comment by jenewingpierce** [comment]
@reitermb @kniz-raft please refine for backlog tomorrow

**Comment by kniz-raft** [comment]
@reitermb I refined a little, please take a look and add anything else of value.

**Comment by jenewingpierce** [comment]
@kniz-raft I think this is now blocked by the regional managers meeting?  Holler if you agree.

**Comment by jenewingpierce** [comment]
I'd like to have a team sync around this schedule---the topics for these sessions are just initial very hypothetical PROPOSALS but I need to sync with @lfrohlich @shubhi-raft and @kniz-raft about this and other timelines.  The user groups and the type of user session will be a constant.  I'd also like to have an internal sync about the roadmap concerning this.  

Safe to say the dates, user groups, and types of sessions will be utilized regardless of what the content of them are and can be put out for recruiting purposes.

@lfrohlich i say recruit for both times and if we do two workshops with two user groups in one sprint all the better, with the hopes of filling at least one session in the sprints where they are planned. 

Happy to sync on this.

**Comment by jenewingpierce** [comment]
Also @kniz-raft I can ticket these when it's past QASP

**Comment by lfrohlich** [comment]
Looks good! Two minor things: Of the three tribal workshop holds, is the idea to offer three times and plan on two? A
It would be helpful if you could note which sprints are planning sprints or which round of research they will pertain too. Thanks! @jenewingpierce

**Comment by shubhi-raft** [comment]
#747 created for tribal workshop scheduling.

**Comment by lfrohlich** [comment]
This is complete
