### ISSUE TITLE
Draft Research Plan for Round 5 (Sprints 16-18) 

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#668]
Description:
This ticket will deliver a research plan for sprints 16-18 and will be in alignment with the established R&D pathway. Focusing on Tribe workshop and another ST workshop. For this round of research we plan to run an internal workshop (PO invited) to plan the research strategy for the next three sprints, which will include tribes and other ST workshops.  

AC:

- [x] Research Plan Workshop Mural board is presented to PO

Proposed Tasks:
- [x] Collaborative research workshop 
- [x] Present completed plan to PO for validation

DoD:
 - [x] Documentation: Research plan has been shared with the PO and team for feedback
 - [x] @lfrohlich has reviewed and signed off

Deliverables: 
[Mural board research plan](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1615833934656/565301228299949b5e68eee82e0bd48fbb882883) :lock:

**Comment by jenewingpierce** [comment]
@kniz-raft @reitermb  please refine by backlog refinement

**Comment by kniz-raft** [comment]
@reitermb @jenewingpierce I refined, main thing was removing the concept of draft (I think that was confusing for round 4 because we never really knew when it was done) and suggested a task of collaborating earlier and more often with Lauren to make sure everyone is on the same page.

**Comment by kniz-raft** [comment]
Moving this out of current sprint and into next sprint due to priority change
@lfrohlich @jenewingpierce

**Comment by kniz-raft** [comment]
@reitermb @jenewingpierce updated AC and Tasks to better align with what we did, please review and move when ready.

**Comment by lfrohlich** [comment]
Can you move the Mural to OFA and link to it here?
