### ISSUE TITLE
Research Synthesis for Round 4 (Sprints 13-15)

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#669]
Description:
This ticket will deliver a documented synthesis for all the research conducted within round 4 (sprints 13-15) and any other relevant unsynthesized research.

AC:

- [x] Synthesis has been documented in a doc

Proposed Tasks:

- [x] Gather all notes
- [x] Deidentify data
- [x] Perform topline synthesis
- [x] Document synthesis - Scope (research goal(s)), High-level findings, Actionable learnings, Issues that have to be added to Zenhub, Takeways for future research

Documentation -
- [x] Draft for review is [here](https://hackmd.io/@jepierce/S1QvhpqMd/edit)
- [x] Document synthesis in Code<> docs.

DoD:
 - [x] Documentation: Research synthesis has been documented in Code<>docs and shared with PO and team
 - [x] @lfrohlich has reviewed and signed off

**Comment by jenewingpierce** [comment]
@kniz-raft @reitermb please refine by backlog refinement

**Comment by kniz-raft** [comment]
@reitermb I did a refinement on it, please take a look too.

**Comment by kniz-raft** [comment]
#492 and ST Workshop

**Comment by jenewingpierce** [comment]
ready for QASP---

https://hackmd.io/@jepierce/S1QvhpqMd/edit

**Comment by lfrohlich** [comment]
Reviewed and added comments. One additional thought: I don't think we have fully explored whether there is a role and different persona for STT program managers in the system. This may be a later area of investigation, in which case we should note it as an open question before closing the door on multiple personas (or we should specify that we only think there is one persona for this role).

**Comment by jenewingpierce** [comment]
This is a great point.  Can I note it in our research plan or do you want me to add it to the synthesis?

**Comment by lfrohlich** [comment]
@jenewingpierce It depends on whether you're talking about one persona for data analysts, or one persona for all STT users. Either way I think it would be helpful to clarify in the first bullet under Immediate Next Steps. If the latter, you could add "or is there a need for another management persona?"

**Comment by jenewingpierce** [comment]
@lfrohlich ok let me think about the best way to mark this so it becomes actionable.

**Comment by lfrohlich** [comment]
@jenewingpierce  your understanding of STT user/data analyst/program manager is generally correct. STT program managers would be higher level -- not necessarily responsible for submitting data but would want potentially want a dashboard view (much later in the roadmap). I think we're on the same page about this after our most recent discussion

**Comment by lfrohlich** [comment]
Thanks for resolving the comments -- this is good to go into docs
