### ISSUE TITLE
[Design] OFA MVP Clickable Prototype for Upload/Download

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#671]
Problem Statement:
Questions:
This is a follow-on to #661

AC: 
- [x] Mockups have been delivered and refined to the point of all changes recorded during this sprint. 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [x] The design is usable, meaning... 
   - [x] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [x] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [x] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [x] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [x] Share design rationale for recommending UI changes
- [x] Make updates and share w/ team
- [x] Ensure that prototype is dev ready (e.g. behavior is documented, pertinent notes for a11y, potential error messages and other departures from the "happy path" are designed)

Deliverables
https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4124%3A0

DD
- [x] Documentation: Design has been shared with the PO and team for feedback
- [x] @lfrohlich has reviewed and signed off

**Comment by kniz-raft** [comment]
Moving this into current sprint due to a change in priority
@lfrohlich @jenewingpierce

**Comment by jenewingpierce** [comment]
@reitermb just noting here that we have an accessibility task here.

**Comment by jenewingpierce** [comment]
Updating on progress on this ticket: 

A full functionality list will be delivered on Friday, which we will share with @lfrohlich and @kniz-raft and @shubhi-raft for validation. 

Once that is signed off on the visual designer will prepare the complete prototype for delivery at the end of the sprint.

**Comment by jenewingpierce** [comment]
Noting that I have changed this ticket to reflect the PO request for updated annotated mockups in place of a dev ready prototype to adjust for spec refinements initiated by Design Lead, PM, and PO. @dk-ui @reitermb

**Comment by dk-ui** [comment]
@jenewingpierce annotated mockup link has been added to description

**Comment by kniz-raft** [comment]
Moving to QASP based on our conversation today

**Comment by kniz-raft** [comment]
THis will be delivered after 661

**Comment by lfrohlich** [comment]
This is approved! Thanks for all of the great work! @reitermb  @dk-ui
