### ISSUE TITLE
As OFA regional/tribal TANF staff, I would like to be made aware of and provide feedback into the TDP research pathway

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#672]
Description: To have an agenda and time scheduled with the Regional Managers and Staff the covers the research pathway, gathers feedback and inputs, and next steps.

AC:

- [x] Final agenda for the meeting
- [x] Meeting scheduled (2/25)

Proposed Tasks

- [x] Create [mural board](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1614628817099/a7ffd7a8ddaa3baa0581bce2cbf53cc57d1ec4bb) to use during the meeting

DOD:

- [x] reviewed and signed off by @lfrohlich

**Comment by jenewingpierce** [comment]
@lfrohlich is the summary you delivered adequate or do you need something more flushed out from us?

**Comment by lfrohlich** [comment]
Rough agenda from Kati: 
- Review the research pathway (what we're doing, how we're doing it, why we're doing it)
 - Interactive section (ideas below) -- How do we connect with users? -- What pain points do you have
 - What happens next (what to expect after this meeting)

**Comment by kniz-raft** [comment]
@jenewingpierce I put this into Raft Review - please move into QASP when it's ready

**Comment by lfrohlich** [comment]
This is done
