### ISSUE TITLE
As a user, I would like to be able to navigate according to my environment

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#673]
**Description:**
Right now we don't have a way to add environment variables for different environments on the frontend. We need to add separate Dockerfile files per environment to alleviate this issue.

By doing so we will enable automated CI deployments for distinct Cloud.gov environments, specifically for `Vendor Staging` with this iteration. 

**Acceptance Criteria:** 

- [x] Dockerfiles for development and vendor-staging environments added
- [x] Dockerfiles include the appropriate values for the Backend URL
- [ ] Remove ` && echo "REACT_APP_BACKEND_URL=https://tdp-backend.app.cloud.gov/v1" >> .env.production` from `~/tdrs-frontend/Dockerfile.dev`
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Comment by lfrohlich** [comment]
Can someone add something to the description about what this does practically? (e.g. CI/CD  for staging site) @jtwillis92  @carltonsmith  @alexsoble

**Comment by jtwillis92** [comment]
> Can someone add something to the description about what this does practically? (e.g. CI/CD for staging site) @jtwillis92 @carltonsmith @alexsoble

@lfrohlich updated! This work unblocks progress on the staging site.
