### ISSUE TITLE
[SPIKE] Pro/Cons for moving to a single repo

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#674]
Problems have arisen as a result of working from both the main government repo and the forked raft repo. A recommendation is needed for how we might change our workflow to resolve those issues.

Timebox: 4 hours

AC:
- [x] A pull request is issued with an ADR with a recommendation on how these issues might be resolved.
- [x] Existing documentation is updated accordingly to reflect new decisions

Proposed Tasks:
- [x] Meeting with Raft, 18F and OFA to discuss potential solutions
- [x] Document proposed solution with an ADR pull request
- [x] Review existing HHS PRs to make sure there is a corresponding Raft-tech PR before the HHS one is closed

**Comment by lfrohlich** [comment]
The new workflow was discussed and documented here: https://github.com/HHS/TANF-app/blob/main/docs/Architecture%20Decision%20Record/009-git-workflow.md
