### ISSUE TITLE
IA-08: IDENTIFICATION AND AUTHENTICATION (NON-ORGANIZATIONAL USERS)

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#712]
AC:
- [x] Control implementation statement has been reviewed by Raft for technical accuracy
- [x] Control implementation statement has passed QASP review

DoD:
- [x] Control implementation statement has been documented in GitHub

**Control Description:**
The information system uniquely identifies and authenticates non-organizational users (or processes acting on behalf of non-organizational users).

*Note from Romelo*
IA-8 should be inherited from login.gov.  The only thing to check with this is if Data Preppers (STTs) are considered part of the organization.  If they are then, this can simply be documented as "N/A - All users of the TDP application are organizational users.  There are no external or non-organizational users of the TDP application"

**Comment by lfrohlich** [comment]
Merged 4/2/21
