### ISSUE TITLE
As a dev/Tech Lead, I want to have automated deploys to production

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#724]
For context, see https://github.com/raft-tech/TANF-app/issues/721#issue-819093118.

**Tasks:**

+ [ ] Configure HHS CircleCI jobs to deploy to the production space
  + Will CircleCI contexts be helpful to us here, to distinguish the Raft CircleCI from the HHS CircleCI?https://circleci.com/docs/2.0/contexts/
+ [ ] Deploy latest code to production space using CircleCI automated deploy

Note that this is one ticket within a larger Epic, further work will be needed to have a functional and secure prod site.

**Comment by ADPennington** [comment]
can this be closed @alexsoble?

**Comment by alexsoble** [comment]
See https://github.com/raft-tech/TANF-app/issues/723#issuecomment-822477180

**Comment by ADPennington** [comment]
Let's recycle for prod.

**Comment by alexsoble** [comment]
@ADPennington Recycled this into a ticket for setting up the prod space & simplified

**Comment by amilash** [comment]
Duplicate of #895 closing.
