### ISSUE TITLE
As a Regional Manager and OFA Staff Member, I want to know how I can help solicit STT engagement

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#729]
Description:

AC:

- [ ] Email has been submitted to Lauren 

Proposed Tasks:

- [ ] Create a draft email recapitulating the RO & OFA Regional Workshop and asking them to communicate with STTs for engagement for ongoing user research and testing.
  
Documentation -
- [ ] 

DoD:
 - [ ] Documentation: 
 - [ ] @lfrohlich has reviewed and signed off

**Comment by amilash** [comment]
@lfrohlich This seems old and closable. Agree?

**Comment by lfrohlich** [comment]
agree @amilash !
