### ISSUE TITLE
[SPIKE] Investigate and develop a plan for integrating with ACF AMS

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#751]
We need to understand what it will take to integrate with the ACF AMS, this spike should provide documentation and plan for what we need to do to get that integration done. Regional PMs, OFA staff and those with the most privilege would ONLY be able to log in using this option while those without this privilege would not be able to use this method.
Faren said she would send the integration spreadsheet, which would ask for the key, password, OpenID, etc. 

Approx timebox: 3 hours

AC: 

- [x] Issues are created in zenhub

Proposed Tasks:

- [x] Meeting with ACF AMS lead (Faren Howell - Business Analyst, Henok Worku - engineer) 
- [x] Review documentation (see below)
- [x] Develop a plan for how to move to this (including a list of stories that would need to added to backlog)
- [x] Present plan to Alex P and Lauren in sync, get their sign off

Related Files 
[Authentication & Authorization folder](https://teams.microsoft.com/_#/files/compliance?threadId=19%3A3658d5183f3e4e648c0304832c1eafc4%40thread.skype&ctx=channel&context=Authentication%2520%2526%2520Authorization&rootfolder=%252Fsites%252FTANFDataPortalOFA%252FShared%2520Documents%252Fcompliance%252FAuthentication%2520%2526%2520Authorization)

**Comment by lfrohlich** [comment]
This was presented 4/27/21 and we will follow up with Login.gov alternative
