### ISSUE TITLE
As a Tech Lead, I want my project to join a Bug Bounty or Responsible Disclosure program

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#753]
## Context

Participating in a bug bounty or responsible disclosure program is an industry wide best practice for security: 

https://18f.gsa.gov/2017/05/11/the-next-steps-towards-bug-bounty-program-for-technology-transformation-service/ 

All government systems will eventually need a a Vulnerability Disclosure Policy, as per: https://cyber.dhs.gov/bod/20-01.

There is an existing HHS Responsible Disclosure program, currently only one system is in scope: https://www.hhs.gov/vulnerability-disclosure-policy/index.html

## Goal

Join or use a Bug Bounty or Responsible Disclosure program, most likely the HHS Responsible Disclosure program. 

## Tasks

+ [x] Let Tijan/Penyin know that we'd like to join the HHS responsible disclosure program: https://hhs.responsibledisclosure.com/
+ [x] Reach out to contact to ask about joining the program: csirc@hhs.gov

**Comment by alexsoble** [comment]
Discussed at IPT today, sent links to HHS Responsible Disclosure Program for Tijan and Penyin to take a look at and review.

**Comment by alexsoble** [comment]
@lfrohlich reached out to the HHS Cybersecurity Program (HHS/OS) about this at <HHS.Cybersecurity@hhs.gov> on Thu, Apr 15, 2:00 PM and again this morning.

**Comment by valcollignon** [comment]
>  Reach out to contact to ask about joining the program: csirc@hhs.gov
has been completed per @ADPennington during backlog refinement 12.21.21.

This ticket can stay unrefined at this time, but will be worked on at a later date.

**Comment by lfrohlich** [comment]
Sent another email 4/26/22

**Comment by stevenino** [comment]
So is this ready to close @lfrohlich @ADPennington ?

**Comment by lfrohlich** [comment]
Ready to close with follow on ticket #1979
