### ISSUE TITLE
As OFA tech lead, I'd like to deploy locally on windows machine

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#763]
Still not able to spin-up the backend locally on Windows. Code snippet of where the issue occurs is below. Also attaching mirror snapshots of what success looks like on my mac vs failure on windows, in case it's helpful. Essentially, problem starts at the step where database migrations would be applied.

P.S. using Docker for Windows. 

```
...
postgres_1  | 2021-03-15 15:35:44.665 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-03-15 15:35:44.665 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-03-15 15:35:44.683 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-03-15 15:35:44.732 UTC [65] LOG:  database system was shut down at 2021-03-15 15:35:44 UTC
postgres_1  | 2021-03-15 15:35:44.768 UTC [1] LOG:  database system is ready to accept connections
web_1       | Postgres is ready! ? ?
web_1       | /usr/bin/env: ▒bash\r▒: No such file or directory
web_1       | Postgres is ready! ? ?
web_1       | /usr/bin/env: ▒bash\r▒: No such file or directory
tdrs-backend_web_1 exited with code 127
...
```
**Mac**
![backend_composeup_mac.png](https://images.zenhubusercontent.com/602d96c4a2838adc2bf22d46/4c649415-d6c8-4c5e-ba2e-5c557829cb95)

**Windows**
![backend_composeup_win.PNG](https://images.zenhubusercontent.com/602d96c4a2838adc2bf22d46/6be7a553-47f7-4bcf-b12c-a624f04658cb)

**Comment by riatzukiza** [comment]
Hello, I believe I have a solution for this, I am about to test it.

**Comment by riatzukiza** [comment]
Alright! All that it should take is for you to reinstall git with a different option.

Git defaults to converting all carriage returns to Windows style on pull, then converting to unix style on push.
you have to change the setting to unix on pull and on push, then also re clone the repo.

It will help to ensure that your text editor is set to use Unix style carriage returns instead of windows returns as well so any edits that you make will be consistant with out being pushed.

**Comment by alexsoble** [comment]
@riatzukiza Ooooooh, interesting! Good find!

What do you think about the idea of configuring this via `.gitattributes`? https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings#per-repository-settings

Could help create more consistency across users regardless of local settings.

**Comment by riatzukiza** [comment]
@alexsoble This sounds like a much better solution.

**Comment by alexsoble** [comment]
@riatzukiza Glad to hear you like it! It has the additional benefit that it can be tracked as a PR to the repo!

**Comment by alexsoble** [comment]
Paired with @ADPennington and Thomas on this.

We read general documentation on line endings and `.gitattributes`: 

+ [StackOverflow: Difference between CR LF, LF and CR line break types?](https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types)
+ [git docs: gitattributes](https://git-scm.com/docs/gitattributes)

We tried [using this .gitattributes file](https://github.com/usdoj-crt/crt-portal/blob/develop/.gitattributes) from the USDOJ CRT project, and [following the relevant GitHub Docs](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings).

Unfortunately @ADPennington kept seeing the same error on her local Windows machine when she tried to run the project locally. 😞 

Will work on some other routes that we can try next time!

**Comment by alexsoble** [comment]
Did a little more digging and searching, I have some new hypotheses. 

#### First new hypothesis: 

There are no Windows-style newlines in the codebase that are causing this error for @ADPennington.

Run `grep -rl "\r" .` in the root directory of the project. When I do this, I see `\r` newlines only in binary files, none in code that the application runs. 

#### Next hypothesis: 

What's causing the crash for @ADPennington is the emoji characters in the `wait_for_postgres.py` script.

https://github.com/HHS/TANF-app/blob/main/tdrs-backend/wait_for_postgres.py#L30 

```
logger.info("Postgres is ready! ✨ 💅")
```

From the error stack screenshots that @ADPennington posted, the crash occurs immediately after "Postgres is ready!" is logged.

@ADPennington, if you remove those emoji characters or the whole logging line, does the app run successfully locally?

**Comment by ADPennington** [comment]
confirming that the emoji characters are indeed the culprit! removing them unblocked me! 

🥇 🥇 🥇  @alexsoble 
<img width="489" alt="backend_composeup_winv2" src="https://user-images.githubusercontent.com/63075587/113939974-b45b4380-97ca-11eb-8b0c-40301754cd88.PNG">
1) curious why the emojis are a problem and
2) reaffirming that having a .gitattributes files still seems worth it for future dev collaborators

**Comment by ADPennington** [comment]
re: why the emojis are a problem--issue seems related to docker images and the need to generate some locales. reference links below:

https://medium.com/quiq-blog/handling-emoticons-or-other-unicode-characters-beware-of-docker-images-f0f11673dac4
https://stackoverflow.com/questions/39760663/docker-ubuntu-bin-sh-1-locale-gen-not-found

adding the piece of code below (from the stackoverflow link) to `dockerfile.local` (and restoring the emojis in `wait_for_postgres.py`) also unblocks the problem:

`
RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8
`

the emojis still appear in git bash as `?` but not a deal breaker 😄 💅🏾 ✨
