### ISSUE TITLE
Design Sprint for Tribal MVP

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#764]
**Description:**
Design Sprint for intensive work with the tribal users to understand their needs and create a clickable prototype that can be used to build out the MVP scope.

**AC:** 
- [ ] ~~Clickable Prototype is created and reviewed with PO and Team~~
- [x] Team has aligned on Release 2 Prototype

**Proposed Tasks:** 
All artifacts will be linked to in the "Research and Design - Sensitive" teams channel by the end of the day.
- [x] Update tribe focused journey map (March 17-18)
- [x] Create high-level user stories (March 17-18)
- [x] Collaborative User Workshop 1 (March 19)
- [x] Collaborative User Workshop 2 (March 24)
- [x] Collaborative User Workshop 3 (March 29)
- [x] Affinity/Empathy Mapping (March 22)
- [x] Create lo-fi prototype (March 23-24)
- [x] Create concept testing rubric (March 23-24)
- [x] Create hi-fi prototype (March 29-30) - _this might not be shared prior to the workshop_
- [x] MVP prototype proposal - (March 30-31) depending on scheduling the OFA-Raft MVP Workshop

**DOD**

- [x] @lfrohlich has reviewed and signed off on the annotated mockups of Release 2 (FKA Tribal MVP)

**Comment by reitermb** [comment]
@kniz-raft Created!

**Comment by shubhi-raft** [comment]
Deprioritized for Sprint 18, until we get more information from OFA needs. Adding this to blocked pipeline.

**Comment by lfrohlich** [comment]
Clickable prototype ready to be picked up again when we're ready for it
