### ISSUE TITLE
[SPIKE] Investigate alternative to Signed URLs for download

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#771]
Investigate if there are security issues with using signed URLs or if we want to use the back end to serve files to the front end instead. Dev team has already proposed this process for upload, and that is okay for right now, but for future work, consider impacts to upload during investigation

Timebox: 3 hours

AC:
- [x] Decision on if we continue to use signed URLs
- [x] Create issue(s) for any work needed to change direction (if applicable)

**Comment by kniz-raft** [comment]
Issues #818, #833, #834 were created as an outcome of this ticket.

**Comment by lfrohlich** [comment]
@jtwillis92  is drafting additional documentation on the codebase
