### ISSUE TITLE
[Spike] Logging Options

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#772]
**Description:**

As a long term solution we would like to investigate logging packages to see if there is a more robust long term solution.

**Acceptance Criteria:** 

- [ ] Create ADR with Findings
- [ ] Create issue to implement solution, if one found
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Comment by valcollignon** [comment]
Closing per backlog refinement 12.21.21. Duplicate ticket. 
OK to close per @ADPennington.
