### ISSUE TITLE
As a logged out user, I should not see the header menu with Welcome, Reports, Profile, Admin links

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#773]
**Description:**

What I see right now as a logged-out user:

![Screen Shot 2021-03-17 at 10 16 46 AM](https://user-images.githubusercontent.com/3209501/111492424-a73abf80-870a-11eb-845e-f7512458159d.png)

* When I click "Profile" and "Reports," I see a "Please sign in first" splash message. 
* When I click "Welcome" or "Admin", I see a blank white page.

**Acceptance Criteria:** 

- [ ] As a logged out user, I should not see the header menu with Welcome, Reports, Profile, Admin links
- [ ] As a logged in user, I want to review the header links and check for any access control issues by user/role type

**Comment by ADPennington** [comment]
this is good @alexsoble! should we add to the 2nd ac "by user/role type" ?

**Comment by alexsoble** [comment]
@ADPennington I like that idea! Will update
