### ISSUE TITLE
PLACEHOLDER: Design Pre-Work for MVP 

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#786]
Description: This issue is to inspire the team to optimize base concept solutions for upload and download for STT MVP before adding functionality in the STT MVP Design Sprint.  

AC:

- [ ] A refined set of mock-ups for STT MVP 

Proposed Tasks:

Research plan
- [ ] Plan a collaborative, cross-functional generative design workshop (internal Raft-OFA only) (DK and JP) 
   - [ ] Return to initial design principles for re-evaluation 
   - [ ] Propose a set of Design Inspirations 
   - [ ] Generate multiple iterations for initial mockups for STT MVP 
   - [ ] Set metrics and Design Questions for STT MVP Design Sprint (MR, KN) 
   

DoD:
 - [ ] Documentation: Workshop board and synthesis is shared with PO and Team 
 - [ ] @lfrohlich has reviewed and signed off on Mock-Ups

**Comment by amilash** [comment]
Duplicate and done, closing
