### ISSUE TITLE
CI/CD Audit before ATO

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#789]
We want to make sure that our CI/CD pipeline is running correctly.
AC:

- [x] Any issues needed to modify our CI/CD pipeline are added and prioritized (for ATO or after)
- [x] Any existing issues are either refined or closed as part of this work

Proposed tasks:
 - [x] Check Pa11y (Carl to provide more context on what "check" means
 - [x] Check OWASP ZAP by putting in an error, running it, seeing the error (documenting it), removing the error and then running it again to show that it's working
 - [x] Check Cypress
 - [x] Review what is included in "Code Coverage" to make sure it's relevant
 - [x] Check that all test steps correctly catch failures (similar to the OWASP ZAP task above)
 - [ ] Create template for "CI/CD Health Check" and use it for this first one to create an audit of our audits

**Comment by jtwillis92** [comment]
https://github.com/raft-tech/TANF-app/issues/737 is somewhat related to this but doesn't necessarily need to be solved by ATO.

**Comment by jtwillis92** [comment]
[This issue](https://github.com/raft-tech/TANF-app/issues/870) will cover the Pa11y task for this issue.

**Comment by jtwillis92** [comment]
https://github.com/raft-tech/TANF-app/pull/819 introduces changes that resolve a false positive issue with unit tests and satisfy the task for confirming those work correctly

https://github.com/raft-tech/TANF-app/pull/857 satisfied the OWASP portion of the tasks

**Comment by jtwillis92** [comment]
Created/refined follow on issues for things found during CI Audit.

The following issue(s) should be completed prior to ATO:
https://github.com/raft-tech/TANF-app/issues/879

These issue(s) should be completed, but may be done after ATO:
https://github.com/raft-tech/TANF-app/issues/737
https://github.com/raft-tech/TANF-app/issues/872
https://github.com/raft-tech/TANF-app/issues/880
