### ISSUE TITLE
Evil User Prioritized (Approximate) Threat Model

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#799]
This is the follow up ticket to #454. Evil user journeys were presented to the team and the next step is to figure out how to approach these potential threats. This ticket will help with that prioritization. 

**AC:**

- [x] Evil user threat model is created

**Proposed Tasks:**

- [x] Model is created
- [x] Jen to meet with Carl and John to discuss research
- [ ] A meeting is scheduled with the data team - proposed for sprint 20

**Deliverables:**
Evil User Prioritization Workshop: https://app.mural.co/t/raft2792/m/raft2792/1617910393783/b99bc1cead378478fb854e3429cc34e3f82cf007

**DoD:**

- [x] @lfrohlich has reviewed and signed off

**Comment by lfrohlich** [comment]
Now planning workshop/focus for Sprint 22 so closing this. Model is ready
