### ISSUE TITLE
Refining and Delivering Tribal MVP Clickable Prototype

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#803]
Objective: To create a clickable prototype that allows stakeholders the ability to click through the target state of the Tribal MVP. This prototype will include edge cases, and documentation around future UX improvements.

Tasks:
- [ ] Finalize designs with PO for hifi prototypes of screens concept tested in Tribal MVP design sprint
- [ ] Meet with dev to capture edge cases
- [ ] Create placeholder screens, documenting the functionality of the Django Admin interface
- [ ] String up all screens to make one clickable prototype
- [ ] Annotate each screen with:
- Functionality List
- Related Stories
- Future UX Improvements
- Edge Cases

AC:
- [ ] Clickable prototype that covers learnings from Tribal MVP design sprint

Deliverables: 
Figma Prototype: Link

**Comment by dk-ui** [comment]
@kniz-raft tasks are ready for review

**Comment by amilash** [comment]
This ticket is work that was referenced in #1215 and can be closed.
