### ISSUE TITLE
[Design] OFA-MVP Audit 

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#806]
The purpose of this issue is to conduct an internal user test of OFA-MVP to validate that we achieved all User Functionality required for ATO.  

AC: 
- [ ] All functionality has been accounted for and represented in the OFA-MVP prototype. 

Tasks
- [ ] Conduct internal user test with Dev and UX 
- [ ] Check for accessibility

DD
- [ ] Documentation: ATO-Functionality is presented as a checklist that is completed. 
- [ ] @lfrohlich has reviewed and signed off

**Comment by amilash** [comment]
@lfrohlich was this completed, or do we still need it?
