### ISSUE TITLE
CM-07(02): PREVENT PROGRAM EXECUTION 

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#811]
AC:
- [x] Control implementation statement has been reviewed by Raft for technical accuracy
- [x] Control implementation statement has passed QASP review
- [ ] Control implementation statement has passed OCIO review

DoD:
- [ ] Control implementation statement has been documented in GitHub

**Control Description:**
The information system prevents program execution in accordance with [list of authorized software programs; list of unauthorized software programs; rules authorizing the terms and conditions of software program usage].

CM-7 (2) Additional FedRAMP Requirements and Guidance: 
Guidance: This control shall be implemented in a technical manner on the information system to only allow programs to run that adhere to the policy (i.e., white listing).  This control is not to be based off of strictly written policy on what is allowed or not allowed to run.

**Comment by lfrohlich** [comment]
Merged
