### ISSUE TITLE
fTANF Manual Input Replacement

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#83]
Initial ideas here:
https://app.mural.co/t/gsa6/m/gsa6/1584630282345/3231f53b89fe9cfb67b89aab9f3bde4c32676e81

**Comment by amilash** [comment]
@lfrohlich is this considered part of the ATO release? or is this work for v2 when users can access the system? We had talked about enabling upload and download, so Im unclear if this is different.

**Comment by robgendron** [comment]
@reitermb please use this as a reference as we progress through the roadmap.

**Comment by robgendron** [comment]
@reitermb @victoriaatraft let's combine this with #2921

**Comment by reitermb** [comment]
Copied over description to #2921 
Closing this 

cc @robgendron
