### ISSUE TITLE
[Design] User needs to know their account is inactive

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#830]
If a user is marked as inactive and they try to log in, they need to be told what's going on

AC:

- [x] Designs are provided to dev in figma

Tasks:
- [x] Meet with dev to understand development limitations
- [x] Create design iterations
- [x] Meet with PM to understand scope limitations with design iterations to narrow down iterations
- [x] Confirm technical feasibility with dev based on expected timeline

Notes:
 - User should be made aware they are inactive
 - User should know what they should do next if they are inactive 
 - User cannot do anything inside of the application if they are inactive

User Flow:
type in tdp.gov in browser --> arrive at tdp login screen --> click login --> redirected to login.gov --> attempt to login --> redirected back to tdp login screen with inactive modal present (no buttons on this page will be greyed out) --> click "email"to contact admin --> login again after admin reactivates account

Deliverables:
Figma Mockups: https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4598%3A23260

**Comment by dk-ui** [comment]
@kniz-raft @jenewingpierce Ready for raft review

**Comment by kniz-raft** [comment]
Looks great to me - thanks @dk-ui!

**Comment by lfrohlich** [comment]
These designs look good to me!
