### ISSUE TITLE
[Placeholder] Evaluate current state security controls that grantee program directors are used to

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#840]
Description:
Follow-on research round to evaluate current state security controls being used by grantee program directors (for access to federal programs)

AC:

- [ ] [Draft research plan]/[user interviews]/[synthesis] is complete.

Proposed Tasks:

**Comment by amilash** [comment]
This is a dupe of access management tickets @lfrohlich please close this.
