### ISSUE TITLE
[Placeholder] Regional Managers Workshop Sprint 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#841]
Description:
Follow-on research round to evaluate admin functionality with regional specialists and identify any gaps in functionality. 

AC:

- [ ] [Draft research plan]/[user interviews]/[synthesis] is complete.

Proposed Tasks:

Validate admin functionalities required by OFA regional specialists

**Comment by amilash** [comment]
Closing as dupe
