### ISSUE TITLE
UX Planning Sprint for round 6 (sprints 20-22)

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#843]
Description:
Planning Sprint for Sprints 20-22 is intended to synthesize and process the learnings from the prior research round and map out future goals for research and design in accordance with the Road Map and release schedule.  

AC: 
- [x] PO, PM, and Research and Design Team use the roadmap to agree on the actionable insights of the prior research round and also agree on the goals, outputs, and research methods for the next three sprints. 

Proposed Tasks:
- [x] Research Synthesis Workshop 
- [x] Create a Synthesis in Hack MD itemizing the actionable insights from the outputs of the prior Research Round
- [x] Roadmap Workshop/Live Comms Planning (presentation of aspirational journey maps) 
- [x] Roadmap Synthesis Outcome: SWOT analysis of upcoming releases 
- [x] Research Planning Workshop 
- [x] Live Communications with Stakeholders 

DoD: 
- [x] presentation of synthesis, research plan, roadmap, and journey maps 
- [x] @lfrohlich sign off

**Comment by jenewingpierce** [comment]
Ready for your sign-off, @lfrohlich.

**Comment by reitermb** [comment]
Round synthessis draft: https://hackmd.io/XgNyjdk3RQaOVpJv5H1Yug

**Comment by reitermb** [comment]
Associated PR: https://github.com/raft-tech/TANF-app/pull/908

**Comment by lfrohlich** [comment]
Merged and complete
