### ISSUE TITLE
Digit Team Data Analysis

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#877]
Description: the UX Team will conduct a high-level data analysis of current error messaging data and then drill down into detectable patterns for useful insights for the engineering team and for eventual product design goals.  The resulting information will inform the dev team, PO, and PM, and come to bear on the next Roadmap Workshop and Release Strategy discussion. The data report will also provide baseline metrics for measuring the success of future releases.  (The UX Team is proposing reduced error messages as a suggested, persistent metric for future releases.) 

AC: 
- [x] An actionable set of insights contributes to the next Roadmap workshop/DIGIT workshop 2

Proposed Tasks:
- [x] Meeting with Digit team to gather and discuss current analysis and insights (Whole Team, Dmitri prepared Board)
- [x] Data Analysis Workshop (Review of existing data analysis and performer further analysis for actionable insights) (UX Team) 
- [x] Schedule Roadmap Workshop 
- [x] Draft Report  (Dmitri to bring data analysis into Roadmap Workshp) 
- [x] RoadMap Workshop (Presentation of Outputs from Data Analysis Workshop) 
- [x] Digit Workshop 1

DoD:
 - [x] @lfrohlich has reviewed and signed off

Deliverables: See analysis in #906

**Comment by dk-ui** [comment]
@lfrohlich workshop link is updated in the notes

**Comment by lfrohlich** [comment]
Complete pending review of #906
