### ISSUE TITLE
As an STT user,  I want to know how to onboard to the system

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#883]
revisit flow for requesting access to TDP
We want the homepage to make it clear how to request access before you have a login.gov account
Reconsider invite model and consider what that would change

**Comment by valcollignon** [comment]
This ticket seems to duplicate the work of past access request tickets. #1429 will produce a new and better version of this. The invite model (added security to the access request approval process) has been postponed to V4.

We propose to close this ticket, @lfrohlich. Thoughts?

**Comment by lfrohlich** [comment]
agree duplicate - fine to close
