### ISSUE TITLE
Configure HHS/TANF-app:Master CircleCI jobs to deploy to the production space

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#895]
We need to be able to trigger automated deployments to the production environment upon specific branch merges in https://github.com/HHS/TANF-app. When a merge is made from `HHS/TANF-app:main` to  `HHS/TANF-app:master`, a production deployment should be triggered, which includes the initial deployment of services infrastructure including S3 and RDS via Terraform, as well as the TANF application deployment to Cloud.gov. Additionally, a number of environment variables need to be added or updated in CircleCI and Cloud.gov.

AC:
- [x] Deploy latest code to production space on merges to `hhs:master` with CircleCI
- [x] Deploy services to production space with Terraform

Proposed tasks:
- [x] Expand [Terraform](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/terraform) manifest to include production deployment equivalent to `staging`
- [x] create `master` branch in `hhs:tanf-app`
- [x] confirm list of environment variables that should be added to circleci and cloud.gov
- [x]  Configure HHS:master CircleCI jobs to deploy to the production space
- [ ] Update ADR 009 (git-workflow) and ADR 008 (deployment flow) to reflect prod deployment to hhs:master (per #1731)

**Comment by jtwillis92** [comment]
@amilash @abottoms-coder this may need to be refined. I believe the original intent of this ticket was to create the terraform configurations needed to deploy to prod but that isn't necessarily captured here.

**Comment by stevenino** [comment]
Can't be started until May 1, 2022

**Comment by stevenino** [comment]
> Can't be started until May 1, 2022

This can be started prior to the production environment being available on May 1st.

**Comment by ADPennington** [comment]
added a task related to updating ADRs. cc: @jorgegonzalez
