### ISSUE TITLE
Update O&M Manual w/ correct ENV variables on frontend/backend Cloud.gov apps + HHS CircleCI project settings

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#896]
Environment variables in our frontend and backend cloud.gov apps have been updated per [1179 comment](https://github.com/raft-tech/TANF-app/pull/1179#issuecomment-895471705) and also includes additional variables for the SFTP file transfer for release 2](https://github.com/raft-tech/TANF-app/issues/1133#issue-950019156). Similarly, env variables in HHS CircleCI project settings have been updated accordingly. As such, the Operations and Maintenance manual, which includes descriptions of these variables, needs to be updated.  

AC:
- [ ] Update Ops manual

**Comment by ADPennington** [comment]
@jtwillis92 @abottoms-coder can we discuss this at this week's tech sync?

**Comment by jtwillis92** [comment]
For additional reference: https://github.com/raft-tech/TANF-app/pull/1179#issuecomment-895471705

**Comment by ADPennington** [comment]
closing this as a dupe to #1422 which will be more comprehensive re: release 1 ato doc updates cc: @valcollignon @lfrohlich
