### ISSUE TITLE
Remove "Super User" attribute, leverage model permissions

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#901]
At present, users with access to Django Admin Console (DAC) have a "super user" attribute which grants all permissions for all objects similar to a root-level account. We'd like to decouple this to alleviate security concerns and ensure proper permissions are granted.

AC: 
- [x] Ensure no user has "super user" attribute (except for initial superuser, as defined by DJANGO_SU_NAME environment variable - in deployed contexts this is the Product Owner Lauren)
- [x] Ensure users retain relevant functionality through group permissions

Proposed Tasks:
- [x] Decouple "super user" from permissions for DAC functionality
- [x] Creation of groups' permissions sets per matrix below
- [ ] Create documentation in github of relevant model permissions (see matrix below )- document groups, and any relevant implementation approach.

Updated per discussion with @jtwillis92 6/28 by @abottoms-coder 

The current security control [here](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Security-Compliance/Security-Controls/ac-5/index.md) documents the first draft of permissions.

Proposed Permissions Matrix Table: One Note: https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2FPermissions%7C67b61c8f-b200-46e8-8e73-b5aa6382a19c%2F%29

**Comment by amilash** [comment]
Remaining estimate sprint 28: 8
