### ISSUE TITLE
DIGIT Team Research and OFA Regional Staff/Manager Journey Maps 

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#906]
Description: The desired outcome of this ticket is to produce a current state and aspirational state journey map specific to the OFA Regional Staff/Manager personas and to present the next stage data analysis of error messaging to the DIGIT Team for their input and validation.  

AC:
- [ ]  The Journey Map synthesis is applied to the Roadmap and Release Strategy 

Tasks:
- [x]  Bring data from personas and roles documentation to Visual Designer for incorporation into a presumptive map or maps (Miles)
- [x]  Build Current State and Aspirational Maps for DIGIT Workshop and put into prior DIGIT Workshop Board (Dmitri) 
- [x] Plan Workshop Date (Lauren) 
- [x] Digit Workshop 2
- [x ] Write synthesis (Jennifer) 
- [x] Transfer to OFA board (Miles) [here](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1620936409266/794efb109e473ee761b988b692dd8572e159a14e)

DoD: 
- [x] Results of Workshop are presented at UX Sync 
- [x] @lfrohlich has signed off

Deliverables:
Workshop: https://app.mural.co/t/raft2792/m/raft2792/1620058675767/dd097f190c296ff6176fba57c0cd6c01eb6b2d6d
On OFA board: https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1620936409266/794efb109e473ee761b988b692dd8572e159a14e?sender=laurenfrohlich3146

**Comment by dk-ui** [comment]
@lfrohlich workshop link added to the notes
