### ISSUE TITLE
I want a Content Security Policy to protect me from XSS and other client side attacks 

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#907]
This will fix an error currently showing in the OWASP ZAP report. Currently the header tell the browser what kind of content can be uploaded. We need to fix the issue so we don't get pinged in the security scans.

If this were misconfigured it could allow for XSS injection or other vulnerabilities.
https://owasp.org/www-community/attacks/xss/ 

AC:
- [ ] The error will no longer show up on the frontend HTML report

## Context 

+ TDP OWASP Report: https://6509-281707402-gh.circle-artifacts.com/0/tdrs-frontend/reports/owasp_report.html
+ Content Security Policy (CSP) via Mozilla: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
+ Cross-site Scripting (XSS) via NIST: https://csrc.nist.gov/glossary/term/Cross_site_Scripting

**Comment by jorgegonzalez** [comment]
I think this is a fairly simple addition on the frontend https://stackoverflow.com/questions/59592929/content-security-policy-in-react-app-didnt-block-online-script
