### ISSUE TITLE
Convert cloud.gov Organization to FISMA Moderate

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#914]
## Context 

https://cloud.gov/pricing/

## Notes

Before we accept production data, our cloud.gov Organization must be set to the FISMA Moderate level: "Production environment for systems that need assurances in confidentiality, integrity, and availability."
We do not need to go through FITARA review. 

## Tasks

1. [x] Reach out to cloud.gov via email or Slack (#cg-support) requesting to upgrade the Org to FISMA Moderate 
2. [ ] Rename the Org to make clear that our new Org is no longer for prototyping and is for a production system; something like `hhs-acf-tdp`, `hhs-acf-tanf-data-portal`...

**Comment by amilash** [comment]
@abottoms-coder For triage and your awareness. Is this a production thing we need? cc @ADPennington

**Comment by amilash** [comment]
@lfrohlich  Found this one in the backlog. Has there been an assessment for cost and value done for this yet? Lets discuss in grooming. There is a significant price point on this service. Im curious on the origination of the ticket.
https://cloud.gov/pricing/

**Comment by amilash** [comment]
as per @jtwillis92 and @lfrohlich there is no discussion to be had here, this need comes from ATO and the PII that will be handled on the platform.
Laurens team may have ways to cost share or save.
Lets flip this switch closer to production so as to incur costs near term to the prod release.

**Comment by ADPennington** [comment]
@valcollignon this is release 1.

**Comment by lfrohlich** [comment]
Received draft from cloud.gov for review 3/11. Plan to start FISMA moderate w/ 7GB/month starting May

**Comment by lfrohlich** [comment]
The IAA is complete and we will move to production in the HHS-ACF-OFA organization starting in May 2022
