### ISSUE TITLE
Create a home for desired data validations rules

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#92]
Description:
This will be done when, a small set of data validation rules have been documented. 

What is the right way to write these validation rules? 
TANF data format and current business needs are not the same
Potential coworking discussion? 

In response to vendor questions, user research

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Identify a few rules to use as examples for documentation
- [ ] How should we document?
- [ ] What data validation rules should be used in new system?
- [ ] Understand how the current prototype understands and consumes rules?
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
Can we close this @lfrohlich ?
