### ISSUE TITLE
[Design] Mockup for 404 page

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#927]
Problem Statement: 
As of [this PR](https://github.com/raft-tech/TANF-app/pull/866) we will have a redirect in the React site for any nonexistent URL to a "No Match" page which is currently very basic and not styled to match the rest of the site:
![Screenshot from 2021-05-18 10-47-41-1](https://user-images.githubusercontent.com/22626085/118672833-881de400-b7c6-11eb-93fe-aa8ab7e7ca64.png)

We'd like to request a design for a branded 404 page that is more user friendly and appealing to the eye.

Questions: None

This is a follow-on to #865 

AC: 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 
- [ ] [User flow is updated](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

Tasks
- [ ] Design a lo-fi mockup for a custom 404 page
- [ ] Check for accessibility

DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by amilash** [comment]
we will use the standard design for now. closing as no longer needed. @lfrohlich  we can refactor this and make it prettier later as needed.

**Comment by jtwillis92** [comment]
https://designsystem.digital.gov/templates/404-page/
