### ISSUE TITLE
Demo user research + prototyping progress to regional offices

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#93]
Description:
Why: get regional data leads invested in the new TDRS process and introduce Raft to regional team

"Regional staff wants to have a chance to understand the direction that we're moving in with the new system. They'd like to learn more about what we've learned so far. The data group has at least 1 person from all 10 regions, so may be a good place to present this. Some of those folks aren't the program managers so we may need to broaden."--Lauren, 5/11/2020

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [x] Ask Lauren if RO staff may want to attend
- [ ] Observe session where OHS team shares their research learning with regional folks
- [ ] Schedule session time/day
- [ ] Maybe include personas
- [ ] Maybe doing Design Principles exercise

Some other thoughts:

- read out of research
- talk about how we'll be coming back to them in the future
- we could do a lightweight design principles workshop
- participation in workshop may help identify ROs to talk to
- This could also help demo how we want to involve other user groups at many levels to our vendor.

Notes:
- Schedule after round 3 research sysn theiss has been documented adn shred within OFA data team; Lauren has approved.

**Comment by amilash** [comment]
@dk-ui can you tell me where this fits into the scheme of things? Is this the research you are preparing for now?

**Comment by lfrohlich** [comment]
This has been built into the process with "live comms" . closing out
