### ISSUE TITLE
Re-evaluate Sprint length

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#938]
Do we want to reconsider a 3 week sprint? Pros/cons?

**Comment by amilash** [comment]
@lfrohlich is a 3 week sprint something you want to consider at this point? I would recommend we keep a 2 week sprint at this point. Let me, know. If not, can we close this ticket? Thanks!

**Comment by lfrohlich** [comment]
Let's keep it at 2 for now. This was a response to cadence issues that i don't think we currently have. Thnaks @amilash
