### ISSUE TITLE
Demo Tribal TANF Error Reports prototype

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#94]
**Description:**
Alex P developed a tribal TANF error report prototype. Would be helpful for her to demo for team. Also, could we make the code accessible to the vendors/host in our environment?

**AC:** 

- [ ] Sample acceptance criteria

**Tasks:** 

- [ ] Sample tasks
 

**Open Questions:**

(any clarifying questions in support of the issue)

**Comment by jenewingpierce** [comment]
@lfrohlich can we still arrange for this?  This could be useful for the Tribal workshop...

**Comment by amilash** [comment]
@dk-ui  seems like this is a duplicate of work you are doing. Can I close it?

**Comment by dk-ui** [comment]
@amilash We were able to see this process. This ticket can close

**Comment by amilash** [comment]
Closing. Thanks.
