### ISSUE TITLE
As a system admin, I want accurate documentation of the user roles

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#940]
- [ ] [User Role Management](https://github.com/HHS/TANF-app/blob/main/docs/Technical-Documentation/user_role_management.md#user-role-management) needs to be updated to reflect current users
- [ ] Data Prepper should be changed to Data Analyst in backend https://app.zenhub.com/workspaces/tdrs-product-backlog-5f2c6cdc7c0bb1001bdc43a5/issues/raft-tech/tanf-app/1071 

Permissions matrix for reference: https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2FPermissions%7C67b61c8f-b200-46e8-8e73-b5aa6382a19c%2F%29

**Comment by amilash** [comment]
This is done.
