### ISSUE TITLE
Use clearer ENV variable names for separate AWS services

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#949]

**Comment by alexsoble** [comment]
## Context 

We identified this issue during Dev Sync on 5/19; see Dev Notes > Env Vars in Teams. 

The TDP app uses 2 separate sets of S3 services: one public, to store Django Admin static assets (images, JS, CSS), and one private, to store data files containing PII.

The variable names used for the ENV variables which store the keys to these separate S3 services could be clearer, so that devs immediately know which set relates to Django Admin and which set relates to Data Files.

**Comment by jtwillis92** [comment]
Completed with https://github.com/raft-tech/TANF-app/pull/977
