### ISSUE TITLE
Talk to 3rd party vendors that help STT collect/prep data

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#95]
Description:
We know that there are some vendors that create systems that STTs use to manage their TANF data, and we believe some of these vendors may be involved in preparing TANF data reports. This issue is to investigate further about what level of involvement 3rd party vendors have in the data prep process.

Possible questions to investigate include:
* Which vendors are common among STTs?
* What services do they provide?
  * Do STTs outsource data prep and report submission to 3rd party data preppers?
* How do vendors navigate OFA resources to build systems for STTs?

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

 
 
Thoughts
8/18 Christine: Note that the OFA team has been working with a tribal data contractor on adjusting their data format. [Teams thread here](https://teams.microsoft.com/l/message/19:e92913e3e7d443adb823e6497dff1fb3@thread.skype/1597700219038?tenantId=d58addea-5053-4a80-8499-ba4d944910df&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287&parentMessageId=1597700219038&teamName=TANF%20Data%20Portal%20(OFA)&channelName=Design&createdTime=1597700219038). 
4/27 Christine: We talked about delaying this conversation until after a vendor is selected. [As prep, we've added some thoughts on what discovery questions we have: 

- They build a lot of the systems used by states to prepare (and submit?) their data to ACF. 
- Discovery, not vendor interview 
- What could be helpful to learn from them? 
- Which STTs do they support? 
- Where do Deloitte systems start and stop in this process?  
- Are they building case management systems? Or just integrations? Or reports?  
- Do their systems actually prepare the flat files? 
- Do they actually send the file to OFA? 
- What data checks exist within their systems? 
- What types of exports do they prepare (are they generating flat files?) 
- What APIs could be helpful? 
- If they could change anything about the TANF reporting requirements, process, or system, what would it be?

**Comment by shubhi-raft** [comment]
could this be our next research step after Round 3 synthesis? @reitermb

**Comment by valcollignon** [comment]
Is this still relevant? Discuss at UX sync.
CC: @reitermb @sreedevip

**Comment by lfrohlich** [comment]
This is not a task in itself. We will continue to talk to vendors as they are part of grantee teams, but do not to pursue this independently.
