### ISSUE TITLE
Update Operations & Maintenance Manual

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#950]
## Context

The O&M Manual currently contains a list of all ENV variables used to configure the TDP application. 
Also update O&M with incident response drill findings/steps.
Will need to update as part of ATO docs. 

## Documentation goals 

+ [ ] Create separate lists of ENV variables used to configure the apps in cloud.gov; ENV variables used in CircleCI; and ENV variables used only for local development
+ [ ] Add a short definition of what each ENV variable is responsible for and where it is used in the code

**Comment by alexsoble** [comment]
## Context

The O&M Manual currently contains a list of all ENV variables used to configure the TDP application. 

## Documentation goals 

+ [ ] Create separate lists of ENV variables used to configure the apps in cloud.gov; ENV variables used in CircleCI; and ENV variables used only for local development
+ [ ] Add a short definition of what each ENV variable is responsible for and where it is used in the code

**Comment by ADPennington** [comment]
closing as a dupe to #1422
