### ISSUE TITLE
Configuration (ENV variable) simplification and cleanup 

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#951]
## Notes

This is an Epic to hold issues surfaced in @ADPennington's work leading a review of the ENV variables used to configure the application. 

## Why?

+ Understanding each ENV variable and what it does is key to knowing how to operate and change the system over time. 
+ Eliminating any duplicate ENV variables reduces the chance of a misconfiguration in the app. 
+ Using clearer names for ENV variables reduces the chance of dev mistakes or misunderstandings.

**Comment by amilash** [comment]
@abottoms-coder can you take a look at this epic and discuss when it would be most appropriate that we should tackle this, or if some of this work is done already? Thanks!

**Comment by amilash** [comment]
@abottoms-coder can you triage this and line it up as work ready to go for the next few sprints?

**Comment by jtwillis92** [comment]
All these tasks are complete with the issues already completed in #972 with the exception of #950 - I'm not sure if that one still needs to be done.

**Comment by jtwillis92** [comment]
@ADPennington do we still need these updates in the Operations & Maintenance Manual?

**Comment by ADPennington** [comment]
yes. ill wrap it up next sprint. @jtwillis92

**Comment by ADPennington** [comment]
this is now a dupe of #1422, so closing.
