### ISSUE TITLE
As TDP SO/TL, I need a basic security awareness training developed for IS users (AT-02)

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#953]
This training will satisfy Security Control [AT-02](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=4.0&number=AT-2) (Security Awareness Training). 

SO = System Owner
TL = Tech Lead
IS = Infosec

The organization provides basic security awareness training to information system(IS) users (including managers, senior executives, and contractors):
a. As part of initial training for new users;
b. When required by information system changes; and
c. [At least every 365 days] thereafter.

The content should:
-  provide a basic understanding of the need for information security and user actions to maintain security and to respond to suspected security incidents
-  address awareness of the need for operations security. Security awareness techniques can include, for example, displaying posters, offering supplies inscribed with security reminders, generating email advisories/notices from senior organizational officials, displaying logon screen messages, and conducting information security awareness events.

For CSP Only
AT-2(c) [at least annually]

[Related controls](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/controls?version=4.0&family=AT): AT-01 (security training policy), AT-03 (role-based security), and AT-04 (security training record-keeping) may need to be satisfied in the future. If so, perhaps worthwhile to consider these as we're building strategy to satisfy AT-02. 

### ACs:
- [x] AT-02 implementation statement, indicating list of trainings TDP sys admins complete annually as HHS employees, saved in repo. 
- [x] sys admins certificates of training completions, saved centrally and most recent certs shared with OCIO.

**Comment by ADPennington** [comment]
reached out to Penyin on 6/1 to ask if there are other ACF program offices with system-specific training models we could review.

**Comment by ADPennington** [comment]
stub comment for research findings:

- _certificate [example](https://intranet.hhs.gov/sites/default/files/s3fs-public/s3fs-public/2019-05/Certificate%20of%20Completion.pdf) (only accessible to staff with an HHS PIV)_

**Comment by valcollignon** [comment]
@ADPennington - where does this ticket stand? It's been in "Next Sprint Backlog" since May 21. Can this move back to backlog until we're ready for it?
CC: @lfrohlich

**Comment by lfrohlich** [comment]
I moved it back to product backlog

**Comment by stevenino** [comment]
Will be discussed at the next IPT meeting. Not required for v1

**Comment by lfrohlich** [comment]
Per IPT 4/6/22 -- HHS trainings should be sufficient. Alex and Thomas will need to submit certificates annually.

**Comment by ADPennington** [comment]
> Per IPT 4/6/22 -- HHS trainings should be sufficient. Alex and Thomas will need to submit certificates annually.

recommend we write a security control implementation statement relevant to AT series  and store it [here](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/docs/Security-Compliance/Security-Controls) with the others. cc: @lfrohlich @stevenino

**Comment by stevenino** [comment]
> > Per IPT 4/6/22 -- HHS trainings should be sufficient. Alex and Thomas will need to submit certificates annually.
> 
> recommend we write a security control implementation statement relevant to AT series and store it [here](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/docs/Security-Compliance/Security-Controls) with the others. cc: @lfrohlich @stevenino

Would that be an AC for this ticket or can we close this ticket now as not required?

**Comment by ADPennington** [comment]
> > > Per IPT 4/6/22 -- HHS trainings should be sufficient. Alex and Thomas will need to submit certificates annually.
> > 
> > 
> > recommend we write a security control implementation statement relevant to AT series and store it [here](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/docs/Security-Compliance/Security-Controls) with the others. cc: @lfrohlich @stevenino
> 
> Would that be an AC for this ticket or can we close this ticket now as not required?

i updated ACs @stevenino.
