### ISSUE TITLE
Research and explore manually data entry

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#96]
Initial ideas here:
https://app.mural.co/t/gsa6/m/gsa6/1584630282345/3231f53b89fe9cfb67b89aab9f3bde4c32676e81

**Comment by valcollignon** [comment]
Propose to close. Not actionable or relevant at this time.
CC: @lfrohlich

**Comment by valcollignon** [comment]
Closing per backlog refinement 12.14.21 CC: @lfrohlich
