### ISSUE TITLE
Research prework on 477 tribe question

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#97]
Description:
_This is a pre-Raft issue_

We know that tribes have a different experience submitting data to OFA than states. One thing we've heard of is the [477 program](https://www.indianaffairs.gov/bia/ois/dwd), which allows participating tribes to streamline their reporting requirements. 

We want to verify if participating in this program impacts their TANF reporting (if at all). Our understanding is that this may impact how they communicate with OFA. 

Relates somewhat to #99 

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] We identify who can answer our questions (at OFA or Bureau of Indian Affairs) about how tribes with 477 plans submit TANF data (Believe this is Denise at OFA Tribal TANF)
- [ ] Have initial conversation with them
- [ ] Update process map, open questions and personas as needed.

Supporting Documentation:
* [Process map](https://app.mural.co/t/officeoffamilyassistance2744/mural-password/gsa6/1593114727729/906879aaeb5467c27f0ae3dfbcf5fcfd9cf8ca89)
* [Notes on tribal data processing](https://teams.microsoft.com/l/file/03482E90-1621-42C5-AAC1-C2F311AA4ABA?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FTeam%20Meetings%20%2B%20Presentations%2F2020.07.14%20Chat%20re%20Tribal%20data.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

**Comment by amilash** [comment]
@lfrohlich , @dk-ui  Can we close this as 'will not do'?

**Comment by lfrohlich** [comment]
we still want to talk to 477 tribes at some point, but this doesn't need to be done as written
