### ISSUE TITLE
Discuss and plan research to better understand the need for universe data

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#98]
**Description:**
Some STT submit "universe data" for every TANF recipient. Other STT just submit sample data. Encouraging or requiring all STT to submit universe data may help improve data quality and longitudinal analysis, but it also may pose significant privacy risk. We need to discuss and research the trade offs and options here. 

**Tasks:** 

- [ ]  Identify who has information on universe vs sample breakdown of STTs (something Yun/Alex could pull?)
- [ ] Contact them and get the data

**Considerations**

- Some thoughts about data use and privacy from [Data 4 Black Lives](https://d4bl.org/)

![image.png](https://images.zenhubusercontent.com/5f1f2ac6d113e50aff528932/be72d431-de0b-4869-9cf6-d952e49b9d96)

**Comment by amilash** [comment]
@dk-ui Can you help me contextualize this? Is it still relevant? cc @lfrohlich

**Comment by lfrohlich** [comment]
Some of this is being done through other work on sampling and other conversations re: equity; I think it makes sense to close out here.
