### ISSUE TITLE
As an OFA admin/STT user, I want to be notified if I change search selections after a file has been uploaded but not yet submitted

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#992]
Expected behavior:

1. make initial selections
2. upload file (but do not submit)
3. change selections in combo-box
4. click search
5. modal pop up saying: ` (H1) Files have not been submitted. (body) Searching without submitting will discard your changes and remove any uploaded files`
6. Button updated to `Cancel` and `Discard files and search`

Acceptance Criteria:
- [ ] Frontend raises [an error/warning notification](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4203%3A22618) if user changes selections after upload but prior to submit
- [ ] Frontend matches mock ups

Tasks:
- [x] Meet w/ UX team to discuss list of ACs (or invite to dev sync)
- [ ] Implement changes as proposed by UX and @ADPennington 

Notes:
- Related [finding](https://github.com/raft-tech/TANF-app/pull/787#issuecomment-829591282) re: ensuring data uploaded is associated with users final selections 
- For future: need a diff ticket for trying to navigate away from page. 
- more discussion needed around submission history epic

**Comment by reitermb** [comment]
https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4203%3A22618 Design

**Comment by reitermb** [comment]
![image](https://user-images.githubusercontent.com/28515874/135122593-88da256c-a71e-4d3b-92cd-a2c0b0968364.png)

**Comment by ADPennington** [comment]
revised with @n0remac @jtimpe and @reitermb on 10/25. cc: @andrew-jameson @stevenino
